block/goose

documentation/static/servers.json
This PR adds the VSCode extension to the goose website: https://block.github.io/goose/extensions
=> feat(vscode): add the vscode server to the list

ui/desktop/src/components/settings_v2/extensions/agent-api.ts
Makes it so we only show one error toast when extensions fail to add / activate
**Before**
**After**
=> fix: Only show one toast when extensions fail to add/activate/etc

crates/goose-mcp/src/developer/mod.rs, crates/goose-mcp/src/developer/shell.rs
this fix should allow goose to correctly use powershell in native windows
=> fix developer mcp for windows

Cargo.lock, ui/desktop/src/components/Input.tsx
Fix #1975
The main issue is that we have `setSavedInput(value);` before `setValue(savedInput);` but since it is async method, `savedInput` can still be empty after we call `setSavedInput(value);`. To fix it, we can skip the value set when the index doesn't change
https://github.com/user-attachments/assets/7c7aeb0b-c5ae-48c7-a58a-b5f1c79fd27c
=> fix: fix the empty input with ⌘+Down

Cargo.lock, crates/goose/src/agents/reference.rs, crates/goose/src/agents/summarize.rs, crates/goose/src/agents/truncate.rs, crates/goose/src/session/storage.rs
This PR adds tracking for input and output tokens in SessionMetadata, allowing for more detailed token usage analysis. This will help users monitor input and output tokens separately as they usually have different billing for different token types.
- Added `input_tokens` and `output_tokens` fields to the `SessionMetadata` struct
- Updated the metadata handling in all agent implementations (Reference, Summarize, and Truncate) to store these values
- Updated the deserializer to handle these new fields for backward compatibility
Tests ran successfully locally. 
```
./target/release/goose run -t "write haiku about goose"
```
Graceful on water
Wings spread wide against the sky
Honking wild and free
```
Would you like me to write another haiku about geese? I'd be happy to explore different …
```
=> Add input and output token tracking to SessionMetadata

ui/desktop/src/App.tsx, ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/BottomMenuModeSelection.tsx, ui/desktop/src/components/more_menu/MoreMenu.tsx, ui/desktop/src/flags.ts, ui/desktop/src/utils/providerUtils.ts
Create a named feature flag for settings V2, so we can easily turn it on and off with one line code changes. Right now it remains set to `process.env.ALPHA`, but we can change it soon to `true` to release, and `process.env.ALPHA` if we need to roll back.
=> feat: create named feature flag for settings v2

ui/desktop/src/components/conversation/SearchView.tsx
Temporarily disable search for launch until https://github.com/block/goose/issues/1984 is fixed
=> Temporarily disable search for launch

crates/goose/src/agents/truncate.rs
We check the read-only annotation in tool annotations, if annotation is none, we will use llm-as-a-judge when goose mode is smart approval. If read only hint is true, we directly skip the permission check to save cost and time.
=> feat: check tool annotation before permission check

ui/desktop/src/components/settings_v2/models/bottom_bar/ModelsBottomBar.tsx
Noticed that we had to click the bottom bar to close the models popup. This makes it so you can click anywhere on screen.
=> ui: settings v2 click anywhere to exit models bottom bar

ui/desktop/src/components/settings_v2/models/index.ts, ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx
Uses `Model` objects now when switching models -- this lets us pass around objects in the UI that have the model name, provider, alias (model nickname), and subtext (can be the 'pretty' version of the provider name or something more bespoke like 'Databricks (recommended)'. 
Toasts were showing 'Switched to `<model-name>` by `<lower cased provider name>`'
Now they show 'Switched to `<model-name>` by `<provider display name>`'
=> use provider display names

ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
When testing with radio buttons found that they weren't selecting properly
=> ui: fix radio button selection

ui/desktop/src/components/settings_v2/models/ModelsSection.tsx, ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
Had to leave and come back to settings to see model change -- now happens automatically
=> ui: refresh selected model

ui/desktop/src/components/MarkdownContent.tsx, ui/desktop/src/components/UserMessage.tsx, ui/desktop/src/styles/main.css, ui/desktop/tailwind.config.ts
Key changes
- Updated header sizes
- Updated line heights
- Updated spacing
- Updated base font size (dropped down to 14px)
- Updated inline code block style
Before / Afters
=> styles: update markdown styles

crates/goose/src/providers/formats/google.rs
Fix #2008
The issue is that we have the view response from goose, but it is in the [resource type](https://github.com/block/goose/blob/64d0cd186acf759b3492cc04c755740ab766c2f4/crates/goose-mcp/src/developer/mod.rs#L644) which is not processed in the gemini format_tool
=> fix: fix empty result for view tool response

crates/goose-server/src/routes/providers_and_keys.json, crates/goose/src/providers/formats/gcpvertexai.rs, ui/desktop/src/components/settings/models/GooseModels.tsx, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
This PR introduces support for generic Claude and Gemini model variants within the GCP Vertex AI provider. This allows Goose to handle potentially unknown or future model versions released by Google Cloud without requiring immediate code updates.
Avoids this error for manually configured GCP Vertex AI models.
```
Ran into this error: Execution error: Failed to parse model ID: gemini-2.5-pro-exp-03-25.
Please retry if you think this is a transient or recoverable error.
```
**Changes:**
* Added `Generic(String)` variants to both `ClaudeVersion` and `GeminiVersion` enums to support arbitrary model names
* Updated model parsing to match any model name starting with `claude-` or `gemini-`
* Updated `fmt::Display` implementation to preserve exact model names for generic variants
* Added …
=> # feat(providers): Add support for generic GCP Vertex AI Claude and Gemini models

ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/extensions/extension-manager.ts, ui/desktop/src/components/settings_v2/extensions/modal/EnvVarsSection.tsx, ui/desktop/src/components/settings_v2/models/ModelsSection.tsx, ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
* makes env var section editable
* tells user to click add button so env vars are saved
=> ui: better env var ux

crates/goose-mcp/src/developer/mod.rs
=> fix: handle the case sensitive in mac screenshot name

crates/goose-server/src/routes/configs.rs, crates/goose/src/agents/permission_store.rs, crates/mcp-core/src/resource.rs
the ci is now using rust 1.86, address clippy warnings to fix pipelines
=> style: address clippy clippy::double_ended_iterator_last, and clippy::manual_ok_err

crates/goose-cli/Cargo.toml, crates/goose-cli/src/logging.rs, crates/goose-mcp/Cargo.toml, crates/goose/Cargo.toml, crates/mcp-client/Cargo.toml
This PR addresses #1922.
I believe that `rustls-tls-native-roots` is the most suitable choice for the following reasons:
- It is officially supported by `reqwest`: 
https://docs.rs/reqwest/latest/reqwest/#optional-features  
- It requires minimal changes compared to the original `rustls-tls`.  
- It supports macOS, Linux, and Windows, and also allows customization via environment variables: https://github.com/rustls/rustls-native-certs?tab=readme-ov-file#platform-support
=> bug: change `reqwest` certificate store to platform's native

documentation/static/install-link-generator/index.html, documentation/static/install-link-generator/script.js
This pull request includes significant updates to the `install-link-generator` feature in the documentation. The changes enhance error handling, improve user feedback, and streamline the process for generating install links based on URL parameters.
* [`documentation/static/install-link-generator/index.html`](diffhunk://#diff-70c929fdb5492ca4917ab3778d84e2f9559789d8bfe8a31716f8c3898b98f2b3R8-R23): Added a new CSS class `.error` to style error messages and modified the `.container` and `.result` classes to control their visibility.
* [`documentation/static/install-link-generator/script.js`](diffhunk://#diff-86e778e8b0e0b641fa7e98bdee5164078ff73cab656d5c73914578345a18b14aR2-R89): Introduced a `showError` function to display error messages within the result container.
* …
=> Add deeplink redirect to install link generator

Cargo.lock, crates/goose-server/src/routes/config_management.rs, crates/goose/src/config/extensions.rs, crates/goose/src/config/mod.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts
Right now if `config.yaml` is malformed or cannot deserialize to the right schema, it just responds that there is an empty list of extensions. This makes it respond specifically with an `UNPROCESSABLE_ENTITY` status code. In a next change, we can update the frontend to handle this by showing options to the user (edit the file, or reset config file)
=> fix: properly return errors for malformed config

Cargo.lock, crates/goose-server/src/openapi.rs, crates/goose/src/agents/extension.rs, crates/mcp-core/Cargo.toml, crates/mcp-core/src/tool.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts
Unblock development in the app by rebuilding the OpenAPI schema to include new types for frontend-provided tools
=> fix: fix OpenAPI build

documentation/docs/tutorials/youtube-transcript.md
This pull request includes a small change to the `documentation/docs/tutorials/youtube-transcript.md` file. The change adds an embedded YouTube video to the tutorial using the `YouTubeShortEmbed` component.
* [`documentation/docs/tutorials/youtube-transcript.md`](diffhunk://#diff-b00d715dcdd37842ddd1c954d37fbd3b34c2eff4df218c3a9e759d3580236f61R10-R11): Added a `YouTubeShortEmbed` component to embed a YouTube video.
=> docs: Add shorts to TY extension

ui/desktop/src/components/settings_v2/extensions/agent-api.ts
Small one to bring back the extension name sanitization we had in Settings V1
=> fix: sanitize names before enabling/disabling extensions in Settings V2

crates/goose-mcp/src/google_drive/mod.rs
After reviewing the code, they are very confusing as we have update_file in https://github.com/block/goose/blob/4846d15354a1a1c53381e8e4886f4b23b606f62d/crates/goose-mcp/src/google_drive/mod.rs#L421.
It turns out update is for normal file while update_file is for google related files. Refresh the name and descriptions
=> feat: update the google drive update file tool description

crates/mcp-client/src/transport/mod.rs, crates/mcp-client/src/transport/sse.rs
Motivation:
* When using Goose via the fastmcp client, there is a log line that is emitted at error level even though it does not represent an actual error condition. See bug: https://github.com/block/goose/issues/2051
Approach:
* If there are no remaining pending requests in the queue and the server has been shut down, the logging should be info level. Otherwise if there are messages remaining and the server has been closed there should be an error message logged.
* Add two new methods to PendingRequests -- len and is_empty. Only len is used but is_empty is required by rust: https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
=> Update SSEActor error logging

ui/desktop/src/components/settings_v2/extensions/extension-manager.ts, ui/desktop/src/utils/providerUtils.ts
in settings v2, if an extension is configured with a bad command, or the command fails (warp error, the entire app crashes with the `Honk! Goose experienced a fatal error` message. it would also under the hood toggle off the extension, and on a retry things would seem to magically work
this change updates it so failed extensions are not fatal, instead we present a toast letting the user know it failed and that it will be disabled:
---
- added generic `retryWithBackoff` function for exponential backoff retry 
- update `addToAgentOnStartup` to use that
- attempt to add all extensions in parallel on startup
=> feat: parallelize extension startup and handle errors with toasts

documentation/docs/tutorials/pdf-mcp.md
This adds a new tutorial page for the PDF MCP. 
Note: this does not yet include the plug and play video.
=> docs: adding pdf mcp tutorial

ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
Fixes an issue where extensions didn't show up if they fail to activate/are added to config as disabled. This allows for easy editing of the config right away.
=> feat: show added extensions in settings v2 regardless of whether they activate

ui/desktop/src/utils/providerUtils.ts
Migration logic:
* on startup, check for `configVersion` in `localStorage` if it (doesn’t exist, or is < 2) proceed with migration
* grab extensions from `user_settings` in `localStorage`
* convert and extract all extensions
* iterate through and add them to `config.yaml`, skipping `builtins`
* set `configVersion: 2` in `localStorage` so this only happens once
we skip `builtin` and rely on `initializeBundledExtensions` or `syncBundledExtensions` to setup all bundled extensions in the new format
we then just drop into normal initialization logic afterwards, relying on normal agent/extension startup
=> feat: add migration logic from settingsV1 to settingsV2

crates/goose/src/config/mod.rs, crates/goose/src/config/permission.rs, crates/goose/src/permission/permission_judge.rs
We have three levels for permission: Always Allow, Ask before and Deny. Users can set the permission level for each tool, however, we still have the smart approve and manual approve permission level as the default for the starting point. 
The permission yaml format will be:
```
user:
always_allow:
- xxxx
ask_before:
- xxxx
deny:
- xxxx
smart_approve:
....
```
It means the workflow should be like:
Note: only in smart approve and manual approve goose mode
1. Check the user permission level first
2. If find the tool permission, use it
3. If not, base on current goose mode, if it is manual approve mode, always be Ask before; if it is smart_approve, get the permission level(either always allow - readonly or ask before - write/mixed)
The reason we store smart approve default permission is to …
=> feat: add permission manager for tool permission control

crates/goose-bench/src/bench_config.rs, crates/goose-bench/src/runners/model_runner.rs
- update config to allow you to pass path to .env file which may contain env vars like provider api keys (so don't have to go through keychain access)
- update evals to set parallel_safe per-eval (as some evals such as Fetch may have trouble running many concurrently)
- small fix to setting GOOSE_MODEL, GOOSE_PROVIDER env vars properly before running the evals
=> feat: goosebench - update bench config

crates/goose-server/src/openapi.rs, crates/goose-server/src/routes/agent.rs, crates/goose/src/agents/extension.rs, crates/goose/src/agents/reference.rs, crates/goose/src/agents/summarize.rs, crates/goose/src/agents/truncate.rs, crates/goose/src/config/permission.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts
Add list query filter to list tools for specified extensions. And use ToolInfo instead of Tool for the response because ToolInfo contains the enough info and adding permission field doesn't have any impact on existing code, while Tool is aligning with MCP Tool definition.
=> feat: add permission field to the list tools response

crates/goose-mcp/src/google_drive/mod.rs
saw multiple instances where goose would try
```
gdrive:///document/$SOME_DOC_ID
```
and fail, not knowing that it needed to only pass in `$SOME_DOC_ID`
* add instructions on mapping URLs to URI format expected (examples are random IDs that don't exist)
* add a check in tool call to look for any extra `/` chars and error out on that
could not find a spec on what a valid ID is, so this is best effort
=> feat: add google_drive uri verification, and example instructions

crates/goose-cli/src/commands/configure.rs, crates/goose/src/config/permission.rs
Remove all extension related tool permissions when we delete the extension
=> feat: remove permission when deleting extension

ui/desktop/src/components/Modal.tsx, ui/desktop/src/components/settings/extensions/ManualExtensionModal.tsx, ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/extensions/modal/EnvVarsSection.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionInfoFields.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionTimeoutField.tsx, ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionItem.tsx, ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx, ui/desktop/src/components/settings_v2/mode/ConfigureApproveMode.tsx, ui/desktop/src/components/settings_v2/mode/ModeSection.tsx, ui/desktop/src/components/settings_v2/mode/ModeSelectionItem.tsx, ui/desktop/src/components/settings_v2/models/ModelsSection.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelButton.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/ModelSettingsButtons.tsx, ui/desktop/src/components/settings_v2/providers/subcomponents/CardContainer.tsx, ui/desktop/src/components/settings_v2/sessions/SessionSharingSection.tsx, ui/desktop/src/components/ui/BackButton.tsx, ui/desktop/src/components/ui/Select.tsx, ui/desktop/src/components/ui/button.tsx, ui/desktop/tailwind.config.ts
**sample screens**
buttons are no longer full-width. secondaries have a different treatment -
synced the input styles - 
extension cards now have a hover state and clicking on the card toggles it -
=> styles: settings v2 

ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/extensions/extension-manager.ts, ui/desktop/src/toasts.tsx
Removes the escape toasts
When adding / deleting an extension, the modal will close automatically while it loads and a loading toast will appear. If the addition/deletion succeeds, then the success toast will appear. If it fails, a failure toast will appear
=> no more esc toasts

documentation/docs/tutorials/pdf-mcp.md
This PR adds the PDF Reader MCP Youtube short to the tutorial page. I also updated the doc to refer to the extension as "PDF Reader" as opposed to just "PDF".
=> docs: adding pdf mcp youtube short

crates/goose/src/config/extensions.rs
Resolves issues when `config.yaml` exists but does not contain an `extensions` value
Previously `goose-server` would return a 500 from `/config/extensions` in this case. Now it simply returns an empty array, and the rest of the app's logic for syncing extensions functions normally afterward.
=> feat: allow empty extensions to return an empty Vec

crates/goose-cli/src/session/output.rs
respect `NO_COLOR` environment variable, https://docs.rs/console/0.15.11/console/fn.colors_enabled.html which we use to print colored text already respects it
```bash
NO_COLOR=1 goose session
```
to disable colors from `bat::PrettyPrinter` and `console::style` usage
=> feat: support NO_COLOR when PrettyPrinter is used

crates/goose-cli/src/session/mod.rs, crates/goose-server/src/routes/reply.rs, crates/goose/src/agents/agent.rs, crates/goose/src/config/permission.rs, crates/goose/src/permission/permission_confirmation.rs, crates/goose/src/permission/permission_judge.rs
Changes in this PR:
1. Smart approve stops checking the tool call arguments, it only checks the tool name and descriptions(tool level check)
2. Smart approve will only provide the default permission for the tool, if users choose always allow the tool, user permission will override the default one.
Test:
```
( O)> write a demo.txt file to my current dir
I'll help you create a demo.txt file in the current directory.
─── text_editor | developer ──────────────────────────
path: ~/Documents/block/goose/demo.txt
command: write
file_text: ...
◆  Goose would like to call the above tool, do you allow?
│  ● Allow (Allow the tool call once)
│  ○ Always Allow 
│  ○ Deny 
```
```
cat ~/.config/goose/permission.yaml 
smart_approve:
always_allow:
- developer__shell
ask_before:
- developer__text_editor …
```
=> feat: use tool level permission control

crates/goose-cli/src/commands/configure.rs, crates/goose-cli/src/session/mod.rs, crates/goose-server/src/routes/extension.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/extension.rs, crates/goose/src/agents/extension_manager.rs, crates/goose/src/config/extensions.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/settings_v2/extensions/bundled-extensions.json, ui/desktop/src/components/settings_v2/extensions/bundled-extensions.ts, ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionItem.tsx
Makes it so bundled extensions (as well as the existing legacy check for `type === 'builtin') do not have editable config in the settings UI
=> feat: non-editable bundled extensions

crates/goose-cli/src/commands/configure.rs, crates/goose/src/agents/extension.rs, crates/goose/src/agents/extension_manager.rs
Test:
```
│
│  Goose Settings 
│
◇  What setting would you like to configure?
│  Tool Permission 
│
◇  Choose an extension to configure tools
│  developer 
│
◇  Choose a tool to update permission
│  developer__screen_capture 
│
└  Configuring tool: developer__screen_capture, Current permission level: Always Allow
◇  Set permission level for tool developer__screen_capture
│  Always Allow 
│
└  Updated permission level for tool developer__screen_capture to Always Allow.
```
=> feat: configure tool level permission in CLI

documentation/docs/tutorials/agentql-mcp.md
This pull request adds a new tutorial to the documentation for integrating the AgentQL MCP Server as a Goose extension. The tutorial includes detailed instructions for both the Goose CLI and Goose Desktop interfaces, as well as an example usage scenario.
Key changes:
* Added a new tutorial file `documentation/docs/tutorials/agentql-mcp.md` for integrating the AgentQL MCP Server as a Goose extension. The tutorial covers configuration steps, example usage, and key insights for planning tech conference submissions.
* Provided step-by-step instructions for configuring the AgentQL extension using the Goose CLI, including commands and environment variable setup.
* Included instructions for configuring the extension using the Goose Desktop interface, with a link to launch the installer and steps …
=> docs: Agentql mcp tutorial

crates/goose/src/permission/permission_judge.rs
Manual approve should be `approve`
=> fix: correct the goose mode name

crates/goose-bench/src/runners/model_runner.rs, crates/goose-bench/src/utilities.rs
The union_hashmap function overwrites selectors with the same suite as hashmap.extend actually overwrites existing keys where we instead want to extend the vector for that key. Fix + code simplification
The error occurs if you have in your goosebench config two selectors like `vibes:goose_wiki` and `vibes:restaurant_research`, only one eval from the vibes suite will be run.
=> fix: goosebench selector collection issue

ui/desktop/src/components/ToolCount.tsx
Popover was translucent and the header/footer text color didnt change for darkmode so it disappeared into the background
=> tool count: fix colors and opacity

crates/goose/src/agents/agent.rs, crates/goose/src/session/storage.rs
Currently, the token usage metadata in the session file only reflects the usage from the last turn-of-conversation. Having accumulated data of input and output token usage is a useful metric for tracking cost over the course of an entire session.
This PR adds `accumulated_input_tokens`, `accumulated_output_tokens` and `accumulated_total_tokens` fields to the `SessionMetadata` and persists them to the session file.
Test Plan:
1. Started a session and terminated it. Session file line 1 at the end:
`{"working_dir":"/Users/sana.verma/goose-fork","description":"Code review discussion","message_count":34,"total_tokens":44226,"input_tokens":43898,"output_tokens":328,"accumulated_total_tokens":343542,"accumulated_input_tokens":341161,"accumulated_output_tokens":2381}`
2. Resumed the session. …
=> Tokens in session file should accumulate for accurate reporting of token usage

ui/desktop/package-lock.json, ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/extensions/deeplink.ts
We had deeplink support for extensions with _no_ env vars, but if we do have env vars, we need a way for users to fill them out. Video below: 
https://github.com/user-attachments/assets/c81e0e07-72ea-413d-ae8e-455d42e4c8a8
=> settingsv2: fix process for deeplinks with env vars

crates/goose-cli/src/cli.rs
copy how we handle `goose session` for the `run` command https://github.com/block/goose/blob/main/crates/goose-cli/src/cli.rs#L405
in the `goose run --interactive` case when a user `ctrl+d` we would get `Error: EOF`
this doesn't happen in the `goose session` case because we `let _ = session...` and ignore the error
do the same thing as the session case to keep it consistent
=> chore: handle errors from goose run like we do with goose session

crates/goose/src/agents/agent.rs, crates/goose/src/permission/permission_judge.rs
instead of having different logic for enable extension and tool call, we can combine them into one.
Note: enable extension tool will always run before normal tools
=> feat: avoid duplicate confirmation handle code

.github/workflows/deploy-docs-and-extensions.yml
This pull request includes changes to the `.github/workflows/deploy-docs-and-extensions.yml` file to improve the deployment process for documentation and extensions. The most important changes include removing the `pull_request` trigger and adding a new configuration to preserve existing files in the `gh-pages` branch.
Workflow trigger changes:
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3L7-L8): Removed the `pull_request` trigger to streamline the deployment process.
Deployment configuration changes:
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R49): Added `keep_files: true` to the `publish_dir` configuration …
=> docs: Update workflow to fix broken pr previews

ui/desktop/package-lock.json, ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx
We used to only check extensions that were of type `builtin` for a `display_name` and if yes, use that to label the Extension card in the setting page -- this is because bundled extensions (defined in json) may have a specific display name we want to show to users
However, some bundled extensions may be of type `stdio` or `sse` so rather than check that `extension.type == 'builtin'` we should check that `extension.bundled == true`. This will make sure that all bundled extensions use the display name if a display name is present in the extension object
=> ui: make sure all bundled extensions use the display name

crates/goose-cli/src/commands/configure.rs, crates/goose-server/src/routes/agent.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/extension_manager.rs, crates/goose/src/agents/reply_parts.rs, ui/desktop/src/components/settings_v2/permission/PermissionModal.tsx
Previously we first list all tool and do the filter, it takes longer time than filter by extension name first.
Test:
```
│
│  Goose Settings 
│
◇  What setting would you like to configure?
│  Tool Permission 
│
◇  Choose an extension to configure tools
│  developer 
│
◇  Choose a tool to update permission
│  developer__list_windows 
│
◇  Set permission level for tool developer__list_windows, current permission level: Always Allow
│  Always Allow 
│
└  Updated permission level for tool developer__list_windows to Always Allow.
```
=> feat: improve tool loading

ui/desktop/src/components/RecipeEditor.tsx
we are able to use the copy button even when the required fields are *not* set, which produces a bad deeplink, disable it until all fields are set like the "open agent"
the cursor changes to the cursor with circle with a slash through it - can't screenshot my cursor
=> feat: disable copy button unless all fields are set

crates/goose/src/agents/agent.rs
previously it was a let _ = ... which would ignore the error from the result and always look like a success
=> fix: propagate errors when attempting to add extensions

crates/goose/src/providers/errors.rs, crates/goose/src/providers/openrouter.rs, ui/desktop/openapi.json
Support parsing error code as number, in openrouter, the error code is number instead of string, so we will not expose the error detail to user.
Before:
After:
=> fix: expose tool not support error

ui/desktop/src/App.tsx, ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/BottomMenuModeSelection.tsx, ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/mode/ModeSection.tsx, ui/desktop/src/components/settings_v2/mode/ModeSelectionItem.tsx, ui/desktop/src/components/settings_v2/permission/PermissionSetting.tsx
We use the parentView to track which view page we should go back from permission page. When we enter permission view from the bottom menu, we should go back to the chat view, otherwise, go back to the setting view
https://github.com/user-attachments/assets/30de6e10-68a4-418d-82eb-947dbb96fc9a
=> feat: use the permission page in bottom menu

crates/goose/src/providers/utils.rs
Similar to https://github.com/block/goose/pull/2228
Fix #1589
Before:
After:
=> fix: expose not support tool call error

crates/goose/src/providers/openai.rs, documentation/docs/getting-started/providers.md
Having this value available in the config file makes it much easier not to lose track of the header
=> feat: allow OPENAI_CUSTOM_HEADERS to be set in goose config

crates/goose-cli/src/session/output.rs
Previously, theme was not persisted across sessions because it was reading from an environment variable. Now, theme is also stored in config and read from there.
Testing:
Changed to Light mode in a session:
In a new terminal, started a new session and verified it stayed in light mode:
=> Make GOOSE_CLI_THEME persist to config file and stick for future session

crates/goose-cli/src/commands/configure.rs, crates/goose-cli/src/session/mod.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/platform_tools.rs, crates/goose/src/agents/tool_execution.rs, crates/goose/src/message.rs, crates/goose/src/permission/permission_judge.rs, crates/goose/src/prompts/system.md, ui/desktop/openapi.json, ui/desktop/src/components/ExtensionConfirmation.tsx, ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/types/message.ts
Part of AAI-301
* Allows enabling and disabling of one or more extensions, previously just one
* Simply changes _extension_ naming to -> _extensions_ and passes in a vec instead of string
=> feat: handle enabling and disabling multiple extensions

crates/goose-server/src/routes/extension.rs
comments out the allowlist checks. added a bunch of `#[allow(dead_code)]` to just comment out allowlisting for now
=> revert: check is_command_allowed for allowlisted extensions

ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
=> fix: update the extension section border

Cargo.lock, crates/goose-server/src/routes/agent.rs
Previously we use the write lock which may cause the deadlock issue when listing tools during chat
=> fix: resolve the deadlock while listing tools

crates/goose-cli/src/commands/configure.rs, crates/goose-server/src/routes/extension.rs, crates/goose/src/agents/extension.rs, crates/goose/src/agents/extension_manager.rs
Expectations:
- `goose configure`: when configuring extensions only write the env key to config.yaml and write to values to keychain. If keychain write fails, default to writing env key/value pair to config as envs
- `agent.add_extension`: uses the extension configuration to set the full envs before starting server. it'll use envs (empty if not there), and then for env_keys it will pull the values from keychain and append to the envs hash map, which is passed along to transport
- `add_extension` route on goose-server: remove logic for pulling in keychain secrets and sending full envs as this is handled on the agent side now. only pass through env_keys.
=> feat: enhance extension environment variable security

crates/goose-server/src/routes/extension.rs, crates/goose/src/agents/extension_manager.rs, ui/desktop/src/utils/providerUtils.ts
* update config migration to 3, this was already sending env_keys and now the backend handles it to write to the config.yaml, so we just need to call that endpoint again
* update ExtensionConfigRequest to accept envs , looks like we were also already sending envs in the payload, just dropping it
=> feat: migrate config v3, update extensions/add to accept envs map

ui/desktop/src/App.tsx, ui/desktop/src/main.ts, ui/desktop/src/preload.ts, ui/desktop/test-extension-dialog.js
This uses the GOOSE_ALLOWLIST (if set) to check that the extension being proposed from a deeplink is valid: 
(you can override and install it after this warning). if there is no allowlist or not valid, it will not show
This will not affect already installed extensions
=> GUI warning when installing extension from deeplink

Cargo.lock, crates/goose/Cargo.toml, crates/goose/src/config/base.rs, ui/desktop/openapi.json, ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionItem.tsx
* Adds file locking when writing to `config.yaml` for extensions configuration
* Disables the toggleable input for enabling/disabling an extension when the writes are in progress
=> fix: extension config write locks

crates/goose-cli/src/session/builder.rs
Improving confusing messaging when session workdir and current workdir doesn't match.
=> goose: improve message for change workdir warning

documentation/docs/quickstart.md
- added quickstart videos to the Goose CLI and Goose Desktop sections of the quickstart page to provide a visual guide for users
- made Desktop the default tab
**Collapsed**
**Expanded**
**Mobile**
=> docs: adding quickstart videos to quickstart page

crates/goose/src/agents/agent.rs, crates/goose/src/agents/extension_manager.rs, crates/goose/src/agents/platform_tools.rs, crates/goose/src/agents/prompt_manager.rs, crates/goose/src/agents/reply_parts.rs, crates/goose/src/permission/permission_judge.rs, crates/goose/src/prompts/system.md, ui/desktop/openapi.json
* Adds a disable extension capability for mcp router
* Rebases on agent refactor, also extension enabling now falls under tool permissions, which simplifies the code
--- 
**1.** goose will bring up that you have too many extensions enabled unprompted. As well, goose does not bring it up again if you decline.
--- 
**2.** repurposes `search_available_extensions` to also show extensions available to disable
--- 
**3.** disable occurs as tool calls, individually
=> feat: mcp router disable extensions

documentation/docs/getting-started/providers.md, documentation/docs/getting-started/using-extensions.md, documentation/docs/guides/handling-llm-rate-limits-with-goose.md, documentation/docs/tutorials/computer-controller-mcp.md, documentation/docs/tutorials/developer-mcp.md, documentation/docs/tutorials/filesystem-mcp.md, documentation/docs/tutorials/jetbrains-mcp.md, documentation/docs/tutorials/memory-mcp.md, documentation/docs/tutorials/tutorial-extension.md
User created a Discussion post informing us that the docs don't not matching the UI. Docs say settings. UI says Advanced Settings. https://github.com/block/goose/discussions/2251
I opened an issue to track it #2329
=> docs: update from settings to advanced settings

ui/desktop/openapi.json, ui/desktop/src/components/settings_v2/models/index.ts, ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx
* Leverage the new `/agent/update_provider` endpoint to make it a simpler process when we add/change models
* Replace the call to `initializeSystem` in `changeModel` with a simpler call to `initializeAgent` which doesn't need to do anything with extensions
* Simplify signature of `changeModel` now that it doesn't need extension management methods passed through
=> feat: add/change model without reinit of extensions

ui/desktop/src/components/settings_v2/extensions/utils.ts
This fix allows for extension commands to be paths to local binaries (e.g. the vantage-mcp). The fully qualified path was being removed when the toolshim's were being used (i.e. when using the UI). This only looks for the existing shims that we support and pass through commands with full paths through.
=> fix: only remove toolshim paths that we know of to preserve full paths to extension binaries

crates/goose-mcp/src/google_drive/mod.rs
We have two create tools and two update tool, one for google drive file, one for non-google files.
We can combine them into one to reduce the # of gdrive tools
=> feat: reduce the # of gdrive tools

crates/goose/src/model.rs
Included `gemini-2.5` and `gemini-2-5` (as well as `gpt-4.1` and `gpt-4-1`) as occasionally model names use the `-` over the `.`
=> Add context limits for latest gemini and gpt models

documentation/docs/guides/tips.md
updated description. currently it shows as this
=> docs: add description for Quick Tips guide

crates/goose/src/providers/errors.rs
Fix #2314
Before:
```
◇  Enter a model from that provider:
│  gemma3:27b-it-qat
│
◇  Request failed: Unknown error (status 404 Not Found)
│
└  Failed to configure provider: init chat completion request with tool did not succeed.
```
After:
```
◇  Enter a model from that provider:
│  gemma3:27b-it-qat
│
◇  Request failed: registry.ollama.ai/library/gemma3:27b-it-qat does not support tools (type: api_error) (status 400)
│
└  Failed to configure provider: init chat completion request with tool did not succeed.
```
=> fix: expose ollama error

documentation/docs/guides/environment-variables.md
Topic was missing closing code fences for a few bash examples, causing following markdown content to be formatted as code
=> Added missing code fence close ticks

crates/goose-mcp/src/google_drive/mod.rs
The file fetch doesn't return the mime type as it is not required in request params, we can use pre fetched mime type
Test:
=> fix: use the pre-fetched mime type

crates/goose-llm/src/completion.rs, crates/goose-llm/src/lib.rs, crates/goose-llm/src/types.rs
```
❯ cargo run -p goose-llm --example simple
User Input: Add 10037 + 23123
Completion Response:
{
...
"runtime_metrics": {
"total_time_ms": 11842,
"total_time_ms_provider": 4167,
"tokens_per_second": 238.06095512359013
}
}
```
=> feat: add runtime metrics to completion response

documentation/docs/guides/goose-cli-commands.md
Apparently it was removed at #2091.
=> docs: Remove "agent" subcommand which does not exist.

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/managing-goose-sessions.md
This pull request adds documentation for the new `goose session remove` CLI command, which allows users to delete saved sessions either by specific ID or using a regex pattern. The changes include updates to both the CLI command reference and the session management guide.
* **CLI Command Reference (`documentation/docs/guides/goose-cli-commands.md`)**:
- Added a new section detailing the `goose session remove` command, its options (`-i` for ID and `-r` for regex), and usage examples. The command includes a confirmation step before deletion.
* **Session Management Guide (`documentation/docs/guides/managing-goose-sessions.md`)**:
- Introduced a "Remove Sessions" section explaining how to use the `goose session remove` command in the CLI. This includes examples for removing sessions by ID or …
=> docs: Removing sessions

ui/desktop/src/components/ChatView.tsx, ui/desktop/src/components/context_management/ContextLengthExceededHandler.tsx
Handles case where summarization fails -- user can retry fetching summary twice and after that user will be prompted to start a new session 
Errors in summarization in my testing have only been caused by giant tool responses -- because these tool responses do not get summarized we can end up with a summary that is still outside the context window for the LLM
**NOTE: This PR also moves summarization to production**
=> cxt-mgmt: only two retries for summarization and move to prod

crates/goose-llm/src/completion.rs, crates/goose/src/agents/prompt_manager.rs
Fix #2431
We have the current [timestamp](https://github.com/block/goose/blob/8ba40bdccc3bc5b1068394ea52f45c3de773ec35/crates/goose/src/prompts/system.md?plain=1#L3) in our system prompt, the timestamp was the real timestamp of the reply, this would lead the prompt cache invalidation as our system prompt has such dynamic content. Since the prompt cache only lasts 5 minutes, we can use the timestamp with hours to avoid the frequent cache invalidation
=> fix: use less strict timestamp in system prompt

crates/goose-cli/src/session/output.rs
A default priority of 0.0 for CLI is just too verbose - 0.5 seems much nicer as a default value (these can be overridden but probably better to start with something that doesn't fill the screen for routine editing/work)
=> this is so much nicer

Justfile, crates/goose-server/ALLOWLIST.md, ui/desktop/src/App.tsx, ui/desktop/src/main.ts
SSE extensions just get a warning notice (as risk profile is different)
MCP stdio will now block if an allowlist is enabled.
=> allowlist blocks and shift SSE to warning

crates/goose-cli/src/session/input.rs, crates/goose-cli/src/session/mod.rs
Adds a `/summarize` slash command that allows the user to summarize their current session on command
=> cli: add summarize slash command

ui/desktop/src/components/SplashPills.tsx
This allows an option `message:` to be specified to show up as a message of the day/welcome message for when a recipe deep link is activated in the GUI: 
doesn't change usual operation
To use it, have one of the activity messages start with `message:` prefix to have it show up that way, instead of a "splash bubble". This has been asked for as when people click on a deep link, the context may not be obvious, so gives a chance to present it to the user. 
Example for the above to try: 
```
goose://recipe?config=eyJpZCI6Im1lc3NhZ2UtcmVjaXBlIiwibmFtZSI6Ik1lc3NhZ2UgUmVjaXBlIiwidGl0bGUiOiJSZWNpcGUgd2l0aCBNZXNzYWdlIiwiZGVzY3JpcHRpb24iOiJBIHJlY2lwZSB3aXRoIGEgbWVzc2FnZSBkaXNwbGF5ZWQgcHJvbWluZW50bHkiLCJhY3Rpdml0aWVzIjpbIm1lc3NhZ2U6IFRoaXMgcmVjaXBlIGRlbW9uc3RyYXRlcyBob3cgdG8gdXNlIHRoZSBtZXNzYWdpbmcgZm …
```
=> recipe welcome message

crates/goose-cli/src/cli.rs, crates/goose-cli/src/session/mod.rs
Small improvement to the UX of CLI `--resume` command.
If the resume flag is passed, render all previous messages, so a user can understand where the agent left off in the previous conversation.
=> load all previous messages if --resume is passed

crates/goose/src/providers/formats/databricks.rs, crates/goose/src/providers/formats/openai.rs
Previously, tool descriptions were truncated to 1024 characters to conform to an assumed OpenAI limit. This truncation is now removed to avoid silent behavior changes and make debugging easier. OpenAI no longer appears to enforce this limit, so it's better to allow full descriptions and surface any real errors explicitly.
=> Remove outdated truncation of tool descriptions in OpenAI and Databricks providers

ui/desktop/src/components/ToolCallArguments.tsx, ui/desktop/src/components/ToolCallWithResponse.tsx, ui/desktop/src/components/ui/scroll-area.tsx
Currently goose won't always follow along once you add a subsequent command (this happens with compact or expanded tools)
This PR also adds short tool descriptions that were missing when in compact mode
dark mode:
=> fix: will now correctly follow along with tool results

crates/goose-server/src/openapi.rs, crates/goose/src/message.rs, crates/goose/src/providers/formats/anthropic.rs, crates/goose/src/providers/formats/bedrock.rs, crates/goose/src/providers/formats/databricks.rs, crates/goose/src/providers/formats/openai.rs, ui/desktop/openapi.json, ui/desktop/src/App.tsx, ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/ChatView.tsx, ui/desktop/src/components/bottom_menu/BottomMenu.tsx, ui/desktop/src/components/context_management/ChatContextManager.tsx, ui/desktop/src/components/context_management/ContextHandler.tsx, ui/desktop/src/components/context_management/ContextManager.tsx, ui/desktop/src/components/context_management/ManualSummaryButton.tsx, ui/desktop/src/components/context_management/index.ts, ui/desktop/src/hooks/useMessageStream.ts, ui/desktop/src/types/message.ts
This allows users to summarize their conversations on command. Uses similar flow as CLE events
1. User clicks button
2. This button click inserts a 'summarizationRequested' message into the message list 
3. The rest of the flow is the same as how we handle CLE events, I just added an additional check for the `summarizationRequested` message type in addition to the `contextLengthExceededMessage` type. If either of those conditions are met, then we go the same summarization process
4. I modified the text around the summarization (see video) to differentiate it from the CLE events 
5. 
https://github.com/user-attachments/assets/cf842bf5-864e-4e4f-ba99-b811f34f11b2
=> ctx_management: summarize on command button

documentation/docs/tutorials/pieces-mcp.md, documentation/docs/tutorials/postgres-mcp.md
This pull request updates the documentation for two tutorials by embedding YouTube short videos to enhance the learning experience. The changes include the addition of a reusable `YouTubeShortEmbed` component and its integration into the respective tutorial files.
* **Pieces for Developers MCP Server Tutorial**:
- Embedded a YouTube short video using the `YouTubeShortEmbed` component to provide a visual walkthrough. (`documentation/docs/tutorials/pieces-mcp.md`, [documentation/docs/tutorials/pieces-mcp.mdR9-R12](diffhunk://#diff-522415b372265f73c241b58601f431b589c393b28b391090badceba47ff5b2cbR9-R12))
* **PostgreSQL MCP Server Tutorial**:
- Added a YouTube short video embed to visually demonstrate the PostgreSQL MCP Server extension's functionality. …
=> docs: Adding YT short to Pieces and Postgres Tutorial

ui/desktop/openapi.json, ui/desktop/src/components/GooseMessage.tsx
I don't know what change caused this, but `MessageCopyLink` components were not clickable on `GooseMessage`s
=> fix: Make MessageCopyLinks clickable again on goose messages

documentation/docs/tutorials/youtube-transcript.md
Currently the [Youtube Transcript](https://block.github.io/goose/docs/tutorials/youtube-transcript) extension page installer is broken. Returning an error like this:
`Error: Error activating extension: Failed to add extension configuration, error: Initialization(Stdio { name: "youtubetranscript", cmd: "/private/var/folders/45/n6wzns216zl85v_c_37cmhyc0000gn/T/AppTranslocation/BF82C9F6-4794-45E3-919B-5824D8C2FC64/d/Goose.app/Contents/Resources/bin/npx", args: ["-y", "@jkawamoto/mcp-youtube-transcript"], envs: Envs { map: {} }, env_keys: [], timeout: Some(300), description: None, bundled: None }, McpServerError { method: "initialize", server: "", source: ServerBoxError(StdioProcessError("npm error code E404\nnpm error 404 Not Found - GET …
=> Fix error on installation of Youtube Transcript extension

documentation/docs/tutorials/nostrbook-mcp.md
This is related to: https://github.com/block/goose/pull/2500  
Sorry, I should have tripled checked.
=> docs: fix typo in nostrbook mcp tutorial

documentation/docs/guides/session-recipes.md
added documentation about creating and using recipes with parameters
=> docs: recipe parameters

crates/goose-cli/src/cli.rs, crates/goose-cli/src/commands/bench.rs, crates/goose-cli/src/session/builder.rs, crates/goose-cli/src/session/output.rs
this will be a helpful option for massive automations using goose
=> allow running `goose run` with no session persistence

crates/goose-cli/src/session/mod.rs
Title.
We do generally use config.yaml for such configurations, so I think it would be better if both `GOOSE_PLANNER_MODEL`/`GOOSE_PLANNER_PROVIDER` are consistent with `GOOSE_MODEL` and `GOOSE_PROVIDER`
=> Allow putting GOOSE_PLANNER_MODEL and GOOSE_PLANNER_PROVIDER to config.yaml

crates/goose-ffi/README.md
I was getting this error when trying to build goose ffi
```
cargo build --release --package goose_ffi
error: package ID specification `goose_ffi` did not match any packages
help: a package with a similar name exists: `goose-ffi`
```
=> chore: fix docs for building goose ffi

crates/goose-cli/src/cli.rs, crates/goose-cli/src/commands/bench.rs, crates/goose-cli/src/session/builder.rs, crates/goose/src/agents/agent.rs, crates/goose/src/lib.rs, crates/goose/src/tool_monitor.rs
Adds a new tool monitoring system that can detect and prevent infinite loops caused by repeated identical tool calls. The implementation includes:
- New ToolMonitor struct for tracking tool call patterns
- CLI flag --max-tool-repetitions to configure limits
- Integration with Agent dispatch system
- Session configuration support
The monitor tracks consecutive identical tool calls and can prevent them after a configurable limit is reached, helping prevent cases where the AI gets stuck in a loop making the same tool call repeatedly.
Example usage:
goose run --max-tool-repetitions 5 ...
=> feat: add tool repetition monitoring to prevent infinite loops

documentation/docs/guides/managing-goose-sessions.md
Add "Search Session History" session to documentation/docs/guides/managing-goose-sessions.md
=> docs: add search session history section

Cargo.lock, crates/goose-cli/Cargo.toml, crates/goose-cli/src/recipes/github_recipe.rs, crates/goose-cli/src/recipes/print_recipe.rs, crates/goose-cli/src/recipes/recipe.rs, crates/goose-cli/src/recipes/search_recipe.rs
**Why**
https://github.com/block/goose/issues/2559
[Jira ticket](https://block.atlassian.net/browse/DX-790).
Make it easy for users to refer additional files in the recipe. For example: https://github.com/squareup/goose-recipes/tree/lifei/test-recipe-dir/test-recipe. 
In the example, the theme.txt is very simple, but user can have files to provide additional context or data and refer them in the recipe.
**What**
Introduced a built-in param `recipe_dir`, the value is the parent directory of the recipe file, user can use the parameter value to refer the location of the files they needed in the recipe such as extra context or data.   
If the recipe is shared on github, these files can be added in the same directory.  When Goose pulls the recipe from the github, and these files will be pulled …
=> added recipe_dir

documentation/docs/tutorials/fetch-mcp.md
removing the warning about gemini models when using the fetch mcp
=> docs: remove fetch limitation

.github/workflows/ci.yml
We would like to enforce checks before merge, but this makes the documentation build looks like it stalls (if only docs changes are made), this corrects that (at the cost of running CI for doc only changes for now, which can be optimised away by caching)
=> run CI on docs so we can enforce checks

crates/goose/src/model.rs
And remove o1 as it is deprecated
=> fix: update o3/mini and o4 mini context limit

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/running-tasks.md
This pull request documents how to enable debug mode in the Goose CLI.
- `documentation/docs/guides/goose-cli-commands.md`: Doc the `--debug` option for the `session` and `run` commands.
- `documentation/docs/guides/running-tasks.md`: Add "Debug Mode" section.
=> docs: debug mode

documentation/docs/getting-started/using-extensions.md
This pull request documents the base commands that can be used in deeplinks for installing extensions.
- `documentation/docs/getting-started/using-extensions.md`: In the "Deeplinks" section, list allowed commands in the `cmd` description for StandardIO
=> docs: list allowed deeplink commands

documentation/docs/tutorials/square-mcp.md
Adding [Square MCP walkthrough video](https://www.youtube.com/watch?v=y6pklrzhzNg) to tutorial page. 
There's something smelly about how the two video components sit side by side. Would love any thoughts on how we can make this look a bit better.
=> docs: adding Square MCP video to tutorial page

crates/goose-llm/src/providers/utils.rs, crates/goose/src/providers/utils.rs
- extend `test_load_image_file` to verify `.gif` files are rejected
- detect GIF header bytes so unsupported format is reached
- `cargo test -p goose providers::utils::tests::test_load_image_file -- --nocapture` *(fails: could not connect to crates.io)*
=> Add GIF unsupported format test

documentation/docs/guides/session-recipes.md
define the parameters used to the recipe yaml with the required info, otherwise the `goose recipe validate` does not work.
=> update docs around parameters

documentation/docs/guides/goose-cli-commands.md
Document new `--explain` flag used when running a recipe.
=> Docs: recipe explain flag in CLI commands

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/managing-goose-sessions.md
This pull request documents the `project` and `projects` commands.
- `documentation/docs/guides/goose-cli-commands.md`: Added the `project` and `projects` commands
- `documentation/docs/guides/managing-goose-sessions.md`: Added a tip under the "Start Session" and "Resume Session" sections that links to the command descriptions
=> docs: add project and projects commands

documentation/docs/quickstart.md
Community member pointed out that quickstart guide doesnt include intel option. I included options for Intel, MacOS, linux, windows.
=> docs: Quickstart Intel Installation method

documentation/docs/guides/tool-router.md
Devs kindly created and merged this doc, but this feature is unreleased and not using some of our format, so let's hide it for now
=> docs: Temporarily hide tool router doc

crates/goose/src/agents/large_response_handler.rs
The limit was set to 20K chars, which was a bit low, well below context windows, but for some tools (eg JIRA) it was hurting performance by a large factor. 
This will still keep it under context windows so should be useful but hopefully not practically hurt performance.
=> fix: increase limit for direct to disk for performance

documentation/docs/tutorials/context7-mcp.mdx
Replaced the placeholder video embed with the actual YouTube Short for the Context7 MCP tutorial.
- Updated `videoUrl` in `Context7 MCP` tutorial:
- From: `"https://www.youtube.com/embed/VIDEO_ID"`
- To: `"https://www.youtube.com/embed/LNmPi6YCocI"`
The embedded video now shows the actual tutorial walkthrough, helping users better understand how to set up the Context7 MCP extension in Goose. No more broken video embeds!
=> docs: Add Context7 YouTube Video

documentation/docs/tutorials/google-drive-mcp.md
Normalizes all path references to credential files to use `$USER_HOME` and clarifies the documentation accordingly. Also clarifies that absolute paths are required. Without this, the plugin does not start on Mac OS.
=> Fix paths in google drive mcp documentation

bindings/kotlin/example/Usage.kt, bindings/kotlin/uniffi/goose_llm/goose_llm.kt, crates/goose-llm/Cargo.toml, crates/goose-llm/README.md, crates/goose-llm/examples/prompt_override.rs, crates/goose-llm/examples/simple.rs, crates/goose-llm/src/completion.rs, crates/goose-llm/src/types/completion.rs
we could have included the entire tool name in the prompt, eg. tile_creator__list_available_extensions. this one can be a bit tricky cause for other tool calls that we need to gather such as extension: slack, tool: lookup_sources -> we dont want the __ formatting.  instead, we allow system prompt override so we can experiment a bit quicker on the prompt
=> [goose-llm] system prompt override

documentation/static/servers.json
This PR adds the Speech MCP extension to the extensions directory, making it discoverable through the  page.
- Added  entry to 
- Includes comprehensive extension details:
- Voice interaction with audio visualization
- Real-time voice interaction, audio/video transcription, text-to-speech
- Multi-speaker audio generation capabilities
- Installation via `uvx -p 3.10.14 speech-mcp@latest`
- PortAudio requirement noted in installation notes
- 43 GitHub stars, marked as endorsed
The Speech MCP extension already has:
- ✅ Comprehensive tutorial at `documentation/docs/tutorials/speech-mcp.md`
- ✅ Blog post about "Vibe Coding with Goose and the Speech MCP"
- ✅ Active GitHub repository: https://github.com/Kvadratni/speech-mcp
- ✅ Working deep-link installation for Goose Desktop
This PR completes …
=> Add Speech MCP extension to extensions directory

crates/goose/src/config/base.rs
fixes issues with saving config on windows
=> debug config issues on windows

ui/desktop/src/components/RecipeEditor.tsx
gate the scheduler behind an alpha flag so we can release 1.0.25 - scheduler aimed release 1.0.26
note the dark mode colors may need to be tweaked
=> feat(ui): put the scheduler behind an alpha

ui/desktop/package-lock.json, ui/desktop/package.json, ui/desktop/src/main.ts
nuff said 
https://github.com/user-attachments/assets/4aae0ab1-acfd-4c16-acc0-9dd603151a00
=> remember window position

documentation/docs/getting-started/installation.md
Closes: https://github.com/block/goose/issues/2644
---
=> Update macOS install guide with Homebrew instructions

documentation/docs/tutorials/nostrbook-mcp.md
The Nostrbook MCP was previously developed in Deno, and required weird hacks to get it working with Node. Now it runs directly in node: https://www.npmjs.com/package/@nostrbook/mcp
=> Nostrbook MCP is now on npm

crates/goose-cli/src/session/mod.rs, crates/goose-cli/src/session/output.rs
Cleans up tool streaming output in interactive mode.
Before:
https://github.com/user-attachments/assets/06c1d97e-63bd-4230-b82d-32967e203e6f
After:
https://github.com/user-attachments/assets/601fb700-90d2-4c47-9038-298d4ae9e106
=> fix: Use the existing spinner in interactive mode

Cargo.lock, crates/goose-cli/Cargo.toml, crates/goose-cli/src/commands/recipe.rs, ui/desktop/src/main.ts
**Why**
Without the encoding/decode uri, the deeplink generated for recipe containing "```" cannot be decoded on Desktop side. It will show error.  [Example recipe](https://github.com/squareup/goose-recipes/blob/main/weekly-updates/recipe.yaml)
**What**
Added the uri encoding on Rust side and uri decoding on Desktop side to handle the deeplink for recipe.
=> fix: added url encoding and decoding for goose recipe url

ui/desktop/src/components/RecipeExpandableInfo.tsx, ui/desktop/src/components/RecipeInfoModal.tsx
Dark mode themes weren't applied to some parts of the recipe view.
=> Fix: Adding dark mode support for recipe modal

documentation/docs/guides/smart-context-management.md
This PR documents the new token usage display features in the Goose CLI in the [Smart Context Management](https://block.github.io/goose/docs/guides/smart-context-management) topic.
- `documentation/docs/guides/smart-context-management.md`: 
- Move intro out from Desktop tab 
- Describe CLI usage info
=> docs: add CLI token usage

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/managing-goose-sessions.md
This pull request introduces a new feature to Goose CLI: the ability to export sessions to Markdown format. It includes updates to the documentation to explain the feature, its usage, and its options. The changes aim to improve usability for sharing, documenting, and archiving sessions.
* **Documentation update in `goose-cli-commands.md`:** Added a new section detailing the `session export` command, including options (`--name`, `--path`, `--output`) and example usage for exporting sessions to Markdown format.
* **Documentation update in `managing-goose-sessions.md`:** Added a section on exporting sessions, including instructions for Goose Desktop and Goose CLI, and links to further details on CLI export options.
=> Docs: Session Export via CLI

crates/goose/src/temporal_scheduler.rs, temporal-service/main.go, ui/desktop/openapi.json, ui/desktop/src/goosed.ts
This should fix the problem for temporal startup on just commands and on directly running of the Goosed server.
=> dynamic port selection for temporal

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/session-recipes.md
Document the `schedule` command in the CLI commands doc and the Shareable Recipes doc
=> Docs: Schedule recipes with the CLI

documentation/docs/guides/smart-context-management.md, documentation/src/css/custom.css
fix #2788
fix #2883 
- Removed `goose configure set GOOSE_CONTEXT_STRATEGY summarize` as that's not a current command.
- Fixed navbar breakpoints, so it shows hamburger menu earlier rather than having overlapping menu items.  
https://github.com/user-attachments/assets/f1ff755b-6e95-42c6-87d5-b4402fbbd36b
=> Docs: Fix Nav Bar and wrong command in docs

crates/mcp-client/examples/integration_test.rs, crates/mcp-client/src/client.rs
Previously the message handling block treated only JsonRpcMessage::JsonRpcResponse types with ids as request responses, and all other messages were sent to the notification stream. But, servers may send back a JsonRpcError which is distinct from JsonRpcResponse. This should not be sent to the notification stream.
Also added this to the integration test.
Fixes #2884
=> fix: handle JsonRPC error variants as responses

crates/goose-cli/src/session/builder.rs
This pull request improves error handling in the `build_session` function of the `goose-cli` crate. Specifically, it replaces an `unwrap` call with a more robust error-handling mechanism to provide user-friendly error messages and guidance.
* Updated the `build_session` function in `crates/goose-cli/src/session/builder.rs` to replace the `unwrap` call with a `match` statement. This change ensures that errors during the creation of a provider are caught and handled gracefully. If an error occurs, a detailed error message is displayed, including troubleshooting steps and a link to relevant documentation, before the process exits with a non-zero status.
The error message displayed when no keyring is found is different from what [the goose …
=> fix: handled the missing keyring error gracefully with a user-friendly message

crates/goose/src/agents/router_tool_selector.rs
Fix the error:
```
error[E0050]: method `index_tools` has 2 parameters but the declaration in trait `RouterToolSelector::index_tools` has 3
--> crates/goose/src/agents/router_tool_selector.rs:285:26
|
28  |     async fn index_tools(&self, tools: &[Tool], extension_name: &str) -> Result<(), ToolError>;
|                          ------------------------------------------- trait requires 3 parameters
...
285 |     async fn index_tools(&self, tools: &[Tool]) -> Result<(), ToolError> {
|                          ^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters, found 2
For more information about this error, try `rustc --explain E0050`.
```
=> fix router trait error

crates/goose-bench/src/assets/kubernetes_swagger.json, crates/goose/src/agents/extension.rs, crates/goose/src/agents/router_tools.rs, crates/goose/src/prompts/system_gpt_4.1.md, crates/goose/src/providers/oauth.rs, crates/mcp-server/src/main.rs
This PR corrects various spelling errors found throughout the codebase in error messages, documentation, and configuration files. 
- extension.rs: Fixed "accomodate" → "accommodate" in context limit error message
- router_tools.rs: Fixed "Imporant" → "Important" in tool selection instructions
- system_gpt_4.1.md: Fixed "CRITIAL" → "CRITICAL" in system prompt documentation
- oauth.rs: Fixed "recieve" → "receive" in OAuth flow comment
- main.rs (mcp-server): Fixed "agrument" → "argument" in example prompt description
- kubernetes_swagger.json: Fixed "classses" → "classes" in DeviceClassSpec descriptions (2 instances)
=> fix: correct spelling in error messages and documentation

documentation/docs/guides/config-file.md, documentation/docs/guides/creating-plans.md, documentation/docs/guides/environment-variables.md
This PR updates docs for the lead/worker model section in the Environment Variables topic and adds links from related topics.
- `documentation/docs/guides/environment-variables.md`: Updated lead/worker model section with additional description about behavior.
- `documentation/docs/guides/config-file.md`: Added `GOOSE_LEAD_PROVIDER` and `GOOSE_LEAD_MODEL` settings to the configuration file. Also linked to the Environment Variables topic.
- `documentation/docs/guides/creating-plans.md`: Added tip about the lead/worker mode alternative with link to related content.
=> docs: updates for lead-worker model

crates/goose-cli/src/cli.rs
A system prompt could only be passed through recipes in the `run` command. This param makes it easier
=> feat(cli): add system prompt parameter to run command

.github/workflows/bundle-desktop-windows.yml, .github/workflows/canary.yml, .github/workflows/pr-comment-bundle-windows.yml, .github/workflows/release.yml, ui/desktop/forge.config.ts
props to @finn-block for helping me through this
=> enabling windows builds with code signing

crates/goose-cli/src/commands/configure.rs
In the `goose configure` CLI, extensions are now sorted alphabetically.
=> feat: alphabetize extensions in goose CLI

ui/desktop/src/components/settings/extensions/modal/EnvVarsSection.tsx, ui/desktop/src/components/settings/extensions/modal/ExtensionModal.tsx
This PR adds a confirmation dialog when users try to close the extension modal with unsaved changes, preventing accidental loss of configuration data.
I had experienced frustration when accidentally clicking outside the extension modal (backdrop) accidentally after entering API keys that I had copied and closed the window that they came from causing me to re-generate the keys.
We listen for changes in the environment variables and the command fields for requiring the prompt, since the name/description fields are a bit easier to reproduce.
https://github.com/user-attachments/assets/ab790a18-87e3-45fd-9277-b63718810702
=> feat(ui): Add confirmation dialog for unsaved changes in extension modal

documentation/docs/guides/session-recipes.md
Document optional settings for recipe `yaml` files. 
https://github.com/block/goose/pull/2397/files
=> Docs: Recipe settings

crates/goose-bench/src/assets/kubernetes_swagger.json, crates/goose-llm/src/extractors/session_name.rs, crates/goose-llm/tests/extract_session_name.rs, crates/goose/src/prompts/plan.md, crates/goose/src/prompts/system_gpt_4.1.md
https://github.com/block/goose/issues/2812
Updating Goose default prompts to use standard ascii quotation marks instead of unicode quotation marks. It's a small change but every token counts.
| Before | After |
| --- | --- |
| ![Before](https://github.com/user-attachments/assets/a4306263-dee3-45d4-ba4a-a1dca32e3a3c) | ![After](https://github.com/user-attachments/assets/3e8f6d97-63de-4885-9ebc-0b3e94a8304c)
[open ai tokenizer ui](https://platform.openai.com/tokenizer)
=> [fix][small] Replaced goose prompt unicode quotations with ascii quotations

documentation/docs/getting-started/installation.md, documentation/docs/guides/updating-goose.md, documentation/docs/quickstart.md, documentation/src/components/LinuxDesktopInstallButtons.js
This pull request introduces support for Linux installations of Goose Desktop and updates the documentation to reflect these changes. The most important updates include the addition of a new component for Linux installation buttons, updates to installation instructions across multiple documentation files, and enhancements to the update process for Goose CLI and Desktop on Linux and Windows.
* [`documentation/src/components/LinuxDesktopInstallButtons.js`](diffhunk://#diff-6442dbb0af7be033dc433df0ec23196ce16d0d820ed6189831764be54837c354R1-R32): Added a new component, `LinuxDesktopInstallButtons`, that provides download links for Goose Desktop on Linux, including x86_64, ARM64, and RPM packages.
* [`documentation/docs/getting-started/installation.md`](diffhunk://#diff-1da95befef448a968841697b …
=> Docs linux desktop

crates/goose-cli/src/commands/web.rs, crates/goose-cli/static/index.html, crates/goose-cli/static/style.css
Resolves: https://github.com/block/goose/issues/2987
Tested locally:
=> Use official logo in Goose web

documentation/blog/2025-06-19-isolated-development-environments/index.md
This pull request updates the blog post `2025-06-19-isolated-development-environments/index.md` to enhance its content and presentation. The changes include improving metadata tags and embedding a video player for better user engagement.
Content enhancements:
* [`documentation/blog/2025-06-19-isolated-development-environments/index.md`](diffhunk://#diff-c50c51129d7cf4e6405d3e50c3477c60f79e5b44373a6cd44a9a0ecc0f7385e8L6): Removed the `tags` metadata line, which previously included keywords like `extensions`, `containers`, and `development`.
Presentation improvements:
* [`documentation/blog/2025-06-19-isolated-development-environments/index.md`](diffhunk://#diff-c50c51129d7cf4e6405d3e50c3477c60f79e5b44373a6cd44a9a0ecc0f7385e8R107-R120): Added an embedded YouTube video player with responsive …
=> Blog: Add video to container use blog

crates/goose/src/providers/openrouter.rs
The OpenRouter known models are outdated. In the case of `google/gemini-2.5-pro-exp-03-25:free` it no longer exists on OpenRouter, so requests fail when users select this suggested model. In cases where the model still exists, there were most recent models available. 
No other changes are introduced beyond replacing the items in the model list.
=> fix: updated openrouter known models

documentation/docs/docker/Dockerfile
This PR adds `protobuf-compiler` to the Dockerfile so that the `lance-encoding` crate can compile successfully during the `cargo build` step.
Without this change, the Docker build fails with the following error:
```
Error: Custom { kind: NotFound, error: "Could not find protoc. If protoc is installed, try setting the PROTOC environment variable..." }
```
This fix installs the required `protoc` binary using `apt-get`, allowing Goose to build in Docker without error.
Tested on Apple M4 MacBook Pro with `docker-compose up --build`.
=> fix(docker): install protoc to fix lance-encoding build

crates/goose/src/providers/google.rs
- Update default model from gemini-2.0-flash to gemini-2.5-flash
- Add comprehensive list of current Google Gemini models including:
- Gemini 2.5 models (pro, flash, flash-lite, native audio, TTS)
- Gemini 2.0 models (flash variants, live API)
- Gemini 1.5 models (flash, flash-8b, pro variants)
- Update documentation URL to point to official Gemini API docs
Reference: https://ai.google.dev/gemini-api/docs/models
=> feat(providers): update Google Gemini models to latest available models

.github/ISSUE_TEMPLATE/submit-recipe.yml, documentation/src/pages/recipes/index.tsx
This PR adds a "Submit Recipe" button to the Recipes Cookbook page and updates the `submit-recipe.yml` issue template for improved clarity and consistency.
- Added a **"Submit Recipe"** button on the `/recipes` page that links directly to the GitHub issue template for recipe submissions.
- Refined copy and formatting in the `.github/ISSUE_TEMPLATE/submit-recipe.yml` file:
- Clearer step-by-step instructions for submitting a recipe.
- Updated example recipe JSON with correct fields and ordering.
- Added helpful tips section explaining each field.
This update makes it easier for users to discover how to contribute recipes and ensures they have clear guidance on how to format their submissions.
- Cookbook page: `/recipes`
- Issue template: `.github/ISSUE_TEMPLATE/submit-recipe.yml`
=> docs: Add "Add Recipe button" To Recipe Cookbook

crates/goose-cli/src/commands/configure.rs, crates/goose/src/providers/databricks.rs
This PR adds the following changes:
- implement the `fetch_supported_models_async` function for the Databricks provider. this allows users to interactively select their model during configuration, instead of needing to know the model name ahead of time and typing it in manually. This aligns with how most of the other provider interfaces are implemented (e.g. [openai.rs](https://github.com/block/goose/blob/main/crates/goose/src/providers/openai.rs#L183), [anthropic.rs](https://github.com/block/goose/blob/main/crates/goose/src/providers/anthropic.rs#L191)). In case of error we return `None` so the prompt can still fall back to manual input 
- enable "fuzzy search" filtering on the `cliclack` prompt. this allows users to type a fuzzy match query against the list of provider models that will …
=> feat: list Databricks-supported models and enable fuzzy search during model configuration

crates/goose/src/agents/platform_tools.rs, crates/goose/src/cron_test.rs, crates/goose/src/lib.rs, crates/goose/src/scheduler.rs, crates/goose/src/temporal_scheduler.rs
Cron parsing was not working correctly on windows.
This fix was tested on both mac and windows.
=> fix cron parsing for windows

documentation/docs/getting-started/using-extensions.md
This pull request updates the documentation to reflect a change in the configuration file for extensions, specifically replacing the `fetch` extension with a `github` extension.
* [`documentation/docs/getting-started/using-extensions.md`](diffhunk://#diff-51503ee9089502f4a3c4577a1ee0d5f4f09b616d6226c8eb076d358d5950c1caL307-R307): Updated the example configuration file to use the `github` extension instead of the `fetch` extension, with corresponding updates to the `name`, `cmd`, and `args` fields.
=> docs: typo - wrong extension id

temporal-service/main.go
The serialized nature of it meant that even a slightly larger than
expected delay could quickly add up to enough to trigger timeouts
consistently. Since these operations are highly IO bound there's no
reason not to run them all asynchronously.
=> fix(temporal-service): makes the search for possible temporal paths parallel.

download_cli.sh
Add a `GOOSE_VERSION` environment variable to the `download_cli.sh` install script to support installing arbitrary versions of Goose
This is a convenience to allow for integration testing of specific Goose versions to validate backwards compatibility. We verify the input version string is valid semver and prefix with `v` if not already present
`GOOSE_VERSION` is used with/without quotes, and the `v` prefix is auto added:
```bash
🐚 ~/Development/goose-fork wpfleger/support-install-versions GOOSE_VERSION=1.0.27 bash download_cli.sh 
Downloading v1.0.27 release: goose-aarch64-apple-darwin.tar.bz2...
Extracting goose-aarch64-apple-darwin.tar.bz2 to temporary directory...
```
```bash
🐚 ~/Development/goose-fork wpfleger/support-install-versions GOOSE_VERSION="1.0.27" bash download_cli.sh …
```
=> Update download_cli.sh to support arbitrary Goose versions

documentation/docs/getting-started/installation.md, documentation/docs/guides/updating-goose.md, documentation/docs/quickstart.md
This pull request updates the installation instructions for the Goose Desktop application across multiple documentation files to reflect a new installation process for Debian/Ubuntu-based distributions. The changes replace the previous tar.bz2 extraction method with steps for downloading and installing a DEB package.
* [`documentation/docs/getting-started/installation.md`](diffhunk://#diff-1da95befef448a968841697bffcbb8f9c53f1238842a36a63444ca5d4ea0499aL93-R97): Updated the installation steps for Debian/Ubuntu-based distributions to include downloading a DEB file, navigating to it in a terminal, running `sudo dpkg -i (filename).deb`, and launching Goose from the app menu.
* [`documentation/docs/guides/updating-goose.md`](diffhunk://#diff-73634242804f8cf84d6a17bd17773e3dbe74d393409f94c6e7a6 …
=> Update linux instructions

ui/desktop/package-lock.json, ui/desktop/src/components/ToolCallWithResponse.tsx
Not the cleanest way to do it perhaps (the tools might want to expose descriptive short messages themselves) but a quick quality of life improvement.
before:
after:
=> Richer tool call ui messages

crates/goose-cli/src/commands/configure.rs
=> add scheduler type  setting

crates/goose/src/session/storage.rs
=> fix windows session paths

documentation/docs/tutorials/recipes-tutorial.md
This PR adds a Goose Recipes tutorial.
- `documentation/docs/tutorials/recipes-tutorial.md`: Tutorial topic
=> docs: add recipes tutorial

Cargo.lock, async_token_counter_demo.rs, crates/goose-server/src/routes/audio.rs, crates/goose/Cargo.toml, crates/goose/examples/async_token_counter_demo.rs, crates/goose/src/agents/context.rs, crates/goose/src/context_mgmt/common.rs, crates/goose/src/context_mgmt/summarize.rs, crates/goose/src/token_counter.rs
- Replace blocking `Runtime::new().block_on()` pattern with proper async/await to eliminate deadlock risk
- Add global tokenizer caching with concurrent access using DashMap
- Implement token result caching with AHasher for 30% faster lookups
- Add robust network failure handling with exponential backoff retry logic
- Comprehensive test coverage for concurrency and network resilience
- **Eliminated blocking runtime anti-pattern** that could cause deadlocks in async contexts
- **Lock-free concurrent access** with DashMap replacing RwLock<HashMap>
- **Faster hash performance** with AHasher vs DefaultHasher (~30% improvement)
- **Bounded caches** prevent memory bloat (10K token cache, 50 tokenizer cache)
- **Global tokenizer sharing** eliminates redundant downloads/loading
- **Exponential …
=> feat: implement async token counter with network resilience and performance optimizations

download_cli.sh
- Windows releases contain files in 'goose-package/' subdirectory
- Installation script now detects and handles this structure
- Maintains backward compatibility with root-level file structure
- Fixes 'chmod: cannot access goose.exe' error on Windows
- All file operations now use correct extraction directory
Resolves installation failures on Git Bash, MSYS2, and similar Windows environments.
=> fix: handle Windows package subdirectory in CLI installation script

crates/goose/src/scheduler.rs
this PR reconciles cron formats between temporal and tokio-cron
=> fixes cron parsing issues

documentation/docs/guides/recipes/index.md
This pull request updates the `index.md` file in the documentation's guides section to replace a placeholder comment with an embedded YouTube video showcasing a new tutorial. 
Content updates:
* Replaced the placeholder comment in the `index.md` file with an embedded video titled "Create Reusable AI Agents with Recipes," updating the `src` attribute to point to the new video link (`https://www.youtube.com/embed/8rTliYrQ6Iw`).
=> Docs: Add Recipe video to landing page

.github/ISSUE_TEMPLATE/submit-recipe.yml, documentation/docs/guides/recipes/session-recipes.md, ui/desktop/src/components/more_menu/MoreMenu.tsx
Uses consistent naming/branding when surfacing the recipe editor/creator in the more menu links. Right now it's confusing to users why the button says to make "an agent", and the page it goes to is all about making a "recipe"
=> feat: change naming of recipe creation in more menu links

documentation/docs/guides/recipes/recipe-reference.md, documentation/docs/guides/recipes/session-recipes.md
This PR adds the Recipe Generator option to the Create Recipe section in the Shareable Recipes topic.
- `documentation/docs/guides/recipes/recipe-reference.md`: Added:
- Link to CLI commands topic in case someone expects that info to be here too
- Note about prompt being required in headless mode
- `documentation/docs/guides/recipes/session-recipes.md`: Added:
- Recipe Generator tab with equivalent instructions
- Add prompt field to Desktop tab
- Link to Recipe Reference Guide in CLI tab
- Changes to sync with the UI -- gear icon and "View recipe"
=> docs: add generator option to create recipe

crates/goose-cli/src/session/builder.rs, crates/goose-cli/src/session/mod.rs, crates/goose/src/scheduler.rs, crates/goose/src/session/storage.rs, crates/goose/tests/private_tests.rs
this is a more robust way to implement the `no-session` argument which does not rely on paths.
=> pipe the argument to storage

Cargo.lock, crates/goose-cli/Cargo.toml, crates/goose-cli/src/cli.rs, crates/goose-cli/src/recipes/extract_from_cli.rs, crates/goose-cli/src/recipes/mod.rs
**Why**
Currently we can define the sub recipes in the main recipe.  Sometimes users want to add additional sub-recipes for their specific workflow dynamically.
Example use case:
I have a main recipe with sub_recipe 1 (task 1), sub_recipe 2 (task 2). This can be reused by other teams.
Team A wants to add sub_recipe_a for their specific task for their workflow in addition to the existing sub recipes in the main recipe.   
**What**
- Added command argument --sub-recipe to accept additional sub-recipes.  It can call `--sub-recipe sub_recipe1.yaml --sub_recipe sub_recipe2.yaml` to add multiple sub recipes
=> feat: additional sub recipes via command line

ui/desktop/src/components/more_menu/MoreMenuLayout.tsx
For long file paths, the last segments (e.g. the current directory) are typically the most relevant.  
We now truncate from the **start** of the path instead of the end, so users see the meaningful suffix rather than a generic unchanging prefix like `/Users/foo/`.
- Path Field was a fixed size
- If the path did not fit, Truncated the most useful information from the end of the string
- Path field grows to fit the path if there is room to do so
- If the path still does not fit, Truncate from the beginning of the string
- **RTL truncation** (`direction: rtl`)  
- Makes text truncate from the left, keeping the rightmost (suffix) part visible.
- **`unicode-bidi: plaintext`**
- Prevents path segments from rendering out of order when using RTL.
- **Switched `<div>` to `<span>`**
- Inline …
=> feat(desktop): Prioritize suffix when truncating path in header

documentation/src/pages/extension.tsx
I want to add Goose as a recommended MCP Client in https://github.com/microsoft/playwright-mcp/pull/575
GitHub markdown does not allow me use a custom protocol in the rendered README, which means that our `goose://` link will not work.
We can add a new `/goose/extension` path that will redirect to the application and forward the query string to install the extension. With this change, playwright-mcp is installable into Goose using this URL: 
```
https://block.github.io/goose/extension?cmd=npx&arg=%40playwright%2Fmcp%40latest&id=playwright&name=Playwright&description=Interact%20with%20web%20pages%20through%20structured%20accessibility%20snapshots%20using%20Playwright
```
=> Add `/extension` path for extension installation

documentation/docs/guides/managing-goose-sessions.md, documentation/docs/guides/recipes/session-recipes.md
This PR fixes some display issues in the Managing Goose Sessions and Shareable Recipes topics.
- `documentation/docs/guides/managing-goose-sessions.md`: Added `groupId` to sync all tabs with selection
- `documentation/docs/guides/recipes/session-recipes.md`:
- Added `groupId` to sync all tabs with selection
- Removed h3s in tabs to work around issue with on-page navigation links not working unless parent tab is active:
- Promoted Validate and Share to h2
- Demoted Configure Recipe Location, Run Recipe, and Schedule Recipe to h4 and added intro with links
- Moved warnings down and fixed typos
=> docs: fix tab navigation

.github/workflows/create-recipe-pr.yml
I believe this should do the trick.
https://docs.github.com/en/actions/reference/evaluate-expressions-in-workflows-and-actions#contains
Related to https://github.com/block/goose/pull/3064
cc @EbonyLouis
=> fix: use the correct `contains` syntax on create-recipe-pr.yml

documentation/docs/guides/smart-context-management.md
Documenting the cost tracking UI for Goose desktop
=> Docs: Cost tracking on the desktop app

crates/goose/src/providers/google.rs
Sometimes the Google AI HTTP query is logged. If the key is a query param then it'll be visible to the user.
Closes https://github.com/block/goose/issues/3191
=> fix: Pass Google AI API key in HTTP header, not query param

ui/desktop/openapi.json, ui/desktop/src/components/RecipeEditor.tsx, ui/desktop/src/components/schedule/CreateScheduleModal.tsx, ui/desktop/src/components/ui/DeepLinkModal.tsx, ui/desktop/src/main.ts
Some users are reporting issues with desktop recipe creation, where they create the recipe and are unable to open the deeplink. I believe the issue is that the base64 deeplink is not being encoded. In the CLI, the base64 config is encoded with `let url_safe = urlencoding::encode(&deeplink);` when creating the deeplink. But in the UI, the deeplink is not url encoded. This PR urlencodes the base64 config in UI recipe creation.
=> fix: fix desktop recipe url generation

Cargo.lock
Whenever I build, `fancy-regex` Cargo.lock changes.
To test it out, run the CLI from a clean `main` branch.
```shell
cargo run --bin goose
```
=> build: Check in Cargo.lock changes

documentation/docs/guides/recipes/session-recipes.md
This PR updates the recipe example in the Shareable Recipes topic.
- `session-recipes.md`:
- Sync example with recent updates to make the recipe work in both Desktop and CLI
- Add links to CLI commands topic
=> docs: update recipe example

ui/desktop/src/App.tsx, ui/desktop/src/hooks/useWindowManager.ts
This PR ensures the window does not resize when the diff panel closes.
https://github.com/user-attachments/assets/c76b8326-1d88-4a75-bf30-ec6c9a2baeca
=> Fix window resize

crates/goose-bench/src/bench_session.rs, crates/goose-bench/src/runners/eval_runner.rs, crates/goose-cli/src/cli.rs, crates/goose-cli/src/commands/bench.rs, crates/goose-cli/src/session/builder.rs, crates/goose-cli/src/session/mod.rs, crates/goose-cli/src/session/output.rs, crates/goose/src/scheduler.rs, crates/goose/src/session/storage.rs, crates/goose/tests/private_tests.rs
Instead of using /dev/null or flags, make the session file optional on the agent and only try to save when we have one.
Closes #3228
=> Clean up session file optionality for --no-session

crates/goose-server/src/routes/agent.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/final_output_tool.rs, ui/desktop/src/components/ToolCallWithResponse.tsx, ui/desktop/src/utils/providerUtils.ts
This PR doesn't give the gui the ability to view or edit structured output but if structured output is part of the recipe it will now be used. Support in CLI was added in #3188
=> feat: GUI can use structured output present in recipes

ui/desktop/src/styles/main.css, ui/desktop/src/toasts.tsx
This PR adds a close button (X) to Goose's toast notifications to improve user experience.
- Enable closeButton in react-toastify commonToastOptions in `ui/desktop/src/toasts.tsx`
- Add custom CSS styling for close button with hover/focus states in `ui/desktop/src/styles/main.css`
- Ensure consistent theming with Goose's design system using CSS custom properties
- Maintain compatibility with existing 'Copy error' buttons
Previously, users had to click anywhere on the toast notification to close it, which wasn't intuitive UX. Now users have a clear X button in the top-right corner of each notification.
- Leverages react-toastify's built-in close button functionality
- Custom CSS ensures the close button matches Goose's visual design
- Uses Goose's existing CSS custom properties for …
=> feat: Add close button (X) to toast notifications

crates/goose/Cargo.toml
#3049 merged to remove it, but #2992 added use of it.
=> fix: Add back lazy_static

ui/desktop/src/components/settings/SettingsView.tsx
I got stuck in the settings menu. If you scroll down in the settings menu, the back link stays up at the top. This PR supports pressing escape to dismiss the settings menu and return to the main screen. A follow up to pin the back link to the top may make sense as well
https://github.com/user-attachments/assets/f07db13e-b8d0-4fe4-9e9b-7c42359b9aa3
Botched a rebase of a [previous PR](https://github.com/block/goose/pull/3124) of the same change. It was easier to create a new PR.
=> Add support for escape key to dismiss settings menu

ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/MarkdownContent.tsx, ui/desktop/src/components/UserMessage.tsx
Weird formatting of markdown styles (headers, bold) in light mode 
Before
After
=> update styling of user messages

crates/goose/src/agents/agent.rs, crates/goose/src/agents/final_output_tool.rs
There was a bug that the final tool continuation message was not being added to the internal 'messages' variable so the llm never saw the message telling it to use the final tool (creating an infinite loop). This PR fixes that by adding the message to the 'messages' variable. As this is all internal to the reply loop I can't easily write a test for it but I have tested it locally.
=> fix: Enable agent to see instruction to use final output tool when it wasn't called

ui/desktop/src/components/settings/extensions/deeplink.ts, ui/desktop/src/components/settings/extensions/utils.ts, ui/desktop/src/extensions.tsx
Container Use (cu) is featured in our content and Dagger's documentation:
- We have a [blog post](https://block.github.io/goose/blog/2025/06/19/isolated-development-environments) about Container Use with Goose
- We have a [YouTube video](https://www.youtube.com/watch?v=pGce9T4E5Yw) demonstrating it
- Dagger includes [deeplink installation](https://container-use.com/quickstart#method-3%3A-goose-desktop) instructions in their documentation
However, when users try to install cu-based extensions via the documented deeplinks, they encounter this error:
`Failed to install extension: Invalid command: cu. Only docker, jbang, npx, uvx, goosed are allowed.`
This PR solves that by adding : 
- Add 'cu' to allowedCommands list in deeplink validation
- Include 'cu' in shimPatterns for path resolution
- …
=> feat: add support for 'cu' command in extension installation

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/managing-goose-sessions.md, documentation/docs/guides/managing-projects.md, documentation/docs/guides/projects.md
This pull request updates the Goose documentation to streamline project and session management guides by consolidating details into a new "Managing Projects" guide and simplifying related CLI command documentation. The changes aim to improve clarity and user navigation.
* **New "Managing Projects" Guide**: Added a dedicated guide (`documentation/docs/guides/managing-projects.md`) that introduces Goose Projects, explains their purpose, and provides detailed usage examples, workflows, and benefits. This includes information previously scattered across other guides.
* **Simplified CLI Command Documentation**: Updated the `goose-cli-commands.md` file to replace detailed project-related instructions with links to the new "Managing Projects" guide. This affects the `project` and `projects` …
=> Goose projects docs

crates/goose-cli/src/logging.rs
Logging tests on Macos were flaky because of how the OS cleans up the files.
This change improves the reliability and cleanup process of temporary test directories. The changes replaces manual directory management with the use of the `tempfile` crate, ensuring automatic cleanup and reducing the risk of test interference.
=> refactor(tests): make logging test in goose-cli less flaky on macos

documentation/docs/mcp/alby-mcp.md
This tutorial instructs on how to enable goose to seamlessly interact with bitcoin lightning wallets using the Nostr Wallet Connect protocol.
You can seamlessly connect to a variety of lightning wallets, including [Alby Hub](https://albyhub.com) which is powered by [Lightning Dev Kit](https://github.com/lightningdevkit)
Example prompts:
- "Pay $1 to my friend Rene"
- "Make me a 10 sat invoice"
- "Was it paid?" (check if the invoice was paid)
- "Pay lnbc...." (pay an invoice)
- "What's my balance?"
- "What's the alias of my lightning node?"
Alby MCP can be also used to seamlessly use paid MCP tools, such as the Bitrefill MCP server ("buy me a 200THB Lotus's gift card") and e.g. a paid weather server ("What's the weather in Wellington?")
The tutorial has instructions for both STDIO and …
=> docs: add Alby MCP tutorial

crates/goose-cli/src/commands/configure.rs
Adds support for configuring streamable HTTP MCP Servers
* **Updated extension list**: Added "Streaming HTTP" as a new option in the extension configuration dialog, with a description explaining its purpose as connecting to a remote extension via MCP Streaming HTTP. (`crates/goose-cli/src/commands/configure.rs`, [crates/goose-cli/src/commands/configure.rsL501-R507](diffhunk://#diff-29570269be581343f6b3201b4f0aae99751428f3b6b64080b7e29e252c3c21c8L501-R507))
* **Configuration prompts for "Streaming HTTP"**: Implemented detailed user prompts for setting up the "Streaming HTTP" extension, including inputs for name, URI, timeout, optional description, and custom headers. Environment variable configuration is excluded for this extension type. (`crates/goose-cli/src/commands/configure.rs`, …
=> Add support in goose configure for streaming http mcp tools

crates/goose/examples/image_tool.rs, crates/goose/src/providers/formats/bedrock.rs, crates/goose/tests/providers.rs
might be a bit over-tested, feedback welcome :) 
closes #1481
=> feat: bedrock image content support

documentation/docs/guides/goose-cli-commands.md, documentation/docs/tutorials/benchmarking.md, documentation/docs/tutorials/goose-in-docker.md
This PR moves the two topics to the Tutorials section:
- `documentation/docs/tutorials/benchmarking.md`: Moved from /guides section & fix link to experimental-features topic
- `documentation/docs/tutorials/goose-in-docker.md`: Moved from /guides section
- `documentation/docs/guides/goose-cli-commands.md`: Update link to goose-in-docker topic
=> docs: move topics to tutorials section

documentation/docs/mcp/netlify-mcp.md
This PR adds a YouTube video to the Netlify MCP documentation page to enhance the user experience and provide visual guidance.
- Added YouTube Short video (https://www.youtube.com/shorts/iSUNmxOf6gw) to the netlify-mcp.md documentation page
- Video embedded using the YouTubeShortEmbed component following the same pattern as other MCP pages
- Video positioned at the top of the page after imports and before main content
- Verified the video URL format matches the embed pattern used in other MCP documentation pages
- Confirmed the YouTubeShortEmbed component is properly imported and used
The video will help users better understand how to use the Netlify MCP extension with Goose.
=> Add YouTube video to Netlify MCP documentation

documentation/docs/mcp/vscode-mcp.md
Added VS Code short to the tutorial
=> docs: VS Code MCP video

documentation/docs/mcp/filesystem-mcp.md
This PR updates the **Filesystem MCP tutorial** to remove the non-functional deeplink for the Goose Desktop extension.
- The `goose://` URI deeplink under the TLDR section and setup instructions for Goose Desktop. Since the Filesystem MCP server requires a user-specified directory path at runtime, it cannot support deeplinks.
- Clear manual setup instructions for adding the Filesystem MCP Server to Goose Desktop via `Advanced Settings`, including:
- Extension Type: `Standard IO`
- Command: `npx -y @modelcontextprotocol/server-filesystem </path/to/allowed/directory>`
=> docs: Remove Deeplink for Filesystem MCP Server

ui/desktop/src/utils/binaryPath.ts
this resolves the issue reported on discord of npx extensions not working via deeplink
=> fix the npx.cmd mapping issue

documentation/src/css/custom.css
=> fix: resolve hamburger menu breakpoint bug in docs

Cargo.lock, Justfile, crates/goose-mcp/Cargo.toml, crates/goose-mcp/src/google_drive/mod.rs, crates/goose-mcp/src/google_drive/oauth_pkce.rs, crates/goose-mcp/src/google_drive/storage.rs, crates/goose/src/config/base.rs, crates/goose/src/keyring/factory.rs, crates/goose/src/keyring/file.rs, crates/goose/src/keyring/mock.rs, crates/goose/src/keyring/mod.rs, crates/goose/src/keyring/system.rs, crates/goose/src/lib.rs, crates/goose/src/providers/factory.rs
This change introduces a clean keyring abstraction layer to replace global keyring state with dependency injection, addressing critical runtime errors and improving testability. 
The implementation creates a KeyringBackend trait with concrete implementations for system keyring (SystemKeyringBackend) and file-based storage (FileKeyringBackend), allowing the configuration system to use different keyring backends based on the GOOSE_DISABLE_KEYRING environment variable. 
This architectural improvement eliminates the need to touch the user's real OS keyring and thus enables comprehensive unit testing without keychain popups. The refactoring maintains full backward compatibility while establishing a foundation for reliable testing and development workflows
---
- **feat: introduce a keyring …
=> refactor: abstract keyring logic to better enable DI

crates/goose/src/agents/prompt_manager.rs
Fixes the naming of the system prompt for OpenAI GPT 4.1, fixing #3348
=> Fix name of GPT-4.1 System Prompt (#3348)

documentation/docs/tutorials/lead-worker.md
This PR adds instructions for using the lead/worker model with Goose desktop.
=> Docs: Lead/worker model in Goose Desktop

crates/goose/src/session/storage.rs
When saving a session, `SessionMetadata::default()` uses `get_home_dir()`, regardless of the actual working directory. If you try and resume a session using a non-home working directory from the GUI, the model is confused doesn't know the correct working directory.
This PR changes the default to be the current working directory, which allows session resumption to work. If the current working directory is not available, it falls back to the home directory.
In the screenshot below you can see all the sessions (which actually took place with `/Users/jud/Projects/goose` as the working directory) showing `/Users/jud`, except the second entry, which was a debug build incorporating this fix.
=> Use `current_dir()` or fall back to `get_home_dir()` when writing default session metadata

documentation/docs/mcp/alby-mcp.md
- update to use streamable http instead of SSE
- replace custom nwc parameter with authorization header (See https://github.com/block/goose/pull/3217#discussion_r2180347881)
- rename Alby MCP and PaidMCP library
- fix ordered list numbering
=> docs: simplify alby mcp

documentation/docs/mcp/youtube-transcript-mcp.md
YouTube Transcript MCP uses uv but we incorrectly listed Node
=> docs: fix YouTube Transcript MCP package manager

documentation/docs/guides/cli-providers.md
=> docs: update CLI provider guide

crates/goose/src/providers/githubcopilot.rs, crates/goose/src/providers/openrouter.rs
You have to type out a model manually.
```bash
┌   goose-configure
│
│  Configure Providers
│
│  OpenRouter
│
●  OPENROUTER_API_KEY is already configured
│
│  Yes
│
◇  Enter new value for OPENROUTER_API_KEY
│  [REDACTED]
│
◇  Model fetch complete
│
◆  Enter a model from that provider:
│  anthropic/claude-3.5-sonnet (default)
└
```
Goose CLI will automatically fetch the list of models that support tool use from OpenRouter when you configure it as a provider:
```bash
┌   goose-configure
│
│  Configure Providers
│
│  OpenRouter
│
●  OPENROUTER_API_KEY is already configured
│
◇  Would you like to update …
```
=> feat: fetch openrouter supported models in `goose configure`

documentation/docs/guides/config-file.md, documentation/docs/guides/environment-variables.md, documentation/docs/guides/goose-cli-commands.md
This PR extends the documentation about the CLI syntax highlighting theme.
- `documentation/docs/guides/config-file.md` and  `documentation/docs/guides/environment-variables.md`: Add `GOOSE_CLI_THEME`
- `documentation/docs/guides/goose-cli-commands.md`: Add "Themes" section with usage, configuration, and examples
=> docs: cli theme persistence

crates/goose/src/providers/azure.rs, ui/desktop/src/components/settings/providers/ProviderRegistry.tsx
AZURE_OPENAI_API_KEY was previously an optional parameter and since only required parameters are visible in the UI, it was not possible to configure it. Let's make it required with an empty string as the default value. See also #2582.
Example from the UI
=> feat: Add AZURE_OPENAI_API_KEY as a visible config parameter

crates/goose-server/src/routes/reply.rs
Streamed message chunks should be grouped into a single message when the message id matches, and that's what push_message does. Here, I missed two places in goosed where we push messages to a vector.
It's probably worth thinking about how this could be done such that the compiler catches when we miss this. Maybe the streaming should not yield Messages, but instead MessageChunks?
=> fix: message concatenation in server session management

ui/desktop/src/components/settings/extensions/subcomponents/ExtensionList.tsx
Small but impactful UX change that sorts extensions alphabetically before rendering
=> ux: alphabetize extensions

crates/goose-cli/src/recipes/extract_from_cli.rs, crates/goose-cli/src/recipes/recipe.rs, crates/goose-cli/src/recipes/search_recipe.rs, crates/goose-cli/src/recipes/template_recipe.rs
**Why**
@dianed-square reported the issue:
If we set in goose recipe
```
prompt: ""
```
It will pass an empty message to agent, and get a 404 error 
```
2025-07-10T23:21:27.753310Z ERROR goose::agents::agent: Error: Request failed: Request failed with status: 400 Bad Request. Message: {"external_model_provider":"databricks-model-serving","external_model_error":{"error_code":"BAD_REQUEST","message":"{\"message\":\"messages: at least one message is required\"}"}}
at crates/goose/src/agents/agent.rs:1006
```
**What**
- Avoid `""` escape when rendering the recipe file as a template
- If the parsed recipe has empty `prompt`, don't send the empty string as a message
**With fix**
- If user run the recipe in `non-interactive` mode,  it will return error "Error: no text provided for prompt in …
=> fix: avoid pass encoded empty string to goose run --recipe

documentation/docs/guides/environment-variables.md, documentation/docs/guides/smart-context-management.md
This PR extends the documentation about the Model Context Limit Overrides feature.
- `documentation/docs/guides/environment-variables.md`: Add link to new content
- `documentation/docs/guides/smart-context-management.md`: Add "Model Context Limit Overrides" section
=> docs: model context limit overrides

crates/goose-cli/src/recipes/template_recipe.rs
**Why**
Currently if user adds content `results/{{hf_model_org}__{hf_model_name}}/{model commit id}/{task name}.json` in the recipe, it will fail when rendering the template.
With this example, the user does not intend to introduce variables in the recipe file. Instead, they are the raw content.
**What**
Convert the string that seems like template variable to raw content
**How**
- Extract all strings enclosed with {{ }}
- If they only contain alphanumeric characters and _, treat as template variables
- Otherwise, test each string by attempting to render it with MiniJinja
- If rendering succeeds, treat as template variable; if it fails, convert to raw content using {% raw %} blocks
**Note**
With this implementation, user could add the template variables incorrectly and then it will be …
=> fix: convert invalid recipe variable name to raw content

documentation/docs/tutorials/lead-worker.md
=> docs: typo in guide description

ui/desktop/src/components/schedule/SchedulesView.tsx
Duplicate CTA when Scheduler section is empty
Made updates based on design by @spencrmartin .
=> Remove duplicate CTA within empty Scheduler section

crates/goose-cli/src/session/builder.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/recipe_tools/dynamic_task_tools.rs, crates/goose/src/agents/recipe_tools/mod.rs, crates/goose/src/agents/recipe_tools/sub_recipe_tools.rs
* adds the dynamic_task__create_task tool which creates text_instruction tasks dynamically
=> feat: dynamic tasks

crates/goose/src/providers/azure.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/formats/databricks.rs, crates/goose/src/providers/formats/openai.rs, crates/goose/src/providers/githubcopilot.rs, crates/goose/src/providers/groq.rs, crates/goose/src/providers/ollama.rs, crates/goose/src/providers/openai.rs, crates/goose/src/providers/openrouter.rs, crates/goose/src/providers/utils.rs, crates/goose/src/providers/xai.rs
This implements streaming for OpenAI, which is really just the same implementation as Databricks as the latter uses the format of the former. I also moved that implementation into the formats/openai.rs accordingly, and cleaned up the get_usage function a bit (it only ever returned one type of error, which we just turned into Usage::default).
=> feat: Implement streaming for OpenAI

documentation/docs/mcp/github-mcp.md
This PR switches the GitHub MCP extension from the archived npx method to the new streaming server.
- `documentation/docs/mcp/github-mcp.md`: Updated configuration steps and links
Also fixes #3322
=> docs: update github mcp config

crates/goose/src/providers/openai.rs
In order to get token usage when streaming, you must set this option in the OpenAI API.
=> fix: Set include_usage=true for OpenAI streaming

documentation/docs/mcp/github-mcp.md, documentation/src/components/CLIRemoteStreamingExtensionInstructions.js, documentation/src/components/CLIStreamExtensionInstructions.js
This PR adds a component for Add Extension -> Remote Extension (Streaming HTTP) reusable steps. It also updates the GitHub extension tutorial to use the component
- `documentation/docs/mcp/github-mcp.md`: Use CLIRemoteStreamingExtensionInstructions for CLI steps
Components:
- `documentation/src/components/CLIStreamExtensionInstructions.js`: New component based on CLIExtensionInstructions but with streaming-http config options
=> docs: add CLIStreamExtensionInstructions component

crates/goose/src/agents/agent.rs, crates/goose/src/agents/final_output_tool.rs, crates/goose/tests/agent.rs
When streaming was introduced https://github.com/block/goose/pull/2677 a bug was introduced around structured output. Every text streaming chunk has no tool calls and so the inner loop would check if final output had been recorded yet and send a warning directive to the agent rather than waiting till the end of the llm's response.
Added a test that would have caught this (tested against main).
=> fix: Fixes structured output after streaming change to agent

ui/desktop/src/components/schedule/ScheduleDetailView.tsx, ui/desktop/src/components/sessions/SessionHistoryView.tsx, ui/desktop/src/components/ui/BackButton.tsx
- Restyled back button (incl. change of icon.)
- Centralized styling (so we weren't having to restyle each instance)
- Fixed some padding issues to align titles across pages.
before
after
=> Back Button Restyling

ui/desktop/src/App.tsx, ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/components/Layout/MainPanelLayout.tsx, ui/desktop/src/components/SidecarLayout.tsx
This PR cleans up the text diff sidecar UI to match the new look and feel:
https://github.com/user-attachments/assets/7066b666-028e-4a48-8f1f-01037d9e44ad
Currently lacks window width management and sidecar entrance animations.
=> refine global checkpoints UI

crates/goose/src/providers/anthropic.rs, crates/goose/src/providers/formats/anthropic.rs
Similar to openai: https://github.com/block/goose/pull/3413 
this adds in streaming for anthropic provider
=> chore: implement streaming for anthropic.rs firstparty provider

.github/workflows/build-cli.yml
Rather than checking out main by default, we should pass an empty string, which actions/checkout interprets as the triggering ref.
Fixes #3466
=> Don't default to main for build-cli

ui/desktop/src/components/settings/app/AppSettingsSection.tsx, ui/desktop/src/main.ts, ui/desktop/src/preload.ts, ui/desktop/src/utils/settings.ts
- Add wakelock toggle UI in App Settings, default to false
- Hooks into the messaging infra to know when goose is working
- Releases wakelock when Goose is done with work to prevent killing your battery
- Use Electron's powerSaveBlocker with 'prevent-app-suspension' to allow the screen to still lock for security
=> Add wakelock feature to prevent system sleep while Goose is working

ui/desktop/src/components/RecipesView.tsx
Looks like in https://github.com/block/goose/pull/2845 we starting url encoding deeplinks in the cli and the ui was updated for opening deeplinks in that pr. However since then there is an Import recipe dialogue and that code has a different execution path that was not urldecoding.
This PR fixes that for https://github.com/block/goose/issues/3373 . Just exploring if there is a way to unify some of the code a little.
We should have a separate discussion around the expected recipe deeplink format: url-encoded vs base64 no padding etc.
Also unifying this import code with the existing code in main.ts#processProtocolUrl is a deeper investigation and needs to wait for the new UI to land.
=> fix: Fixes importing url encoded recipe deeplinks

ui/desktop/src/components/ToolCallWithResponse.tsx
> **⚠️ DEPENDENCY**: This PR depends on #3231 being merged first. Please review and merge #3231 before this PR.
Adds hover tooltips to tool banners showing extension names (e.g., "developer extension") without cluttering the UI. This builds on the clean tool descriptions from #3231 by providing extension information on demand through tooltips.
- **Extension Name Tooltips**: Hover over tool descriptions to see which extension provides that tool
- **Left-Aligned Positioning**: Tooltips align with text start for natural reading flow
- **Smart Detection**: Extracts extension names from tool patterns (`developer__shell` → "developer extension")
- **Graceful Fallback**: Tools without `__` separator show no tooltip
- Modified `ui/desktop/src/components/ToolCallWithResponse.tsx`
- Added …
=> Enhancement: Extension name tooltips for tool banners

Cargo.lock, Cargo.toml, crates/goose-bench/Cargo.toml, crates/goose-cli/Cargo.toml, crates/goose-mcp/Cargo.toml, crates/goose-server/Cargo.toml, crates/goose/Cargo.toml
Add baseline access to https://github.com/modelcontextprotocol/rust-sdk for all relevant crates in the workspace
=> feat: add rmcp as a workspace dep

documentation/docs/guides/goose-permissions.md, documentation/docs/guides/managing-tools/adjust-tool-output.md, documentation/docs/guides/using-goosehints.md
Updates the following doc pages with Desktop instructions for the new Goose UI:
* **Using Goosehints**
* **Adjust Tool Output**
* **Goose Permissions**
=> Docs: Access settings in new UI

documentation/docs/guides/managing-tools/tool-router.md
This PR updates the Desktop steps in the Tool Selection Strategy topic.
- `documentation/docs/guides/managing-tools/tool-router.md`: Updated to use the new UI
=> docs: update desktop instructions for tool router

ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/CheckpointActions.tsx, ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/components/SidecarLayout.tsx, ui/desktop/src/hooks/useWindowManager.ts
This PR addresses window resizing issues in the diff viewer sidecar functionality and lays groundwork for improved transitions.
- **Fixed window resizing toggle behavior**: The `useWindowManager` hook now properly handles both expansion and collapse states when toggling the diff viewer
- **Improved wide window handling**: Windows that are already wide enough (>2200px) now properly show the sidecar without unnecessary resizing
- **Enhanced state management**: Fixed edge cases where the window state could become inconsistent during toggle operations
- ✅ Window growing too wide when clicking "View Diff" button repeatedly
- ✅ Sidecar not closing properly when clicking "View Diff" again
- ✅ Window not returning to original size when sidecar is closed
- ✅ Proper handling of windows that are …
=> Improve diff viewer window resizing and sidecar transitions

documentation/docs/guides/recipes/session-recipes.md
This PR updates the Desktop steps in the Shareable Recipes topic.
- `documentation/docs/guides/recipes/session-recipes.md`: 
- Updated to use the new UI
- Doc new "create from template" steps
=> docs: update desktop instructions for session recipes

documentation/docs/guides/managing-goose-sessions.md
This PR updates the Desktop steps in the Managing Goose Sessions topic.
- `documentation/docs/guides/managing-goose-sessions.md`: 
- Updated to use the new UI
- NOTE: The session history in Desktop no longer exposes the filename so the workarounds for Resume Desktop session in the CLI and export Desktop session aren't currently supported
=> docs: update desktop instructions for managing sessions

crates/goose-server/src/routes/recipe.rs, ui/desktop/src/recipe/index.ts
More consistent route naming (and one step closer to restful given we will have a lot more crud recipe routes in the future).
=> refactor: Renames recipe route to recipes to be consistent

crates/goose/src/providers/claude_code.rs
The previous error "Failed to spawn command: No such file or directory" was unclear for users when the Claude CLI wasn't installed or in PATH.
The new error message shows the exact command that failed and provides clear guidance on how to fix the issue, including mentioning the CLAUDE_CODE_COMMAND config option.
=> Improve Claude Code provider error message for missing CLI

documentation/docs/getting-started/installation.md, documentation/docs/getting-started/providers.md, documentation/docs/getting-started/using-extensions.md, documentation/docs/guides/handling-llm-rate-limits-with-goose.md, documentation/docs/guides/recipes/storing-recipes.md, documentation/docs/guides/smart-context-management.md, documentation/docs/guides/using-goosehints.md
Updated the following docs to match the new UI
* Using Goose Hints
* Installation
* Providers
* Using Extensions
* Handling LLM Rate Limits with Goose
* Storing Recipes
* Smart Context Management
=> Updating docs to match new UI

crates/goose/src/providers/ollama.rs
Without this change, even if one recompiles `ollama` to extend timeouts there, `goose` times out HTTP requests to `ollama` at ten minutes.
Those of us who choose to run LLMs on CPUs, despite the slowness, profit from LLMs doing asynchronous work. This change allows users to increase the timeout `goose` sets on HTTP requests to `ollama`.
=> Env var to set Ollama request timeout

ui/desktop/src/components/RecipeEditor.tsx, ui/desktop/src/components/RecipesView.tsx, ui/desktop/src/hooks/useEscapeKey.ts
This PR is to make closing the Recipes modals easier, via the `esc` key. Currently users must click the "close" button on the modal.
=> feat (ui): close recipe modals with esc key

crates/goose/src/providers/formats/anthropic.rs
this fixes: https://github.com/block/goose/issues/3570 
a fairly serious bug where messages don't accumulate correctly.
Fixes GUI and CLI, and should help fix token accounting.
=> fix: track message id to keep like with like

crates/goose/src/agents/recipe_tools/sub_recipe_tools.rs, crates/goose/src/agents/subagent_execution_tool/lib/mod.rs, crates/goose/src/agents/subagent_execution_tool/tasks_manager.rs
**What** 
-  use sequential when sub recipe task is 1.  This was removed accidentally during a pr merge
- a small refactoring to move "get the task" logic to tasks_manager
=> fix: use sequential when sub recipe task is 1.

documentation/docs/guides/using-goosehints.md
This PR adds a YouTube video embed to the using-goosehints.md documentation page. The video (https://www.youtube.com/watch?v=kWXJC5p0608) provides additional context about using Goose hints and follows the same pattern as other embedded videos in the documentation.
=> Add YouTube video embed to using-goosehints.md

ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/BaseChat.tsx, ui/desktop/src/components/ui/RecipeWarningModal.tsx, ui/desktop/src/hooks/useRecipeManager.ts, ui/desktop/src/main.ts, ui/desktop/src/preload.ts, ui/desktop/src/utils/recipeHash.ts
Ported from https://github.com/block/goose/pull/3425 to work with updated main code
=> Add recipe install warning

crates/mcp-core/src/protocol.rs, crates/mcp-server/src/errors.rs
Remove definition and usage of `ErrorData` from the internal MCP crates and replace with `rmcp`'s version
=> feat: migrate ErrorData from internal mcp crates to rmcp version

documentation/docs/guides/recipes/recipe-reference.md, documentation/docs/guides/recipes/session-recipes.md, documentation/docs/guides/recipes/storing-recipes.md
This PR documents the Desktop recipe format and the ability to run saved Desktop recipes from the CLI.
- `documentation/docs/guides/recipes/recipe-reference.md`: Added sections with examples and field descriptions
- `documentation/docs/guides/recipes/session-recipes.md`: Added section with link to recipe-reference 
- `documentation/docs/guides/recipes/storing-recipes.md`: Added Format Compatibility note
=> docs: desktop recipe format

documentation/docs/getting-started/using-extensions.md, documentation/docs/mcp/mongodb-mcp.md
This PR updates the MongoDB extension tutorial and the Using Extensions topic.
- `documentation/docs/getting-started/using-extensions.md`:
- Updated the built-in extensions list to sync with https://github.com/block/goose/blob/main/ui/desktop/src/components/settings/extensions/bundled-extensions.json
- Added Updating Extension Properties section
- `documentation/docs/mcp/mongodb-mcp.md`: Migrated manual steps to component to sync with new UI
=> docs: use installer component for tutorial, add updating extensions section

crates/goose/src/providers/formats/openai.rs
Previously this did not properly handle when the provider streams back a reply with >1 tool call.
The stream used here for the test was captured with a simple proxy. We should consider doing more of this, perhaps building out something like the scenario test to capture at the request level to test this provider code.
=> fix: multi-tool calls in streamed openai-compatible responses

documentation/docs/getting-started/providers.md
Hi everyone! Personally had issues with context size and Ollama, and saw several other cases. So I've extended tool calling warning with information about context size. Updated this one for Ollama and Ramalama.
Before: 
After, for Ollama:
> Note: Ollama docs poorly explain how to set this variable in the desktop app. I'm using systemd and cli but I guess most of the users will go for UI. There will be a reference by now, but it's not really useful. Need to contribute to their docs too :smiling_face_with_tear: 
After, for Ramalama:
and small change in Ramalama example:
If you wan't to change something I'm happy to help!
=> docs: local LLMs context size tip

documentation/docusaurus.config.ts
Path in announcement banner was relative and only sometimes led to the grants program page
This pull request includes a small update to the `announcementBar` configuration in the Docusaurus site settings. The change updates the link for the Goose Grant program to use a more specific path (`/goose/grants`) for improved navigation.
=> Fixing grants path

documentation/docs/mcp/context7-mcp.mdx, documentation/docs/mcp/mongodb-mcp.md, documentation/src/components/server-card.tsx, documentation/src/pages/extensions/detail.tsx, documentation/static/servers.json
This PR adds the Context7 MongoDB and Context7 MongoDB extensions to the Extensions library.
- `documentation/docs/mcp/context7-mcp.mdx`: Fix typo
- `documentation/docs/mcp/mongodb-mcp.md`: Add link to server repo and remove bold on headers
- `documentation/static/servers.json`: Add context7 and mongodb
Updates after approval:
- `documentation/static/servers.json`: 
- Changed tutorial to use built-in patterns
- Updated `installation_notes` for other built-ins to sync with new UI
- Updated `installation_notes` for mongodb to mention connection-string
- `documentation/src/pages/extensions/detail.tsx` and `documentation/static/servers.json`: Updated built-in strings to sync with new UI
TODO future task: Update jetbrains server info and tutorial as needed per …
=> docs: update extensions library

documentation/src/pages/community/data/june-2025.json
The thumbnail for community member was not saved to file before merging in https://github.com/block/goose/pull/3631/files
=> docs: Quick spotlight fix

crates/goose-server/src/openapi.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts
Small one to replace usages of `Tool/ToolAnnotations` in the generated openapi schema
For https://github.com/block/goose/issues/3578
=> feat: Replace usage of mcp_core Tools/ToolAnnotations in openapi schema

documentation/static/servers.json
Following up on #3390, servers.json also needs to be updated.
This is also related to https://github.com/jkawamoto/mcp-youtube-transcript/issues/26.
=> docs: fix installation command for YouTube Transcript MCP in servers.json

documentation/blog/2025-07-21-orchestrating-subagents/index.md
This pull request includes minor edits to the `documentation/blog/2025-07-21-orchestrating-subagents/index.md` file. The changes primarily address grammatical corrections and formatting improvements.
Grammatical corrections:
* Corrected punctuation in several sentences by replacing periods with proper sentence-ending punctuation. [[1]](diffhunk://#diff-e64cfbe897310ef36a00e4249a4ab87f38890c1821b506ac2bf0488baa0982dfL23-R23) [[2]](diffhunk://#diff-e64cfbe897310ef36a00e4249a4ab87f38890c1821b506ac2bf0488baa0982dfL86-R86)
Formatting improvements:
* Standardized capitalization for "3 Sequential Subagents" to ensure consistency.
=> small blog fixes

crates/goose-cli/src/session/output.rs, documentation/docs/guides/environment-variables.md
While these messages, like "Calculating the meaning of life", are amusing, being amused can sometimes be distracting. I prefer the UI to be consistent so I don't waste time on reading text that's not relevant to what I'm trying to accomplish. This patch adds the setting RANDOM_THINKING_MESSAGES, default true, that when changed to false replaces those messages with the less amusing text: "Thinking..."
=> Possible to disable random thinking messages

crates/goose/src/providers/claude_code.rs, crates/goose/src/providers/gemini_cli.rs
fixes: https://github.com/block/goose/issues/3682
=> fix: have option for cli providers to use their configured or default model 

crates/goose/src/model.rs
I did have a look at making openrouter load models context sizes (as it does return them in a list) but wasn't reliably able to get the correct size, so this just adds some new popular models with the correct context size
=> chore: adding in some new models token limits

documentation/docs/guides/managing-tools/index.md
Added `goose/` to link leading to Using Extensions page.
=> fix: Fixed 404 broken link to extensions page in index.md

crates/goose/src/providers/githubcopilot.rs
This PR introduces a new function `fetch_supported_models_async` to the `GithubCopilotProvider`. This function makes an API call to the `/models` endpoint of the GitHub Copilot service to retrieve a list of currently supported model identifiers.
=> feat(githubcopilot): add ability to fetch supported models

crates/goose/src/providers/formats/databricks.rs, crates/goose/src/providers/formats/openai.rs, crates/goose/src/providers/utils.rs
- Add json_escape_control_chars_in_string() utility function
- Apply fix to OpenAI and Databricks response parsers
- Enhance error messages with raw and processed arguments
- Add comprehensive test coverage for control character escaping
- ✅ Added unit tests for the new utility function covering various control character scenarios
- ✅ Updated existing tests to verify empty argument handling
- ✅ Manual testing with both OpenAI providers
- ✅ Verified that valid JSON arguments are unchanged
- ✅ Confirmed that structural JSON elements (quotes, backslashes) are preserved
This change is fully backwards compatible. It only affects the processing of malformed JSON arguments that would have previously failed to parse. Valid JSON arguments continue to work exactly as before.
Fixes …
=> fix: escape control characters in LLM tool call arguments JSON

documentation/docusaurus.config.ts
This error keeps popping up in development, and I get distracted from it/it's slowing me down 🤣 so here's a PR to make do the analytics for prod but not run in dev mode.
=> only run google analytics in prod

documentation/docs/mcp/git-mcp.md
This PR introduces a new tutorial to the documentation site demonstrating how to use the [GitMCP Server](https://github.com/idosal/git-mcp) as a Goose extension.
- A new guide at `docs/mcp/git-mcp.md`
- Step-by-step setup instructions for both Goose Desktop and CLI
- One-click installer for Goose Desktop using the dynamic GitMCP endpoint: `https://gitmcp.io/docs`
- Example prompt using the `openai/whisper` repo to show real-time documentation retrieval and code usage with GitMCP
- Full Goose output with a generated Markdown guide explaining the Whisper speech-to-text model
GitMCP gives LLMs real-time access to any public GitHub repository via the Model Context Protocol (MCP), significantly reducing hallucinations and enabling more accurate, grounded responses.
This tutorial makes it easy …
=> docs: GitMCP Tutorial 

crates/goose/src/agents/tool_vectordb.rs, crates/goose/src/recipe/mod.rs
we were creating dbs but not with unique names and weren't cleaning them up always either which presumably led to test failures when we had an instance that had this already around? this introduces a method to create a new unique db and returns also a clean up task
=> Fix tool vector tests

.github/workflows/ci.yml
This pull request updates the CI workflow configuration to optimize when the workflow is triggered. The most important change is the addition of `paths-ignore` rules to exclude documentation-only changes from triggering the CI workflow.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR8-R14): Added `paths-ignore` rules under both `pull_request` and `merge_group` triggers to prevent the CI workflow from running for changes made exclusively in the `documentation/**` directory.
=> skip app-related CI jobs for doc/blog PRs

documentation/docs/mcp/neon-mcp.md, documentation/static/servers.json
This PR adds the [Neon MCP server](https://github.com/neondatabase-labs/mcp-server-neon) to the MCP docs. 
- add `neon-mcp.md` tutorial to mcp docs
- documents two configuration setups: Remote MCP (streamable HTTP) or Local MCP (npx)
- lists three examples prompts & outputs for illustration purposes
=> docs: Add Neon MCP Server tutorial

ui/desktop/package-lock.json, ui/desktop/package.json
addresses
```
esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
```
=> chore: Update vitest to address moderate-level vuln in 2.x

crates/goose-mcp/src/developer/mod.rs, documentation/docs/guides/tips.md, documentation/docs/guides/using-goosehints.md
Rather than hardcoding `.goosehints`, enable the hints file name to be configurable (as it is with, say, the Gemini CLI tool or OpenCode.ai). Also enable the use of multiple such context files.
=> feat: Allow configuring hints filename(s)

crates/goose/src/config/base.rs
Start with the json, but provide reasonable primitive parses for non-quoted primitives.
lots of test cases.
Original justification for changes here was .0001 failed json parsing silently and didn't get picked up.
=> Env parsing for primitive types

documentation/docs/guides/managing-goose-sessions.md, documentation/docs/guides/recipes/session-recipes.md, documentation/docs/guides/recipes/storing-recipes.md, documentation/docs/mcp/_template_.mdx
This PR consolidates search sessions content and documents the Import Recipe button.
- `documentation/docs/guides/managing-goose-sessions.md`: 
- Added ## Search Sessions section and moved/condensed all search content here
- Added steps for searching a historical session (added somewhat recently)
- `documentation/docs/guides/recipes/session-recipes.md`: Added link to import steps
- `documentation/docs/guides/recipes/storing-recipes.md`: Added import steps
- `documentation/docs/mcp/_template_.mdx`: Fix typo
=> docs: consolidate search session content, doc import recipe

crates/goose-cli/src/commands/info.rs
=> Stable goose info -v

crates/goose-cli/src/session/mod.rs, crates/goose-cli/src/session/output.rs
There is a check here to write the output differently if it's a sub-agent, but with .unwrap_or(), we'd always hit that path
=> fix: cli tool logging

crates/goose-mcp/src/developer/mod.rs, crates/goose/src/model.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/context_management/index.ts
The shell (bash) command can result in a lot of pointless context filling, if is running a compile, or log tailing and so on. 
In reality only some of it is relevant, in this case it will limit it to around 100 lines (a few percentage points of context) and allow it to then search for more content when needed. 
For example, you can tell it to run a command like: 
```can you run find /System/Library -type f | head -n 2000```
(that was just an example I could consistently use) 
by default - this eats half the context window in one fell swoop: 
with this change: 
that is a contrived example but it isn't uncommon to hit this.
=> fix: don't return full shell output when very large

crates/goose/src/providers/anthropic.rs
https://docs.anthropic.com/en/docs/about-claude/models/overview#model-aliases for the aliases. Confusingly, -latest is used for the 3.5 and 3.7 models while -0 is used for the 4 models
Fixes #3757
=> Fix claude model names

crates/goose/src/conversation_fixer.rs
turns out we don't have a tool role, which means that we can't blindly collapse messages
=> No tool role means we should not collapse messages

.github/workflows/pr-comment-build-cli.yml, .github/workflows/pr-comment-bundle-intel.yml, .github/workflows/pr-comment-bundle-windows.yml, .github/workflows/pr-comment-bundle.yml
for issue_comment events, github.ref points to the default branch, so the builds get canceled when a new one on main starts
=> Use PR number for concurrency group

crates/goose-server/src/routes/agent.rs, crates/goose/src/providers/factory.rs, crates/goose/src/providers/mod.rs
This builds on https://github.com/block/goose/pull/3296 to support passing a lead model from a recipe to allow recipes to override default model configs and use the LeadWorkerProvider.
The existing code for creating a LeadWorkerProvider pulls env vars in the factory method, which makes it hard to override the values for a specific recipe's session. To address this limitation, I added a new factory method that allows providing construction dependencies for the specific provider type based on what that provider needs.
This is my first time writing Rust, so I'm not sure if my changes are idiomatic/proper, but I made a best effort there. Shout out  to Goose for helping me understand the codebase and Rust syntax.
=> Add support for setting `goose_lead_model` from a recipe

documentation/docs/tutorials/advanced-cognee-usage.md
I'm not the original author of this tutorial, but it seems that the markdown formatting on this tutorial was slightly incorrect, resulting in the instructions file being cut off prematurely.
=> docs: fix markdown for cognee tutorial

crates/goose/src/providers/base.rs, crates/goose/src/providers/ollama.rs
Addresses https://github.com/block/goose/issues/3294
=> Override session name generator for ollama provider

crates/goose-mcp/src/developer/mod.rs
- Fix TOCTOU races by opening the file exactly once and querying metadata from the fd
- Ensure that if the file changes as we read it, we still don't go over the limit
- Drop the `.chars()` iterator because the number of Unicode characters is always *less* than the file size in bytes and it's just extremely inefficient to iterate over the entire content of a large file just to compute a limit which is almost the same
=> developer: Optimize text_editor_view a bit

documentation/docs/guides/recipes/recipe-reference.md, documentation/docs/tutorials/recipes-tutorial.md
[Community members in Discord](https://discord.com/channels/1287729918100246654/1287729920319033345/1401046617225822359) were unsure how to set the model/provider for a recipe. 
This PR documents goose_provider, goose_model, and temperature settings for recipe-specific model configuration in the recipe reference document and the recipe tutorial
=> Add settings field documentation to recipe guides

ui/desktop/src/App.tsx, ui/desktop/src/hooks/useChat.ts
Noticed resuming sessions wasn't working after https://github.com/block/goose/pull/3742 
There was 404/401 errors in the console for config/init
=> fix session resume in new window

crates/goose-mcp/src/computercontroller/mod.rs, crates/goose-mcp/src/developer/mod.rs, crates/goose/src/agents/extension_manager.rs, crates/mcp-core/src/handler.rs
- Avoids redundant code
- Doesn't ignore parameters on type mismatches
Motivated specifically by me having a typo in my optional parameter name when developing.
Note: I only changed a random selection of goose-mcp, but if we choose to do this it'd likely be trivial to ask goose to finish it. I didn't do so yet to not make this a conflict-fest.
=> chore(mcp): Add helpers to parse parameters

crates/goose-mcp/src/developer/mod.rs
This makes these like the other tests. This race
condition was introduced by:
bbf1f1eee8eb3bbc33dbb152799ea99712dc0a2b
The real fix here is to stop using `set_current_dir()`, it is process global state and will just keep causing race conditions.
=> tests: Add missing `#[serial]` to two tests

documentation/src/components/LinuxDesktopInstallButtons.js
Linux install buttons were hard coded to 1.0.29. Community members were asking about this. 
This PR replaces hardcoded version URLs by fetching the latest using GitHub API. 
If the API call fails, it brings users to the release page with the latest binaries.
=> docs: Dynamic linux install buttons

.gitignore, Cargo.lock, crates/goose-cli/Cargo.toml, crates/goose-cli/src/recipes/print_recipe.rs, crates/goose-cli/src/session/output.rs
If you capture the output of goose, you don't need the ansi stuff
fixes #3736
=> Suppress ansi with pipes

ui/desktop/package-lock.json, ui/desktop/package.json
we should also do #3859 but this should fix the immediate build problem with windows/linux
=> Pin @mcp-ui/client in package.json

crates/goose-mcp/src/developer/mod.rs
after some time using the new version, we see more errors and increased usage of find
=> fix: replace glob/grep tool with shell

crates/goose/src/providers/formats/openai.rs
Goose was failing to properly serialize streamed content from GitHub Models using the OpenAI provider due to subtle differences in the response body from OpenAI vs GitHub Models. Namely:
1. The first streamed chunk from GitHub Models does _not_ contain a `model` key. 
2. The final chunk from GitHub Models, which contains the usage information, has `content: null`, which needs to be special cased as this is neither a text block nor a tool block.
I have addressed these issues by making the streaming parser logic less strict, allowing for slight variations in implementation to allow GitHub Models to continue to be usable with Goose.  
I had originally reported this in https://github.com/block/goose/issues/3615, but mistakenly closed it out as a duplicate of an unrelated issue. 
If you'd like …
=> Fix OpenAI Provider with GitHub Models

CONTRIBUTING.md, crates/goose-cli/src/commands/configure.rs, crates/goose/src/providers/base.rs, crates/goose/src/providers/githubcopilot.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts
It states in the [getting started / providers](https://block.github.io/goose/docs/getting-started/providers) page that GitHub CoPilot uses device code authentication flow for secure access. Unfortunately, the cli and web app prompt the user for a GITHUB_COPILOT_TOKEN instead. There is an [open issue](https://github.com/block/goose/issues/3037) about this as well. 
These changes only fix this for the cli. However, once you successfully configure CoPilot from the cli, the web app will use those credentials. 
The contents of this pull request were substantially written using opencode with Claude 4. I've reviewed to the best of my ability (I have not extensively programmed in Rust).
=> feat: add OAuth provider abstraction for CLI configuration

ui/desktop/src/components/settings/dictation/DictationSection.tsx
- Removed the `disabled` attribute from OpenAI Whisper option in the voice dictation provider dropdown
- Added dropdown refresh logic to update OpenAI configuration status when dropdown is opened
- Users can now switch back to OpenAI Whisper after selecting ElevenLabs
- Maintained visual indicator showing "(not configured)" when OpenAI is not set up
This fixes a critical UX bug where users would get permanently stuck after exploring ElevenLabs. The issue occurred because:
1. User starts with OpenAI Whisper (working or not)
2. User clicks ElevenLabs to explore it
3. **BUG**: OpenAI Whisper becomes disabled and unclickable
4. User cannot return to OpenAI, even to configure it
The root cause was the `disabled={!hasOpenAIKey}` attribute that prevented any interaction with the OpenAI option …
=> Fix voice dictation provider selection bug

ui/desktop/src/components/GooseSidebar/AppSidebar.tsx
so you can better see what you are doing if you have multiple sessions going:
fixes #1504
=> Make the window title reflect what we are doing

crates/goose/src/agents/agent.rs, crates/goose/src/scheduler.rs, ui/desktop/src/components/BaseChat.tsx, ui/desktop/src/hooks/useRecipeManager.ts
Fix issue https://github.com/block/goose/issues/3882
**What**
- Used `chat` mode for `foreground` job and `auto` for background job
- Set the extensions for schedule job in legacy mode
- UI
- enabled the recipe progress/messages in the conversation panel when auto executing foreground schedule job
- do not show the prompt in the chat input for auto executed foreground schedule job
=> fixed recipe schedule jobs

documentation/docs/guides/goose-cli-commands.md
This PR documents the Ctrl+R command history search feature for the Goose CLI.
- `documentation/docs/guides/goose-cli-commands.md`: Add Command History Search section
=> docs: cli command history search

ui/desktop/src/components/settings/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings/extensions/agent-api.ts, ui/desktop/src/components/settings/extensions/extension-manager.ts
Fixed race conditions from manually updating extension list by calling `setExtensions`
Extensions is now a computed value that automatically updates when `extensionsList` from context changes (memoized for performance)
Bonus: fixed toast message that was always showing "Removed" for deactivated extensions.
Tested and verified locally with manual and deeplink extensions.
=> fix: extension list not refreshing after installing from deeplink

Cargo.lock, Cargo.toml, crates/goose-cli/src/session/output.rs
rmcp 0.5.0 contains a fix for the numeric types in progress notifications
=> chore: rmcp 0.5.0

.github/workflows/bundle-desktop-linux.yml
Updates the linux desktop bundle workflow to use https://github.com/cross-rs/cross instead of cargo build. This lets us build for maximum compatibility. We're already using this for the CLI.
fixes #3236 
fixes #3820
=> Use cross in linux bundle workflow

documentation/docs/mcp/kiwi-flight-search.md, documentation/src/pages/extensions/index.tsx, documentation/src/utils/mcp-servers.ts, documentation/static/servers.json
- Added Kiwi Flight Extension Tutorial
- Put extensions in alphabetical order in extensions library
- Added section headers to separate built-in and community extensions
-
=> Docs: Add Kiwi Flight Search Extension Tutorial

ui/desktop/src/components/settings/extensions/deeplink.ts
Deeplinks for streamable HTTP extensions had two issues:
1. Only recognized `transport=streamable_http`, ignored `type=streamable_http` (some organizations like Kiwi Flight search have the goose URI
2. No support for authentication headers
This caused extensions like Kiwi.com to be registered as SSE instead of streamable_http, and prevented GitHub-style extensions requiring auth headers from working via deeplinks.
Enhanced the deeplink parser to:
- Support both `transport` and `type` parameters
- Parse `header=key%3Dvalue` parameters for streamable HTTP extensions
- Maintain backward compatibility
The deeplink parser only recognized `transport=streamable_http` but the actual config schema uses `type: 'streamable_http'`. This inconsistency led extension developers (like Kiwi.com) to …
=> Adding better deeplink support for streamable-http

BUILDING_LINUX.md
I needed to install **libxcb1-dev libxcb-util-dev protobuf-compiler** to compile the goose cli on a quite clean system. Maybe that should be added to the BUILDING_LINUX.md
=> add missing dependencies for developer setup

RELEASE.md
Right now `git branch --set-upstream-to origin/release/1.3.0` is required, but not documented before `just tag-push`
=> docs: update release docs with an additional step needed + adjust list formatting

crates/goose-cli/src/commands/configure.rs, crates/goose/src/agents/agent.rs, crates/goose/src/agents/prompt_manager.rs, crates/goose/src/agents/reply_parts.rs, crates/goose/src/agents/router_tool_selector.rs, crates/goose/src/agents/tool_route_manager.rs, crates/goose/src/agents/tool_router_index_manager.rs, crates/goose/src/providers/openrouter.rs, ui/desktop/src/components/settings/tool_selection_strategy/ToolSelectionStrategySection.tsx
Before:
`GOOSE_ROUTER_TOOL_SELECTION_STRATEGY = {llm, vector}`
After:
`GOOSE_ENABLE_ROUTER = {true , false}`
=> chore: enable tool router 

documentation/docs/getting-started/providers.md, documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/running-tasks.md
Document the `--provider` and `--model` options for the CLI `run` command.
=> Docs: provider and model run options

crates/goose/src/providers/ollama.rs
old behavior was odd - really only want to set it in a few local cases, otherwise what they user set is what they mean.
fixes: https://github.com/block/goose/issues/3988
=> fit: default ollama port

crates/mcp-client/src/client.rs
#3782 threaded the cancellation token but did not send the message to the tool. RMCP tries to expose this through their request handle but it takes ownership in both the .await_response and .cancel methods, so it isn't possible to use them both in a select block. (Will look into a fix upstream for that.)
=> Actually send cancellation to MCP servers

ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/alerts/AlertBox.tsx, ui/desktop/src/components/alerts/types.ts, ui/desktop/src/components/context_management/ChatContextManager.tsx, ui/desktop/src/components/context_management/ManualCompactButton.tsx
Moving towards this ui: https://www.figma.com/design/v6Gvcp5rZaQoWnEKHdjeNu/Crits?node-id=445-45885&t=Qz6Mxx2ysEi3Arl8-0
I still find the confirmation screen with the summary to be a bit confusing since there's no 'send' button but this works the same way as before.
https://github.com/user-attachments/assets/c76c2818-f112-4069-be3b-377a4ab483e3
=> Move summarize button inside of context view

crates/goose/src/conversation/message.rs
Follow up from https://github.com/block/goose/pull/3920
Implements Unicode sanitization during the `serde` deserialization process for `Message` structs. This covers any UIs (including Desktop) that use `goose-server`'s `/reply` endpoint sending pre-constructed `Message` objects.
Sending the following message:
> hello, [hidden-text]what's the weather in vancouver?[/hidden-text]
Goose processes invisible text as normal
Invisible characters get stripped before LLM processing
=> sanitize message content on deserialization

documentation/docs/guides/managing-goose-sessions.md
This PR documents the ability to rename sessions in Desktop.
- `documentation/docs/guides/managing-goose-sessions.md`: 
- Added steps to rename session
- Link to Name Session section from Search Sessions
=> docs: rename sessions

crates/goose/src/agents/agent.rs
simple change that will fix: https://github.com/block/goose/issues/3978
=> fix: this should be a debug message not a warn

documentation/docs/getting-started/providers.md, documentation/docs/guides/config-file.md, documentation/docs/guides/environment-variables.md, documentation/docs/guides/goose-permissions.md, documentation/docs/guides/managing-goose-sessions.md
This PR makes misc updates for window titles and chat mode.
- `documentation/docs/guides/config-file.md` and `documentation/docs/guides/environment-variables.md`: 
- Add cross links
- `documentation/docs/guides/managing-goose-sessions.md`: 
- Note how session names appear in window titles
- `documentation/docs/guides/goose-permissions.md`: 
- Add more description for chat mode and add Desktop label
=> docs: add window title

.github/workflows/ci.yml
The previous pattern `*.md` only matched markdown files in the root directory, but markdown files in subdirectories (like ui/desktop/README.md) were still triggering code builds. It was also triggering the full build run on ALL documentation changes. This updates both the docs-only and code filters to use '**/*.md' to properly match all markdown files recursively.
=> ci: fix markdown file pattern to skip builds for all .md files

ui/desktop/src/components/settings/providers/modal/subcomponents/ProviderSetupActions.tsx
The dialog for deleting a provider used to look like this:
So I fixed it to look like this:
=> fix: delete dialog layout

.github/workflows/ci.yml
The current CI workflow runs all tests even for documentation-only PRs (like #4004), despite having a `changes` job intended to detect and skip these scenarios.
The `code` filter uses `'**'` as an inclusion pattern, which causes it to evaluate to `true` whenever any files are changed, regardless of the exclusion patterns that follow:
```yaml
code:
- '**'                    # Matches all files (always true if any files changed)
- '!documentation/**'     # Exclusions don't prevent the filter from being true
- '!**/*.md'
```
Remove the `'**'` pattern and use only exclusion patterns for the `code` filter. Also expand markdown detection to include subdirectories:
```yaml
docs-only:
- 'documentation/**'
- '**/*.md'              # Matches .md files anywhere in repo
code:
- '!documentation/**' …
```
=> ci: fix docs-only filter to properly skip tests for documentation changes

.github/workflows/pr-comment-bundle.yml, .github/workflows/release-branches.yml
Right now we don't have signed builds from `.bundle` comments or on release branches, so messages like this need to be made accurate https://github.com/block/goose/pull/4069#issuecomment-3184371477
=> docs: make accurate the comments with links to unsigned builds of the app

crates/goose/src/prompts/summarize_oneshot.md
Trying to address some issues we're seeing with overly aggressive/short summaries during auto-compaction
Open to feedback on any of this, and also good methods to test
=> feat: iterating on summarize oneshot prompt

documentation/blog/2025-08-11-mcp-ui-post-browser-world/index.md, documentation/docs/guides/interactive-chat/mcp-ui.md, documentation/docs/mcp/dev.to-mcp.md, documentation/docs/mcp/neon-mcp.md, documentation/src/utils/install-links.ts, documentation/static/servers.json
This PR adds install links for streaming HTTP extensions that currently support it.
Documentation and blog updates: 
- Add install links to:
- `documentation/blog/2025-08-11-mcp-ui-post-browser-world/index.md` blog
- `documentation/docs/guides/interactive-chat/mcp-ui.md` guide topic
- `documentation/docs/mcp/neon-mcp.md` tutorial
- `documentation/docs/mcp/dev.to-mcp.md` tutorial
Extension library:
- `documentation/src/utils/install-links.ts`: 
- Add type=streamable_http parameter to deeplink
- `documentation/static/servers.json`:
- Change Neon entry to streamable
- Add Dev.to entry
=> docs: add streamable_http install links

crates/goose/src/providers/utils.rs
Anthropic throws a 529 which is somewhat unofficial - this makes us have a ServerError for all 500's which then all get retried.
=> Retry all 500 codes

documentation/docs/mcp/figma-mcp.md
Unlisting figma tutorial to be replaced with official Figma MCP Server
=> Unlist figma tutorial

ui/desktop/src/components/dashboard/DashboardWidget.tsx
- Individual session rows are now clickable and navigate to session details
- 'See all' button routes to sessions history view
- Added proper pointer-events handling for interactive elements
- Integrated with React Router navigation system
- Sessions load automatically when clicked from dashboard widget
This enables users to quickly access their chat history directly from the dashboard without losing the drag-and-drop widget functionality.
=> feat: add clickable functionality to Recent Chats widget

ui/desktop/src/components/InterruptionHandler.tsx, ui/desktop/src/components/MessageQueue.tsx, ui/desktop/src/components/dashboard/DashboardCanvas.tsx, ui/desktop/src/components/dashboard/DashboardWidget.tsx
- Remove unused onWidgetResize parameter from DashboardCanvas
- Remove unused onReset parameter from DashboardWidget
- Remove unused message variable from InterruptionHandler
- Remove unused MoreHorizontal import from MessageQueue
All lint errors have been resolved while maintaining functionality.
=> fix: resolve TypeScript lint errors

ui/desktop/src/components/ProviderGuard.tsx
- Add explicit navigation to chat after successful OpenRouter setup
- Add explicit navigation to chat after successful Ollama setup
- Fixes issue where users couldn't click navigation items after provider setup
- Ensures proper routing state after provider configuration
=> Fix navigation bugs after provider selection

documentation/docs/guides/environment-variables.md, documentation/docs/troubleshooting.md
The PR documents how the GOOSE_TERMINAL environment variable can be used to detect when Goose runs a command.
- `documentation/docs/guides/environment-variables.md`: 
- Add "Variables Controlled by Goose" section to separate from user-configurable settings
- `documentation/docs/troubleshooting.md`: 
- Add "Preventing Long-Running Commands" section with cross link
=> docs: goose_terminal env var

crates/goose-mcp/src/developer/mod.rs
I noticed that Gemini 2.5 Pro kept trying to use `insert` with `insert_line` set to -1. This makes sense, because:
- there is no easy way to append to the end of the file
- we use -1 to mean "end of file" in other contexts (`view_range`).
So, let's make -1 do the expected thing!
=> feat(mcp/developer): accept -1 for insert_line number

ui/desktop/package-lock.json, ui/desktop/package.json, ui/desktop/src/components/MarkdownContent.test.tsx, ui/desktop/src/components/MarkdownContent.tsx
Closes: #2278 
This PR enhances the markdown rendering capabilities in the goose desktop application by adding support for single line breaks.
**Changes Made :** 
- Added `remark-breaks` package to project dependencies
- Updated `MarkdownContent.tsx` to include the new plugin
- Added unit test for the functionality 
**Preview:** 
| Before | After |
|--------|-------|
| ![Preserve-single-newlines-before](https://github.com/user-attachments/assets/3763f373-27b2-410d-b8c0-12386e92c4e8) | ![Preserve-single-newlines-after](https://github.com/user-attachments/assets/dc901617-8c97-47bd-b850-cfb46e3a98a1) |
=> feat: add remark-breaks plugin to preserve single newlines in markdown

.gitignore, flake.lock, flake.nix
This PR adds Nix flake support for reproducible builds of the Goose CLI. The flake provides a consistent build environment across different systems and makes it easy for Nix users to build, develop, and run Goose.
What's included
- flake.nix - Main flake configuration that:
- Dynamically reads package metadata from Cargo.toml files (no hardcoded versions)
- Builds the goose-cli package with all required dependencies
- Provides a development shell with cargo tools
- Configures tests to run with proper HOME/XDG directories
- Supports both Linux and macOS platforms
- flake.lock - Pinned dependencies for reproducible builds
- .gitignore - Added result symlink exclusion
Testing
✅ CLI build and execution tested on NixOS (Linux/aarch64)
- nix build - Successfully builds the CLI binary
- nix run …
=> Add Nix flake for reproducible builds

crates/goose-cli/src/commands/configure.rs, crates/goose-server/src/routes/setup.rs, crates/goose/examples/tetrate_auth.rs, crates/goose/src/config/mod.rs, crates/goose/src/config/signup_tetrate/mod.rs, crates/goose/src/config/signup_tetrate/server.rs, crates/goose/src/config/signup_tetrate/templates/error.html, crates/goose/src/config/signup_tetrate/templates/invalid.html, crates/goose/src/config/signup_tetrate/templates/success.html, crates/goose/src/config/signup_tetrate/tests.rs, crates/goose/src/providers/factory.rs, crates/goose/src/providers/mod.rs, crates/goose/src/providers/tetrate.rs, ui/desktop/src/components/ProviderGuard.tsx, ui/desktop/src/components/settings/providers/ProviderSettingsPage.tsx, ui/desktop/src/utils/tetrateSetup.ts
Adds PKCE support for Tetrate Agent Router Service, similar to openrouter PKCE signup flow
Tetrate when signed up via a "work address" currently will give goose users starter credit, which is ideal.
=> Add PKCE support for Tetrate Agent Router Service

documentation/docs/guides/environment-variables.md, documentation/docs/guides/recipes/session-recipes.md, documentation/docs/guides/using-goosehints.md
This PR adds .cursorrule examples and clarifies the use case per feedback:
Documentation updates: 
- `documentation/docs/guides/environment-variables.md`: Add ". cursorrules" to example
- `documentation/docs/guides/recipes/session-recipes.md`: Format env var name
- `documentation/docs/guides/using-goosehints.md`: 
- Clarify use case in tip
- Add toolchain example
=> docs: custom context files improvements

ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/components/GooseMessage.tsx.backup, ui/desktop/src/components/ToolCallChain.tsx, ui/desktop/src/utils/toolCallChaining.ts
- Add tool call chaining logic to group consecutive tool-only messages
- Create ToolCallChain component to render chained tool calls with single timestamp
- Skip tool response messages when detecting chains to avoid breaking sequences
- Hide intermediate messages in chains, show only first message with all tool calls
- Disable chaining during streaming to prevent flickering
- Maintain all existing functionality (status indicators, expansion, notifications)
Visual improvements:
- Multiple consecutive tool calls now show as a single grouped section
- Single timestamp displayed for the entire chain instead of individual timestamps
- Reduces visual clutter when LLM makes multiple tool calls in sequence
- Preserves individual display for mixed content (text + tool calls)
Files added:
- …
=> feat: implement tool call chaining for consecutive tool calls

crates/goose/src/providers/errors.rs, crates/goose/src/providers/utils.rs
Improves error handling reliability for OpenAI-compatible providers and adds comprehensive test coverage.
I tried using Goose through a gateway which had an incorrect max payload size. The gateway returned a plain text error.
Before, the underlying error was obfuscated by a JSON failure: `Error: Request failed: error decoding response body`
```bash
$ goose run --debug -t 'should I install goose?'
starting session | provider: openai model: qwen3
logging to /Users/codefromthecrypt/.local/share/goose/sessions/20250819_090611.jsonl
working directory: /Users/codefromthecrypt/oss/goose
Error: Request failed: error decoding response body
Interrupted before the model replied and removed the last message.
error: The error above was an exception we were not able to handle.
These errors are often …
```
=> fix: improve OpenAI-compatible error handling and add test coverage

ui/desktop/src/components/BaseChat.tsx, ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/hub.tsx, ui/desktop/src/components/pair.tsx
Do the auto-submit using props instead of imperatively so we don't need to wait.
=> Remove half-second wait, rework auto submit

documentation/docs/tutorials/goose-in-docker.md
The Docker tutorial documentation contained broken links to `hardcoded_stuff.tsx` which was removed in commit a89fa18502 (PR #2744). These links were returning 404 errors when users tried to access them.
Updated the broken links to point to the current `ProviderRegistry.tsx` file, which contains the same provider and API key information that users need for Docker configuration.
- Fixed broken GitHub links in `documentation/docs/tutorials/goose-in-docker.md`
- Updated link text to be more descriptive
- Verified new link works and points to correct provider registry
**Before:** 
- Link to non-existent `hardcoded_stuff.tsx` (404 error)
**After:**
- Link to current `ProviderRegistry.tsx` (working link with same information)
This ensures users can actually access the provider and API key …
=> docs: fix broken links in Docker tutorial

documentation/docs/tutorials/cicd.md
This PR is to fix the pipeline(goose.yml) in tutorials.
1. Fixed indentation issue.
2. Added GH_TOKEN to run "gh" commands.
=> docs: fixed cicd tutorial pipeline in docs

.github/workflows/nightly.yml
Step one of having nightly releases. This sets up a new workflow for nightly releases of goose. These won't be signed yet.
Followups:
* Figure out signing keys that will work for nightly builds and update `with.signing` to be `true`
* Set up https://www.electronjs.org/docs/latest/tutorial/updates#using-cloud-object-storage-serverless as a deliver channel
* Add UI to settings to enable the user to opt into nightly builds
=> feat(releases): set up a workflow for nightly releases

documentation/docs/guides/using-goosehints.md
updated docs to specify `AGENTS.md` is now also read by default
=> docs: AGENTS.md is read by default

crates/goose/src/providers/api_client.rs
Fixes: https://github.com/block/goose/issues/3777#issuecomment-3223671268
```
~/.config/goose/custom_providers/custom_bigm_-_glm.json
{
"name": "custom_bigm_-_glm",
"engine": "anthropic",
"display_name": "BIGM - GLM",
"description": "Custom BIGM - GLM provider",
"api_key_env": "CUSTOM_BIGM_-_GLM_API_KEY",
"base_url": "https://open.bigmodel.cn/api/anthropic/v1/messages",
"models": [
{
"name": "glm-4.5",
"context_limit": 128000,
"input_token_cost": null,
"output_token_cost": null,
"currency": null,
"supports_cache_control": null
},
{
"name": "glm-45.-air",
"context_limit": 128000,
"input_token_cost": null,
"output_token_cost": null,
"currency": null,
"supports_cache_control": null
}
],
"headers": null,
"timeout_seconds": null,
"supports_streaming": true
}
% goose session
starting session | …
```
=> fix: url path trailing slash for custom-providers

ui/desktop/src/components/ProviderGuard.tsx
=> remove Ollama card from welcome screen

BUILDING_LINUX.md, crates/goose-mcp/src/computercontroller/platform/mod.rs
Updated,
Just support  linux computer control for android.
For build issue, let termux-package (termux upstream) to handle.
----
Updated,
We need some minor changes to support goose run on termux.
1. (goose-mcp) linux computer control add termux support
2. (goose-mcp) -  I use android-patch.sh to handle  xcap
- latest xcap required ubuntu newer than 20.04 but cross.rs only support 20.04
- xcap support android build not merge to upstream yet.
- latest xcap handle w.tilte() is different to xcap 0.0.14
3.  create [.github/workflows/build-termux-cli.yml](https://github.com/block/goose/pull/3890/files#diff-c92a843ffd904619ba4c9359133dd6f452e2f670877e25cfd93ae8e89642d7c0) to trigger termux build.
If people like to try https://github.com/shawn111/goose/releases/download/termux/goose-termux-aarch6 …
=> feat: linux computer control for android (termux)

crates/goose/src/recipe/read_recipe_file_content.rs, ui/desktop/src/main.ts, ui/desktop/src/utils/pathUtils.ts
fixing bug https://github.com/block/goose/issues/4362
=> Enhance `convert_path_with_tilde_expansion` to handle Windows

crates/goose-cli/src/cli.rs, crates/goose-server/src/routes/reply.rs, crates/goose-server/src/routes/schedule.rs, ui/desktop/src/hooks/useChatEngine.ts
- Adds additional recipe related telemetry to the UI 
- Adds tags to CLI recipe telemetry
=> Add metrics for recipe metadata in scheduler, UI, and CLI

documentation/src/pages/recipes/data/recipes/test-recipe.yaml
=> [Recipe Cookbook] test recipe flow

.github/workflows/recipe-security-scanner.yml, .github/workflows/send-api-key.yml, .github/workflows/validate-recipe-pr.yml
if the PR is ONLY doing a delete, all 3 of these workflows should be skipped
=> updating our 3 workflows to only operate if the PR is adding/editing a recipe

crates/goose-server/src/routes/schedule.rs
fix for comment in 
https://github.com/block/goose/pull/4399/files/d0a11254837dc7d7eb5a2299292a07a33803c24c#r2308781571
=> fix double filtering

documentation/src/pages/community/data/august-2025.json, documentation/src/pages/community/data/config.json, documentation/src/pages/community/data/july-2025.json, documentation/src/pages/community/index.tsx
Each month, to create a new spotlight for a given month, I just have to submit a month-year.json file, and set that given month to default on the [community landing page](https://block.github.io/goose/community). This PR pushes a new spotlight for July and August 2025.
Previously, I worked with goose to build a community landing page. This was carefully reviewed by both Rizel and Anthony to formatting choices and everything.
For reference, the list of all contributors to the block/goose project are pulled from GitHub, and are then analyzed and populated into the following lists:
1. Community Stars - This list consists of the top 5 contributors from the external community
2. Team Stars - This list consists the top 5 contributors from the internal community, aka the goose team and any …
=> docs: July and August 2025 Community All-Stars Update

crates/goose/src/agents/agent.rs, crates/goose/src/context_mgmt/auto_compact.rs
- When context limit is exceeded, automatically compact the conversation to continue instead of failing.
- Fixes https://github.com/block/goose/issues/1303
- Catch `ProviderError::ContextLengthExceeded` in agent reply loop
- Call `auto_compact::perform_compaction` to reduce conversation size without threshold checking
- Refactored compaction logic to separate threshold checking from actual compaction
- Continue conversation if compaction succeeds, fail gracefully with clear error message if not
=> fix: auto-compact on context limit error

documentation/docs/guides/sessions/session-management.md, documentation/docs/guides/sessions/smart-context-management.md
This PR documents the Summarize -> Compact button name change and removal of the summary view/editing modal. Also docs a keyboard shortcut.
- `documentation/docs/guides/sessions/session-management.md`:
- Add toggle sidebar shortcut
- `documentation/docs/guides/sessions/smart-context-management.md`: 
- Update button name
- Update manual steps (no view/edit summary)
- Misc edits to integrate "compact" terminology
=> docs: non-interactive compact now

AGENTS.md
Adds an `AGENTS.md` file following the emerging industry standard for guiding AI coding assistants in repository navigation and development workflows.
AGENTS.md is becoming the standard way to provide repository-specific context to AI coding assistants. It's already adopted by 20k+ open source projects including Apache Airflow, Temporal SDK, and LangGraph. The format serves as a "README for agents" - a predictable location where AI tools can find project-specific commands, structure, and constraints. Goose already reads AGENTS.md by default along with .goosehints.
See: https://agents.md/ for the standard specification.
As an AI agent framework, Goose should naturally support AI-assisted development of itself. This enables:
- Faster onboarding for contributors using AI assistants
- …
=> Add AGENTS.md for AI coding assistant support

documentation/docs/guides/recipes/session-recipes.md, documentation/docs/troubleshooting.md
This PR documents the "New Recipe Warning" model that runs each time a new/modified recipe is opened in Goose Desktop.
- `documentation/docs/guides/recipes/session-recipes.md`: 
- Add as step in "Use Recipe" section
- `documentation/docs/troubleshooting.md`:
- Add "New Recipe Warning" section
=> docs: new recipe warning

ui/desktop/src/recipe/recipeStorage.ts
Fixes https://github.com/block/goose/issues/4452
Changed `getStorageDirectory()` to use `window.appConfig.get('GOOSE_WORKING_DIR')` for building absolute paths instead of relative `.goose/recipes` paths, ensuring directory recipes are saved to the user's actual working directory rather than the Electron main process directory.
=> Fix local (working directory) recipes storage

documentation/docs/getting-started/using-extensions.md, documentation/docs/quickstart.md, documentation/docs/troubleshooting.md, documentation/docusaurus.config.ts
This PR updates the list of built-in extensions and updates links.
- `documentation/docs/getting-started/using-extensions.md`:
- Add Auto Visualiser as a built-in extension
- `documentation/docs/quickstart.md`:
- Replace broken v1 link
- Remove reference links (mostly unused) for consistency
- Change "Browse extensions" link target
- `documentation/docusaurus.config.ts`: 
- Add redirect
=> docs: update built-in extensions list and fix link

crates/goose-mcp/src/developer/rmcp_developer.rs
LLMs like gpt5-mini have trouble with the unified diff format. Allow them to use the simpler old/new_str str_replace
=> Soften str_replace instructions for weaker LLMs

ui/desktop/src/main.ts
Fixes https://github.com/block/goose/issues/1718
=> fix(1718): make --dir work when launching Goose.app

crates/goose/src/agents/agent.rs, crates/goose/src/agents/final_output_tool.rs, crates/goose/tests/agent.rs
When using structured output in a recipe and the agent completes its reply without calling the final_output tool. The agent will immediately be triggered to try again until it does call the final_output tool.
When this scenario occurs we create a user message telling the agent to call the final_output tool. This is yielded from the agent loop so users see it. However the problem was that this message was not being added to the messages vector, therefore the agent never saw this correctional guidance.
This can result in the agent repeating its mistake multiple times or taking entirely different trajectories rather than immediately fixing itself and calling the final_output tool on the next turn.
Append the correction message to messages vector so agent loop sees it on next turn.
I've also …
=> fix: Missing final structured output should provide guidance to model

documentation/docs/guides/interactive-chat/index.md, documentation/docs/guides/recipes/index.mdx, documentation/src/components/VideoCarousel.js
This PR adds a video carousel for recipe videos and a card to the interactive-chat landing page.
- `documentation/docs/guides/interactive-chat/index.md`: Add card for new blog post
- `documentation/docs/guides/recipes/index.mdx`: Change file type to mdx and add video carousel
- `documentation/src/components/VideoCarousel.js`:  New component
=> docs: recipe video carousel

crates/goose-cli/src/commands/mcp.rs, crates/goose-mcp/src/lib.rs, crates/goose-mcp/src/tutorial/mod.rs, crates/goose-server/src/commands/mcp.rs
- Server two of the change originally in https://github.com/block/goose/pull/4488
- Converts tutorial to only use the rust sdk for mcp, and not our internal mcp-server crate
- Verified all the input schemas and tool descriptions are the exact same as before
=> chore(mcp): convert tutorial mcp server to use the rust sdk for mcp

crates/goose-cli/src/commands/mcp.rs, crates/goose-mcp/examples/mcp.rs, crates/goose-mcp/src/lib.rs, crates/goose-mcp/src/memory/mod.rs, crates/goose-server/src/commands/mcp.rs
- Server three of the change originally in https://github.com/block/goose/pull/4488
- Converts memory to only use the rust sdk for mcp, and not our internal mcp-server crate
- Verified all the input schemas and tool descriptions are the exact same as before
=> chore(mcp): convert memory mcp server to use the rust sdk for mcp

crates/goose/src/agents/agent.rs
Ran into a context limit exceeded error while using an anthropic model that was not caught by the provider specific error parsing in `crates/goose/src/providers/anthropic.rs`
Considering adding this as a catchall at the top level.
=> fix(compaction): try to catch more context limit exceeded errors and compact

crates/goose-server/src/routes/reply.rs, crates/goose-server/src/state.rs
Previously the metric was called on every /reply call. Now its only on the first time scoped by session_id.
Tested running recipe from ui still runs.
=> fix: Only metric a recipe run from ui on the first /reply call

CONTRIBUTING.md, Justfile, ui/desktop/src/goosed.ts
Fixes an issue where the UI failed to start when using an external backend due to the client not being properly initialised.
Kudos to @tlongwell-block for the [help on discord](https://discord.com/channels/1287729918100246654/1417899132286271721) and the UI patch.
=> fix client initialization when using an external backend

crates/goose-cli/src/commands/acp.rs
Makes tool calls look nicer when rendered by an acp client.
Example in Zed:
**Before**
**After**
=> feat(acp): add nicer formatting for tool names

ui/desktop/forge.config.ts, ui/desktop/forge.deb.desktop, ui/desktop/forge.rpm.desktop
To fix #4079 we'll need electron forge to spit out a desktop file with an absolute path for the 'Exec' line. This change directs each linux maker to use a flat, pre-filled desktop file that electronforge calls a 'desktopTemplate'.
The `Icon` line benefits from this change as well as it is now an absolute path.
=> refactor(forge): employ desktopTemplate to support absolute paths

Cargo.lock, crates/goose-mcp/Cargo.toml, crates/goose-mcp/src/developer/rmcp_developer.rs, crates/goose-mcp/src/developer/shell.rs
Addresses https://github.com/block/goose/issues/4125
https://github.com/user-attachments/assets/fb09ff1d-7385-4257-9098-fbfc73f46fb3
=> When the developer extension gets a cancellation message, it should kill any running processes that it owns.

documentation/docs/guides/acp-clients.md, documentation/docs/guides/goose-cli-commands.md
This PR documents Agent Client Protocol (ACP) support.
- `documentation/docs/guides/acp-clients.md`: 
- New topic
- `documentation/docs/guides/goose-cli-commands.md`: 
- Add `goose acp` command in CLI reference
=> docs: acp support

crates/goose-cli/src/session/mod.rs
Implements https://github.com/block/goose/issues/3641.
Simple change to add elapsed time to the session output in the CLI. Here's a screenshot showing how it looks.
=> Add elapsed time to the CLI output.

documentation/docs/mcp/openmetadata-mcp.md, documentation/static/servers.json
Added OpenMetadata's MCP server to list of Goose extension tutorials. OpenMetadata is an open-source metadata platform  for data discovery, observability, and governance. You can find more at information in pr and at https://open-metadata.org/mcp
Thanks!
=> docs: Add openmetadata extension to goose mcp docs

crates/goose-mcp/src/computercontroller/mod.rs
Fixing windows builds by removing nested double quotes in an os specific tool macro description
=> fix: remove nested double quotes in windows automation_script tool description

crates/goose/tests/pricing_integration_test.rs
The real fix here is that we should not have a test that breaks when an external API changes. If we want to keep this text around we should mock the API
=> fix: pricing integration test

.github/workflows/stale.yml
We will mark PRs as stale if there hasn't been any activity for 23 days. 7 days after the stale label, the PR will be automatically closed if there are no new acitivities. 
Sample run on my personal repo
=> add automation for marking and closing stale PRs

crates/goose-server/src/routes/audio.rs, crates/goose-server/src/routes/reply.rs, crates/goose/src/providers/factory.rs, crates/goose/src/tool_inspection.rs, crates/goose/tests/agent.rs
Removing unused code, and adding test cases where there was unused code that should have been used
=> chore: fix all warnings in test compilation

.github/workflows/stale.yml
When only-pr-labels is used, the stale action will only consider pull requests that contain all of the specified labels for its staleness checks.
=> remove only-pr-labels

crates/goose-mcp/src/developer/rmcp_developer.rs
Small change - now it uses preferred SHELL this hints to the system what it is: 
https://github.com/block/goose/pull/4702
TBH not sure if needed as it can work it out - but may hint to some LLMs
=> can tell the system what shell it is using

documentation/src/pages/extensions/index.tsx
Seems out of place/unintended?
=> docs: remove recipe generator link from next to extension search

documentation/.goosehints
- Ensures goose is always written with lowercase 'g' in docs and blog
- brand guideline compliance
- Provides clear examples for correct usage
=> Add .goosehints file to enforce lowercase branding in documentation

crates/goose-cli/src/cli.rs
This PR fixes the CLI to properly return a non-zero exit code (1) when a session ends with an error, allowing scripts and CI/CD pipelines to detect failures.
When the goose CLI encounters an error during a session (such as an invalid temperature parameter), it prints the error message to stderr but still exits with code 0. This makes it impossible for automated scripts to detect when goose has failed.
Added `std::process::exit(1)` after printing the error message when a session fails. This ensures the process exits with a non-zero status code that scripts can detect.
- Modified `crates/goose-cli/src/cli.rs` to call `std::process::exit(1)` when `session.interactive()` returns an error
- Built the project with `cargo build --package goose-cli`
- Ran existing tests with `cargo test --package …
=> Fix #4612: Return non-zero exit code when CLI session ends with error

crates/goose-mcp/src/developer/text_editor.rs
There is an issue opened 
https://github.com/block/goose/issues/4658
Path is duplicated on tool calls causing them to fail
What happens is when LLM calls text_editor in diff mode it passes
path: /a/b/c/base/src/file.go
in diff there is path: base/src/file.go
Inside mpatch they are merged and produce
path: /a/b/c/base/src/base/src/file.go
This path doesn't exist and tool fails.
Maybe it's an error from LLM side, that it calls tool incorrectly. But I tried several and it's a common issue. 
So I propose to remove overlapping part from base_dir before sending to mpatch. I tested fix in Linux and it works good.
=> fix: path is duplicated on tool calls causing them to fail (#4658)

crates/goose-cli/src/session/input.rs
This PR addresses a Windows-specific bug where ANSI escape sequences in the Goose CLI prompt cause incorrect cursor positioning and visual artifacts. This is a follow-up to the draft PR #3989 originally started by another contributor, with a refined implementation focused on simplicity and reliability.
On Windows, the Goose CLI prompt uses ANSI escape sequences for styling (cyan and bold colors):
```rust
let prompt = format!("{} ", console::style("( O)>").cyan().bold());
```
However, `rustyline` on Windows has a known issue with ANSI escape sequence width calculation that causes:
- Cursor positioning to be offset from the actual text
- Visual artifacts when editing commands
- A poor user experience with input handling
This is a known issue in the `rustyline` library where ANSI escape …
=> fix: Windows prompt cursor positioning issue with ANSI escape sequences

crates/goose-cli/src/cli.rs, crates/goose-cli/src/commands/schedule.rs, crates/goose-cli/src/commands/session.rs
adds `-p/--path` and `-l/--limit` to `goose session list` command
---
**Email**:
=> feat(cli): add `path` & `limit` to `session list` command

crates/goose/src/providers/databricks.rs, crates/goose/src/providers/openrouter.rs
added claude-sonnet-4-5 to list of models
=> added claude-sonnet-4-5

recipe-scanner/base_recipe.yaml
instructing goose to redact environment variables deemed "necessary" in a user recipe for the security scanner
=> patching the security scanner to redact environment variables

crates/goose-cli/src/cli.rs, crates/goose-cli/src/session/mod.rs, crates/goose-cli/src/session/output.rs
This PR restores the ability to resume a session using its ID and name interchangeably with the `--name` CLI flag
I also added print statements so that the session ID is printed to the console at session start and end, similar to how the session file path was printed at session start/end before the SQLite migration. This makes it easier to quickly resume a previous session from the same terminal, without needing to run `goose session list` and pick through the output to the correct session ID
Fixes #4935
=> Using --resume with --name should still accept session IDs

BUILDING_LINUX.md
The libxcb-devel package is missing for building under fedora systems.
=> Add missing library for fedora/rhel/centos docs

crates/goose/src/session/session_manager.rs
=> Make create_session work concurrently

crates/goose-cli/src/commands/configure.rs
Some providers like ollama/ramalama does not require an API Key to serve models locally, for that, we can make this option accept empty values.
Closes #4797
=> Allow empty API Key when registering custom provider

documentation/src/pages/community/data/community-content.json, documentation/src/pages/community/index.tsx
This adds a section for community-submitted blog posts and videos to have a spot to live. While also allowing Hacktoberfest PRs for them submit a file change.
We can change the "default" card to be empty! Made with the help of goose with some tweaks. 😸 
Tested the changes and preview locally to make sure everything is working.
Relates to #ISSUE_ID  
Discussion: LINK (if any)
Before:  
(previously, page ended after community all-stars section)
After:   
**Email**:
=> docs: Add Community Content section to Community Page

crates/goose-cli/src/session/builder.rs
Add support for GOOSE_DEBUG environment variable to enable debug mode without requiring the --debug CLI flag. Follows existing precedence pattern where CLI flags take priority over environment variables.
- CLI --debug flag overrides GOOSE_DEBUG env var
- GOOSE_DEBUG=true shows full tool parameters without truncation
- Defaults to false if neither CLI flag nor env var is set
- Uses same config.get_param() pattern as GOOSE_PROVIDER/GOOSE_MODEL
=> feat(cli): add GOOSE_DEBUG environment variable support

documentation/src/pages/recipes/data/recipes/full-stack-project-initializer.yaml
Advanced recipe for automated full-stack project initialization supporting multiple framework combinations (React/Vue/Svelte/Next.js + Node.js/Python/Go/Rust), database integrations (PostgreSQL/MongoDB/MySQL/SQLite), Docker, CI/CD, and production-ready configurations with comprehensive testing and documentation.
**Key Features:**
- 8 customizable parameters for complete project control
- 20+ framework/database combinations
- Automated setup for ESLint, Prettier, Vitest, Jest, Docker Compose, GitHub Actions
- Advanced Jinja2 templating with conditional logic
- 8-step orchestration workflow (structure → frontend → backend → quality tools → Docker → CI/CD → docs → verification)
used command:
```bash
goose run --recipe documentation/src/pages/recipes/data/recipes/full-stack-project-initializer …
```
=> feat: add advanced software project generator initializer recipe (#4767)

documentation/src/pages/recipes/data/recipes/smart-task-organizer.yaml, temp_batch_fetch.txt
Add an impressive **Smart Task Organizer** recipe for Hacktoberfest 2025 that transforms scattered information into organized, actionable task lists using AI-powered automation.
This recipe demonstrates how AI can turn chaotic information from multiple sources (files, emails, messages, notes) into structured, prioritized todo lists. It's designed for professionals who struggle with task overload and need intelligent task management.
**Multi-Source Task Intelligence**: Unlike simple task managers, this recipe:
- Scans multiple file types and formats for hidden action items
- Converts vague commitments into concrete next steps
- Intelligently categorizes by urgency, importance, and project
- Provides immediate actionable next steps for each task
- **Smart Task Extraction**: Identifies …
=> feat: add Smart Task Organizer recipe for Hacktoberfest

download_cli.sh
Goose CLI install script shows **Unix-style PATH instructions** on Windows (e.g., `.bashrc`, `.zshrc`).
This confuses Windows users, who primarily use **PowerShell**.
```text
Warning: goose installed, but /home/rob-admin/.local/bin is not in your PATH.
Add it to your PATH by editing ~/.bashrc, ~/.zshrc, or similar...
```
```text
Warning: goose installed, but C:\Users\<user>\.local\bin is not in your PATH.
To add goose to your PATH in PowerShell:
$profilePath = $PROFILE
if (!(Test-Path $profilePath)) { New-Item -Path $profilePath -ItemType File -Force }
Add-Content -Path $profilePath -Value '$env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"'
. $PROFILE
Alternatively: goose configure
```
* Detect Windows and show **PowerShell instructions**.
* Keep Bash/Zsh for Unix systems.
* Added …
=> fix: show PowerShell PATH instructions for Windows users

crates/goose/src/model.rs, crates/goose/src/providers/xai.rs
Added support for xAI's grok-code-fast-1 model, which is cost-effective, fast, and particularly good at writing code with a 256K context window.
- Added `grok-code-fast-1` to `XAI_KNOWN_MODELS` array
- Set `grok-code-fast-1` as the default xAI model
Closes #4386
https://openrouter.ai/x-ai/grok-code-fast-1
---
**Email**:
=> feat: add grok-code-fast-1 support for xAI provider

ui/desktop/src/components/settings/models/subcomponents/LeadWorkerSettings.test.tsx, ui/desktop/src/components/settings/models/subcomponents/LeadWorkerSettings.tsx
This PR adds the ability to set a custom model ID for lead and/or worker.
Long term, would it be more consistent to use the Provider -> Model components as seen in the Switch Model modal?
=> feat: set custom models for lead/worker

documentation/src/pages/recipes/data/recipes/code-review-mentor.yaml
Intelligent code review assistant that combines Developer and Memory extensions to provide personalized, actionable feedback on code changes. The recipe learns reviewer preferences over time and adapts its feedback style, making code reviews more effective and educational.
- Learns and remembers coding preferences and team standards
-  Multi-layered analysis (security, performance, readability, testing, documentation)
-  Configurable review depth (quick/balanced/thorough) and scope (staged/unstaged/commit/branch)
-  Educational feedback with examples and explanations
-  Tracks improvement patterns across reviews
Manual testing performed:
- YAML structure validation
-  Parameter configuration with various combinations
-  Extension integration (Developer + Memory)
-  Jinja2 template …
=> feat: add Code Review Mentor recipe with Developer and Memory extensions (#4992)

documentation/src/pages/recipes/data/recipes/data-analysis-pipeline.yaml, documentation/src/pages/recipes/data/recipes/subrecipes/chart-generator.yaml, documentation/src/pages/recipes/data/recipes/subrecipes/data-cleaner.yaml, documentation/src/pages/recipes/data/recipes/subrecipes/data-validator.yaml, documentation/src/pages/recipes/data/recipes/subrecipes/statistical-analyzer.yaml
Advanced recipe that orchestrates data validation, cleaning, statistical analysis, and visualization through 4 specialized sub-recipes. Features 3 extensions, conditional logic, OS-compatible path handling, and comprehensive error recovery. Optimized for token reduction and faster execution.
Extensions usage:
1. Developer (Builtin)
- Type: builtin
- Name: developer
- Timeout: 600s (main), 300s (validator, analyzer, cleaner, generator)
- Purpose: File operations, data processing, script execution, running Python code
- Used in: All 5 recipes (main + all 4 sub-recipes)
2. Memory (Builtin)
- Type: builtin
- Name: memory
- Timeout: 300s
- Purpose: Storing analysis context and intermediate results across stages, passing validation results between sub-recipes
- Used in: Main recipe only 
3. …
=> feat: Add advanced data analysis pipeline recipe (#4990)

crates/goose/src/providers/cursor_agent.rs
As described in [issue #4540](https://github.com/block/goose/issues/4540), on Mac (at least) the Cursor Agent provider could not be configured via `goose configure` because the process failed with error: 
```
◇  Request failed: Command failed with exit code: Some(1)
│
└  Failed to configure provider: init chat completion request with tool did not succeed.
```
This was not (at least in my case) a permissions error, but a result of two difficulties with cursor-agent's model parameter. 
First, for some reason the documented "-m" argument to `cursor-agent` does not work in current versions; the full "--model" form must be used. 
Second, "gpt-5" was not recognized as a valid by `cursor-agent` (at least on my system, though the model is certainly available and listed under certain …
=> fix: Issue #4540: `goose configure` -> Cursor Agent succeeds

ui/desktop/src/main.ts
**Issue:** When deeplink is triggered in chrome, a new window is created but the recipe is not loaded. 
**Why:**  There is a race condition that the server is not up when triggering decode recipe api call
**Fix:** 
-  Check server is ready when creating a new window (in create_chat). 
-  This will the centralised place to check server status.  Removed the existing check in `get-goosed-host-port` handling as it is redundant now
Manual testing
=> fix: check server is ready so that we can decode the recipe deeplink

.github/workflows/ci.yml
This job runs lint and test, so it should say so in the title
=> chore: put test in the name

documentation/src/pages/community/data/community-content.json
Add a comprehensive blog  on "Running Goose in Containerized Environments".  The guide provides best practices, examples, and production notes for running Goose in Docker, Docker Compose, Kubernetes, and cloud container services. It also includes troubleshooting tips, CI/CD integration examples, and security recommendations.
Relates to #4719
=> docs(blog): Add blog for running Goose in containerized envs 

crates/goose-mcp/src/developer/analyze/mod.rs
When using the `analyze` tool's focus mode on a file path instead of a directory, show a brief note suggesting that directory paths work better for cross-file analysis.
**Example**:
```
NOTE: Focus mode works best with directory paths. Use a parent directory in the path for cross-file analysis.
FOCUSED ANALYSIS: symbol_name
...
```
The hint appears only when both conditions are met: focus mode is active and the target is a file. Directory analysis is unchanged.
=> Add hint for focus mode when used on file paths for `analyze` tool
