block/goose

pyproject.toml
Fixes an issue where metadata.plugins export should have a valid module
=> fix: export metadata.plugins export should have valid module

.github/workflows/deploy_docs.yaml
=> docs: add callout plugin

packages/exchange/src/exchange/providers/google.py, packages/exchange/tests/test_integration_vision.py
#129 
@codefromthecrypt is this all that's needed? The integration test passes locally for me and it looks to be reading the text from within the image. I haven't yet recorded a VCR test for it.
=> feat: add vision support for Google

packages/exchange/pyproject.toml
bumping `exchange` release to include 
- #141
- #150
=> chore(release): exchange 0.9.5

CHANGELOG.md, pyproject.toml
release 0.9.5
- #140
- #142
- #143
- #145
=> chore(release): goose 0.9.5

justfile
* added justfile to `format` recipe
* added recipe descriptions
* added guards to ensure commands fail early 
* switched from `grep` to use `toml-cli` for consistency
* use --long-options for self documentation
for convenient review, `diff` [without whitespace](https://github.com/block-open-source/goose/pull/163/files?diff=unified&w=1)
=> chore: add justfile to format recipe

.github/workflows/release-monitor.yml
Will check releases that goose can run, if it fails, will open an issue:
=> fix: adding a release checker

src/goose/cli/main.py, tests/cli/test_main.py
=> feat: list moderators

src/goose/profile.py
has been working quite well for some time now
=> feat: default to synopsis

README.md
*note* this is a shared branch intentionally for collaboration
This is a stab to make the intro more outcome based. I originally wanted less total words, maybe it is about the same. However, I like focusing on what goose does for me vs what goose can do in abstract. Feel free to revise.
=> docs: reworks README to be outcome based

CHANGELOG.md, packages/exchange/pyproject.toml, pyproject.toml
Updating exchange version to 0.9.9 with goose 0.9.10 release
=> chore: release v0.9.10

pyproject.toml, src/goose/toolkit/memory.py, src/goose/toolkit/prompts/memory.jinja, tests/toolkit/test_memory.py
Adds a Memory toolkit that enables storing and recalling information across Goose conversations. The toolki 
provides persistent storage with categorization and tagging support.                                        
- Dual-scope storage: local (.goose/memory/) for project-specific info and global (~/.config/goose/memory/) 
for user preferences                                                                                        
- Category-based organization with optional tags for improved searchability                                 
- Plain text storage format for easy inspection and version control                                         
- Automatic integration with system prompts                                                                 
The toolkit provides four core …
=> feat: add memory toolkit

docs/plugins/available-toolkits.md
added description for missing toolkits
- Browser
- Memory
- Reasoner
- Synopsis
removed description for Lint which is not a real toolkit
=> chore: update toolkit docs

pyproject.toml, src/goose/toolkit/google_workspace.py, src/goose/toolkit/prompts/google_workspace.jinja, src/goose/tools/gmail_client.py, src/goose/tools/google_calendar_client.py, src/goose/tools/google_oauth_handler.py, tests/toolkit/test_google_workspace.py
Implements a toolkit for interfacing with Google Workspace tools like email and calendar.
- Handles the OAuth flow on first tool use
- Simply lists recent emails right now
- List today's Google calendar events
You must have a valid credentials file `~/.config/goose/google_credentials.json` which is generated in the Google developer console.
Demo video:
Listing emails
https://github.com/user-attachments/assets/5effe8f2-5cdc-473c-a633-ceb773270719
Getting today's events
=> feat: Google Workspace Toolkit

crates/goose-cli/src/main.rs, crates/goose/src/errors.rs, crates/goose/src/lib.rs, crates/goose/src/providers/base.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/openai.rs, crates/goose/src/providers/types.rs, crates/goose/src/providers/types/content.rs, crates/goose/src/providers/types/message.rs, crates/goose/src/providers/utils.rs, crates/goose/src/systems.rs, crates/goose/src/tool.rs, crates/goose/tests/systems.rs, docs/errors.md
Best viewed commit by commit - the first shows the refactor of the errors, the second is making it work elsewhere
=> feat: Error refactor

crates/goose-cli/src/main.rs, crates/goose/Cargo.toml, crates/goose/src/errors.rs, crates/goose/src/lib.rs, crates/goose/src/providers/base.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/openai.rs, crates/goose/src/providers/types.rs, crates/goose/src/providers/types/content.rs, crates/goose/src/providers/types/message.rs, crates/goose/src/providers/types/tool.rs, crates/goose/src/providers/utils.rs, crates/goose/src/systems.rs, crates/goose/src/systems/error.rs, crates/goose/src/tool.rs, crates/goose/tests/systems.rs, docs/errors.md, docs/systems.md
See the example in tests/systems.rs
I've also put some documentatino in that previews an idea around macros, but they are not yet implemented
=> feat: Implement system protocol

README.md, docs/index.md
This pull request includes updates to the `README.md` and `docs/index.md` files to improve the clarity and inclusivity of the testimonials section. The main changes involve updating references from "Block employees" to "users" and revising the corresponding section titles and links.
Updates to testimonials section:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L29-R29): Changed section title from "What Block employees have to say about Goose" to "What users have to say about Goose" and updated the corresponding link. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L29-R29) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L67-R67)
* …
=> docs: Update testimonial references to all users

README.md, docs/index.md, docs/quickstart.md
This pull request includes significant updates to the documentation for Goose, focusing on improving the quickstart guide and setup instructions. The most important changes include the addition of a new quickstart guide, detailed setup instructions for providers, and updates to existing documentation links.
* [`docs/quickstart.md`](diffhunk://#diff-988a5392cf907f7c5728b8ac90445facc7f835f3c00375764ec99769dcde2d5aR1-R108): Added a comprehensive quickstart guide, including installation instructions, session management, and additional tips for using Goose.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R140-R150): Added instructions for setting up a provider, including details on setting the `OPENAI_API_KEY` and billing …
=> docs: Update docs quickstart

docs/guidance/managing-goose-sessions.md, mkdocs.yml
I noticed that members of our community have had questions about managing sessions with these commands, so it’s likely that our broader, external community could benefit from similar guidance.
This guide provides detailed instructions on:
Starting, ending, saving, resuming, and deleting sessions.
---
- https://app.asana.com/0/0/1208665181140610
=> docs: adding Managing Goose Sessions guide

docs/index.md, docs/quickstart.md, mkdocs.yml
This pull request includes several documentation updates and an addition to the navigation menu in the `mkdocs.yml` file. The most important changes are focused on improving the quickstart guide and session management documentation.
* [`docs/index.md`](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6L30-R30): Updated the link for the quickstart guide to point to the correct URL.
* [`docs/quickstart.md`](diffhunk://#diff-988a5392cf907f7c5728b8ac90445facc7f835f3c00375764ec99769dcde2d5aR69-R71): Added a new section to guide users on managing Goose sessions and included a link to the managing sessions documentation. [[1]](diffhunk://#diff-988a5392cf907f7c5728b8ac90445facc7f835f3c00375764ec99769dcde2d5aR69-R71) …
=> docs: Update references to Quickstart and managing sessions guide

crates/goose-cli/src/commands/session.rs, crates/goose-cli/src/prompt/cliclack.rs, crates/goose-cli/src/prompt/mod.rs, crates/goose-cli/src/prompt/prompt.rs, crates/goose-cli/src/session.rs
Reorganise prompt code in cli crate.
=> [cli] Splits profile.rs into interface and cliclack implementation files

crates/goose-cli/src/commands/session.rs, crates/goose-cli/src/prompt/prompt.rs, crates/goose-cli/src/session/session.rs
Show the provider and model during goose startup.
=> [cli] Show provider and model during startup

crates/goose/src/developer.rs, crates/goose/src/prompts/system.md
This might still need a few iterations
=> feat: clarify the dev system prompt

mkdocs.yml
---
- https://app.asana.com/0/0/1208779278872489
=> docs: moving Blog lower in the menu

crates/goose-server/src/routes/reply.rs, ui/desktop/package-lock.json, ui/desktop/package.json, ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/components/ToolInvocation.tsx, ui/desktop/tailwind.config.ts
Required both fixes for tailwind (which interferes with markdown rendering), a plugin for it, as well as correctly setting newlines in the stream from the server.
=> fix: fix markdown for agent response 

ui/desktop/package.json
helper script to do it in right order
=> feat: Macos sign

Justfile
I got tired of copying the binary to UI on release so I added a small just file. 
Might be useful for future
=> [chore]: add Just for build script modification

Justfile, crates/goose-cli/src/session.rs, crates/goose-server/src/routes/reply.rs, crates/goose/Cargo.toml, crates/goose/src/lib.rs, crates/goose/src/memory.rs
This is an adapted version of `memory` toolkit from the python goose. 
It is used to store and retrieve memories in both global and local contexts.
Due to run dir still being in an ambiguous state - advice is to use global memory
=> [feat]: Add memory system

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/components/GooseResponseForm.tsx, ui/desktop/src/components/ToolInvocations.tsx, ui/desktop/src/utils/urlUtils.ts
- Filter out non-relevant tool results for the user, when the user is not in audience
- Clean up and remove verbose debug logging from other features
=> [app] Only render ToolResults relevant to the user - clean up logging

crates/goose-server/src/main.rs, crates/goose-server/src/routes/reply.rs, crates/goose-server/src/state.rs, crates/goose/src/developer.rs
This makes the agent part of app state, and relies on each client process having a separate copy of goosed
=> fix: server state persists

docs/configuration.md
This pull request includes updates to the `docs/configuration.md` file to improve clarity and add new information about toolkits. The most important changes include correcting a grammatical error and adding a new section on toolkits.
Documentation improvements:
* Corrected a grammatical error in the description of LLM providers.
* Added a new section on toolkits, explaining their purpose and providing a command to list available toolkits.
---
- https://app.asana.com/0/0/1208808316738867
=> docs: Add toolkits section to fields

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/components/Splash.tsx, ui/desktop/src/goosed.ts, ui/desktop/src/main.ts, ui/desktop/src/utils/recentDirs.ts
=> feat: open dir for goose

docs/plugins/using-toolkits.md
- added more details and example around `profiles` 
- added more details around `goose-plugins` toolkits 
---
- https://app.asana.com/0/0/1208838154670050
=> docs: providing more clarity to our `Using Toolkits Guide`

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/components/WingToWing.tsx, ui/desktop/src/utils/askAI.ts
ChatWindow.tsx was getting a little large
=> fix: tidy up chat only

ui/desktop/src/components/Splash.tsx, ui/desktop/src/main.ts, ui/desktop/src/preload.js
=> feat: clickable working dir

ui/desktop/src/components/Input.tsx
Implements use effect on the input component so user does not have to click on the input box to type
=> fix: return cursor to input text

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/utils/askAI.ts
making main chat tsx smaller for goose itself to use
=> fix: tidup prompts

docs/blog/posts/2024-11-22-screenshot-driven-development.md
Adding social card for `docs/blog/posts/2024-11-22-screenshot-driven-development.md` blog post
=> docs: adding social card

crates/goose/Cargo.toml, crates/goose/benches/tokenization_benchmark.rs, crates/goose/src/agent.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/openai.rs, crates/goose/src/providers/utils.rs, crates/goose/src/token_counter.rs
Changes:
- raise context limit exceeded error 
- catch & handle that in the agent loop
=> Rewrite messages (with trimmed status) when context limit is exceeded

.github/workflows/deploy_docs.yaml, mkdocs.yml
Social card is working locally when i run `uv run mkdocs serve` however, when i run `mkdocs serve` its insisting it can't find certain dependencies. 
What I'm hoping will fix it is if I put the install dependencies for the social card in our `deploy_docs` workflow. I added a trigger on PR to test out that theory. 
It worked 🥳
=> docs: Test updated deploy_docs workflow

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/components/WelcomeScreen.tsx
Most importantly this warns about ephemeral sessions
=> feat: Add welcome screen

docs/configuration.md, docs/installation.md, docs/plugins/providers.md, docs/quickstart.md
This pull request includes several updates to the documentation for Goose, particularly focusing on configuration, installation, and supported providers. The changes aim to improve clarity, provide more detailed instructions, and update the structure of the documentation.
* **Configuration Documentation:**
- Simplified the explanation of the default profile in `docs/configuration.md` and moved the description of the `default` profile behavior to a separate section. [[1]](diffhunk://#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180L7-R7) [[2]](diffhunk://#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180R20-L30)
- Removed redundant example profiles and consolidated the information on setting up profiles and toolkits.
- Added references to external …
=> docs: Update docs for better installation and provider setups

crates/goose-cli/src/session.rs, download_cli.sh
Process:
- Finds the latest pre-release github release that includes an asset called 'goose'.
- downloads the goose asset
- creates ~/.local/bin if it does not exist
- makes goose executable and moves it to ~/.local/bin as `rgoose` (to avoid conflict with existing goose)
- Checks if ~/.local/bin is on users path and provides guidance to user on how to add it if its not
- Instructs user to run goose configure to set things up
Output when ~/.local/bin is already on path:
```
Flocking to the nearest goose binary location...
Downloading goose...
Sending goose to /Users/jsibbison/.local/bin/rgoose
Setup Goose by running: rgoose configure
Then run Goose using: rgoose session
```
=> Download script for goose cli pre-release

ui/desktop/src/goosed.ts
=> fix: slow GUI with stdio

ui/desktop/helper-scripts/README.md, ui/desktop/helper-scripts/goosey, ui/desktop/src/main.ts
allows you to launch with
`goosey .` (which is really launching the .app)
small one @alexhancock @jsibbison-square - which may help
=> feat: launch GUI from shell

.github/workflows/ci.yaml
=> fix: lib - add libxcb1-dev

ui/desktop/index.html
=> fix: theme default

docs/guidance/tips.md
This pull request fixes formatting issues that made the tips hard to read, and added additional quick tips.
Formatting issues fixed:
- Added bold start to each bullet point.
- Fixed formatting where one bullet point would continue on a second line due to a random break.
Tips added:
> - **Goose can troubleshoot.** If something goes wrong, Goose can help troubleshoot issues by examining logs, analyzing error messages, and suggesting possible resolutions.
> - **Leverage Goose to learn.** Use Goose to learn new technologies or frameworks by asking it to explain things like code snippets, concepts, or for best practices relevant to your project.
> - **Keep Goose updated.** Regularly update Goose to benefit from our latest features, bug fixes, and performance improvements.
=> docs: Quick Tips Fix & Bullet list update

docs/guidance/getting-started.md
=> fix: Update getting-started.md

mkdocs.yml
Adding blog title to nav bar 
---
- https://app.asana.com/0/0/1208938177681179
=> docs: adding blog name to nav bar

docs/plugins/cli.md
=> fix: Update cli.md

crates/goose/src/process_store.rs
You don't notice the change much because the rust tests run in parallel but now this test runs almost 1 sec faster (and all the tests in the module take about 4.3sec)
=> Reduce sleeps in goose rust tests

.github/workflows/cli-release.yml
trying to reduce noise on main v1.0
=> chore: V1.0 release automation

ui/desktop/src/components/UserMessage.tsx
=> stop bubbles filling screen

crates/goose-server/src/state.rs
don't need to have all the providers in state.rs
=> can just use clone macro

docs/index.md, mkdocs.yml
- more visibility to our social links 
- updated 'broken' discord link
- added social links for discord & GH to the footer 
- changed Discord wording in our `index.md` page from `join us` to `Join Discord` my eyes overlooked it quite a few times when it was `join us`
---
- https://app.asana.com/0/0/1209084217759583
=> docs: adding social links to footer 

ui/desktop/src/main.ts
adding back in - was accidentally removed in the MCP merge+follow on
=> [chore] need this for packaging goose with provider config

crates/goose-cli/src/commands/mcp.rs, crates/goose-cli/src/commands/session.rs, crates/goose-mcp/src/developer2/lang.rs, crates/goose-mcp/src/developer2/mod.rs, crates/goose-mcp/src/lib.rs, crates/goose/src/agents/mod.rs, crates/goose/src/agents/reference.rs, crates/goose/src/message.rs, crates/goose/src/providers/openai_utils.rs, crates/mcp-core/src/content.rs
you can run this all with
```
GOOSE_SYSTEM=developer2 cargo run -p goose-cli session --agent reference
```
we will do better system handling shortly for the CLI
=> feat: Implement a simplified reference agent and dev toolkit

crates/goose-cli/src/commands/session.rs, crates/goose-server/src/commands/mcp.rs, crates/goose/src/agents/factory.rs, ui/desktop/src/ChatWindow.tsx
This has been performing more reliably
=> feat: Make the reference agent the default

crates/goose/src/agents/capabilities.rs, crates/goose/src/agents/default.rs, crates/goose/src/prompts/system.md, crates/mcp-client/src/client.rs
try starting the agent without a system
```
cargo run --bin goosed -- agent
```
and then running:
```
❯ curl --request POST \
--url http://localhost:3000/ask \
--header 'Content-Type: application/json' \
--header 'X-Secret-Key: test' \
--data '{
"prompt": "hi there"
}'
```
=> fix: goose failure on first msg without adding system

crates/goose-mcp/src/developer/mod.rs, crates/goose-mcp/src/developer2/mod.rs
Also fixed a bug in list windows original implementation
=> feat: support screenshots in developer2

crates/goose-server/src/routes/reply.rs
https://sdk.vercel.ai/docs/ai-sdk-ui/stream-protocol#error-part
=> fix: error formatting for vercel data format

crates/goose/src/providers.rs, crates/goose/src/providers/anthropic.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/errors.rs, crates/goose/src/providers/google.rs, crates/goose/src/providers/groq.rs, crates/goose/src/providers/ollama.rs, crates/goose/src/providers/openai.rs, crates/goose/src/providers/openai_utils.rs, crates/goose/src/providers/openrouter.rs, crates/goose/src/providers/utils.rs
https://sq-block.slack.com/archives/C07LZBPEDCJ/p1736925945586169?thread_ts=1736924415.946889&cid=C07LZBPEDCJ
anthropic - invalid key
openai - invalid key
=> feat: map non-ok responses from provider to human readable error msgs

ui/desktop/src/main.ts
=> nit: small change to give a choice

download_cli.sh
This will use the new cross platform builds
=> feat: update the cli to be cross platform

.ruff.toml, docs/configuration.md, docs/plugins/providers.md, packages/exchange/src/exchange/providers/bedrock.py, packages/exchange/tests/test_summarizer.py, src/goose/cli/prompt/lexer.py, src/goose/synopsis/toolkit.py, src/goose/toolkit/lint.py, tests/toolkit/test_utils.py
A user ran into an issue when using `developer` toolkit with Anthropic, once changed to `synopsis` toolkit & moderator their issue was resolved. To avoid this issue in the future I'm updating the docs to provide more info on `synopsis` and a tip for Anthropic users. 
Another issue, is that Google's Gemini works best with `developer` toolkit and `truncate` moderator. I'm updating the guide to highlight this as well. 
- added `synopsis` definition to `configurations.md` guide 
- added more configuration info surrounding `synopsis` to `providers.md` guide to avoid others running into this issue in the future
- added a note highlighting that gemini works best with `developer` toolkit
---
- …
=> docs: updating guides to provide more clarity around moderator

ui/desktop/src/main.ts
=> extension popup from menu

download_cli.sh
This takes advantage of the stable release we are using via gh actions
=> feat: simplify download script

documentation/docusaurus.config.ts
- changed title to Codename Goose
- added links for twitter and linkedin
- added company name to the footer
=> docs: Added new social links

ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/settings/models/ModelRadioList.tsx, ui/desktop/src/components/settings/models/RecentModels.tsx, ui/desktop/src/components/settings/models/toasts.tsx
Adds little model menu selector menu in bottom right corner 
currently only shown in development
=> feat: Add mini model menu

ui/desktop/src/components/settings/models/MoreModels.tsx
=> bugfix:fix moremodels width

ui/desktop/src/ChatWindow.tsx, ui/desktop/src/components/MoreMenu.tsx, ui/desktop/src/components/chat_window/ChatRoutes.tsx, ui/desktop/src/components/settings/providers/ConfigureProviders.tsx, ui/desktop/src/components/settings/providers/Provider.tsx, ui/desktop/src/components/settings/providers/ProviderGrid.tsx, ui/desktop/src/components/ui/Tooltip.tsx, ui/desktop/src/components/welcome_screen/WelcomeModal.tsx, ui/desktop/src/components/welcome_screen/WelcomeScreen.tsx
https://github.com/user-attachments/assets/74614945-d52b-4e11-af8b-eeff893ef955
=> feat: welcome page

ACCEPTABLE_USAGE.md
---
- https://app.asana.com/0/0/1209217675455672
=> chore: AUP

ui/desktop/src/components/settings/Settings.tsx, ui/desktop/src/components/settings/extensions/ConfigureExtensionModal.tsx
=> add extension removal capability

crates/goose-cli/src/prompt/renderer.rs
tested with a mysql mcp server:
Fairly verbose, so click to open, main differences are the error messages & the output of the sql query not being printed for this specific example:
<details>
I'll show you the schema of the 'user_clicks' table using the DESCRIBE command.
─── execute_sql | mysql_mcp_server ──────────────────────────
query: DESCRIBE analytics.user_clicks;
Error executing query: Unread result found
I apologize for the error. Let me try using SHOW CREATE TABLE instead, which should give us the complete schema:
─── execute_sql | mysql_mcp_server ──────────────────────────
query: SHOW CREATE TABLE analytics.user_clicks;
Error executing query: Unread result found
I apologize for the continued errors. Let me try one more approach using information_schema:
─── execute_sql | …
=> [CLI] do not render missing priority 

crates/goose-cli/src/commands/configure.rs, crates/goose/src/config/base.rs, download_cli.sh
This should be more clear about possible failure modes including path and invalid credentials
=> fix: improve installer handling

ui/desktop/src/components/welcome_screen/WelcomeScreen.tsx
applied drag ability to entire screen in #713 so provider cards were unresponsive
=> fix: fix welcome window

crates/goose-cli/src/commands/configure.rs, crates/goose-cli/src/commands/session.rs, crates/goose-server/src/routes/extension.rs, crates/goose/examples/agent.rs, crates/goose/src/agents/capabilities.rs, crates/goose/src/agents/extension.rs, crates/goose/src/config/extensions.rs
as per 
https://sq-block.slack.com/archives/C07LZBPEDCJ/p1737663130608459
=> maintain extension name consistent

documentation/docs/guides/handling-llm-rate-limits-with-goose.md
This pull request includes a change to the `documentation/docs/guides/handling-llm-rate-limits-with-goose.md` file. The change adds two imports to support tab functionality in the documentation.
* [`documentation/docs/guides/handling-llm-rate-limits-with-goose.md`](diffhunk://#diff-f2f9e26be6b67d9f24f7c261a2668df19ccd89703269aa3aad2c4a91f868f3d2R6-R8): Added imports for `Tabs` and `TabItem` from `@theme` to enable tab functionality in the documentation.
=> quickfix: Building docs site

.github/workflows/deploy-docs-and-extensions.yml, documentation/docusaurus.config.ts, documentation/package-lock.json, documentation/package.json
This pull request includes several changes to integrate Inkeep services into the documentation build process and configuration. The most important changes involve updating environment variables, modifying the Docusaurus configuration, and adding necessary dependencies.
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R23-R26): Added environment variables for Inkeep API key, integration ID, and organization ID to the documentation build step.
* [`documentation/docusaurus.config.ts`](diffhunk://#diff-18363c0e89010c49d5f105f49fdc20200f1de368a3ec607c830d47b4a6b7d06cR7-R12): Loaded environment variables using `dotenv` and added Inkeep-specific themes and configuration settings, including API key, integration …
=> Add search to docs

extensions-site/app/mcp-servers.ts
=> fix: use fetch servers from url

.github/workflows/pr-comment-bundle-desktop.yml
https://github.com/peter-evans/create-or-update-comment?tab=readme-ov-file#add-a-comment-to-an-issue-or-pull-request
=> fix: workflow commenting on PR

documentation/src/css/custom.css
Improve accessibility and consistency in link styling
=> docs: adding link decoration

ui/desktop/src/components/settings/Settings.tsx, ui/desktop/src/extensions.ts
Clearer toast messages for extension enable/disable/remove
=> feat: Better messages for extension enable/disable/remove

ui/desktop/src/main.ts
Slightly cleaner not to have this in the file menu as it wasn't meant to be end-user facing
=> chore: Make debug MCP install keyboard shortcut only

.github/workflows/pr-comment-bundle-desktop.yml
allow generation of preview app without first getting PR approved.
=> nit: Update pr-comment-bundle-desktop.yml

documentation/docs/getting-started/providers.md
put providers in a table to simplify the guide
=> docs: streamlined providers into table

ui/desktop/src/components/ToolCallArguments.tsx
=> fix: dark mode colors for long commands

ui/desktop/src/components/settings/Settings.tsx, ui/desktop/src/components/settings/extensions/ConfigureBuiltInExtensionModal.tsx, ui/desktop/src/components/settings/extensions/ExtensionItem.tsx, ui/desktop/src/extensions.tsx
Created a special modal for built-ins that allows for configuration only
(fyi in the video below for some reason I see non-developer and also computer configurer -- I think something got messed up in my local storage but not 100% sure. Purpose of video is to show new modal)
https://github.com/user-attachments/assets/61c6475d-b6f0-4cf4-9f5b-b4e0c2aa86c8
=> fix:dont allow builtin deletion

documentation/docs/getting-started/providers.md, documentation/docs/troubleshooting.md
added instructions on downloading Ollama and running models locally
=> docs: more info on configuring Ollama

ui/desktop/src/components/settings/api_keys/utils.tsx, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx, ui/desktop/src/components/settings/providers/BaseProviderGrid.tsx, ui/desktop/src/components/settings/providers/ConfigureProvidersGrid.tsx, ui/desktop/src/components/settings/providers/utils.tsx, ui/desktop/src/main.ts, ui/desktop/src/preload.js
Checks if user has Ollama installed under `Applications/Ollama.app` and if not, the plus button will take them to the download page. 
The only way for the user to remove the ollama provider from goose at this point is to delete the Ollama app or move it from Applications folder
=> feat: ollama check

documentation/docusaurus.config.ts
new yt, who dis
---
- https://app.asana.com/0/0/1209244627242076
=> docs: change youtube link

documentation/docs/getting-started/installation.md, documentation/docs/guides/managing-goose-sessions.md, documentation/docs/quickstart.md, documentation/src/components/RateLimits.js, documentation/src/components/SupportedEnvironments.js
This PR addresses documentation feedback by improving clarity, enhancing usability, and reducing duplication with reusable components. Key updates include:
1. **Reusable Components:**
- Added `SupportedEnvironments.js`:
- Displays information about supported platforms and architectures.
- Added `RateLimits.js`:
- Provides guidance on billing, free-tier options, and rate limit management.
2. **Documentation Updates:**
- Replaced inline admonitions with reusable components (`SupportedEnvironments` and `RateLimits`) in:
- `installation.md`
- `managing-goose-sessions.md`
- `quickstart.md`
- Updated session management instructions:
- Added guidance for starting new sessions in the Goose UI.
- Added a tip recommending new sessions for distinct use cases to maintain organized workflows.
---
- To …
=> Address Documentation Feedback and Add Reusable Components

extensions-site/app/components/header.tsx
cc @EbonyLouis @angiejones @baxen @alexhancock
=> hotfix: add a link to download stable for extensions site

ui/desktop/src/components/GooseResponseForm.tsx, ui/desktop/src/components/welcome_screen/WelcomeScreen.tsx, ui/desktop/src/styles/main.css, ui/desktop/tailwind.config.ts
Realized the tailwind config for the fontFamily slipped. Likely in between my changes and rebases. 🙏🏽
=> styles: fixed cash sans

.github/workflows/deploy-docs-and-extensions.yml, README.md, documentation/docs/guides/tips.md, documentation/docusaurus.config.ts, documentation/package-lock.json, documentation/package.json, documentation/static/img/bot.svg, documentation/yarn.lock, ui/desktop/src/components/welcome_screen/WelcomeScreen.tsx
This pull request includes several changes to update the documentation and deployment paths for the Goose project. The most important changes involve updating URLs and paths to remove the version number from the documentation URLs, adding client-side redirects, and modifying the deployment configuration.
Moves documentation to the base, but keeps the extensions url the same. With redirects in place for other docs links.
Documentation and URL updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L21-R21): Updated the documentation and installation links to remove the version number from the URLs.
* [`documentation/docs/guides/tips.md`](diffhunk://#diff-74c43a5639cd1e6aed46d7b03d4cc7c5b30c071fc8ec4ed69d0f3ef788d33a9cL49-R49): Updated the …
=> Publish launch

.github/workflows/deploy-docs-and-extensions.yml
This pull request includes updates to the GitHub Actions workflow for deploying documentation and extensions. The most important changes include the addition of a trigger for pull requests that affect the documentation and a minor cleanup of environment variable comments.
Workflow updates:
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R8-R11): Added a trigger for pull requests that modify files under the `documentation` directory.
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3L24-R28): Removed an unnecessary comment from the environment variable section in the `deploy` job.
=> Update docs workflow

documentation/docs/getting-started/installation.md, documentation/docs/quickstart.md, download_cli.sh
This improves compatibility across setups
=> fix: install with bash

ui/desktop/src/components/GooseResponseForm.tsx, ui/desktop/src/components/ToolCallArguments.tsx
Consolidate on one markdown rendering component with our desired styling applied across the board
=> chore: Consolidate on one markdown rendering component

documentation/docs/guides/managing-goose-sessions.md
Unable to list sessions or resume specific sessions. Removed docs on that.
=> docs: removing docs on listing sessions

documentation/docs/troubleshooting.md
add more explicit instructions for troubleshooting keyring issues, and how to ignore/get past them
see https://github.com/block/goose/issues/879
=> docs: add section for troubleshooting keyring issues

crates/goose-cli/src/commands/configure.rs, crates/goose/src/providers/anthropic.rs, crates/goose/src/providers/databricks.rs, crates/goose/src/providers/google.rs, crates/goose/src/providers/utils.rs
Show error message during configuration.
Test:
=> fix: improve configure process with error message

ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
comment from: https://github.com/block/goose/pull/957
=> chore: remove gpt-3.5-turbo UI suggestion, as it is deprecated

ui/desktop/src/components/MoreMenu.tsx, ui/desktop/src/components/settings/api_keys/utils.tsx, ui/desktop/src/components/settings/providers/BaseProviderGrid.tsx, ui/desktop/src/components/settings/providers/ConfigureProvidersGrid.tsx, ui/desktop/src/components/settings/providers/utils.tsx, ui/desktop/src/utils/deleteAllKeys.tsx
https://github.com/user-attachments/assets/6e83b56b-9d16-4045-8178-608955dfc1e7
=> fix: clean tooltips, allow for clearing keychain keys

.intersect/intersect-config.yaml
This PR enables security checks to run on PRs alongside the base branch scans that occur.
=> [FEAT] Introduce PR level security scans

documentation/docs/configuration/_category_.json, documentation/docs/getting-started/_category_.json, documentation/docs/guides/_category_.json, documentation/docs/quickstart.md, documentation/docs/tutorials/_category_.json, documentation/docs/tutorials/custom-extensions.md, documentation/docs/tutorials/github-mcp.md, documentation/docusaurus.config.ts
- Made Tutorials section in Docs
- Added tutorial for adding GitHub extension
- Moved 'Building Custom Extensions' from Guides to Tutorials
=> docs: github tutorial

.github/workflows/canary.yml
=> ci: checkout code to read Cargo.toml for version

documentation/docs/tutorials/_template_.md, documentation/docs/tutorials/github-mcp.md
Created Plug & Play tutorial template for future tutorials
=> docs: added tutorial template

documentation/docs/getting-started/using-extensions.md, documentation/docs/goose-architecture/goose-architecture.md, documentation/docs/guides/managing-goose-sessions.md, documentation/docs/guides/using-goosehints.md, documentation/docs/troubleshooting.md, documentation/docs/tutorials/github-mcp.md
This pull request includes several updates to the Goose documentation, focusing on improving the clarity and usability of the instructions for using extensions and managing sessions. The most important changes include adding new sections and tips for using MCP servers, updating the structure of the Goose architecture documentation, and refining the session management guide.
* [`documentation/docs/getting-started/using-extensions.md`](diffhunk://#diff-51503ee9089502f4a3c4577a1ee0d5f4f09b616d6226c8eb076d358d5950c1caL89-R92): Added new sections and tips for using MCP servers as Goose extensions, including examples and a link to the MCP Server Directory. [[1]](diffhunk://#diff-51503ee9089502f4a3c4577a1ee0d5f4f09b616d6226c8eb076d358d5950c1caL89-R92) …
=> docs: cleanup

crates/goose-mcp/src/computercontroller/mod.rs
=> fix: conditional safari prompting on macos only for CC

crates/goose/src/providers/formats/openai.rs
Fixes #1005 
redirects user to use o1 or o3 models if using o1-mini
=> fix: support o3 models

documentation/docs/getting-started/providers.md
This PR updates the **`providers.md`** documentation to improve clarity and accuracy in configuring providers within Goose. The changes ensure that users have a more structured guide for adding or changing their LLM provider and models.  
- **Expanded and clarified provider setup instructions** for Goose Desktop.  
- **Updated step-by-step instructions** for:  
- Adding an LLM provider.  
- Configuring an API key.  
- Selecting and adding a new model.  
---
- https://app.asana.com/0/0/1209299625228228
=> update provider.md instructions

.github/workflows/pr-website-preview.yml, documentation/docusaurus.config.ts
This adds previews for the docs site to PRs that change things in the `documentation/` folder using [rossjrw/pr-preview-action](https://github.com/rossjrw/pr-preview-action)
=> docs site: add PR previews

crates/mcp-core/src/protocol.rs
Update notification detection to comply with JSON-RPC 2.0 specification by checking
for absence of request ID rather than "notifications/" prefix. The previous
implementation incorrectly relied on prefix matching, which prevented custom
notification implementations and was incompatible with pre-release MCP versions.
This change brings the codebase in line with the JSON-RPC 2.0 specification for
proper notification handling.
=> fix: improve JSON-RPC notification handling to match specification

documentation/docs/tutorials/developer-mcp.md
This PR adds a **Developer Extension tutorial** to the documentation, covering how to enable and use the **Developer MCP Server** in Goose. The tutorial walks through configuring the extension and provides a real-world example of automating a **JavaScript developer environment setup** with Goose.
**Changes:**  
✅ Added **developer-mcp.md** under `documentation/docs/tutorials/`  
✅ Explained **how to enable the Developer extension** via CLI and UI  
✅ Included a **step-by-step tutorial** showcasing Goose setting up a JavaScript project with:  
- Express, Mongoose, Nodemon, and Dotenv  
- Fetching **latest package versions** dynamically  
- Generating a **README** with dependencies  
- Initializing **Git and project structure**  
✅ Added example **Goose prompt and output**  
**Why This is …
=> docs: developer extension tutorial

crates/goose/src/providers/google.rs, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
Model list: https://ai.google.dev/gemini-api/docs/models/gemini
UI changes:
=> feat: update gemini models

documentation/docs/getting-started/using-extensions.md, documentation/docs/guides/goose-cli-commands.md, documentation/docs/troubleshooting.md, documentation/docs/tutorials/figma-mcp.md, documentation/docs/tutorials/github-mcp.md
=> docs: package runner info

documentation/docs/tutorials/fetch-mcp.md
=> docs: fetch video

CONTRIBUTING.md
Instructions on keepings PRs up to date
=> chore: update contributing doc for forks

crates/goose-cli/src/commands/configure.rs
fixes: https://github.com/block/goose/issues/997
=> fix: write to config yaml if provider test succeeds

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/managing-goose-sessions.md
Added directions for resuming sessions via the CLI. 
Let me know your thoughts 👀
=> docs: Adding clarity about resuming sessions to docs

crates/goose-cli/src/commands/configure.rs, crates/goose-cli/src/commands/mcp.rs, crates/goose-mcp/src/developer/mod.rs, crates/goose-mcp/src/lib.rs, crates/goose-mcp/src/tutorial/mod.rs, crates/goose-mcp/src/tutorial/tutorials/build-mcp-extension.md, crates/goose-mcp/src/tutorial/tutorials/first-game.md, crates/goose-server/src/commands/mcp.rs
This is a quick first pass at the idea, curious to hear feedback! The tutorials were written by goose and i'm confident could use some improvements
=> feat: tutorial extension

documentation/docs/tutorials/memory-mcp.md
This pull request updates the Memory MCP tutorial with an improved example that highlights how to teach Goose personalized knowledge and utilize stored information in practical development tasks. The new content makes it clear how Goose can recall stored preferences, standards, and configurations to assist users in building compliant and consistent projects.
- **Updated tutorial introduction**: Emphasizes how the Memory extension allows users to teach Goose personalized key information.
- **Added "Why Use Memory?" section**: Demonstrates the value of Goose's dynamic recall and proactive assistance.
- **Expanded Example Usage**:  
- Replaced the previous example with a more practical and detailed API development scenario.
- Showcases how to store commands, code patterns, and project …
=> docs: Update Memory Tutorial Example

documentation/docs/troubleshooting.md
=> docs: troubleshooting - last resort tip

run_cross_local.md
Hi,
"which" seemed to be missing. I added it: see commit diff for details. 
Didier
=> Update run_cross_local.md: adding 1 missing word

documentation/docs/tutorials/figma-mcp.md
Embedded the Figma short into the Figma tutorial
=> docs: embed figma short video

documentation/docs/guides/handling-llm-rate-limits-with-goose.md, documentation/docs/troubleshooting.md
This pull request includes updates to the documentation for handling rate limits and troubleshooting with Goose. The changes enhance the clarity and completeness of the instructions.
* [`documentation/docs/guides/handling-llm-rate-limits-with-goose.md`](diffhunk://#diff-f2f9e26be6b67d9f24f7c261a2668df19ccd89703269aa3aad2c4a91f868f3d2R15-R21): Added a tip on how to find a log of token usage with Goose by running a specific command.
* [`documentation/docs/troubleshooting.md`](diffhunk://#diff-8c51971673bb409bf261d7a5b924b79c9d4a7b3da703ae5b8927c3786866f8c5L99-L101): Updated the section title to "Uninstall Goose or Remove Cached Data" and provided additional instructions on uninstalling Goose and clearing cached data, including the removal of the app itself on macOS. …
=> Docs: token and uninstall update 

documentation/docs/guides/file-management.md, documentation/docs/guides/handling-llm-rate-limits-with-goose.md, documentation/docs/guides/logs.md
New guide that covers the various Goose logs. Please review for accuracy.
=> docs: logging guide

documentation/docs/getting-started/using-extensions.md
documenting new feature that allows users to remove an extension via CLI
=> docs: remove extension from CLI

crates/goose/src/providers/utils.rs
fix #1292 
Before:
```
│
│  Configure Providers 
│
│  OpenRouter 
│
●  OPENROUTER_API_KEY is already configured
│  
│  No 
│
◇  Enter a model from that provider:
│  mistralai/mistral-small-24b-instruct-2501
│
◇  Request failed: Request failed with status: 404 Not Found
│
└  Failed to configure provider: init chat completion request with tool did not succeed.
```
after:
```
│
│  Configure Providers 
│
│  OpenRouter 
│
●  OPENROUTER_API_KEY is already configured
│  
│  No 
│
◇  Enter a model from that provider:
│ …
```
=> fix:expose unsupported tool use error

documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/updating-goose.md
This pull request includes a new guide to help users update their Goose installation. The guide provides detailed instructions for both the command-line interface (CLI) and the desktop application.
* [`documentation/docs/guides/updating-goose.md`](diffhunk://#diff-73634242804f8cf84d6a17bd17773e3dbe74d393409f94c6e7a64b83d7842a9bR1-R35): Added a new guide that explains how to update Goose using the CLI and the desktop application, including steps to download and install the latest version.
=> docs: updating goose

crates/goose-mcp/src/google_drive/mod.rs
- update JSON schema to include "corpora" (must be "user", "drive", or "allDrives") and "pageSize" (number between 0 and 100, default 10), add validation
=> feat(google_drive): add corpora and pageSize parameter to search tool

ui/desktop/src/components/settings/ProviderSetupModal.tsx, ui/desktop/src/components/settings/api_keys/utils.tsx, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
=> feat: add default value for openai host

CONTRIBUTING.md, README.md
Added in different ways community members can contribute that is comprehensive and relevant to our team.
Ways to contribute added to `CONTRIBUTING.MD`
- **Stars on GitHub**
- **Ask Questions**
- **Give Feedback**
- **Participate in Community Events**
- **Improve Documentation**
- **Help Other Members**
- **Showcase Your Work**
- **Give Shoutouts**
- **Spread the Word**
Sections added to `README.MD`
- **Quick Links** (placed existing blurb under heading)
- **Goose Around with Us** social links
---
- https://app.asana.com/0/0/1209309932537991
=> chore: Update Contributing doc with actions & readme with quick links

CONTRIBUTING.md, README.md
updates to the `CONTRIBUTING.md` and `README.md` files to improve clarity and provide more comprehensive information on contributing and the project's capabilities.
* Updated the project description to highlight what goose is
* Expanded the description to detail goose's capabilities
* Updated the "Quick Links" and "Goose Around with Us" sections to improve navigation and engagement with the community.
* Simplified the introduction and emphasized the welcoming of pull requests for general contributions.
* Added a new section, "Other Ways to Contribute," detailing various ways community members can get involved
=> updates to readme and contributing guides

documentation/docs/tutorials/knowledge-graph-mcp.md
added video to Knowledge Graph Memory tutorial to provide additional visual guidance.
=> docs: video for knowledge graph memory tutorial

documentation/docs/tutorials/tutorial-extension.md
This pull request adds a new tutorial on using Goose's built-in Tutorial extension. 
Documentation improvements:
* [`documentation/docs/tutorials/tutorial-extension.md`](diffhunk://#diff-e46a8b96391d8334a76edac6d2a3a54a200fff8ea87b5341e125aaeccaa85163R1-R154): Added a comprehensive guide on how to use Goose's built-in Tutorial extension, including configuration steps, available tutorials, and best practices for using the extension.
[Part generated with Goose :D )
---
- https://app.asana.com/0/0/1209497698647532
=> docs: Tutorial extension

documentation/docs/tutorials/puppeteer-mcp.md
This PR adds a tutorial on integrating the **Puppeteer MCP Server** as a Goose extension. The tutorial provides step-by-step instructions for configuring Puppeteer in both the **Goose CLI** and **Goose Desktop**, as well as an example use case for performing an **automated accessibility audit**.
-  ✅ Created a new documentation file: `documentation/docs/tutorials/puppeteer-mcp.md`  
-  ✅ Added instructions for:  
-  ✅ Installing the Puppeteer MCP Server  
-  ✅ Configuring it as a **Command-line Extension** in Goose  
-  ✅ Setting it up in **Goose Desktop**  
-  ✅ Included a **detailed example** demonstrating how to use Puppeteer for an **accessibility audit**  
- ✅ Provided **Goose prompt and output examples**  
- ✅ Added **Further Automation section** with **GitHub automation steps** for …
=> docs: Add Puppeteer Extension Tutorial

documentation/docs/guides/goose-permissions.md
This PR introduces a new **Goose Permissions Guide**, which provides users with a clear understanding of how to configure Goose's automation settings. The guide explains **permission modes**, their use cases, and step-by-step instructions for adjusting settings via **CLI and Goose Desktop**.
✅ **Added:** `documentation/docs/guides/goose-permissions.md`
✅ A table outlining the three modes of Goose permissions:
- **Auto Mode** → Full automation, no approval required.
- **Approve Mode** → Requires confirmation before modifying files or using extensions.
- **Chat Mode** → No file modifications or extensions, chat-only mode.
- ✅ **CLI:** Step-by-step guide on running `goose configure` to set permissions.
- ✅ **No Desktop instructions yet** → A **note has been added** to clarify that **Goose …
=> docs: Add Managing Goose Permissions Guide

ui/desktop/src/built-in-extensions.json, ui/desktop/src/extensions.ts, ui/desktop/src/json.d.ts
This will make it easier to customize these from builds etc
=> chore: load default built-in extensions from a json file instead of ts

ui/desktop/.goosehints, ui/desktop/src/App.tsx, ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/ChatView.tsx, ui/desktop/src/components/GoosehintsModal.tsx, ui/desktop/src/components/MoreMenu.tsx
* Moves `Configure Goosehints` functionality from the BottomMenu to the MoreMenu
* Improves the UI in darkmode
**Before**
**After**
=> feat: move configure goosehints to the MoreMenu

ui/desktop/src/main.ts
This is causing issues colliding with other common shortcuts on dvorak keyboards - see https://github.com/block/goose/issues/1433
=> fix: remove MCP extension install debug shortcut - fixes #1433

ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/components/ToolCallConfirmation.tsx, ui/desktop/src/types/message.ts
https://github.com/user-attachments/assets/e41de2c8-3c69-4d4a-8aa3-f7cba11daca6
=> feat: improve the allow tool ui

ui/desktop/src/components/MoreMenu.tsx
Fairly subjective, so open to comments :)
=> chore: re-order MoreMenu items

Cargo.lock, ui/desktop/openapi.json, ui/desktop/package-lock.json, ui/desktop/package.json, ui/desktop/src/components/MarkdownContent.tsx
fixes: https://github.com/block/goose/issues/1494
github flavoured markdown is popular, so this supports it (and embedded markup - which is also popular)
=> fix: [gui] table formatting

documentation/docs/tutorials/google-drive-mcp.md
=> docs: add tip for gdrive environment variables

crates/goose/src/agents/truncate.rs
I played around with this a bit, the only thing I don't like about the experience is that goose **_apologizes_** too much for not being able to run the tool - even if we tell goose explicitly to not apologize
=> feat: adjust chat tool response

documentation/docs/guides/using-goosehints.md
Added instructions for adding .goosehints in Desktop
=> docs: goosehints in desktop

ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/settings/SettingsView.tsx, ui/desktop/src/components/settings/models/AddModelInline.tsx, ui/desktop/src/components/settings/models/GooseModels.tsx, ui/desktop/src/components/settings/models/ModelContext.tsx, ui/desktop/src/components/settings/models/ModelRadioList.tsx, ui/desktop/src/components/settings/models/ProviderButtons.tsx, ui/desktop/src/components/settings/models/RecentModels.tsx, ui/desktop/src/components/settings/models/Search.tsx, ui/desktop/src/components/settings/models/goose_models.tsx, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx, ui/desktop/src/components/settings/models/toasts.tsx, ui/desktop/src/components/settings/models/utils.tsx
Makes it easier to configure / maintain the models section
=> refactor models component

documentation/blog/2025-03-10-goose-calls-vyop/index.md
fixed the spelling of Ebony's last name
=> docs: typo fix

ui/desktop/src/components/BottomMenu.tsx, ui/desktop/src/components/settings/models/ModelRadioList.tsx
=> chore: update types and imports

crates/goose-cli/src/log_usage.rs
=> change to make build work on windows, macos, linux

crates/goose-server/src/routes/config_management.rs, crates/goose-server/src/routes/mod.rs, crates/goose-server/src/routes/utils.rs, crates/goose/src/config/base.rs, ui/desktop/src/components/settings_v2/providers/ProviderGrid.tsx, ui/desktop/src/components/settings_v2/providers/ProviderSettingsPage.tsx, ui/desktop/src/components/settings_v2/providers/modal/ProviderConfiguationModal.tsx, ui/desktop/src/components/settings_v2/providers/modal/ProviderModalProvider.tsx, ui/desktop/src/components/settings_v2/providers/modal/subcomponents/forms/DefaultProviderSetupForm.tsx, ui/desktop/src/components/settings_v2/providers/modal/subcomponents/handlers/DefaultSubmitHandler.tsx
There was a lag in configuring a new provider getting the green checkmark
before:
1. submit the configuration for the provider
2. leave the settings page
3. come back and you will see the green check
now:
1. submit the configuration for the provider
2. the green check appears
also fixed a bug where providers with a combo of required keys with no defaults + required keys with defaults (like openai) weren't being registered as configured)
=> ui: auto update card upon config

documentation/docs/guides/experimental-features.md
This pull request introduces documentation for enabling and using experimental features in Goose. The new guide provides detailed steps for configuring these features and highlights the `GOOSE_SMART_APPROVE` experimental feature.
[`documentation/docs/guides/experimental-features.md`](diffhunk://#diff-32392a64d53c7833cd7372db51195df00b81aa3644d0695ceb68037176c574feR1-R84): Added a comprehensive guide on experimental features, including how to enable them, a description of available features, and instructions for providing feedback.
---
- https://app.asana.com/0/0/1209564071738936
=> docs: Add experimental features

crates/goose-bench/src/eval_suites/core/create_file.rs, crates/goose-bench/src/eval_suites/core/image.rs, crates/goose-bench/src/eval_suites/core/list_files.rs, crates/goose-bench/src/eval_suites/core/save_fact.rs, crates/goose-bench/src/eval_suites/core/script.rs, crates/goose-bench/src/eval_suites/core/search_replace.rs, crates/goose-bench/src/eval_suites/core/web_scrape.rs
This PR adds default metrics to the the core eval suite
=> feat: add default metrics for core evals

extensions-site/public/servers.json
lots asking for PDF reader - this one has been in use by quite a few
=> feat: add pdf reader

ui/desktop/src/main.ts
fixes #1460 
Creates a new window if there is no existing window and the top bar 'Show Window' is clicked
=> fix: show window bugfix

crates/goose/src/providers/google.rs
Add retry for gemini model, gemini is free and always has the quota issue
=> feat: add retry for google

crates/goose-cli/src/session/input.rs
=> fix: cli empty line

Justfile
All I want to do is help... just let me know what you want or what is needed...
I typically run 
just win-tot-dbg -all
to build everything for debug including desktop
or
just win-tot-rls -all
to build everything for release including desktop
-all means test, examples, bench,,,,
I believe I can separate my changes into a sub Justfile if that makes things "cleaner" I used win- as a prefix, but I tried to keep the recipes I added generic to run on any system I hope. I did not include yarn in my builds, but I easily can... Adjust as needed or as you like.
Basically do what makes sense for the project... no conerns here
s := if os() == "windows" { "\\" } else { "/" }
os:
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"] win-bld M F:
win-bld-dbg:
win-bld-dbg-all:
win-bld-rls: …
=> (fixed the linux copy command in my recipes)

crates/goose/src/providers/azure.rs, ui/desktop/src/components/settings/api_keys/utils.tsx, ui/desktop/src/components/settings/models/hardcoded_stuff.tsx, ui/desktop/src/components/settings_v2/providers/ProviderRegistry.tsx
Test: 
```
◇  Provider Azure OpenAI requires AZURE_OPENAI_DEPLOYMENT_NAME, please enter a value
│  test
│
◆  Provider Azure OpenAI requires AZURE_OPENAI_API_VERSION, please enter a value
│  2024-10-21 (default)
└ 
```
=> feat: export azure api version

ui/desktop/src/components/Modal.tsx, ui/desktop/src/components/settings_v2/extensions/modal/EnvVarsSection.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx
Hooks the `EnvVarSection` component up to editing the env vars properly
=> feat: Hook env vars editor up when adding/editing extensions

ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx
Changes some text in Change Models Modal 
* add model -> switch model
Also does form validation -> we were able to submit without selecting a model which caused errors when trying to chat
=> ui: change add model modal to 'switch model' and add form validation

crates/goose/src/providers/bedrock.rs
- make loading from secrets/keyring only run if we get values from config
- don't fail if we can't get keyring (for CLI) fixes #1852 
- load AWS environment variables from both config and secrets
- change default AWS_PROFILE from "us-west-2" to "default"
- add credential validation to fail early if credentials are invalid
example error from invalid creds:
```bash
> goose session
thread 'main' panicked at .../crates/goose-cli/src/session/builder.rs:32:64:
Failed to create provider: the credential provider was not enabled
Caused by:
no providers in chain provided credentials
```
=> fix: improve AWS credential handling in Bedrock provider, make keyring optional

crates/goose-mcp/src/computercontroller/mod.rs
this fixes: https://github.com/block/goose/issues/1715 
there are much better options in MCP now, this gets in the way.
=> fix: better search options now, this crowds prompt

ui/desktop/src/main.ts
fix for mini agents that weren't opening when packaged as it was looking for path not hostname. Now consistent with extensions and sessions. 
fixes: https://github.com/block/goose/issues/1896
=> fix: use hostname when packaged app

ui/desktop/src/components/Input.tsx
=> feat: Enable Option + Enter to insert a new line

ui/desktop/src/components/ChatView.tsx, ui/desktop/src/components/conversation/SearchBar.tsx, ui/desktop/src/components/conversation/SearchView.tsx, ui/desktop/src/components/icons/ArrowDown.tsx, ui/desktop/src/components/icons/ArrowUp.tsx, ui/desktop/src/components/icons/index.tsx, ui/desktop/src/components/ui/scroll-area.tsx, ui/desktop/src/styles/main.css, ui/desktop/src/styles/search.css, ui/desktop/src/utils/searchHighlighter.ts
**Add searchable chat history with the following features:**
- Open/close search with Cmd/Ctrl+F
- Case-sensitive search toggle
- Result navigation with arrow keys
- Smooth animations for search bar
- Visual highlighting of matches
- Current match indicator
**Components:**
- SearchView: Wrapper component that enables search in its children
- SearchBar: Search input with navigation controls
- SearchHighlighter: Utility for text highlighting and match tracking
**Style:**
- Theme-aware highlighting
- Smooth expand/collapse animations
- Consistent UI with existing components
<div style="text-align: center;">
<video src="https://github.com/user-attachments/assets/7e0f153b-b25d-4b17-94dc-a709d58e4b57" width="600" controls>
</div>
=> feat(ui): add search functionality to chat view

ui/desktop/openapi.json, ui/desktop/src/components/BottomMenuModeSelection.tsx, ui/desktop/src/components/settings/basic/ModeSelection.tsx, ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/mode/ConfigureApproveMode.tsx, ui/desktop/src/components/settings_v2/mode/ModeSection.tsx, ui/desktop/src/components/settings_v2/mode/ModeSelectionItem.tsx
Branch says "mode and sessions" but just modes
=> move modes  settings v2

CONTRIBUTING.md
Small fix for a broken tip callout block in `CONTRIBUTING.md`.
=> Fixed tip callout in CONTRIBUTING.md

ui/desktop/src/components/Modal.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx, ui/desktop/src/components/ui/Select.tsx
Fixes issues with the z positioning of provider/model select menus
**Before**
**After**
=> fix: Fix display issues for the provider/model select menus

ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/sessions/SessionSharingSection.tsx
Only change was making the toggle styling match everything else in the settings page.
=> ui: copy over base session sharing settings over to settings v2

ui/desktop/src/components/settings_v2/providers/modal/ProviderConfiguationModal.tsx, ui/desktop/src/components/settings_v2/providers/modal/subcomponents/ProviderSetupActions.tsx
Add check to not allow users to delete provider keys for current provider -> causes fatal error
=> ui: do not delete current provider

ui/desktop/src/components/Modal.tsx, ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx, ui/desktop/src/components/settings_v2/extensions/modal/ExtensionTimeoutField.tsx, ui/desktop/src/components/settings_v2/extensions/utils.ts
=> ui: add timeout field to settings v2 modal

documentation/docs/tutorials/speech-mcp.md
added speech video to tutorial
=> docs: speech mcp video

ui/desktop/src/components/sessions/SessionHistoryView.tsx, ui/desktop/src/components/sessions/SessionListView.tsx, ui/desktop/src/components/sessions/SessionViewComponents.tsx, ui/desktop/src/components/sessions/SharedSessionView.tsx, ui/desktop/src/components/ui/BackButton.tsx
=> feat: styling changes for viewing sessions 

crates/goose/src/agents/truncate.rs
Fix #1971
Emphasize the action after user decline the tool call
=> fix: improve the prompt when user decline the tool call

ui/desktop/openapi.json, ui/desktop/src/components/sessions/SharedSessionView.tsx
without this change, last msg sometimes gets cut off
=> fix: see last msg fully in shared session view

ui/desktop/src/components/ErrorBoundary.tsx
=> feat: better ErrorBoundary UI

ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
changeModel was missing some required params
=> Fix function params 

crates/goose/src/config/base.rs
For systems that don't have keyrings
Fixes: #1724
=> feat: support file based secrets

crates/mcp-core/src/resource.rs, ui/desktop/src/components/sessions/SessionHistoryView.tsx, ui/desktop/src/components/sessions/SessionViewComponents.tsx
=> feat: add tooltips, fix back button inverse color

Cargo.lock, crates/goose-bench/src/eval_suites/core/developer/mod.rs, crates/goose-bench/src/eval_suites/core/developer/simple_repo_clone_test.rs
Enhances the benchmark to work on a project in git. 
clone a known project, add a test to it and run it.
=> chore: add to the benchmark suite core developer a git project scenario

documentation/blog/2025-03-28-vibe-coding-with-goose/index.md
This pull request includes a minor update to the `documentation/blog/2025-03-28-vibe-coding-with-goose/index.md` file. The change updates the URLs of the images used for social media previews to use HTTPS instead of HTTP.
* Updated `og:image` and `twitter:image` URLs to use HTTPS for better security and compatibility.
=> docs:fix metadata image

documentation/docs/getting-started/installation.md
Updated a hint to use an editorially more correct word.
=> Editorial change to replace 'reperform' with 'perform again'

ui/desktop/src/components/more_menu/MoreMenu.tsx
resolves #1142 
menu now includes a theme option with choices - light, dark, system
=> added system theme option

ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
When clicking radio buttons for changing models, the agent needs to be re-initialized with these changes, and that process was blocking the radio button changing from unclicked to clicked, these changes allow for immediate UI updates optimistically
=> ui: radio buttons show click without waiting for agent to reload

ui/desktop/src/main.ts
Small one. Enable `spellcheck`. fixes #2112
=> feat: enable spellcheck

crates/goose-mcp/src/google_drive/mod.rs
also support passing in the full URL to the `read` tool call and use a regex to extract the URI
=> feat: add support for full url extraction for google_drive

documentation/docs/tutorials/repomix-mcp.md
This PR adds a full tutorial for integrating the **Repomix MCP Server** as a Goose extension. The tutorial walks users step-by-step through installing and configuring Repomix, running it as a Goose extension, and automating developer onboarding by analyzing open-source repositories (like Axios) using natural language prompts.
The tutorial includes:
- ✅ TL;DR command block for quick start
- ✅ Goose CLI extension configuration walkthrough
- ✅ Goose Desktop installer link
- ✅ Practical example prompt for onboarding into the Axios repository
- ✅ Full expected Goose output, including:
- Repo architecture analysis
- Suggested improvements
- Auto-generated improved README.md for Axios
- Browser support chart (fixed ✅)
- ✅ Markdown + MDX-friendly formatting for clean display in Docusaurus
- 📝 …
=> Add Repomix Tutorial

crates/goose/src/agents/agent.rs, crates/goose/src/permission/permission_judge.rs, crates/goose/src/prompts/system.md
In agent.ts, we only care about the which tools are approved, which requires confirmation, which are denied, so move goose mode check into permission judge
Test:
```
Goose is running! Enter your instructions, or try asking what goose can do.
( O)> list files in my current dir
I apologize, but I notice that I don't currently have any extensions enabled that would allow me to interact with the file system. Let me search for an available extension that might help with this.
─── search_available_extensions | platform ──────────────────────────
I see there's a "computercontroller" extension that might help us with file system operations. Let me enable that.
─── enable_extension | platform ──────────────────────────
extension_name: computercontroller
◇  Goose would like to install the following …
```
=> fix: fix the mismatched tool result/call when using enable/search extension tools

crates/goose-server/src/routes/extension.rs
=> fix: allowlist with scoping

crates/goose/src/providers/bedrock.rs
=> Added Exponential Backoff to Bedrock provider

Cargo.lock, crates/goose/Cargo.toml, crates/goose/src/model.rs
No hard feelings if you'd prefer this implemented a different way. Also apologies if there is already a way to set temp.
=> feat: add temperature env var

ui/desktop/src/flags.ts
Now `just run-ui` will build with settings v2
=> feat: enable settings V2 

documentation/blog/2025-04-11-finetuning-toolshim/index.md
=> docs: fix meta img url

documentation/docs/tutorials/tavily-mcp.md
=> docs: link typo

crates/goose/src/providers/formats/google.rs
=> fix: add default content for gemini tool response

ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx, ui/desktop/src/components/settings_v2/models/subcomponents/AddModelButton.tsx, ui/desktop/src/components/ui/switch.tsx, ui/desktop/src/styles/main.css, ui/desktop/tailwind.config.ts
=> styles: settings extensions tweaks

documentation/docs/tutorials/selenium-mcp.md
=> docs: selenium tutorial

documentation/docs/tutorials/postgres-mcp.md
Adding a tutorial guide for a PostgreSQL MCP server.
I'll be adding a video at the top of the page before this can be merged.
---
- https://app.asana.com/0/0/1209944172468602
=> docs: PostgreSQL tutorial 

documentation/docs/tutorials/blender-mcp.md
Quick update to the Blender MCP tutorial! 🎨
Added a YouTube Short to give users a fast, visual walkthrough on using the Blender MCP server — from creating 3D scenes to controlling Blender with natural language.
- Embedded the YouTube Short in `blender-mcp.md`
=> Add Blender Short

crates/goose/src/agents/agent.rs, crates/goose/src/agents/reply_parts.rs, ui/desktop/src/components/settings_v2/permission/PermissionModal.tsx
Also reuse the list_tool method in the agent reply
=> fix: filter out the enable extension tool in the ui as it should always ask for permission 

ui/desktop/src/components/RecipeEditor.tsx, ui/desktop/src/components/Splash.tsx
make recipe editor fields required and show error messages when they are empty. fix goose logo on main page
=> recipe-editor

ui/desktop/src/App.tsx, ui/desktop/src/components/ErrorBoundary.tsx
if there is a problem parsing the recipe config, raise an error on the newly created chat window
=> feat: show error on broken recipe url's

ui/desktop/src/App.tsx, ui/desktop/src/components/settings_v2/SettingsView.tsx, ui/desktop/src/components/settings_v2/mode/ModeSection.tsx, ui/desktop/src/components/settings_v2/mode/ModeSelectionItem.tsx, ui/desktop/src/components/settings_v2/permission/PermissionModal.tsx, ui/desktop/src/components/settings_v2/permission/PermissionSetting.tsx
Test: 
https://github.com/user-attachments/assets/c8290d59-c76b-4bf8-a17d-cb4da84c03c0
=> feat: init UI implementation for tool permission control

ui/desktop/package-lock.json, ui/desktop/package.json, ui/desktop/tsconfig.json, ui/desktop/tsconfig.node.json
This fixes `tsc` command not running. Forgot to leave the package in a revert. Also cleaned up stuff we don't need.
=> Added missing electron-types package and cleaned up tsconfig

crates/goose-cli/src/session/mod.rs, crates/goose/src/message.rs, crates/goose/src/permission/permission_judge.rs, crates/goose/src/providers/formats/anthropic.rs, crates/goose/src/providers/formats/bedrock.rs, crates/goose/src/providers/formats/databricks.rs, crates/goose/src/providers/formats/openai.rs, ui/desktop/src/components/ChatView.tsx, ui/desktop/src/components/ExtensionConfirmation.tsx, ui/desktop/src/components/GooseMessage.tsx, ui/desktop/src/types/message.ts
preserves existing functionality, allows extension requests to be sent for enables and disables
=> chore: generalize extension request

documentation/docs/troubleshooting.md
- Add Mirrored Networking Link for WSL troubleshooting
I spent about 3 hours trying to get goose to able to connect to Ollama using windows. The existing trouble shooting information didn't work for me. I stumbled on this solution in the Microsoft docs and hope it could save some else some time.
👋 @alexhancock
=> Update troubleshooting.md with Mirror Networking Link

Cargo.lock, crates/goose-ffi/Cargo.toml, crates/goose-ffi/README.md, crates/goose-ffi/build.rs, crates/goose-ffi/examples/goose_agent.py, crates/goose-ffi/include/goose_ffi.h, crates/goose-ffi/src/lib.rs, crates/goose/src/providers/databricks.rs
This currently only builds functions to initialize and send message to goose.
We will work on supporting tools in a follow up
=> feat: Build an FFI for goose rust library

crates/goose/src/providers/formats/openai.rs, crates/goose/src/providers/google.rs, crates/goose/src/providers/openai.rs, ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
Fix #2241
Also clean up some old gemini models
=> feat: support o4-mini model

Cargo.lock, ui/desktop/src/components/settings_v2/extensions/agent-api.ts, ui/desktop/src/components/settings_v2/extensions/extension-manager.ts
Minimal change to address env var issues with extensions in settings v2
=> fix: specify extension env vars only by name

crates/goose-mcp/src/google_drive/mod.rs
I realized during my last PR that there was this entire "instructions" block of text in the Gdrive MCP that I hadn't noticed before. This PR adds entries for each of the available tools.
Also, the numbered list is re-sorted to group like-types of operations together and hopefully read more cohesively.
=> Update gdrive instructions to be comprehensive

documentation/blog/2025-04-17-goose-goes-to-NY/index.mdx, documentation/src/components/ImageCarousel.js
This PR adds a new blog post recapping Goose’s second-ever community meetup in NYC. The post highlights the event experience, community feedback, and includes multiple photo carousels.
- New blog post: `goose-goes-to-NY/index.mdx`
- Title: **Codename Goose Goes to New York**
- Description: *Goose lands in NYC for its second ever community meetup — lightning talks, live demos, and hands-on hacking with an amazing crowd.*
- Event summary, quotes, and shoutouts
- RSVP link for the next meetup in Atlanta
- Updated blog metadata for social sharing
- 3 `ImageCarousel` components used for photo highlights (swag, speakers, games)
- Local image imports for all carousel images
Minor update to `ImageCarousel.js` to prevent fallback titles (`Image 1`, `Image 2`, etc.) from showing when no `names` …
=> docs: recap blog for goose nyc meetup

documentation/docs/guides/creating-plans.md
New topic that documents the `/plan` prompt completion feature in the Goose CLI
=> docs: Plans

Cargo.lock, crates/goose-cli/Cargo.toml, crates/goose-cli/src/cli.rs, crates/goose-cli/src/commands/session.rs
Allow user to remove session by using
1) --all flag: remove all sessions
2) --session-name: remove speicifc session
=> Add remove session capacity

crates/goose/src/providers/google.rs
add models/gemini-2.5-flash-preview-04-17
=> Add new model to  google.rs

crates/goose-cli/src/commands/session.rs, crates/goose/src/session/info.rs
Test:
`cargo run --bin goose session remove --regex "20250422_.*"`
```
The following sessions will be removed:
- 20250422_113353
- 20250422_103053
◇  Are you sure you want to delete all these sessions? (yes/no):
│  Yes 
│
Session `20250422_113353` removed.
Session `20250422_103053` removed.
```
=> feat: preview to-be-removed session

documentation/docs/getting-started/installation.md
we inadvertently committed the a repeated paragraph
=> docs: remove repeated paragraph

ui/desktop/src/main.ts
In response to some feedback that spellcheck / click to correct wasn't working in the app. I thought I had taken care of this in https://github.com/block/goose/pull/2116 but there is more implementation required
**Demo Screenshot**
=> feat: full spellcheck/correction support for editable content in the app

documentation/docs/tutorials/blender-mcp.md, documentation/docs/tutorials/selenium-mcp.md
Shorts for Selenium and Blender MCPs
=> docs: tutorial shorts

documentation/docs/guides/session-recipes.md
there is no "Save" when creating recipes
=> docs: remove invalid step

documentation/docs/guides/allowlist.md
Added a new topic for setting up a Goose allowlist.
=> docs: Jaustin/goose-allowlist

documentation/docs/tutorials/blender-mcp.md
=> docs: new blender video

documentation/docs/guides/session-recipes.md
=> docs: added description to Recipe guide

documentation/docs/guides/tips.md
This pull request significantly revises the "Quick Tips" section in the `documentation/docs/guides/tips.md` file to provide a more structured, user-friendly guide for working with Goose. The changes focus on improving clarity, introducing new tips, and reorganizing content to emphasize key features and best practices.
=> docs: Update quick tips doc

documentation/docs/tutorials/_template_.md, documentation/docs/tutorials/brave-mcp.md
Updated the template to reflect the new "do you want to add a description" prompt in the CLI tool
=> new Brave Search MCP tutorial, and updated template

documentation/docs/guides/managing-goose-sessions.md
This pull request updates the documentation for managing Goose sessions by introducing a new section on search functionality, standardizing terminology, and simplifying command examples.
---
- https://app.asana.com/0/0/1209864018195103
=> docs: adding docs for search functionality in ui

documentation/docs/tutorials/pieces-mcp.md
Jim kindly contributed documentation for how to use the Pieces MCP server. I made some edits to add more detail and better fit our formatting. 
Side note: this MCP server seems cool..it basically can give you a summary of what you did on your computer yesterday, last week, 5 minutes ago. I think a cool youtube short can be like "I wrote some code yesterday and I forgot where I left off or what the code does" something like that
=> docs: Pieces MCP Server Tutorial Quick Edits

Cargo.lock, crates/goose-llm/Cargo.toml, crates/goose-llm/README.md, crates/goose-llm/examples/simple.rs, crates/goose-llm/src/completion.rs, crates/goose-llm/src/lib.rs, crates/goose-llm/src/prompt_template.rs, crates/goose-llm/src/prompts/mock.md, crates/goose-llm/src/prompts/system.md, crates/goose/src/permission/permission_judge.rs
Run:
```
cargo run -p goose-llm --example simple
```
Output:
```
---------------
User Input: Add 10037 + 23123
Completion Response:
{
"message": {
"role": "assistant",
"created": 1745591803,
"content": [
{
"type": "text",
"text": "I'll help you add those numbers using the calculator function."
},
{
"type": "toolRequest",
"id": "toolu_bdrk_01M95KdDwHwfHYhhH7s9bn6z",
"toolCall": {
"status": "success",
"value": {
"name": "calculator",
"arguments": {
"numbers": [
10037,
23123
],
"operation": "add"
}
}
}
}
]
},
"usage": {
"model": "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
"usage": {
"input_tokens": 551,
"output_tokens": 88,
"total_tokens": 639
}
},
"tool_approvals": {
"approved": [
"toolu_bdrk_01M95KdDwHwfHYhhH7s9bn6z"
],
"needs_approval": [],
"denied": []
}
}
---------------
User Input: …
```
=> goose-llm crate

documentation/docs/guides/environment-variables.md
Added a comprehensive guide detailing the environment variables supported by Goose. The guide organizes variables into categories, provides usage examples, and includes tips for configuration.
=> docs: list of environment variables

documentation/docs/tutorials/elevenlabs-mcp.md, documentation/docs/tutorials/repomix-mcp.md
adding youtube short to ElevenLabs and Repomix tutorials
=> docs: adding youtube shorts to tutorials

documentation/docs/tutorials/agentql-mcp.md, documentation/docs/tutorials/asana-mcp.md, documentation/docs/tutorials/blender-mcp.md, documentation/docs/tutorials/brave-mcp.md, documentation/docs/tutorials/elevenlabs-mcp.md, documentation/docs/tutorials/fetch-mcp.md, documentation/docs/tutorials/figma-mcp.md, documentation/docs/tutorials/filesystem-mcp.md, documentation/docs/tutorials/github-mcp.md, documentation/docs/tutorials/google-drive-mcp.md, documentation/docs/tutorials/google-maps-mcp.md, documentation/docs/tutorials/jetbrains-mcp.md, documentation/docs/tutorials/knowledge-graph-mcp.md, documentation/docs/tutorials/memory-mcp.md, documentation/docs/tutorials/pdf-mcp.md, documentation/docs/tutorials/pieces-mcp.md, documentation/docs/tutorials/postgres-mcp.md, documentation/docs/tutorials/puppeteer-mcp.md, documentation/docs/tutorials/repomix-mcp.md, documentation/docs/tutorials/selenium-mcp.md, documentation/docs/tutorials/speech-mcp.md, documentation/docs/tutorials/tavily-mcp.md, documentation/docs/tutorials/vscode-mcp.md, documentation/docs/tutorials/youtube-transcript.md
also added youtube short to brave-mcp tutorial
=> added Description prompt to tutorials

crates/goose-mcp/src/google_drive/mod.rs
=> feat: combine create and reply comment tools

documentation/docs/tutorials/square-mcp.md
Added YouTube link, and updated "official" to say "open-source"
=> updated to include youtube embed

documentation/docs/guides/goose-cli-commands.md
=> docs: fix cli arrow command

documentation/docs/getting-started/using-extensions.md, documentation/docs/guides/smart-extension-recommendation.md
This pull request enhances the documentation for Goose by introducing a new guide on the Smart Extension Recommendation feature and adding a tip about it to the existing "Using Extensions" documentation. These changes aim to help users better understand how Goose dynamically suggests and enables extensions based on their tasks.
* **Added Smart Extension Recommendation Guide**: Introduced a new guide, `smart-extension-recommendation.md`, explaining how Goose identifies and suggests relevant extensions dynamically. The guide includes examples of automatic detection and direct requests for extensions, demonstrating both UI and CLI workflows.
* **Added Tip to "Using Extensions" Documentation**: Included a tip in `using-extensions.md` about Goose's ability to suggest extensions based on tasks, …
=> docs: Smart Extension Recommendation

documentation/docs/guides/managing-context.md, documentation/docs/guides/smart-context-management.md
This pull request introduces a new documentation guide for "Smart Context Management" in Goose, explaining how to handle conversation history effectively when working with Large Language Models (LLMs). The guide includes an overview of key concepts, features, and usage instructions for both the Goose Desktop and CLI interfaces.
* **Overview of Key Concepts**: Introduced terms like "Context Length," "Context Limit," and "Context Management" to explain the challenges of managing conversation history with LLMs.
* **Features Explained**: Added a table describing three context management strategies—Summarization, Truncation, and Clear—along with their use cases and impacts.
* **Usage Instructions for Goose Desktop**: Provided step-by-step guidance for handling context limits in the desktop …
=> Docs: smart context management

documentation/blog/2025-05-06-recipe-for-success.md/index.md
I messed up the link for my blog post. 🤦🏿‍♀️
This PR fixes it.
=> blog: fix metadata link

crates/goose/src/providers/factory.rs, crates/goose/src/providers/githubcopilot.rs, crates/goose/src/providers/mod.rs
This implements support for github copilot as an LLM provider
Fixes: #1189
=> goose/providers: add github copilot

documentation/docs/tutorials/_template_.md, documentation/docs/tutorials/agentql-mcp.md, documentation/docs/tutorials/asana-mcp.md, documentation/docs/tutorials/blender-mcp.md, documentation/docs/tutorials/brave-mcp.md, documentation/docs/tutorials/computer-controller-mcp.md, documentation/docs/tutorials/elevenlabs-mcp.md, documentation/docs/tutorials/fetch-mcp.md, documentation/docs/tutorials/figma-mcp.md, documentation/docs/tutorials/filesystem-mcp.md, documentation/docs/tutorials/github-mcp.md, documentation/docs/tutorials/google-drive-mcp.md, documentation/docs/tutorials/google-maps-mcp.md, documentation/docs/tutorials/jetbrains-mcp.md, documentation/docs/tutorials/knowledge-graph-mcp.md, documentation/docs/tutorials/mbot-mcp.md, documentation/docs/tutorials/memory-mcp.md, documentation/docs/tutorials/pdf-mcp.md, documentation/docs/tutorials/pieces-mcp.md, documentation/docs/tutorials/postgres-mcp.md, documentation/docs/tutorials/puppeteer-mcp.md, documentation/docs/tutorials/repomix-mcp.md, documentation/docs/tutorials/selenium-mcp.md, documentation/docs/tutorials/speech-mcp.md, documentation/docs/tutorials/square-mcp.md, documentation/docs/tutorials/tavily-mcp.md, documentation/docs/tutorials/tutorial-extension.md, documentation/docs/tutorials/vscode-mcp.md, documentation/docs/tutorials/youtube-transcript.md
Goose's CLI interface has changed some text, so I updated other tutorials to match
=> docs: added Square's remote MCP to previous tutorial

documentation/docs/tutorials/_template_.md, documentation/docs/tutorials/agentql-mcp.md, documentation/docs/tutorials/asana-mcp.md, documentation/docs/tutorials/blender-mcp.md, documentation/docs/tutorials/brave-mcp.md, documentation/docs/tutorials/elevenlabs-mcp.md, documentation/docs/tutorials/fetch-mcp.md, documentation/docs/tutorials/figma-mcp.md, documentation/docs/tutorials/filesystem-mcp.md, documentation/docs/tutorials/github-mcp.md, documentation/docs/tutorials/google-drive-mcp.md, documentation/docs/tutorials/google-maps-mcp.md, documentation/docs/tutorials/knowledge-graph-mcp.md, documentation/docs/tutorials/mbot-mcp.md, documentation/docs/tutorials/pdf-mcp.md, documentation/docs/tutorials/postgres-mcp.md, documentation/docs/tutorials/puppeteer-mcp.md, documentation/docs/tutorials/repomix-mcp.md, documentation/docs/tutorials/selenium-mcp.md, documentation/docs/tutorials/speech-mcp.md, documentation/docs/tutorials/square-mcp.md, documentation/docs/tutorials/tavily-mcp.md, documentation/docs/tutorials/vscode-mcp.md, documentation/docs/tutorials/youtube-transcript.md
also ensured that all npx commands include the "-y" flag
=> added tabs on tutorial TLDR blocks

documentation/blog/2025-05-12-local-goose-qwen3/index.md
new blog on this cool new model
=> short post on qwen3

documentation/docs/guides/smart-context-management.md
This PR updates the `smart-context-management.md` guide to reflect the current behavior in Goose Desktop.
🔧 **What changed:**
- ✅ Clarified that Goose Desktop automatically uses summarization when the context limit is reached
- ✅ Updated bullet points to reflect the new UI behavior and flow
- ✅ Removed outdated instructions that referenced clear/truncate options
📌 **Why:**
The previous version described CLI behavior, which doesn't apply to the Desktop UI. This update ensures users get accurate guidance on how context is managed in the Goose Desktop app.
---
- https://app.asana.com/0/0/1210195868945797
- https://app.asana.com/0/0/1210196047652611
=> docs: Update Smart Context Management Guide for Desktop

documentation/docs/guides/managing-goose-sessions.md, documentation/package.json
Add new keyboard shortcuts to the "Start Session" and "Search Within Sessions" sections of the "Managing Goose Sessions" topic.
=> docs: Document new keyboard shortcuts

crates/goose-cli/src/recipes/github_recipe.rs, crates/goose-cli/src/recipes/recipe.rs, crates/goose-cli/src/recipes/search_recipe.rs
Details in https://github.com/block/goose/issues/2560
=> feat: discover recipe in the paths from environment variable GOOSE_RECIPE_PATH

documentation/docs/tutorials/browserbase-mcp.md
This pull request adds a new tutorial to the documentation, explaining how to integrate the Browserbase MCP Server as a Goose extension for web automation. The tutorial includes detailed steps for both the Goose Desktop and CLI interfaces, as well as an example use case for automating data extraction from GitHub.
* `documentation/docs/tutorials/browserbase-mcp.md`: Added a comprehensive tutorial for integrating the Browserbase MCP Server as a Goose extension. The tutorial includes:
- Installation steps for both Goose Desktop and CLI interfaces.
- Configuration instructions, including setting environment variables and adding a command-line extension.
- An example use case showcasing how to automate data extraction from GitHub trending repositories using the extension.
=> docs: Browserbase MCP tutorial

documentation/docs/guides/config-file.md
New external guide for the `config.yaml` file.
=> Docs: New guide on config.yaml file

crates/goose-cli/src/session/mod.rs
goose run (recipes or otherwise) will sometimes stop due to context size and ask user when it must not.
=> fix: don't stop when in non interactive when you need to summarize

documentation/blog/2025-05-22-manage-local-host-conflicts-with-goose/index.md, documentation/docs/tutorials/playwright-mcp.md
- Added playwright video short
- Added truncate for blog post
=> docs: Add Playwright MCP short

crates/goose-cli/src/commands/schedule.rs, crates/goose-server/src/routes/schedule.rs, crates/goose/src/scheduler.rs, ui/desktop/openapi.json, ui/desktop/src/api/types.gen.ts, ui/desktop/src/components/schedule/ScheduleDetailView.tsx, ui/desktop/src/components/schedule/SchedulesView.tsx, ui/desktop/src/schedule.ts
https://github.com/user-attachments/assets/f957cdd8-3313-4441-aa91-75ab0b94f2da
=> (feat): add livetracking of running schedules

ui/desktop/src/main.ts
=> prevent accidental quit

crates/goose-mcp/src/computercontroller/mod.rs
fixes: https://github.com/block/goose/issues/2665 
will make CC work a lot better and waste less time
=> fix: set permissions for quickscript

ui/desktop/src/main.ts
fixing annoyance when developing. reportd by @zanesq
=> allow quick quit in dev mode

documentation/docs/guides/config-file.md, documentation/docs/guides/environment-variables.md, documentation/docs/guides/goose-cli-commands.md, documentation/docs/guides/session-recipes.md
TLDR: The recipe tool will get more features, so I'm cleaning up the doc to make room for more. 
This pull request updates the documentation for Goose recipes, focusing on configuration, usage, and sharing methods. Key changes include the addition of a GitHub repository configuration for recipes, updates to CLI commands, and improvements to the session recipes guide.
* Added a new configuration option `GOOSE_RECIPE_GITHUB_REPO` for specifying a GitHub repository to store and retrieve recipes. [[1]](diffhunk://#diff-41d7c34e289168a865abd4b71c652fff0040f7bcb1074c046298e16f1430d855R32) [[2]](diffhunk://#diff-41d7c34e289168a865abd4b71c652fff0040f7bcb1074c046298e16f1430d855R53-R55)
* Updated the session recipes guide to include instructions for configuring the recipe repository using either …
=> Docs recipe revamp

crates/goose/src/providers/formats/databricks.rs
It was previously for 3.7, but needs this patch for 4 (on databricks)
=> fix: thinking applies to claude 4 as well

.github/workflows/bundle-desktop-windows.yml, .github/workflows/canary.yml, .github/workflows/release.yml
allows to build correctly in canary and release
=> switch roles on condition for windows

crates/goose-server/src/routes/providers_and_keys.json, crates/goose/tests/agent.rs, crates/goose/tests/providers.rs
Follow up to: https://github.com/block/goose/pull/2976
As requested by @salman1993 here: https://github.com/block/goose/pull/2976#issuecomment-2982424895
=> Add xAI Test Coverage

documentation/docusaurus.config.ts, documentation/src/css/custom.css
=> added MCPs menu item

crates/goose/src/session/storage.rs
=> allow to use dev/null for no-session mode

ui/desktop/src/App.tsx
This PR reverts two commits that I accidentally included in https://github.com/block/goose/pull/3203
=> revert commits from WIP global-checkpoints

documentation/docs/mcp/cloudinary-asset-management-mcp.md
This pull request introduces a new tutorial document, `cloudinary-asset-management-mcp.md`, providing comprehensive guidance on integrating the Cloudinary Asset Management MCP Server as a Goose extension. The document includes step-by-step instructions for both GUI and CLI configurations, as well as an example workflow showcasing advanced image processing capabilities.
* **New Tutorial for Cloudinary Integration**: Added a detailed guide on configuring the Cloudinary Asset Management MCP Server as a Goose extension, including both Goose Desktop and CLI setup instructions.
* **Example Workflow**: Demonstrated a practical use case for the extension, including searching for images, applying transformations (e.g., background removal, text overlay), and generating professional product imagery.
=> Docs: Add cloudinary mcp tutorial

documentation/docs/guides/recipes/recipe-reference.md
Recipes can produce structured output when run from either the Goose CLI or Goose Desktop.
=> Structured output in Goose CLI and Goose Desktop

ui/desktop/src/components/ChatInput.tsx, ui/desktop/src/components/bottom_menu/BottomMenuModeSelection.tsx, ui/desktop/src/components/bottom_menu/CostTracker.tsx, ui/desktop/src/components/bottom_menu/DirSwitcher.tsx, ui/desktop/src/components/context_management/ManualSummaryButton.tsx, ui/desktop/src/components/icons/CoinIcon.tsx, ui/desktop/src/components/icons/index.tsx, ui/desktop/src/components/settings/models/bottom_bar/ModelsBottomBar.tsx
=> ui: update chat bottom

documentation/docs/guides/file-management.md
This PR adds docs for the fuzzy file search feature in the "File Access and Management" topic
- `sites/block/docs/tools/goose/guides/file-management.md`: 
- Added "Quick File Search in Goose Desktop" section with feature docs
- Renamed/restructured content by adding "File Access" and "File Management Best Practices" sections to reflect the new dual purpose of the topic
=> docs: add fuzzy search

documentation/docs/guides/cli-providers.md
This pull request updates the `CLI Providers` documentation to improve clarity, reorganization, and usability. Key changes include restructuring sections for better readability, adding detailed benefits and use cases, and removing redundant content to streamline the guide.
=> docs: reflecting benefits of CLI providers

documentation/docs/experimental/goose-mobile.md
=> docs: goose mobile

crates/goose/src/agents/recipe_tools/param_utils/tests.rs, crates/goose/src/agents/recipe_tools/sub_recipe_tools/tests.rs
`cargo test` currently in a broken state, and this fixes it
=> fix: adjust subrecipe description to allow running tests

crates/goose/src/agents/agent.rs
Closes #3700 
Ensure the final output tool is always available during vector and llm tool selections to avoid endless looping.
=> fix: Ensures final output tool is available when using vector tool search

documentation/docs/quickstart.md
=> Fix typo in quickstart document

ui/desktop/README.md
Minor typo in the Desktop README.
=> chore: fix typo in desktop readme for goosed

.goosehints
We should do this more and in more details, but I thought we should tell it at least about our client & server protocol. also tell the humans
=> Update goose hints

documentation/blog/2025-08-13-pulse-mcp-automates-recipe/index.md
=> Fixing typos

crates/goose/src/config/signup_tetrate/mod.rs
Adds headers which TARS can use to identify goose clients during the PKCE flow
=> Add X-Title and referer headers on exchange to tetrate

.husky/pre-commit
When I made a commit, the husky pre-commit hook warned me to delete these lines.
=> Remove a bit from pre-commit that husky says we should

ui/desktop/src/App.tsx, ui/desktop/src/components/Layout/AppLayout.tsx, ui/desktop/src/components/sessions/SessionHistoryView.tsx, ui/desktop/src/components/sessions/SharedSessionView.tsx, ui/desktop/src/components/settings/SettingsView.tsx, ui/desktop/src/components/settings/sessions/SessionSharingSection.tsx, ui/desktop/src/main.ts, ui/desktop/src/sessionLinks.ts, ui/desktop/src/sharedSessions.ts, ui/desktop/src/utils/appInitialization.ts, ui/desktop/src/utils/navigationUtils.ts
Re-adding this feature until we come up with a version that doesn't require a custom backend.
=> feat: re-introduce session sharing

.github/workflows/validate-recipe-pr.yml
fixing a syntax error in our workflows
=> removing a leftover syntax error

documentation/src/pages/recipes/data/recipes/test-recipe2.yaml
=> test recipe

documentation/src/pages/recipes/data/recipes/lint-my-code.yaml
Restoring a deleted recipe (testing scanners/email system)
---
**Email**: iand@squareup.com
=> restoring a deleted recipe

documentation/src/pages/recipes/data/recipes/simplest-recipe.yaml
greet the user -- testing our recipe cookbook workflow again
---
**Email**: iand@squareup.com
=> adding a new recipe

crates/goose/src/providers/tetrate.rs, crates/goose/tests/tetrate_streaming.rs
Adds streaming support to the Tetrate Agent Router Service provider.
=> feat: add streaming support to Tetrate Agent Router Service provider

crates/goose-cli/src/session/output.rs
Switch out the REDACT thing for for long tool calls with a truncation. Also removes the configurable width and replaces it with a measurement of the terminal.
Looks like
=> fix: don't redact tool calls

.github/workflows/send-api-key.yml
=> also adding this change to the api key send for recipes

documentation/src/pages/recipes/data/recipes/dependency-updater.yaml
**Email**:  Abhijay007j@gmail.com
=> refactor: add new recipe dependency updater

Cargo.lock, crates/goose/Cargo.toml
This should work fine on macos
=> fix build: latest bedrock version

crates/goose/src/providers/githubcopilot.rs
addresses https://github.com/block/goose/issues/4853
=> Tiny: fix github casing 

.github/workflows/pr-comment-bundle.yml
For https://github.com/block/goose/security/advisories/GHSA-4h72-4h3w-4587
=> Disable the issue comment trigger on pr-comment-bundle

GOVERNANCE.md, MAINTAINERS.md, README.md
Adds a governance model for goose
Read the formatted version [here](https://github.com/block/goose/blob/2f4bffcd8739b9b5909929b3f1b81953d973a7f9/GOVERNANCE.md)
=> feat(process): Add GOVERNANCE and MAINTAINERS documents

test_acp_client.py
I've removed the unused libraries from the script.
**Email**: mirxoliqov.sayfulla@gmail.com
=> Removed unused libs
