block/goose

- README.md
Per the tin. Goose appears to be publishing as [goose-ai](https://pypi.org/project/goose-ai/) on pypi. Fixes #6
> goose->goose-ai in install instructions

- .github/workflows/pypi_release.yaml
Hopefully this would fix incorrect breaking of main when things are not published: 
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-filters-to-target-specific-branches-for-pull-request-events
> conditionally publish only when config changes

- README.md
- Added gif to demo goose
- Reordered the readme sections and added configuration options instructions
- Added FAQ section
> Modified the readme to be more friendly to new users

- pyproject.toml
- src/goose/cli/main.py
- tests/cli/test_main.py
**Why**
Added the entry point `goose.cli.group_option`so that the plugin can add customised command option as top level cli 
**What**
- added the entry point `goose.cli.group_option` and load plugins
- rename the entry point `"goose.cli` to `goose.cli.group` 
- update the version (will coordinate with the versions in other PRs)
> Enable cli options for plugin

- pyproject.toml
- src/goose/cli/main.py
Solving the issue https://github.com/square/goose/issues/29
- Created an entry point for `goose` (`goose-ai` package)
- Fixed the issue where modules weren’t imported correctly during the `uv run goose version`
Corresponding PR in exchange:
https://github.com/square/exchange/pull/16
> goose version command fix

- pyproject.toml
- src/goose/cli/session.py
- tests/cli/test_session.py
Before this PR, when a session was resumed there were a few edge cases where we would fail to resume correctly. This PR fixes all of them to ensure we always can resume the session safely, while minimizing the context lost.
> fix: resuming sessions

- src/goose/toolkit/developer.py
- src/goose/utils/check_shell_command.py
- tests/utils/test_check_shell_command.py
This pull request enhances the safety of shell command execution by introducing a check for dangerous commands and updating the notification messages accordingly. The most important changes include adding a utility function to identify dangerous commands, modifying the shell command execution logic to incorporate this check, and adding tests to validate the new functionality.
* [`src/goose/utils/check_shell_command.py`](diffhunk://#diff-49bef33f51eea6dab40ca972595545c116f882e07a153c0e32bbb456d881535cR1-R33): Added a new utility function `is_dangerous_command` to identify potentially dangerous shell commands based on predefined patterns.
* [`src/goose/toolkit/developer.py`](diffhunk://#diff-3e5431e1f0b4918b17f7788a405d3b3e22610eb8f91043afb1a6042e41c039a6L159-R166): Updated the `shell` …
> added some regex based checks for dangerous commands

- src/goose/toolkit/developer.py
- tests/toolkit/test_developer.py
After trying a few approaches, this simple one still seems potentially relevant (you can put specific instructions for goose in a repo).
> adding in ability to provide per repo hints

- src/goose/cli/main.py
- src/goose/toolkit/developer.py
- src/goose/toolkit/lint.py
- src/goose/toolkit/repo_context/repo_context.py
- tests/cli/test_main.py
- tests/test_linting.py
Folks did not have a reliable way of discovering toolkits, adding this so they can view all available ones.
Output of running `goose toolkit list`
```
Available toolkits:
- developer: Provides a set of general purpose development capabilities
- github: Provides an additional prompt on how to interact with Github
- repo_context: Provides context about the current repository
- screen: Provides an instructions on when and how to work with screenshots
```
> feat: show available toolkits

- README.md
- justfile
- src/goose/toolkit/developer.py
- src/goose/toolkit/utils.py
- tests/toolkit/test_developer.py
Easier to `include` files like README.md & CONTRIBUTING.md
> Make goosehints jinja templated

- src/goose/utils/check_shell_command.py
Slightly clarifies the method description for what we're defining as a "dangerous command".
> chore(docs): update is_dangerous_command method description

- src/goose/cli/session.py
Rewind to right before the last user message, and prompt them again
> fix: remove unsafe pop of messages

- Dockerfile
This change allows goose to run inside a docker container for those you are more interested in just trying it out without it running entirely in their environment. 
To build it: 
```sh
docker build -t goose . 
docker run -it --env OPENAI_API_KEY goose
```
This will open a new goose session that uses OPENAI (can do similar with anthropic etc) in an environment you can let it play in (it can clone things, try to build etc) all in a container. 
If interested, can have this automatically published to make it easier for people to tyre kick
> feat: run goose in a docker-style sandbox

- ARCHITECTURE.md
exchange is now in square, not squareup
> docs: fix broken link

- src/goose/cli/main.py
- tests/cli/test_main.py
- replace legacy `Dict` with buitin `dict` for python >= 3.9+ / PEP585
- add `-V` / `--version` flags to match other cli tools
* chose `-V` since many applications use `-v` as `--verbose`, which may be useful if we add debug logging
```fish
$ uv run goose version
Goose-ai: 0.9.0
Plugins:
Module: ai-exchange, Version: 0.9.0
$ uv run goose --version
Goose-ai: 0.9.0
Plugins:
Module: ai-exchange, Version: 0.9.0
$ uv run goose -V
Goose-ai: 0.9.0
Plugins:
Module: ai-exchange, Version: 0.9.0
```
```fish
$ uv --version
uv 0.3.3 (deea6025a 2024-08-23)
$ uv -V
uv 0.3.3 (deea6025a 2024-08-23)
$ uv version
uv 0.3.3 (deea6025a 2024-08-23)
```
```fish
$ git --version
git version 2.45.2
$ git -v
git version 2.45.2
$ git version
git version 2.45.2
```
> feat: add version options

- src/goose/cli/main.py
- src/goose/toolkit/utils.py
- tests/toolkit/test_utils.py
Supported Markdown plans, made them Jinja-templated, and allowed passing parameters.
The `plan.md` file can be in a free format, but the **last** group of lines that start with “-” is considered the plan.
Some examples:
Example 1:
```
Here is the python repo
-use {{ dep }}
-use poetry
Here is a plan:
- Open a file
- Run a test
- Setup {{ repo }}
```
the plan is:
```
- Open a file
- Run a test
- Setup {{ repo }}
```
Example 2:
```
Here is the python repo.
You should follow these steps:
- Open a file
- Run a test
- Setup {{ repo }}
```
the plan is:
```
- Open a file
- Run a test
- Setup {{ repo }}
```
To start a session with a plan:
```
goose session planned plan.md --args arg1:value1 arg2:value2
```
> feat: support markdown plans 

- justfile
Add just commands for creating a release PR (also updates ai-exchange package to latest), tagging, and pushing tags.
> chore: add just command for releasing goose

- README.md
small change to mention expermental provider support
> docs: add in ollama

- CONTRIBUTING.md
simple doc addition cc @codefromthecrypt
> docs: document how to run goose fully from source from any dir

- src/goose/toolkit/developer.py
- src/goose/utils/ask.py
This will either return to user and ask them to run it themselves, or ask for more information, or work out how to run it with the information it has. Uses patterns and the accelerator model to supervise command output
fixes: https://github.com/square/goose/issues/49
How this works: 
* Watches stdout and stderr
* looks for patterns which may indicate it is blocking for user response
* If there is will return to the user or ask for more input (no blocking)
* If the process doesn't return any output for a time, it examines the log with the `acclerator` model to see if it may be a long running process and confirm with the user. 
For example, both of these are interactive commands now handled: 
The former one uses the accelerator model to detect if it is long running or not. Former uses a …
> fix: enhance shell() to know when it is interactive

- src/goose/toolkit/screen.py
Updating the screen toolkit to have the capability to resize the image. 
This is a solution for errors in payload size when sending images, for example. We've been seeing this in some providers, but not all. The limits in OpenaAI for payload size is 20MB.
By tools default functionality doesn't change, only when prompted to resize the image if you run into errors.
edit: Additionally, wanted to note that the file size isn't the right number for the payload since the images are being base64 encoded, inflating the disk size by 37%.
> fix: Resize file in screen toolkit

- src/goose/cli/config.py
before this, ollama defaulted to gpt images which would never work.
> fix: default ollama to tested model

- src/goose/toolkit/developer.py
this was picking up too much in output
> fix: remove overly general match for long running commands

- README.md
The discord badge was broken, also fixes a section hyperlink
> chore: fix broken badge on readme

- .github/workflows/deploy_docs.yaml
> ci: add include-markdown for mkdocs

- justfile
When using a client and/or IDE with `git` integration built in, it's difficult to see a failed `ruff` commands until _after_ a commit is pushed up. This change adds the ability to see those errors in your client and/or editors if you have the pre-commit hooks installed.
Note: This is purely opt-in (`just install-hooks`) and a user can bypass with `--no-verify` after it's installed. n.b. this pre-commit hook does have the potential to "lose" a commit message but many clients save the most recent commit (`.git/COMMIT_EDITMSG`) but this is generally a bug with the `git` client/implementation itself.
> fix: resolve uvx when using a git client or IDE

- ARCHITECTURE.md
- CONTRIBUTING.md
- docs/plugins/providers.md
Update old square links to within the new goose location
> docs: update links to exchange to the new location

- src/goose/toolkit/developer.py
**screenshots after removal** 
***shell***
***patch_file***
***write_file***
> fix: removed the panel in the output so that the user won't have unnecessary pane borders in the copied content

- src/goose/toolkit/prompts/developer.jinja
The developer toolkit's `update_plan` tool only accepts "planned", "complete", "failed" and "in-progress" as statuses, but the developer prompt currently has few-shot examples using the "pending" status. I noticed that this sometimes causes the first tool call from Goose to `update_plan` to fail by trying to set statuses to "pending". This PR updates the prompt to use the "planned" status everywhere instead of "pending".
> fix: update developer tool prompts to use plan task status to match allowable statuses update_plan tool call

- src/goose/utils/_cost_calculator.py
- tests/utils/test_cost_calculator.py
Update the pricing for the main gpt-4o models after the last update.
See https://openai.com/api/pricing/ for confirmation.
> fix: Update OpenAI pricing per https://openai.com/api/pricing/

- packages/exchange/src/exchange/providers/ollama.py
> docs: working ollama for desktop

- packages/exchange/src/exchange/providers/anthropic.py
- packages/exchange/src/exchange/providers/azure.py
- packages/exchange/src/exchange/providers/base.py
- packages/exchange/src/exchange/providers/bedrock.py
- packages/exchange/src/exchange/providers/databricks.py
- packages/exchange/src/exchange/providers/google.py
- packages/exchange/src/exchange/providers/ollama.py
- packages/exchange/src/exchange/providers/openai.py
- packages/exchange/src/exchange/providers/utils.py
- src/goose/cli/main.py
- src/goose/toolkit/lint.py
- tests/test_linting.py
> chore: Add goose providers list command

- packages/exchange/tests/providers/cassettes/test_google_complete.yaml
- packages/exchange/tests/providers/cassettes/test_google_tools.yaml
- packages/exchange/tests/providers/conftest.py
- packages/exchange/tests/providers/test_google.py
part of https://github.com/square/exchange/issues/67 closes https://github.com/square/exchange/pull/71
> test: convert Google Gemini tests to VCR

- docs/plugins/providers.md
- src/goose/cli/config.py
Set default model configuration for the Google provider. This enables a working configuration just by specifying `GOOGLE_API_KEY`. Without this PR, the configuration defaults to OpenAI processor and accelerator values, which do not work for the Google provider.
I set it to use the flash version for both the processor and accelerator. The free tier allows 15 requests per minute for flash, but only 2 requests per minute for pro.
Also add Google to the list of providers. 
Relevant issue: #129
> fix: Set default model configuration for the Google provider.

- src/goose/cli/session.py
- tests/cli/test_session.py
corrects a small error in merge conflict i made in [e6a428c](https://github.com/block-open-source/goose/pull/101/commits/e6a428cda5f13d354c28f32cf151a2861340e9c0). 
couldn't find any instantiation tests which would've caught this so will follow up with something so we can check in ci
> fix: use concrete SessionNotifier

- packages/exchange/pyproject.toml
- packages/exchange/src/exchange/providers/__init__.py
- packages/exchange/src/exchange/providers/groq.py
using: 
groq:
provider: groq
processor: llama3-groq-70b-8192-tool-use-preview
accelerator: llama3-groq-70b-8192-tool-use-preview
moderator: truncate
toolkits:
- name: developer
requires: {}
is really really fast - but does get lost after a while (as most llama3 ones do) - interesting to watch!
> feat: add groq provider

- README.md
Some comments around .goosehints got jumbled up in other sections.
> docs: goosehints doc fix only

- README.md
> docs: add link to action, IDE words

- src/goose/cli/main.py
- src/goose/cli/prompt/overwrite_session_prompt.py
- src/goose/cli/session.py
- tests/cli/prompt/test_overwrite_session_prompt.py
- tests/cli/test_session.py
This patch addresses 2 bugs:
- `goose session resume <session_name>` which is used by the IntelliJ plugin to break
-  improper as improper handling of case sensitive menu options used by `@click`.
> fix: session resume with arg handled incorrectly

- packages/exchange/src/exchange/providers/ollama.py
We've been using qwen2.5 in CI successfully for a while now.
> chore: updates ollama default model from mistral-nemo to qwen2.5

- src/goose/toolkit/repo_context/repo_context.py
In the `repo_context` toolkit, Goose summarizes a list of files with the `summarize_files_concurrent` function. This function needs an exchange to work, and we were using the accelerator exchange for this. I found that because that exchange still had the `patch_file` tool, sometimes it would try to use it for single files and it would save the file summary to `path/to/file.txt` (literally). This PR removes tools from the 'blank' exchange we are using to summarize files.
> fix: Remove tools from exchange when summarizing files

- README.md
Called visual attention to the Github action and dockerfile in the **Other ways to run Goose** section
> docs: add subheaders to the 'Other ways to run Goose' section

- .goosehints
- README.md
- src/goose/cli/main.py
adds: 
`goose run --resume-session instructions.md`
> feat: Run with resume session

- pyproject.toml
python 3.13 seems to have introduced changes that some packages haven't
been able to keep up with. we should restrict the latest until we've had
adequate time for it to bake.
adds compatibility: #154
fixes: #156
```
$ uv sync --index-url https://pypi.org/simple
Resolved 102 packages in 543ms
error: Failed to prepare distributions
Caused by: Failed to fetch wheel: greenlet==3.0.3
Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
```
```
error: Failed to prepare distributions
Caused by: Failed to fetch wheel: tiktoken==0.7.0
Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
```
> chore: restrict python version

- packages/exchange/src/exchange/moderators/summarizer.py
This PR fixes a bug with the Summarizer moderator in exchange where the Summarizer would default to using a None model when not passed in. This is updated to use the exchange's model if one is not passed as a parameter to the moderator.
> fix: update summarizer_exchange model to use default model from input exchange

- packages/exchange/pyproject.toml
- packages/exchange/src/exchange/langfuse_wrapper.py
- pyproject.toml
**Issue**
https://github.com/block-open-source/goose/issues/173
**What**
This is only an emergency fix to avoid errors when user starts `goose`.  Will apply a follow up fix to load langfuse the environment variables properly
- Avoid loading the `None` path.  
- Specify the `ai-exchange` version
> fix: added specific ai-exchange version and check path is None to avoid error after starting goose

- packages/exchange/.env.langfuse.local
- packages/exchange/src/exchange/langfuse_wrapper.py
- packages/exchange/tests/test_langfuse_wrapper.py
**What**
Currently the env.langfuse.local is used for 2 purposes:
1. Start the langfuse server on localhost
2. The host, public key, private key is used in goose application as a langfuse client to send tracing data.
For item 2, it would be better to specify the values on the goose client side (user) instead of packaging into the exchange package, either via loading an environment file that user specifies the path or loading the environment variable that user sets.
**What**
In exchange, rendering the environment variables for langfuse host, public key, private key, if any of them does not exists, fallback to the default variable for localhost langfuse
> fix: Simplifed langfuse auth check

- src/goose/synopsis/toolkit.py
- tests/synopsis/test_toolkit.py
This was stuff that didn't make it over yet
> fix: just adding stuff from developer.py to synopsis developer

- README.md
- docs/index.md
small tweaks (all done with goose! latest sonnet too)
> docs: getting index.md in sync with readme

- .github/workflows/license-check.yml
- .github/workflows/scripts/check_licenses.py
- .github/workflows/test-events/pull_request.json
This will check that licensed of dependencies brought in are valid
> feat: trying a license checker

- src/goose/cli/session.py
- tests/cli/test_session.py
This fix corrects session handling with the overwrite session prompt. 
Previously overwriting a session didn't
1. clear the context (which we load at init) https://github.com/block-open-source/goose/blob/7749b8aaf4390a83068045dd98f63345ed9566d9/src/goose/cli/session.py#L95
2. clear the session file when we write immediately (#94)
3. missing test case when adding guards (#101)
4. edge case when resuming a session (#145)
``` 
$ uv run goose session start aaaa
PLEASE NOTE: the ollama provider is experimental, use with care
Session already exists at /Users/lam/.config/goose/sessions/aaaa.jsonl.
Would you like to overwrite it?
[y]es      Overwrite the existing session
[n]o       Pick a new session name
[r]esume   Resume the existing session
Enter your choice: y
Overwriting existing session …
```
> fix: correct context loading from session new/overwrite and resume

- docs/index.md
- docs/plugins/cli.md
- docs/reference/goose/utils/check_shell_command.md
- docs/reference/goose/utils/shell/is_dangerous_command.md
- docs/reference/index.md
i think we had a merge conflict that replaced older content that was fixed in prior versions. this pr adds those back in as well as updated new methods from `synopsis`
> docs: fix mkdocs, update to new references

- src/goose/cli/main.py
- src/goose/cli/session.py
Adding tracing to the run cli command and grouping traces under the session name for easier tracking
> chore: add tracing option to run and group traces under session name

- docs/index.md
```
Issues found in 1 input. Find details below.
[./docs/index.md]:
[404] https://github.com/block-open-source/goose-intellij
🔍 116 Total (in 0s) ✅ 115 OK 🚫 1 Error
[WARN ] There were issues with GitHub URLs. You could try setting a GitHub token and running lychee again.
```
> docs: correct intellij link

- docs/configuration.md
- src/goose/cli/config.py
- src/goose/utils/_cost_calculator.py
This PR includes `claude-3-5-sonnet-20241022` where model versions are mentioned.
Feel free to close this PR if it's too early for this or if I accidentally borked something. 
* updated configuration docs to mention `claude-3-5-sonnet-20241022` instead of `claude-3-5-sonnet-20240620`
* added `claude-3-5-sonnet-20241022` to `_cost_calculator` using pricing data from [here](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table)
* updated recommended anthropic model from `claude-3-5-sonnet-20240620` -> `claude-3-5-sonnet-20241022`
> feat: include new anthropic model in docs and recommended config

- .github/workflows/scripts/check_licenses.py
- .github/workflows/scripts/test_check_licenses.py
- justfile
`just format` triggered `ruff` errors so normalized. ended up adding some quality of life for maintenance and possibly we can consider OSS as an action
**changes**
* added argparse/help
* added docstrings
* added test cases
* colorized output with columnized alignment
* ability to pass in multiple toml files
* sorted output
```
uv run python3 .github/workflows/scripts/check_licenses.py packages/exchange/pyproject.toml pyproject.toml
```
```
$ uv run pytest -m "not integration" .github/workflows/
========================== test session starts ==========================
platform darwin -- Python 3.10.0, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/lam/Development/goose-dev/goose
configfile: pyproject.toml
plugins: vcr-1.0.2, mock-3.14.0, anyio-4.6.2.post1
collected 9 items …
```
> feat: license checker

- packages/exchange/src/exchange/providers/base.py
- packages/exchange/src/exchange/providers/ollama.py
- packages/exchange/tests/providers/test_anthropic.py
- packages/exchange/tests/providers/test_azure.py
- packages/exchange/tests/providers/test_bedrock.py
- packages/exchange/tests/providers/test_databricks.py
- packages/exchange/tests/providers/test_google.py
- packages/exchange/tests/providers/test_openai.py
- packages/exchange/tests/test_base.py
- change in logic for MissingProviderEnvVariableError
-  non-empty check for PROVIDER_NAME
> chore: Minor changes in providers envs logic

- .gitignore
- justfile
- tests/cli/test_session.py
- added macOS specific .gitignores
- sorted recipes since `just --list` is a little longer now it's easier to read
- not sure why i wanted to ignore running the workflow tests, so removed that to run all the time
> chore: housekeeping

- packages/exchange/src/exchange/providers/anthropic.py
- packages/exchange/src/exchange/providers/base.py
- packages/exchange/src/exchange/providers/databricks.py
- packages/exchange/src/exchange/providers/google.py
- packages/exchange/src/exchange/providers/ollama.py
- src/goose/cli/config.py
**Why**
In each provider, define the recommended_models function.  It can be used when we setting the default models for the providers, and the providers in the plugin can override the function to use their recommended models
> refactor: used recommended_models function  as default model

- packages/exchange/src/exchange/exchange.py
- src/goose/cli/session.py
- src/goose/utils/_cost_calculator.py
- src/goose/utils/time_utils.py
- tests/cli/test_session.py
- tests/utils/test_cost_calculator.py
- Added newer model pricing
- Added the session name and time period for the total cost
Log example:
```
2024-10-30 14:29:47,043 - goose - INFO - Session name: x3s0 | Cost for model gpt-4o Usage(input_tokens=8236, output_tokens=701, total_to
kens=8937): $0.03
Session name: x3s0 | 2024-10-30 14:29:08 - 2024-10-30 14:29:47 | Total cost: $0.03
```
> fix: Cost calculation enhancement

- src/goose/cli/session.py
quick fix for prompt rendering, this occurs because of how the color parses in `rich`
> fix: prompt rendering

- .github/workflows/scripts/check_licenses.py
- justfile
this PR refines the approach introduced in #208 to consistently check licenses. i forgot it is used with `pre-commit` hooks which can overwhelm the ui output. especially it's sequenced _after_ `just format` because formatting runs faster and happens more frequently.
* [new] `just list-licenses` - added as a convenience to view allowed licenses before adding dependencies.
* license check phased implementation:
* `pre-commit`: runs license checks only if `pyproject.toml` is modified and `just install-hooks`, but now we avoid the unnecessary noise/speed on every commit
* `just check-license`: for contributors not using `pre-commit` hooks
* [new] `just check-license --force` requiring an explicit check (skips `git staging`, useful during iteration)
* ci enforcement: in the event all of these …
> chore: license-checker improvements

- src/goose/synopsis/moderator.py
This makes it a lot less chatty especially at first
> fix: only run summarize when there is something to summarize vs up front

- src/goose/cli/session.py
This PR fixes a minor oversight in the `single_pass` function where if a plan was provided to the session it would not be processed by the single_pass function.
This issue has been addressed by implementing a global "has_plan" check to maintain if there was originally a plan for the session. We also check the current length of the exchange message stack to ensure we perform this action in the event there was a plan added and it's not yet been processed.
Additionally, the initial_message variable has been changed to optional to allow CLI tools to take advantage of only leveraging session plans as prompts from Goose plugins.
> fix: Session:single_pass isn't plan aware

- src/goose/utils/shell.py
- tests/utils/test_check_shell_command.py
We should have the user confirm any commands related to killing processes.
> fix: Mark kill related commands as dangerous

- crates/goose-cli/src/prompt.rs
- crates/goose-cli/src/session.rs
When goose is processing a request and Ctrl + C is processed we will remove any assistant messages and the most recent user message to allow the user to change the last request they made to goose.
Eg.
> [cli] Ctrl + C interrupts goose and resets message history

- README.md
This pull request fixes a broken link to [LLM providers](https://block.github.io/goose/plugins/providers.html) in our readme file.
Links fixed:
- Under `Set up a provider` section, in README.md, fixed the [preferred LLM](https://block.github.io/goose/plugins/providers.html) link. ([Previous link is outdated](https://block.github.io/goose/providers.html))
> docs: fixed providers link in README

- src/goose/toolkit/web_browser.py
This pull request includes two enhancements to the web browser toolkit. 
The browser extension occasionally has issues clicking on the correct element on the page while navigating a website. This pull request help address the issue by allowing goose to easily scroll through a page and click on links and buttons using the visible text content. 
New functionalities:
* Introduced a new method `scroll_page` to scroll the current page up or down using the `PAGE_UP` and `PAGE_DOWN` keys.
* Added a method `click_element_by_link_text` to click on a page element by its visible text, with an option for exact or partial text match.
> feat: Add new navigation tools to the web browser toolkit

- crates/goose-cli/src/prompt/cliclack.rs
Changed default cliclack multiline hint text.
Starting state
| Original | New |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/1c4c4e55-6d11-4c38-96c8-f4b3675fc1d7) | ![image](https://github.com/user-attachments/assets/73f87b01-dbbd-4926-a126-00617656153a) |
Press 'Esc'
| Original | New |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/86a6421b-29d5-47fd-a519-6604aaddea4b) | ![image](https://github.com/user-attachments/assets/04de3302-1726-4c06-b73d-67ead11ad1c7) |
> [cli] Use clearer Esc -> Enter prompt for sending messages

- crates/goose/src/models/content.rs
This better aligns with client expectations
```json
{"result":[{"Text":{"text":"example"}}],"toolCallId":"call_HZM0sraJtEL0znZd4xaSbckj"}
```
becomes
```json
{"result":[{"text":"example","type":"text"}],"toolCallId":"call_AFJtX3C1mJdzRov6qt72iVZB"}
```
> feat: Cleanup serialization of content

- docs/guidance/using-goosehints.md
This pull request includes a small change to the `docs/guidance/using-goosehints.md` file. The change involves escaping the curly braces in the include directive to ensure proper rendering.
* [`docs/guidance/using-goosehints.md`](diffhunk://#diff-da23e59bb493adae010b24d49c44a73fe715f2afb0582a4c1dd947246c412696L43-R43): Escaped curly braces in the include directive to ensure proper rendering.
> fix: add escaped characters in goosehint docs

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/commands/expected_config.rs
- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/profile/profile.rs
- crates/goose-cli/src/profile/profile_handler.rs
- crates/goose-cli/src/profile/provider_helper.rs
We no longer use processor and accelerator models, we just use one `model`. The cli and profiles had not been updated with this so this PR fixes that, replacing all references to them.
**Incompatibilty**
Existing profiles that do not have `model` in them will cause an error and require deleting the file (or fixing) and recreating using /configure.
If no profile exists, no errors appear.
> Replace all processor/accelerator with model including in profile

- crates/goose-cli/Cargo.toml
- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/prompt/mod.rs
- crates/goose-cli/src/prompt/prompt.rs
- crates/goose-cli/src/prompt/rustyline.rs
- crates/goose-cli/src/session/session.rs
Rustyline single line prompt survives pasting content much like the original python version.
I've made it possible to use GOOSE_INPUT env to specify either the cliclack or rustyline prompt version for people testing.
> [cli] Adds rustyline as the default input method. Configurable via GOOSE_INPUT env.

- .github/workflows/ci.yaml
- .github/workflows/license-check.yml
With these changes the CI and license check workflows will also run when PRs are merged on the main branch, this way we can ensure the main branch is also covered.
> ci: Add CI to main pushes

- .github/workflows/ci.yaml
- crates/goose-cli/src/commands/expected_config.rs
- crates/goose-cli/src/main.rs
- crates/goose-cli/src/profile/provider_helper.rs
- crates/goose-server/src/configuration.rs
- crates/goose-server/src/state.rs
- crates/goose/src/providers.rs
- crates/goose/src/providers/configs.rs
- crates/goose/src/providers/factory.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/tests/providers.rs
feat: This PR migrates the Ollama provider from Python to Rust implementation.
Key changes include:
- Implemented OllamaProvider with async/await support
- Added spawn_blocking for health checks
- Implemented comprehensive test suite including:
- Unit tests with mocks
- Integration tests with real Ollama server
- Error case testing
- Added integration test feature flag
- Maintained parity with Python implementation
Test Plan:
1. Unit tests can be run with:
\`\`\`bash
cargo test --package goose --lib providers::ollama::tests
\`\`\`
2. Integration tests (requires running Ollama server) can be run with:
\`\`\`bash
cargo test --package goose --lib providers::ollama::tests --features integration
\`\`\`
Migration Details:
- Ported all functionality from …
> feat: migrate the ollama provider from python to rust

- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/prompt/cliclack.rs
- crates/goose-cli/src/prompt/rustyline.rs
- crates/goose-cli/src/prompt/thinking.rs
It's important users can always see the full bash command being run in order to know what it happening and have a chance to abort. To do this I added a custom renderer for the bash developer system tool that does not truncate the shell command.
Old
New
There are a few other minor changes in this PR as a result of running `cargo fmt` and `cargo clippy --fix`.
> Always render bash commands

- crates/goose-cli/src/main.rs
- crates/goose/tests/providers.rs
Following the same pattern as other provider integration tests so that we can run `cargo test` completely locally even if we don't have ollama installed.
> Skip ollama intergration test if no ollama env set

- .github/workflows/ci.yaml
- tests/cli/test_session.py
- Locks the UV version according to [their docs](https://docs.astral.sh/uv/guides/integration/github/#installation)
- Fixes the lint complain in the `test_session.py` file
> ci: Lock CI uv version to 0.5.4 and fix file test_session.py format

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/GooseResponseForm.tsx
Should be better at detecting readyness and questions/options (And not notifying over and over)
> fix: notification questions improvements

- crates/goose-cli/src/main.rs
Support pipes and/or text input. Usage:
```
echo "say whats for dinner in japanese" | cargo run --bin goose -- run
```
--- 
```
cargo run --bin goose -- run -t "say hello in japanese"  
```
> feat: support stdin and text input in cli

- ui/desktop/src/components/Input.tsx
- ui/desktop/src/components/UserMessage.tsx
adding ability for the input to be multiline and resize for content to a limit
https://github.com/user-attachments/assets/5ae6cafc-d7a1-4842-a5cc-76b277eeee98
> [feat]: Made input resizable + newline support

- crates/goose-server/src/routes/reply.rs
- crates/goose/src/developer.rs
This PR makes it so that interrupts to the `agent.reply` stream kills the running the bash process if there is one. Essentially it is relying on resources being cleaned up when the stream is cleaned up (leaves scope). So its a shortish term solution that is ok given the majority of systems will be network calls in the future and the shell commands are the most important to be killing atm. To make this work required 2 changes:
- Switch from std::process::Command to tokio::process::Command for running bash commands as this has an option to [kill_on_drop](https://docs.rs/tokio/latest/tokio/process/struct.Command.html#method.kill_on_drop) which allows it to be killed when the parent scope is cleaned up.
- In the goose server use a timeout every 500ms on the stream to detect when the client …
> Interrupt running shell tool commands

- src/goose/synopsis/moderator.py
- src/goose/toolkit/developer.py
- src/goose/utils/goosehints.py
- tests/toolkit/test_developer.py
Recursively resolve `.goosehints`; that is to say, if you have the tree below:
```
.
└── foo
├── .goosehints
└── bar
└── .goosehints
```
and run `goose` from within `foo/bar`, you'll get `foo/.goosehints` plus `foo/bar/.goosehints`. Continues to respect `~/.config/goose/.goosehints` files as well.
Adds a unit test.
> feat: recursively resolve `.goosehints` files

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/main.ts
> feat: use mac main menu

- crates/goose-cli/src/agents/mock_agent.rs
- crates/goose-cli/src/prompt.rs
- crates/goose-cli/src/prompt/cliclack.rs
- crates/goose-cli/src/prompt/rustyline.rs
- crates/goose-cli/src/session.rs
Implemented based on the [old python version](https://github.com/block/goose/blob/main/src/goose/cli/session.py#L248).
Behavior on interrupt:
- If last message is a user message then remove it and inform the user
- If there were tool requests in the last message, then add 'interrupted' tool response messages as a new message
Other changes:
- a bit of plumbing to enable mocking of the prompt to test what messages were being shown to the user.
> [cli] On interrupt repair messages

- crates/goose-cli/src/commands/expected_config.rs
- crates/goose-cli/src/profile.rs
The concept of 'recommended' provider doesn't make sense as the decision is based on use case and a collection of tradeoffs (cost, speed, access) etc.
Before
After
> fix: During configure remove 'recommended' from provider descriptions

- crates/goose-cli/src/session.rs
When the interrupt came after a tool result but before the next assistant message the rewrite code would see the last message (tool result) with user role and remove it. This is the correct behavior if it was an actual user message but not for a tool result as it causes a mismatch in requests-results making the message request invalid.
This PR stops that behavior and adds a assistant message explaining the the tool calls were interrupted, what would the user like to do next.
> fix: Handle interrupt after tool response but before assistant message

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/MoreMenu.tsx
Loosing context is a common complaint, and also discoverability of new session or open dir:
> feat: show context and menu

- ui/desktop/src/ChatWindow.tsx
When the user clicks cancel while goose is working:
The user message will be removed. Ideally we put the content back into the input box but calling `setInput` was breaking everything so I've deferred that aspect.
Each tool call gets marked as interrupted, providing context to the user and ai
> feat: [gui] cancel manipulates message history

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/Input.tsx
@alexhancock this stops it triggering a full chat re-calculation on every single keystroke, as there is no need. Can have input work out and manage its own state.
> fix: speed improvement

- crates/goose-cli/src/main.rs
- crates/goose-cli/src/profile.rs
If you run 'goose' without any commands, improve messaging to help first time use.
Old: 
```
No command provided
```
New:
```
No command provided - Run 'goose help' to see available commands.
```
New when the user does not yet have a profile file:
```
No command provided - Run 'goose help' to see available commands.
Run 'goose configure' to setup goose for the first time.
```
> fix: improve 'no command provided' error

- docs/blog/posts/2024-11-22-screenshot-driven-development.md
- mkdocs.yml
adding social plugin for our blog post, so that when the link is shared there is always an image and description associated with it. 
Removed the manual `html` and now we're utilizing the `social-plugin`, going forward the `social` section needs to be added to the head of each blog post: 
```
---
draft: false
title: "Screenshot-Driven Development"
date: 2024-11-22
authors:
- rizel
categories:
- Web Development
social:
cards_layout_options:
title: "Screenshot-Driven Development"  
description: "AI Agent uses screenshots to assist in styling."
background_image: "https://block.github.io/goose/blog/images/screenshot-driven-development-blog/screenshot-driven-development.png" 
---
```
---
- …
> docs: adding social plugin for blogs

- crates/goose-cli/src/commands/configure.rs
Old behavior: You can see a placeholder text but you cannot just press return to use it.
New behavior: The provider and model option has placeholder text with '(default)' after it. Just pressing return selects that.
> fix: configure allows selecting the suggested option with return

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/main.rs
Allows running configure with all selections pre-specified, therefore requiring no intervention other than keychain questions.
`goose configure -n testcli -p databricks -m goose`
Change: I changed the profile short option from -p to -n so it didn't conflict with 'provider' short name.
> feat: Add cli options for configure to specify provider and model

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/main.ts
- ui/desktop/src/preload.js
Current behavior is that if you click open a dir from bottom left, then it will open a new window, vs replacing current one which hasn't been used. This fixes that. If user has interacted, it doesn't replace, but will open a new one
(tracks messages to set a tainted flag via react hooks)
cc @Kvadratni @alexhancock
> fix: replace empty window

- docs/blog/posts/2024-11-22-screenshot-driven-development.md
- mkdocs.yml
- overrides/social-meta-inject.html
The `social` plugin for MkDocs is enabled and working  however, since we are not sponsors, we do not have access to the `Insiders` features. This limitation makes it impossible for us to use the `background_image` and a few other features. Leaving us with a default social card that looks like this: 
which isn't desirable, and will impact our social media engagement. 
I'm implementing a method to inject custom meta tags into the `<head>`  of our pages. This approach allows us to choose a `background_image` and other meta properties directly in the blog post front matter, overriding the image the `social` plugin is creating.
I wasn't able to fully test this locally, hopefully with this merge we will get the desired output. 
The **second solution** I tried was the standard approach of adding …
> docs: social card meta inject method

- docs/blog/posts/2024-11-22-screenshot-driven-development.md
- mkdocs.yml
- removing `social` and placing `html` inside the `frontmatter`
---
- https://app.asana.com/0/0/1208938177681176
> docs: testing out putting html in `frontmatter`

- crates/goose-cli/src/prompt.rs
- crates/goose-cli/src/prompt/cliclack.rs
- crates/goose-cli/src/prompt/renderer.rs
- crates/goose-cli/src/prompt/rustyline.rs
Three things changed for the cli prompts:
- Extracted common output rendering code for cliclack/rustyline into `renderers.rs` to make it easier to evolve them both.
- Added an env var `GOOSE_CLI_THEME` to allow specifying light or dark theme before opening the cli (still defaults to dark)
- Added an env var `GOOSE_CLI_MIN_PRIORITY` to allow overriding the priority filter, useful for debugging when you want to see everything instead of having 0.0 priority items hidden.
> Extract common renderings

- crates/goose/Cargo.toml
- crates/goose/benches/tokenization_benchmark.rs
- crates/goose/src/agent.rs
- crates/goose/src/developer.rs
- crates/goose/src/memory.rs
- crates/goose/src/models/message.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/openai.rs
- crates/goose/src/providers/utils.rs
- crates/goose/src/systems/goose_hints.rs
- crates/goose/src/systems/mod.rs
- crates/goose/src/systems/resource.rs
- crates/goose/src/systems/system.rs
- crates/goose/src/token_counter.rs
- crates/goose/tests/systems.rs
Changes:
- adds Resource object (from go/mcp) 
- system status returns resources 
- resources can get trimmed based on approx token counts
- benchmarking scripts for tokenization (time taken to compute increases linearly based on # tokens)
TODO: 
- model context limit is hardcoded but this will vary based on the provider
> feat: adding Resource objects, System.status to return list of Resources and trim when needed

- crates/goose/src/developer.rs
- ui/desktop/src/main.ts
Adds a tool to enumerate open windows, which allows screen capture of a specific window based on vague description. Whole screen capture I found didn't work well with multiple monitors and not at all if I wanted something specific. 
asking goose to match a design and iterate:
> fix: screenshot windows

- docs/blog/posts/2024-11-22-screenshot-driven-development.md
- mkdocs.yml
Cleaning up our nav bar to only show `blog` and have table of contents show once you're inside `blog/index.md`
> docs: updating blog nav bar

- crates/goose-cli/Cargo.toml
- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/main.rs
- crates/goose-cli/src/session.rs
- crates/goose-cli/src/test_helpers.rs
Copying the default python goose behavior where the latest session file is used when resuming a session when no session name is provided.
Note also added a `run_with_tmp_dir` to manage temporary profile and session files and the HOME env variable used for those.
> [cli] Resumes most recent modified session if no session name provided

- crates/goose/src/developer.rs
Did a quick check of exploring files in the java monorepo (signal-lib, and some other random ones with large files), and able to catches really large files (>2MB) and those with large number of chars. With large files it looked at, it was able to detect it was an encoded file (*.chunk.js) and say it's not readable so no point in reading it, and for those with large number of chars, it was able to use head/tail to read it and summarize them.
> Raise error if viewing a file greater than 2MB

- crates/goose-cli/src/prompt/rustyline.rs
Allows users to use Up and Down arrows to navigate through command history in the rustyline cli in case they want to reuse something they sent before.
> Adds command history to rustyline cli

- crates/goose-cli/Cargo.toml
- crates/goose-cli/src/agents/agent.rs
- crates/goose-cli/src/agents/mock_agent.rs
- crates/goose-cli/src/log_usage.rs
- crates/goose-cli/src/session.rs
- crates/goose-cli/src/test_helpers.rs
- crates/goose-server/src/routes/reply.rs
- crates/goose/Cargo.toml
- crates/goose/examples/databricks_oauth.rs
- crates/goose/examples/image_tool.rs
- crates/goose/src/agent.rs
- crates/goose/src/providers.rs
- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/base.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/mock.rs
- crates/goose/src/providers/model_pricing.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/src/providers/openai.rs
- crates/goose/src/providers/utils.rs
Adds cost to session.log. We can update the format later just getting the data piped through.
```json
{"session_file":"~/.config/goose/sessions/yoyqaq3e.jsonl","usage":[{"model":"claude-3-5-sonnet-20241022-v2:0","usage":{"input_tokens":2067,"output_tokens":204,"total_tokens":2271},"cost":"0.009261"}]}
{"session_file":"~/.config/goose/sessions/hao4empo.jsonl","usage":[{"model":"gpt-4o-2024-08-06","usage":{"input_tokens":2749,"output_tokens":41,"total_tokens":2790},"cost":"0.0072825"}]}
```
Adds costs for models.
Instead of providers collecting usage and the agent asking for it, the provider returns usage (as it already did) to the agent along with the cost on each 'complete' call. The agent collects all usages (which now includes cost). This keeps providers with less state and also makes …
> Adds session cost to goose.log

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/profile.rs
- crates/goose-cli/src/test_helpers.rs
- crates/goose-server/src/configuration.rs
- crates/goose-server/src/routes/reply.rs
- crates/goose-server/src/state.rs
- crates/goose/examples/image_tool.rs
- crates/goose/src/agent.rs
- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/base.rs
- crates/goose/src/providers/configs.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/mock.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/src/providers/openai.rs
- crates/goose/tests/providers.rs
This PR adds model specific configuration and updates the `goose-cli` and `goose-server` crates to use the updated Provider configuration and handle new configuration
- Introduce a new `ModelConfig` struct that is composed into each `Provider` specific config
- add support for configuring `context_limit` + `estimate_factor` , `temperature` and `max_tokens`
- `context_limit` has some defaults for known models set during [`ModelConfig::new()` construction time](https://github.com/block/goose/blob/kalvin/model-context-limits/crates/goose/src/providers/configs.rs#L54-L69).
- order of preference: `an explicitly set limit > default known model limit > DEFAULT_CONTEXT_LIMIT (128_000)`
- Refactored provider configurations to embed the `ModelConfig` struct and updated relevant uses of the model …
> feat:model-specific-configuration

- docs/guidance/using-goose-free.md
- mkdocs.yml
This pull request includes a new guide on using Goose for free and updates the navigation in the documentation to include this new guide.
* [`docs/guidance/using-goose-free.md`](diffhunk://#diff-06cc60c11c3e49f13ed3369e19d986eb5551045f1d7dfff023c2d5404efc9ec6R1-R39): Added a new guide detailing how to use Goose for free, including instructions for using Google Gemini and noting current limitations.
* [`mkdocs.yml`](diffhunk://#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R122): Updated the navigation to include the new "Using Goose for Free" guide under the Guides section.
> docs: Add using goose free guide

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/FlappyGoose.tsx
Wanna kill time while goose is thinking? 
I got you covered fam:
https://github.com/user-attachments/assets/9d2638af-7eb5-4d4e-9cc0-40dfea6fb997
> feat: flappy goose easter egg

- .github/workflows/cli-release.yml
- .gitignore
Note that I can't really test this, but I successfully use something similar in an existing project.
> feat: build and release binaries to GH releases

- ui/desktop/src/main.ts
this will open up goose to dir where you last were cc @Kvadratni @alexhancock
> tiny change to use most recent in stack

- ui/desktop/eslint.config.js
- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/LoadingGoose.tsx
Before:
* had to manually scroll down to the flying bird gif if user message is very long
* had to manually scroll down to the flying bird gif after in-line link previews
* had to manually scroll past tool output bubbles 
After
* always autoscrolls to the bottom so user can see the flying bird gif immediately after pressing enter
> fix: Ldelalande/fix scroll

- .github/workflows/ci.yaml
- .github/workflows/cli-release.yml
- crates/goose-cli/Cargo.toml
- crates/goose/Cargo.toml
- crates/mcp-client/Cargo.toml
WIP to see if we can use rust-tls instead of openssl on linux and other platforms, as it is more consistent and may improve performance and portability cc @lifeizhou-ap
> fix: use rust tls

- crates/mcp-core/src/protocol.rs
- crates/mcp-server/src/main.rs
- crates/mcp-server/src/router.rs
Instructions describe how to use the server and its features - its part of the initialization phase
https://github.com/modelcontextprotocol/specification/blob/8008e38dc7180acdc95dc6762ea6b92a7976f174/schema/schema.ts#L175
in the protocol, instructions are optional but we make it required in this sdk
> Adds 'instructions' field to InitializeResult

- Justfile
- crates/goose-server/src/state.rs
export GOOSE_SERVER__MEMORY=true
cc @Kvadratni
> conditionally load memory system in goose server

- ui/desktop/src/components/Input.tsx
In the [Goose UI improvements list ](https://docs.google.com/document/d/1vRTSvTGejzLHM6t6SBxN74iABpPaWa6vQ72tvaUExek/edit?usp=sharing), there's a task to make the stop button more obvious, so I:
- Added a visible background to the stop button in both light and dark modes
- Added hover state for better interaction feedback
**Let me know if I should modify the colors**
Light indigo background (`bg-indigo-100`) with indigo text (`text-indigo-600`)
Reduced opacity (`hover:opacity-50`)
Indigo background (`dark:bg-indigo-800`) with light indigo text `text-indigo-200`
Reduced opacity (`hover:opacity-50`)
> fix: Make stop button more obvious

- crates/goose-server/src/configuration.rs
- crates/goose-server/src/routes/reply.rs
- crates/goose/src/providers.rs
- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/base.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/google.rs
- crates/goose/src/providers/groq.rs
- crates/goose/src/providers/mock.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/src/providers/openai.rs
- crates/goose/src/providers/openai_utils.rs
Follow up PR for https://github.com/block/goose/pull/494
Changes:
- Encapsulate the concat_tool_response_content by delegating functions
- Added the context_limit and estimate_factor in groq and google provider config
- Moved get_usage in the traits
> refactor: move get_usage to provider trait

- ui/desktop/src/components/MoreMenu.tsx
Choosing Open Directory or New Session in the More Menu was not working because `handleAction` is not defined.
https://github.com/user-attachments/assets/1319a61d-adab-460f-87b4-3e7e330b3c41
Remove handleAction from the onClick because that wrapper is unnecessary, so now it works.
https://github.com/user-attachments/assets/1af8f3af-58ed-4184-bdd7-3b916f8bbf82
> fix: Broken open directory and new session buttons in more menu

- crates/goose/src/agent.rs
TokenCounter takes about a second to instantiate causing a latency hit every time prepare_infernece is called. This was causing a significant latency hit on every agent interaction.  This PR moves that the instantiation to the Agent struct to minimize this hit
> Latency issue fix with prepare_inference

- ui/desktop/src/components/ApiKeyWarning.tsx
- ui/desktop/src/main.ts
- ui/desktop/src/utils/binaryPath.ts
`goosed` bombs now without valid config, so this change conditionally starts `goosed` based on the presence of valid config. It fixes the app from crash looping without launching a window, and instead now shows the "Credentials Needed" screen as expected.
> [app] Conditionally start goosed based on valid config

- crates/goose-mcp/src/developer/mod.rs
forgot to update these 
here's the original [tools/instructions](https://github.com/block/goose/blob/b3b6cadab5b3648e5e5ec234f1efa509534b05a9/crates/goose/src/developer.rs#L123)
the new one is missing stuff (e.g. compare [this](https://github.com/block/goose/blob/b3b6cadab5b3648e5e5ec234f1efa509534b05a9/crates/goose/src/developer.rs#L196) (old) to [this](https://github.com/block/goose/blob/v1.0/crates/goose-mcp/src/developer/mod.rs#L68) (new))
> fix: update instructions

- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/default.rs
- crates/mcp-client/examples/sse.rs
- crates/mcp-client/examples/stdio.rs
- crates/mcp-client/examples/stdio_integration.rs
- crates/mcp-client/src/client.rs
currently, goose agent hangs when we try to list tools or resources on a server that doesn't support that capability. for example: 
`mcp-server-git` server capabilities: 
```
{ prompts: None, resources: None, tools: Some(ToolsCapability { list_changed: Some(false) }) }
```
instructions on testing:
1. build all the crates with cargo
2. run goosed - `./target/debug/goosed agent`
3. open a terminal and add mcp server
```
curl --request POST \
--url http://localhost:3000/systems/add \
--header 'Content-Type: application/json' \
--data '{
"type": "Stdio",
"cmd": "uvx",
"args": ["mcp-server-git"]
}'\'''
```
4. verify goose has access to tools 
```
curl --request POST \
--url http://localhost:3000/ask \
--header 'Content-Type: application/json' \
--data '{
"prompt": "what tools & resources do …
```
> fix: check server capability when client sends requests

- crates/goose/src/agents/capabilities.rs
sanitize the server name response from the MCP servers, this is propagated throughout the agent's usage and eventually into the tool call to the LLMs
a couple of the example servers use `example-server/$NAME` and that currently breaks goose the error is a `Error: Request failed: 400 Bad Request` and digging into it you eventually get a cryptic 
```
"x-amzn-errortype": "ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/"
```
Both [anthropic](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#specifying-tools) and [openai](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools) have the same format:
>  The name of the tool. Must match the regex `^[a-zA-Z0-9_-]{1,64}$`
*note:* this does not handle the tool names nor the char limit, will …
> fix: sanitize server names for passing into model tool calls

- crates/goose-mcp/src/developer/mod.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/default.rs
- crates/mcp-core/src/resource.rs
MCP servers (such as gdrive) list out 100s of files so reading each file in the agent loop leads to context limit exceeded errors. we make this change to only read 'active' files, i.e. files that have been viewed by the user using the developer system. It's unclear whether this will work well with other MCP servers cause this requires other MCP servers to use the priority annotation on the resource as well which may be less widely used.
> feat: read only active resources in the agent loop

- crates/mcp-client/src/transport/stdio.rs
when you ctrl-c from a `goose session` the ctrl-c signal is propagated to the child processes, set a different process_group to avoid that
> feat: set process_group(0) on stdio systems to avoid ctrl-c handling

- crates/goose-server/src/routes/reply.rs
- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/base.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/google.rs
- crates/goose/src/providers/groq.rs
- crates/goose/src/providers/mock.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/src/providers/openai.rs
- crates/goose/src/providers/openrouter.rs
Adding in moderation for user inputs.
- A Moderation trait is added to the base Provider struct along
- Update the base provider complete method to make a concurrent request to both the moderation and LLM endpoint. If moderation fails, we error out and abort the LLM completion if the request is still in flight. If moderation passes, we wait for the LLM response and continue as normal
- Only moderates on the latest User message
- Implemented moderation for the OpenAI provider using the openai's moderation endpoint, as an example
> Add base moderation to Providers

- crates/goose-mcp/src/developer/mod.rs
- crates/goose-mcp/src/developer2/mod.rs
Some command behavior, notably ripgrep, depend on if stdin is present. Not setting it here led to rg occasionally hanging waiting for input
> fix: Set stdin to null in shell/bash tools

- crates/goose/src/agents/capabilities.rs
- crates/mcp-client/examples/clients.rs
- crates/mcp-client/examples/sse.rs
- crates/mcp-client/examples/stdio.rs
- crates/mcp-client/examples/stdio_integration.rs
- crates/mcp-client/src/client.rs
- crates/mcp-core/src/protocol.rs
- crates/mcp-server/src/router.rs
https://spec.modelcontextprotocol.io/specification/2024-11-05/server/utilities/pagination/
we currently do not support `prompts/list` or `resources/templates/list`
* update the protocol to include `nextCursor`
* update goose to paginate over `tools/list`
> feat: add pagination support for tools/list and resources/list

- crates/goose-server/src/routes/reply.rs
- crates/goose/src/providers/base.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/google.rs
- ui/desktop/src/ChatWindow.tsx
Add moderation for Databricks provider. 
For moderation in Databricks, there is some setup required for end users. Users will need to create an external endpoint called `moderation`. This endpoint needs to have guardrails enabled through AI Gateway, with a minimum of the `input safety` box checked. Other guardrails like pii and keywords can also be enabled. Only user messages will be sent to this endpoint, not the whole history, but it's good practice to pick the cheapest/fastest model to minimize latency and cost.
This PR also adds ModerationError and updates the reply method in goose-server to add ErrorPart's for the Vercel protocol, which gets used for moderation errors.
> Add Databricks moderation

- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/system.rs
- crates/mcp-client/examples/clients.rs
- crates/mcp-client/examples/sse.rs
- crates/mcp-client/examples/stdio.rs
- crates/mcp-client/examples/stdio_integration.rs
- crates/mcp-client/src/transport/sse.rs
- crates/mcp-client/src/transport/stdio.rs
tested with [Tavily MCP Server](https://mcpserver.cloud/server/tavily-mcp-server) for web search:
1. build and run goosed: `cargo run --bin goosed -- agent`
2. add system with secret. you need to replace with free API key that you can get here: https://app.tavily.com/home
```
curl --request POST \
--url http://localhost:3000/systems/add \
--header 'Content-Type: application/json' \
--data '{
"type": "Stdio",
"cmd": "uvx", 
"args": ["mcp-tavily"], 
"envs": {
"TAVILY_API_KEY": "REPLACE_SECRET_HERE"
}
}'
```
3. ask question that requires using the system's tools
```
curl --request POST \
--url http://localhost:3000/ask \
--header 'Content-Type: application/json' \
--data '{
"prompt": "can you do a search for recent news on LA wildfires - give me a timeline of events if possible. only provide …
```
> feat: env and secrets configuration for mcp server

- crates/goose/Cargo.toml
- crates/goose/src/token_counter.rs
Right now the goose CLI doesn't start immediately (about 1.4s) because it has to load tokenizers. This makes it immediately responsive
> feat: quick spinner while loading tokenizers

- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/MoreMenu.tsx
- ui/desktop/src/utils/urlUtils.ts
Fixes a few things we wanted to to get a build out today
* Removes link previews when the host is `localhost` or `127.0.0.1`
* Makes link previews `flex-wrap` so it doesn't make the chat window content too wide for the screen when there are a lot of links
* Fixes an issue where we matched uris in markdown form `[uri](uri)` twice
* Temporarily disables choosing agent version in the `MoreMenu` until we can determine where to put it in the new settings screen
* Temporarily disables the prompting of the user with plans/select options per @baxen mentioning it still doesn't always display at the correct times
> fix: Various improvements and fixes to rough edges in the UX

- crates/mcp-server/src/lib.rs
This increases the BufReader's capacity to `2 * 1024 * 1024` (`2MB`) to handle very large message sizes.
With the default of `8 * 1024` (https://doc.rust-lang.org/std/io/struct.BufReader.html) we saw truncated json-rpc messages coming across to the mcp-server.
couldn't have figured this out without @salman1993, thanks for all the help!
> fix: update BufReader capacity to 2MB

- .gitignore
- crates/goose/src/agents/mod.rs
- crates/goose/src/agents/system.rs
- crates/goose/src/agents/truncate.rs
Adds an agent that handles exceeding the context token-limit by truncation, where truncation is implemented as de-queuing the earliest messages from conversation history until total history is under the context limit. 
an error is returned if truncation completes and no history remains, or the user is actively attempting to send a message that by-itself is too large.
accessible via 
`cargo run --bin goose --session --agent truncate`
> feat: add a truncating agent

- crates/goose-cli/src/log_usage.rs
- ui/desktop/src/goosed.ts
- ui/desktop/src/main.ts
this simply closes the goosed process when the window is finished (which it should have).
> chore [v1.0]: tidy up processes when session closes

- crates/mcp-client/src/client.rs
remove the bare `.unwrap()` when generating server name and default to `""` if we don't have `server_info` for some reason
> remove use of bare unwrap() in error propagation

- crates/goose/src/providers/anthropic.rs
Enable prompt cache for Anthropic following https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#how-prompt-caching-works.
Generally, we add `"cache_control": {"type": "ephemeral"}` into tool, system and message sections. The cache hit can be verified with the usage [response](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#tracking-cache-performance), like
```
usage: {
cache_creation_input_tokens: 1479
cache_read_input_tokens: 0
input_tokens: 4
output_tokens: 78
}
```
And currently, “ephemeral” is the only supported cache type, which corresponds to this 5-minute lifetime.
Cost saving: From the [pricing](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#pricing), 
1. Cache write tokens are 25% more expensive than base input tokens
2. …
> feat: enable prompt cache for anthropic 

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/Input.tsx
- ui/desktop/src/components/MoreMenu.tsx
- ui/desktop/src/components/settings/KeyItem.tsx
- ui/desktop/src/components/settings/Settings.tsx
Reduction of "containers". This results in a flatter UI. And makes the input clearer to discern. 
Examples:
| Before | After |
|--------|--------|
| <img width="745" alt="Screenshot 2025-01-14 at 4 46 14 PM" src="https://github.com/user-attachments/assets/074febd8-987a-438a-9026-f83c8253d935" /> | <img width="750" alt="Screenshot 2025-01-14 at 4 46 20 PM" src="https://github.com/user-attachments/assets/30caa5ea-aab6-4d74-a5ad-8ffb6f8c42eb" /> |
| <img width="749" alt="Screenshot 2025-01-14 at 4 47 07 PM" src="https://github.com/user-attachments/assets/8079e06b-028e-46fa-ac94-86db8e841b93" /> | <img width="749" alt="Screenshot 2025-01-14 at 4 47 12 PM" src="https://github.com/user-attachments/assets/3718f7c9-2ddb-47f4-9bd8-3d794dd22900" /> |
| n/a | <img width="750" alt="Screenshot …
> styles: de-containerize the UI

- crates/goose-mcp/src/google_drive/mod.rs
Set priority of google drive text to `0.1`, the UI then hides the entire body in an `▶ Output` section.
CLI output stays the same.
> feat: set priority of google drive text as 0.1

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/config.ts
- ui/desktop/src/utils/providerUtils.ts
we had a small rename on the rust side that this captures Also used the new terminology for the ts methods and cleaned them up a bit. Still will need to rename systems to extensions later through the rust code
> hotfix: update system config payloads

- download_cli.sh
- download_cli.sh failed to configure goose with '-n default'. We probably don't wanna start off with "goose configure" cause you have to approve in Mac system security settings first and this makes the flow confusing
- pop up for the download_cli script will look like this. hard to know that this is happening cause it needs an approval in security settings
> fix: remove configure args '-n default' which no longer exists

- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/ollama.rs
Ollama and databricks need host configured and stored
> fix: patch host config handling

- crates/goose-cli/src/prompt/renderer.rs
- crates/goose/src/agents/capabilities.rs
previously any server names that also include `__` or any sequence of chars that were sanitized into `__` would fail during tool invocations since we split on `__` for prefixing
this change updates the handling of `__` to use rsplit, and to extract the tool call first, and handle everything else as the mcp client name that is returned by the mcp server (after sanitization)
> fix: update sanitize to strip whitespace, update handling of __ prefix

- crates/goose-mcp/src/developer/mod.rs
Adds back in the tests that were previously in https://github.com/block/goose/blob/23987f7c892e31b10445488149dcc47680f20c45/crates/goose-mcp/src/developer/mod.rs#L902-L1297 for tests that are still relevant.
`test_read_resource` - no longer relevant, since the router `list_resources` just returns an empty list and `read_resource` returns an empty string.
> test: reintroduce relevant developer mcp tests

- crates/goose-mcp/src/developer/mod.rs
- crates/goose/src/agents/capabilities.rs
- crates/mcp-core/src/protocol.rs
- crates/mcp-server/src/router.rs
Per Spec:
https://github.com/modelcontextprotocol/specification/blob/main/schema/2024-11-05/schema.ts#L646-L667
> /**
* Whether the tool call ended in an error.
*
* If not set, this is assumed to be false (the call was successful).
*/
isError?: boolean;
Was getting:
```
1. From Example Servers - Let's use the echo tool:
─── echo | example-servers_everything ──────────────────────────
message: Hello from the example server!
Execution failed: Serialization error: missing field `isError`
```
> fix: is_error is optional per MCP schema for CallToolResult

- crates/goose-mcp/src/memory/mod.rs
**Simplifies memory management**
- removes Resource usage
- loads existing global and project memories into system prompt. This allows memories to persist across sessions.
- adds a category="*" setting in order to remove/retrieve memories from all categories
**How memories works with this change:**
1. Global and project memories will be added to system prompt
2. Subsequent memory will be in the agent loop through tool calls
Memory lives in system prompt - this allows memories to persist across sessions
Memory lives in system prompt - this allows memories to persist across sessions
**Note:**
* Removing memories will not remove it from the system prompt during the session. We try our best to mitigate bringing up removed memories with _Note: if the user removes a memory that was previously …
> feat: simplify memory management

- .github/workflows/ci.yml
- crates/goose-mcp/Cargo.toml
- crates/goose-mcp/src/developer/mod.rs
- Also fix the unit tests by providing the working dir which can be used by std::env::current_dir()
- Use #[serial] instead of lock to avoid parallel test running.
> fix: use serial instead of lock to avoid parallel tests

- crates/goose-cli/src/commands/session.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/extension.rs
- crates/mcp-client/src/transport/stdio.rs
* Capture `stderr` instead of having it pipe back out to the main processes's stderr
* Use `tokio::select` to return when any of the concurrent operations return, in this case capture the process exit
* Capture the output of the subprocess's `stderr` on return and log it with `tracing::error`
* Prettify the error handling output for cli
* Move `eprintln` to `tracing::error`
When submitting a config/command like:
```yaml
extensions:
bad_cmd:
enabled: true
type: stdio
cmd: npx
args:
- this_is_not_real
curl \
-v \
-XPOST \
-H "Content-Type: application/json" \
-H "X-Secret-Key: test" \
http://localhost:3000/extensions/add \
-d'{
"type": "stdio",
"cmd": "npx",
"args": ["this_is_not_real"],
"env_keys" : []
}'
```
The cli/curl command would hang for `300` seconds, the default timeout setup when …
> capture process exit and stderr

- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/utils.rs
Ignore the payload in the error message when the providers have errors. Instead, we output them into the log file.
Before:
It will have the whole page in the CLI output
```
( O)> hello
◒  Caching cosmic calculations... 
2025-01-23T04:27:46.647350Z ERROR goose::providers::utils: Provider request failed with status: 400 Bad Request. Payload: {"max_tokens":4096,"messages":[{"content":[{"cache_control":{"type":"ephemeral"},"text":"hello","type":"text"}],"role":"user"}],"model":"claude-3-5-sonnet-latest","system":[{"cache_control":{"type":"invalid"},"text":"You are a general purpose AI agent called Goose. You are capable\nof dynamically plugging into new extensions and learning how to use them.\n\nYou solve higher level problems using the tools in these extensions, and can\ninteract with …
```
> fix: ignore payload in the CLI output if provider has error

- crates/goose-server/src/routes/extension.rs
Actually respond back to the caller with the error message (stderr if available) in the response body.
```
{
"error": true,
"message": "Failed to add extension configuration"
}
{
"error": true,
"message": "Failed to add extension configuration, error: Initialization(Stdio { cmd: \"uvx\", args: [\"this_is_not_real\"], envs: Envs { map: {} } }, McpServerError { method: \"initialize\", server: \"\", source: ServerBoxError(StdioProcessError(\"  × No solution found when resolving tool dependencies:\\n  ╰─▶ Because this-is-not-real was not found in the package registry and you\\n      require this-is-not-real, we can conclude that your requirements are\\n      unsatisfiable.\\n\")) })"
}
```
part of #694
> add error in /extensions/add response body

- crates/goose/src/agents/capabilities.rs
- crates/goose/src/config/extensions.rs
sanitize name of the extension before storing in various state within capabilities, and run the same sanitize on the name when attempting to remove the extension
> keep extension name consistent when inserting and removing from state

- crates/goose-mcp/src/developer/mod.rs
Add missing serial annotation to the test.
Re-ran 8 times and all looked good, should be less flaky now
> fix flaky unit test

- crates/goose/src/providers/databricks.rs
tiny change - openai format is required (even with anthropic models)
> hotfix: databricks uses openais format

- ui/desktop/src/components/ToolInvocations.tsx
previously content with no priority would output in its entirety by default, this changes for the following logic:
`(priority is defined && priority >= 0.5) OR its already expanded`: show it expanded
otherwise 
`if priority is NOT defined OR priority < 0.5` : minimize by default
> [UI] minimize content with no priority behind a dropdown

- crates/goose-mcp/src/developer/mod.rs
- crates/goose-mcp/src/nondeveloper/mod.rs
- ui/desktop/src/extensions.ts
* minor prompt tuning and pulling out a computer control tool for applescript 
* adds computer control ability (macos)
* fixing a flaky test
* fixing a typo in the extension description
> small fixes to ensure non dev toolkit can control things on mac

- crates/goose/src/agents/capabilities.rs
when we sanitize extension names, we should make it case-insensitive and lowercase the response as well
> feat: lowercase extension names when sanitizing

- ui/desktop/src/extensions.ts
This makes it so we use consistent name sanitization for all interactions with the add/remove extension endpoints, and fixes issues with enabling and disabling
> chore: Properly sanitize extension names on all interactions with add/remove

- crates/goose/src/providers/formats/openai.rs
- crates/goose/src/providers/utils.rs
* make `tool.description` a max of 1024 len string
* include `response.text()` response body from API call in debug tracing to find the errors easier
With `non-developer` extension we would get a `400 Bad Request` when using OpenAI.
The response body was:
```json
{
"error": {
"message": "Invalid 'tools[3].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 2028 instead.",
"type": "invalid_request_error",
"param": "tools[3].function.description",
"code": "string_above_max_length"
}
}
```
> Truncate OpenAI tool.description to 1024

- ui/desktop/src/components/settings/Settings.tsx
Small bugfix: we weren't allowing removal of extensions which were disabled
> fix: Make it possible to remove extensions which are disabled

- documentation/docs/guides/tips.md
- documentation/docs/installation.md
This PR improves the Goose documentation by adding tips on how to keep Goose updated for both the CLI and UI. The update ensures users are informed about the best practices to maintain the latest version of Goose, benefiting from new features, bug fixes, and performance improvements.
1. **Added update tips to the Installation Guide**:
- Included a `:::tip Best Practice` section in both CLI and UI installation instructions:
- `documentation/docs/installation.md`
2. **Updated the Tips Guide**:
- Enhanced the "Keep Goose updated" note to include:
- Instructions for updating the CLI via the installation script.
- Instructions for checking the [GitHub Releases page](https://github.com/block/goose/releases/stable) for Goose UI updates.
- `documentation/docs/guides/tips.md`
---
- To see the …
> Add Update Goose Tips to Docs

- documentation/docs/troubleshooting.md
This PR adds the **Context Length Exceeded Error**. It provides guidance for users on resolving the issue by breaking down input into smaller parts or leveraging `.goosehints` to provide detailed context.
1. Added a new section titled **Context Length Exceeded Error** in:
- `documentation/docs/troubleshooting.md`
2. Included a reference to the [Using Goosehints Guide][goosehints] to help users create and use `.goosehints` files for managing large contexts.
> Add troubleshooting guide tip 

- documentation/docs/guides/handling-llm-rate-limits-with-goose.md
This pull request updates the documentation to provide a more user-friendly guide for configuring OpenRouter with Goose. The most important changes include the addition of tabs for CLI and UI instructions and the removal of the previous environment variable setup instructions.
Documentation improvements:
* [`documentation/docs/guides/handling-llm-rate-limits-with-goose.md`](diffhunk://#diff-f2f9e26be6b67d9f24f7c261a2668df19ccd89703269aa3aad2c4a91f868f3d2L19-R41): Replaced the environment variable setup instructions with a tabbed interface providing separate instructions for configuring OpenRouter using the Goose CLI and Goose UI.
> Update rate limit guide

- crates/goose-mcp/src/nondeveloper/mod.rs
First pass at shortening `computer_control_tool`'s description to be under 1024 (OpenAI's tool description max length), this is currently at 1000.
> shorten NonDeveloper computer_control_tool description

- extensions-site/app/components/server-card.tsx
- extensions-site/app/mcp-servers.ts
- extensions-site/app/routes/detail.tsx
- extensions-site/app/routes/home.tsx
- extensions-site/app/types/server.ts
- extensions-site/public/servers.json
High level changes:
- updates the server.json list to the curated ones in [google sheet](https://docs.google.com/spreadsheets/d/11lKmnI4k_eCqwgZqnbPVcyAY-LkbYl4A4V3aeHEUi10/edit?gid=0#gid=0)
- for prompts that generated this, see #714 
UI changes:
- Adds a Built-in tag for built-in extensions
- Adds information for instructions on how to install from the settings page
- Only shows Install button for non-built-in extensions
- Gives higher priority for built-in extensions in the display sorting
- Loads servers.json file from `public/servers.json` file rather than remote version
> feat: generate server.json for extension site from google sheet

- .github/workflows/pr-comment-bundle-desktop.yml
The 2nd job is trying to use steps.command.outputs.continue from 1st job, and that isn’t allowed. We add outputs from the 1st job that gets reused
> fix: pr comment workflow by adding job output

- extensions-site/app/components/server-card.tsx
- extensions-site/app/mcp-servers.ts
- extensions-site/app/routes/detail.tsx
- extensions-site/app/utils/install-links.tsx
- extensions-site/public/servers.json
* fix links in the details page so goose can load extensions
* change 'nondeveloper' to computer controller 
* `servers.json`: update description in details card
* `servers.json`: fix github install command
> fix: extension page link fix, change nondeveloper to 'computer controller'

- .github/workflows/pr-comment-bundle-desktop.yml
if we don't add in the needs - `${{ needs.trigger-on-command.outputs.pr_number }}` is empty
github action doesn't inject outputs based on transitive dependency. tested this out here: https://github.com/block/goose/pull/775
> fix: add explicit dependency to pr-comment job 

- ui/desktop/src/utils/providerUtils.ts
In theory, we no longer need this delay as the agent should be ready to add extensions when `addAgent` resolves
> fix: Do not wait 5s before adding extensions to agent

- crates/goose-cli/src/commands/configure.rs
Only an active env var can override this, which is still useful for installers
Fixes #787
> fix: suggest correct model on switch

- ui/desktop/src/components/settings/Settings.tsx
- ui/desktop/src/extensions.tsx
Otherwise if settings page was already open it would not immediately load the env vars dialog or render the new extension
> fix: send event to reload settings on link

- ui/desktop/src/bin/npx
- ui/desktop/src/bin/uvx
previously would use the global hermit cache on macos - which is ok, but can interfere if old/broken. This keeps it local to goose. Will use a bit more storage, however if the person is already using hermit elsewhere in theory.
> nit: set the hermit cache to be local to MCP

- download_cli.sh
```
curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | CANARY=true sh
```
> feat: allow canary in installer

- documentation/src/pages/index.tsx
- button links to Install page. the download icon is misleading
- button only encourages desktop download. we also have CLI option
> docs: changed home button text

- .github/workflows/bundle-desktop.yml
- .github/workflows/canary.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
adds `quick_test` input, which isn't used anywhere in this repo but can be useful to reuse this in internal release pipelines
> feat: add quick_test input in bundle-desktop workflow

- crates/goose-cli/src/commands/mcp.rs
- crates/goose-server/src/commands/mcp.rs
* also leave in support for `google_drive` for backward compatibility
* allow both `goose-cli` and `goose-server` to use both names
> feat: support googledrive as mcp server name

- documentation/docs/getting-started/providers.md
- documentation/docs/getting-started/using-goose-free.md
This pull request adds a new section to the `documentation/docs/getting-started/using-goose-free.md` file, providing instructions on setting up the DeepSeek-R1 model with Goose. The most important changes include adding the steps for downloading and configuring the DeepSeek-R1 model via Ollama and integrating it with Goose, both through the CLI and the Goose Desktop interface.
* Added a new section titled "DeepSeek-R1" that introduces the DeepSeek-R1 model and provides a warning about hardware requirements.
* Detailed CLI instructions for installing the `michaelneale/deepseek-r1-goose` model via Ollama and configuring it with Goose.
* Provided step-by-step guidance for configuring the DeepSeek-R1 model in Goose Desktop.
> docs: Add deepseek to free use guide

- documentation/blog/2025-01-28-introducing-codename-goose/index.md
- documentation/docs/guides/managing-goose-sessions.md
This pull request includes updates to the documentation for Goose, focusing on improving clarity and accuracy in the guides and blog posts. The most important changes include updating links for better navigation and correcting references to setup instructions.
* [`documentation/blog/2025-01-28-introducing-codename-goose/index.md`](diffhunk://#diff-0186c426b6019be76fdaa64d36f73aa9f7e8970aa3ad10f6114c5f0b4c9349c6L26-R26): Updated the link to the extensions directory to use a reference-style link for better readability.
* [`documentation/blog/2025-01-28-introducing-codename-goose/index.md`](diffhunk://#diff-0186c426b6019be76fdaa64d36f73aa9f7e8970aa3ad10f6114c5f0b4c9349c6R61-R63): Added a reference link definition for the extensions directory at the end of the document. …
> docs: quickfix broken links

- documentation/docs/getting-started/using-extensions.md
Making example of adding MCP server as an extension clearer
> docs: moving example

- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/UserMessage.tsx
Temporarily disabling link previews due to a layout issue. Will fix and re-enable soon after launch.
Before:
After:
> fix: Temporarily disable link previews as layout is borked

- crates/goose-cli/src/commands/configure.rs
we were previously just returning back up and never displaying the error to the user, instead we handle the error case and display the error along with the "retry" steps
> fix: catch errors in configure_provider_dialog and report the error upwards

- documentation/docs/getting-started/installation.md
- documentation/docs/quickstart.md
The Goose CLI installation script uses `bash` shell. (Note the `#!/usr/bin/env bash` shebang https://github.com/block/goose/blob/main/download_cli.sh#L1)
However, the documentation suggests piping the installation script to `sh` instead of `bash`.
On a number of Linux distributions (Debian, Ubuntu, etc.) `sh` is a symlink to `dash`, a more minimal shell that doesn't support certain `bash` features, like the `pipefail` option. https://github.com/block/goose/blob/main/download_cli.sh#L2
Attempting to run the installation script and piping it to `sh` as outlined in the docs will fail on Debian, Ubuntu, and other Linux distributions which symlink `sh` to `dash`:
```
$ curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | sh
sh: 2: set: Illegal option -o pipefail …
```
> docs: Use bash (not sh) for Goose CLI installation script one-liner

- crates/goose-cli/src/commands/configure.rs
- crates/goose-server/src/routes/secrets.rs
- crates/goose/src/providers/ollama.rs
- documentation/docs/getting-started/providers.md
- ui/desktop/src/components/settings/ProviderSetupModal.tsx
- ui/desktop/src/components/settings/api_keys/utils.tsx
- ui/desktop/src/components/settings/extensions/ConfigureBuiltInExtensionModal.tsx
- ui/desktop/src/components/settings/extensions/ConfigureExtensionModal.tsx
- ui/desktop/src/components/settings/extensions/ManualExtensionModal.tsx
- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
- ui/desktop/src/components/settings/providers/ConfigureProvidersGrid.tsx
- ui/desktop/src/components/welcome_screen/ProviderGrid.tsx
Allow setting ollama host during configuration
Test step:
1. Run `launchctl setenv OLLAMA_HOST "0.0.0.0:11111"` on mac and start run ollama
2. Check ollama ls: `OLLAMA_HOST=0.0.0.0:11111 ollama ls` 
3. Verify the ollama host by sending request:
4. 
```
curl http://localhost:11111/api/generate -d '{
"model": "qwen2.5",
"prompt":"Why is the sky blue?"
}'
{"model":"qwen2.5","created_at":"2025-01-29T02:53:09.321698Z","response":"The","done":false}
{"model":"qwen2.5","created_at":"2025-01-29T02:53:09.337099Z","response":" sky","done":false}
{"model":"qwen2.5","created_at":"2025-01-29T02:53:09.352554Z","response":" appears","done":false}
{"model":"qwen2.5","created_at":"2025-01-29T02:53:09.368318Z","response":" blue","done":false}
```
5.  Run the UI can test with host change
6. Run goose …
> feat: allow setting ollama host

- crates/mcp-client/examples/sse.rs
- crates/mcp-client/src/transport/sse.rs
should fix: https://github.com/block/goose/issues/893
works for these:
```
Base: http://localhost:8080/sse
Relative: /messages/?session=x2y3z
Expected: http://localhost:8080/messages/?session=x2y3z
-------------------------------
Base: http://localhost:8080/mcp/sse
Relative: /mcp/messages/xyz
Expected: http://localhost:8080/mcp/messages/xyz
-------------------------------
Base: http://localhost:8080/mcp/sse
Relative: messages/xyz
Expected: http://localhost:8080/mcp/messages/xyz
-------------------------------
Base: http://example.com/api/sse
Relative: /messages/xyz
Expected: http://example.com/messages/xyz
-------------------------------
Base: http://example.com/api/sse
Relative: messages/xyz
Expected: http://example.com/api/messages/xyz
-------------------------------
```
> fix: post endpoint url on sse endpoint event

- documentation/docs/getting-started/installation.md
- documentation/src/components/SupportedEnvironments.js
This pull request adds a new section to the installation documentation for Goose, providing detailed instructions on how to install and configure Goose CLI on Windows using the Windows Subsystem for Linux (WSL).
* [`documentation/docs/getting-started/installation.md`](diffhunk://#diff-1da95befef448a968841697bffcbb8f9c53f1238842a36a63444ca5d4ea0499aR51-R132): Added a new subsection "Installing on Windows via WSL" with step-by-step instructions for installing WSL, updating packages, installing Goose CLI, setting environment variables, and configuring Goose.
> docs: Goose on Windows via WSL

- .github/workflows/build-cli.yml
- .github/workflows/bundle-desktop.yml
- .github/workflows/canary.yml
- .github/workflows/release.yml
workflow succeeded: https://github.com/block/goose/actions/runs/13045348906
test release (draft) - tagged it as `test.1.0.1` : https://github.com/block/goose/releases/tag/untagged-fe0426d4b3b96b1ddc30
downloaded the CLI and App. looks like the version injections worked:
> feat: substitute version in CLI and Desktop App during release

- crates/goose/src/agents/truncate.rs
- crates/goose/src/token_counter.rs
- crates/goose/src/truncate.rs
* propagate and display any errors that come back from `truncate_messages` instead of ignoring them
* add a note that users should restart in a fresh session if they hit the context limit
* `self.token_counter.count_tokens(&msg.as_concat_text())` was only counting messages of type `Message::Text`, ignoring any `ToolResponse`s which tend to be a large amount of tokens
* use `self.token_counter.count_chat_tokens("", std::slice::from_ref(msg), &[])` to get a full count of the message tokens
* update `context_limit` calculation to subtract the total amount of `system_prompt` and `tools` tokens already in use
> fix: truncation agent token calculations

- documentation/docs/getting-started/installation.md
- documentation/docs/quickstart.md
- download_cli.sh
* allow users to set ` | CONFIGURE=false bash` when running the automated installer, to skip the interactive `goose configure` step
* add "Tip" sections to the quickstart/installation docs
* cleanup trailing whitespaces
see https://github.com/block/goose/issues/918
> feat: add CONFIGURE=false option in install script

- crates/goose-cli/src/commands/configure.rs
- ui/desktop/src/components/settings/providers/ConfigureProvidersGrid.tsx
- ui/desktop/src/components/welcome_screen/ProviderGrid.tsx
Also improve the CLI configuration by providing default value for ollama host
Test:
CLI configuration with default value: 
```
│
│  Configure Providers 
│
│  Ollama 
│
●  OLLAMA_HOST is already configured
│  
│  Yes 
│
◆  Enter new value for OLLAMA_HOST
│  http://localhost:11434 (default)
└  
```
without default value:
```
│
│  Configure Providers 
│
│  Databricks 
│
●  DATABRICKS_HOST is already configured
│  
│  Yes 
│
◆  Enter new value for DATABRICKS_HOST
│   
└ 
```
> fix: missing field in request

- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
remove the o1-mini suggestion from the "Add Model" page since it is not supported (see https://github.com/block/goose/pull/921)
> chore: remove o1-mini suggestion from UI add model view

- .github/workflows/canary.yml
- .github/workflows/ci.yml
- .github/workflows/pr-comment-bundle-desktop.yml
we need to clean up how we do versioning in the release, canary workflows in a later PR. `version` should not be required. if its not passed, it should be extracted from the repo.
> fix: temp fix to make CI workflow pass

- .github/workflows/canary.yml
per: https://semver.org/#spec-item-10, build metadata should be after `+` and not `.`
```
❯ cargo build
error: invalid leading zero in pre-release identifier
--> Cargo.toml:7:11
|
7 | version = "1.0.3-canary.0020123"
|           ^^^^^^^^^^^^^^^^^^^^^^
|
```
vs
```
❯ cargo build
Compiling goose v1.0.3-canary+0020123)
Compiling goose-mcp v1.0.3-canary+0020123 
```
> ci: per semver build metadata should be after +

- documentation/docs/getting-started/using-extensions.md
The `Fetch` extension has a conflict with the `Gemini` LLM. So, using a less problematic extension in the example of how to add an MCP server.
> docs: change MCP example to GitHub

- crates/goose-mcp/src/memory/mod.rs
- crates/goose/src/truncate.rs
We didn't have `remember_memory` the tool in the instructions explicitly. Explicitly tell llm provider to use the `remember_memory` tool to store the information.
> fix: explicitly add remember_memory tool in the instructions/system prompt

- ui/desktop/src/components/LinkPreview.tsx
- ui/desktop/src/components/settings/Settings.tsx
- ui/desktop/src/main.ts
This PR addresses the linked issue by forcing links to open in a new browser window, via an electron configuration change.
Tested by asking Goose variants of "give me a link|hyperlink|source to learn more about kadane" with the expectation being a response either solely or containing a clickable link, which, when clicked opens in a new browser window and not the primary electron window for Goose"
> feat: cfg electron to open links in new window

- .github/workflows/build-cli.yml
- .github/workflows/bundle-desktop.yml
- .github/workflows/canary.yml
- .github/workflows/ci.yml
- .github/workflows/pr-comment-bundle-desktop.yml
- .github/workflows/release.yml
- Justfile
* `Justfile` updates to help automate the release process, modeled after [goose python justfile release](https://github.com/block/goose/blob/eccb1b22614f39b751db4e5efd73d728d9ca40fc/justfile#L90-L122)
* `just release $VERSION` - use this to set the next version we want to release, will create a new branch and set the commit ready to go
* `just tag-push` once the above command has been run + pr merged, run this to set the newest tag and kick off the CI for release process
* removes setting the version based on the pushed tag and instead uses the version already committed, and we can follow https://github.com/block/goose/pull/967 for version bumping
* extract the version from `Cargo.toml` for the canary step 
* makes `version` an optional parameter for the re-usable workflows, will …
> ci: update release processes using Justfile, make reusable workflows have optional version param

- extensions-site/app/components/server-card.tsx
Adds links to github page for extension the Github stats on extension cards (https://github.com/block/goose/issues/791)
https://github.com/user-attachments/assets/ef359816-664f-4940-8372-1d0cb61ce0e9
> feat: Add link to github project on extension cards

- ui/desktop/src/bin/uvx
https://docs.astral.sh/uv/configuration/authentication/#custom-ca-certificates
>If client certificate authentication (mTLS) is desired, set the SSL_CLIENT_CERT
but we want:
> If a direct path to the certificate is required (e.g., in CI), set the SSL_CERT_FILE environment variable to the path of the certificate bundle, to instruct uv to use that file instead of the system's trust store.
> fix: use SSL_CERT_FILE to point to CA bundle, not for mTLS client cert

- documentation/docs/getting-started/providers.md
- documentation/docs/goose-architecture/goose-architecture.md
- documentation/docs/guides/tips.md
- documentation/docs/troubleshooting.md
Asked goose to point out and fix spelling errors in the documentation. I did not include any suggested grammatical changes that I thought were superfluous (It wanted to capitalize a lot of the documentation).
> docs: updated spelling in documentation

- Justfile
had `echo` when testing to ensure no false tags were pushed, forgot to remove it
> ci: run git tag commands when just tag-push

- .github/workflows/deploy-docs-and-extensions.yml
This pull request updates the GitHub Actions workflow to improve the deployment process for documentation and the extensions site. The main changes include adding caching for Node.js modules and conditional deployment to the `gh-pages` branch.
Improvements to deployment workflow:
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R8-R12): Added `pull_request` trigger to run the workflow when changes are made to the `documentation` or `extensions-site` directories.
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R26-R33): Added caching for Node.js modules in the `documentation` directory to speed up the workflow.
* …
> Improve docs & extensions deploy workflow

- documentation/docs/quickstart.md
The quickstart had a screenshot of the older desktop interface, which is no longer relevant.
> docs: remove old desktop screenshot

- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/LoadingGoose.tsx
- ui/desktop/src/components/ui/scroll-area.tsx
* Addresses #909 
* Pulls the automatic scrolling logic into the `ScrollArea` component with an optional `autoScroll` param to enable this behavior
* Removes associated logic from `ChatWindow`
* Exposes a `scrollToBottom` method which parent components can use the programmatically trigger a scroll to the bottom (`ChatWindow` uses this to always scroll to the bottom when a user sends a message)
* Aways scrolls to the bottom when `children` of the `ScrollArea` viewport change if the user was scrolled to the bottom previously
* Temporarily disables auto scroll if the user scrolls away from the bottom
> feat: Better autoscroll - for #909

- documentation/src/components/HomepageFeatures/index.tsx
This PR adds a **video section** to the homepage, showcasing our meet goose video:  
- **Embedded YouTube video** that plays automatically when scrolled into view.  
- **Fixes to ensure the video continues playing even after the user scrolls past it.**  
- **Dark and Light mode support** with appropriate videos for each mode.  
- **Added Intersection Observer logic** to track when the YouTube video enters the viewport.  
- **Updated `HomepageFeatures` component** to include a new video section.  
- **Refactored existing `video` elements** for improved structure and maintainability.  
- **Removed redundant duplicated `<video>` tags.**  
- **Optimized autoplay behavior** to ensure the video only loads once and doesn't restart unnecessarily.  
---
- To see the specific tasks where the Asana …
> add video to homepage

- crates/goose/src/providers/ollama.rs
- package-lock.json
**Overview**:
With this change I am able to use Goose with Ollama over https on 443, before this change it would always use port 11434 even if the scheme was https.
**Findings**:
Per Url docs port() will return None if the scheme is https, even if the port is explicitly provided. This causes the port to always be set to 11434 when trying to use https on 443.
This change will:
- use 11434 for http by default
- always use the port provided
> fix: Allow port 443 to be used with https (ollama provider)

- crates/goose-cli/src/test_helpers.rs
- crates/goose-server/src/routes/providers_and_keys.json
- ui/desktop/src/ChatWindow.tsx
- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
- ui/desktop/src/main.ts
this will ensure that GOOSE_PROVIDER and GOOSE_MODEL are used vs hard coded values
> fix it to use env vars if available

- crates/goose-cli/src/commands/configure.rs
Show the default value when adding a new value
Test:
Before
```
│
│  Configure Providers 
│
│  Ollama 
│
◆  Provider Ollama requires OLLAMA_HOST, please enter a value
│  
└  
```
After:
```
│
│  Configure Providers 
│
│  Ollama 
│
◆  Provider Ollama requires OLLAMA_HOST, please enter a value
│  localhost (default)
└  
```
> fix: show default value when adding new one

- crates/goose/src/providers/openrouter.rs
fix #1066 
Test:
Enable tools and see higher cache_discount
```
{
"data": {
"id": "gen-1738712804-5wvhsREvgvXR99HBpioS",
"upstream_id": "msg_01GQ8Vs5vVjo3C5viSgEYjsm",
"total_cost": 0.0028803,
"cache_discount": 0.0042687,
"provider_name": "Anthropic",
"created_at": "2025-02-04T23:46:48.29004+00:00",
"model": "anthropic/claude-3.5-sonnet",
"app_id": 1784029,
"streamed": true,
"cancelled": false,
"latency": 1191,
"moderation_latency": 205,
"generation_time": 1780,
"tokens_prompt": 1099,
"tokens_completion": 103,
"native_tokens_prompt": 1758,
"native_tokens_completion": 125,
"native_tokens_reasoning": 0,
"is_byok": false,
"finish_reason": "stop",
"native_finish_reason": "stop",
"usage": 0.0028803
}
}
```
> fix: apply cache control correctly to tools

- documentation/docusaurus.config.ts
added redirect such that we ca give ppl a straightforward /docs link: https://block.github.io/goose/docs
> docs: add simple docs link

- documentation/docs/tutorials/_template_.md
- documentation/docs/tutorials/jetbrains-mcp.md
New tutorial on how to use the JetBrains MCP Server as a Goose extension.
fixes #1031
> docs: jetbrains tutorial

- documentation/blog/2025-01-28-introducing-codename-goose/index.md
- documentation/docusaurus.config.ts
bluesky acct now verified so link has changed to https://bsky.app/profile/opensource.block.xyz
> docs: updated bluesky link

- ui/desktop/src/main.ts
This removes the minHeight which allows one to resize the window under the previously set amount. Useful for folks using accessibility settings and larger type.
> feat: removed minHeight

- crates/goose/Cargo.toml
- crates/goose/src/providers/bedrock.rs
- crates/goose/src/providers/factory.rs
- crates/goose/src/providers/formats/bedrock.rs
- crates/goose/src/providers/formats/mod.rs
- crates/goose/src/providers/mod.rs
- crates/goose/tests/providers.rs
- crates/goose/tests/truncate_agent.rs
Adds bedrock as a provider. As there are many possible ways to auth to aws, including:
- setting `AWS_ACCESS_KEY_ID`, `AWS_ACCESS_KEY`, and `AWS_REGION` explicitly as env vars
- setting `AWS_PROFILE` as env var
- working config in ~/.aws/credentials
we do not enforce any required vars to accommodate these multiple auth paths. This PR does not include modifications to the UI to enable Bedrock. This is tested / working for the CLI experience.
> feat: add bedrock provider

- ui/desktop/tailwind.config.ts
Link to font https://cash-f.squarecdn.com/static/fonts/cashsans/woff2/CashSans-Regular.woff2 gives 403 whenever I try to access it
That gives us not so good looking window with default font.
I have noticed website uses "sans-serif" as fallback font and have added it to desktop app too.
> fix: add fallback sans-serif font to desktop app

- crates/goose-cli/src/prompt.rs
- crates/goose-cli/src/prompt/renderer.rs
- crates/goose-cli/src/prompt/rustyline.rs
This patch contains two changes to the CLI app which allows it to respect the base 16 colors of a terminal emulator. While a handful of dependencies print output, most are respecting the console settings already.
The first commit contains a tweak to the hard-coded goose prompt to instead use the console style. I am not sure how controversial this is, if there is special meaning to the teal color currently used. The following commit adds a variant that could be referenced to switch between them.
The second commit adds an `Ansi` variant to the theme. This is only used by the underlying bat renderer for now, but could be a spot for other renderers to hook into in the future if necessary.
Closes https://github.com/block/goose/issues/1089
> Respect the terminal emulator's base colors

- crates/mcp-server/src/lib.rs
* re-use a single `BufReader` across `poll_next` calls, instead of creating a new one each time
* this could cause buffered state to be lost across polls
* ~also create a re-useable `Vec` that we read into, and use `std::mem::take` once we have a full line to read off~
* ~`std::mem::take` will also clear the vector~
this hopefully adresses some odd timing issues we saw when communicating with mcp servers
> fix: re-use BufReader across poll_next invocations, instead of creating a new one

- crates/goose-mcp/src/developer/mod.rs
Fixes #1022
The issue was that Goose was only checking for .goosehints in the current working directory, but not in the global configuration location (~/.config/goose/.goosehints).
Changes made:
- Added support for reading global hints from ~/.config/goose/.goosehints
- Maintains existing support for local .goosehints in project directories
- Both global and local hints will be combined if they exist
- Added clear section headers to distinguish between global and local hints
This allows users to set global hints that apply across all projects while still allowing project-specific overrides.
> fix: global .goosehints configuration not working

- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/main.rs
- documentation/docs/getting-started/using-extensions.md
Currently, you can only specify one extension on the cli through each of the `--with-builtin` and `--with-extension` options: `goose session --with-extension "npx -y @modelcontextprotocol/server-memory" --with-builtin "developer"`. This PR extends the cli to allow for multiple values to be specified for each of these options: 
`goose session --with-builtin developer,memory --with-extension "npx -y @modelcontextprotocol/server-memory" --with-extension "npx -y @modelcontextprotocol/server-github"`
This enables running goose in "headless" mode without modifying configurations and adding extensions on the fly
> feat: allow for multiple values in cli options for adding extensions

- crates/goose/src/providers/formats/openai.rs
- crates/goose/tests/truncate_agent.rs
fix #1108 
Sometimes the arguments can be empty and it will cause invalid json parsing error. We apply empty `{}` to avoid it.
Test:
Before:
```
( O)> list the window titles
I'll use the list_windows tool to show you all available window titles.
Invalid parameters: Could not interpret tool use parameters for id toolu_01CA9USw485HtvPTp53RXT68: EOF while parsing a value at line
1 column 0
◓  Designing data dreams...            
2025-02-06T07:21:55.459232Z  WARN goose::providers::openrouter: Failed to get usage data: No usage data in response
at crates/goose/src/providers/openrouter.rs:228
( O)> 
```
After
```
( O)> list the window titles
I'll help you list all available window titles using the `developer__list_windows` tool.
─── list_windows | developer ──────────────────────────
Here are …
```
> fix: handle empty arguments in tool call

- ui/desktop/src/components/MarkdownContent.tsx
- ui/desktop/src/components/ToolCallArguments.tsx
- ui/desktop/src/components/ToolInvocations.tsx
Tightened the spacing and styles around the Tool Call UI.
** before **
** after **
> styles: tweaks to tool call UI

- documentation/docs/getting-started/using-extensions.md
Enhanced the section on starting sessions with extensions by adding subsections for built-in and external extensions, providing specific command examples, and including instructions for setting environment variables.
> docs: elaborate on starting sessions with extensions

- documentation/docs/tutorials/_template_.md
- documentation/docs/tutorials/developer-mcp.md
- documentation/docs/tutorials/github-mcp.md
- documentation/docs/tutorials/jetbrains-mcp.md
- documentation/src/components/YouTubeShortEmbed.js
- documentation/src/css/custom.css
Added a new `YouTubeShortEmbed` component and updating tutorials to show their corresponding video.
> docs: embed youtube shorts

- documentation/docs/guides/using-goosehints.md
goosehints are an easy concept..so trying to reduce the confusion on slack about it with more deets. 
1. Removed mentions of jinja templating as .goosehints no longer uses it. Confirmed by [Salman](https://sq-block.slack.com/archives/C06PBQ52MCK/p1738874294539219)
2. Added clarity about global and local hints. People on Discord seemed confused.
3. Added clarity of which hints would take precedence if both are used
4. Added a best practice
Out of practice with doc writing..what to remove or add?
> docs: updating goose hints info

- documentation/docs/tutorials/fetch-mcp.md
Noting limitation
> Request failed: Request failed with status: 400 Bad Request. Message: * GenerateContentRequest.tools[0].function_declarations[22].parameters.properties[url].format: only 'enum' is supported for STRING type .
Please retry if you think this is a transient or recoverable error.
> docs: noting Fetch limitation with Gemini

- crates/goose-cli/src/session.rs
the cli should now skip processing entirely if the user message was empty
question for reviewers, should this be applied to headless sessions as well?
> fixes: #987 by ignoring when user submits empty message

- documentation/docs/getting-started/installation.md
- documentation/docs/troubleshooting.md
This PR updates the **Installation** and **Troubleshooting** guides to address a community raised issue for Mac M3 users where the Goose desktop app fails to launch with no visible window. The root cause is related to file and folder permissions for the `~/.config` directory.
- **Installation Guide**
- Added a **Permissions Note for Mac M3** users under the Goose Desktop installation instructions.
- Linked to the new **macOS Permission Issues** section in the Troubleshooting Guide for detailed steps on how to check and fix permissions.
- **Troubleshooting Guide**
- Added a new **macOS Permission Issues (M3 Macs)** section with:
- Steps to check current directory permissions using the `ls -ld ~/.config` command.
- Instructions on how to grant read and write permissions using `chmod` and …
> docs: Add Mac M3 Permission Troubleshooting to Documentation

- crates/goose-cli/Cargo.toml
- crates/goose-mcp/src/computercontroller/platform/macos.rs
- crates/goose-mcp/src/computercontroller/platform/windows.rs
- crates/goose-mcp/src/developer/mod.rs
a few missed things after #880 
* remove redundant winapi dependency, and keep the one in the `target.cfg` block
* remove manual `unsafe impl Send/Send` since the structs are empty and `Send` + `Sync` are [auto derived traits](https://doc.rust-lang.org/nomicon/send-and-sync.html#:~:text=Send%20and%20Sync%20are%20also,with%20are%20Send%20and%20Sync.)
* add back in `test_text_editor_size_limits` in developer tests
> chore: re-add tests, tidy up goose-cli/Cargo.toml, send + sync logic

- crates/goose-cli/src/logging.rs
- documentation/docs/tutorials/langfuse.md
> fix: consistently use LANGFUSE_URL instead of LANGFUSE_HOST

- ui/desktop/src/components/MoreMenu.tsx
removes provider settings from moreMenu in dev mode... does nothing
> remove provider settings from dev mode it does nothing

- crates/goose-cli/src/cli_prompt.rs
- crates/goose-cli/src/commands/session.rs
- crates/goose-cli/src/main.rs
- crates/goose-server/src/routes/agent.rs
- crates/goose/src/agents/agent.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/reference.rs
- crates/goose/src/agents/truncate.rs
The CLI now uses this to have a bit of info about slash commands and keyboard shortcuts. Could similarly use this for the App or other interfaces.
> feat: Support extending the system prompt

- crates/goose/src/providers/formats/openai.rs
- documentation/docs/tutorials/jetbrains-mcp.md
Users reporting openai incompatibility with certain extensions.
Fixes #933, related to #945
Extensions are not providing valid json schemas for openai function tool calling. Adds a function to validate the schema and add missing json schema fields
```
"function": {
"name": "get_weather",
"description": "Get current temperature for a given location.",
"parameters": {
"type": "object",
"properties": {
"location": {
"type": "string",
"description": "City and country e.g. Bogotá, Colombia"
}
},
"required": [
"location"
],
"additionalProperties": False
},
"strict": True
}
```
Databricks likely handled the missing fields on their end.
Tests:
> fix: validate function call json schemas for openai

- crates/goose-server/src/routes/providers_and_keys.json
- crates/goose/Cargo.toml
- crates/goose/src/providers/factory.rs
- crates/goose/src/providers/formats/mod.rs
- crates/goose/src/providers/formats/vertexai.rs
- crates/goose/src/providers/mod.rs
- crates/goose/src/providers/vertexai.rs
- crates/goose/tests/truncate_agent.rs
- ui/desktop/src/components/settings/api_keys/utils.tsx
- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
Add support for [Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/overview).
I've added only Claude sonnet 3.5 in this PR but we can expand it to Gemini or other models later.
> feat: Support VertexAI for Claude

- crates/goose-cli/src/commands/configure.rs
```bash
┌   goose-configure
│
│  Remove Extension
│
◆  Select extensions to remove (note: you can only remove disabled extensions - use "space" to toggle and "enter" to submit)
│  ◻ memory
└
```
> feat: allow removing extensions

- .github/workflows/pr-website-preview.yml
This workflow was failing because:
- When a PR is closed/merged, the workflow skips building documentation 
- but was still attempting to combine the non-existent build artifacts
- I skipped the step to combine builds _if_ closed/merged
---
- https://app.asana.com/0/0/1209391518598115
> Fix website preview action

- crates/goose/src/providers/formats/openai.rs
- crates/goose/src/providers/utils.rs
If you want to tell goose about an image, unless it was a screenshot it usually doesn't know, this will detect and add it as an image so it can understand it:
> feat: handle images mentioned in messages

- crates/goose-cli/src/main.rs
Fixes https://github.com/block/goose/issues/1209
---
Verified that the CLI args help for `--resume` references `--name` instead of `--session`
```
❯ ./target/debug/goose session -h
Start or resume interactive chat sessions
Usage: goose session [OPTIONS]
Options:
-n, --name <NAME>               Name for the chat session (e.g., 'project-x')
-r, --resume                    Resume a previous session (last used or specified by --name)
--with-extension <COMMAND>  Add stdio extensions (can be specified multiple times)
--with-builtin <NAME>       Add builtin extensions by name (e.g., 'developer' or multiple: 'developer,github')
-h, --help                      Print help (see more with '--help')
```
> fix: Update help docs for resume CLI arg

- documentation/docs/tutorials/google-drive-mcp.md
This PR updates the **Google Drive MCP Server tutorial** with the following improvements:
- Updated the authentication command to ensure successful OAuth flow.
- Clarified instructions for setting up and re-authenticating the Google Drive extension.
- Added a helpful tip section to inform users they need to re-authenticate once a day.
---
- https://app.asana.com/0/0/1209398868448865
> docs: Authentication Fix for Google Drive MCP Tutorial

- documentation/docs/troubleshooting.md
This PR updates the **Troubleshooting Guide** with a new section addressing connection errors when using **Ollama** as the provider on **WSL (Windows Subsystem for Linux)**.
- Added a new troubleshooting entry for **"Connection Error with Ollama Provider on WSL"**.
- Provided steps to diagnose and resolve the error, including how to:
- Check if the service is running using `curl`.
- Find and use the correct WSL IP address in Goose configuration.
- Included an example command (`ip route show | grep -i default | awk '{ print $3 }'`) to retrieve the correct WSL IP address.
community members running Goose with Ollama on WSL have encountered this connection issue due to WSL’s handling of localhost. 
---
- …
> docs: Add WSL Localhost Connection Error to Troubleshooting Guide

- crates/goose-mcp/src/computercontroller/mod.rs
- crates/goose-mcp/src/computercontroller/platform/linux.rs
- crates/goose-mcp/src/computercontroller/platform/mod.rs
This pull request introduces support for Linux automation in the `goose-mcp` crate. The most important changes include adding a new `LinuxAutomation` struct, implementing the `SystemAutomation` trait for Linux, and updating the platform module to include Linux-specific logic.
`LinuxAutomation` struct contains methods to detect display server, check dependencies, and execute commands for both X11 and Wayland. (`crates/goose-mcp/src/computercontroller/platform/linux.rs`)
> feat: linux computer control (WIP)

- documentation/docs/tutorials/fetch-mcp.md
for cli users, they need to install `uv` first before they can use this extension
> added note about uv requirement for Fetch extension

- crates/goose/src/providers/openai.rs
- documentation/docs/getting-started/providers.md
**Add organization and project support for OpenAI provider**
What was done:
- Extended the provider configuration to support optional `organization` and `project` headers  
- Updated the provider struct to include the new optional fields  
- Modified the request construction so it conditionally adds these headers when configured  
- Expanded the documentation to explain how to set up these fields for custom OpenAI endpoints
> feat(openai): Add organization and project support for OpenAI provider

- crates/goose/src/providers/formats/openai.rs
- crates/goose/tests/truncate_agent.rs
extract reasoning effort from o1 & o3 model name's last part
duplicate of - https://github.com/block/goose/pull/1045/files (without the comments, and refactoring into different functions)
> feat: support OpenAI reasoning effort configuration for O1/O3 models

- crates/goose-cli/src/commands/info.rs
- crates/goose-cli/src/commands/mod.rs
- crates/goose-cli/src/main.rs
- documentation/docs/guides/goose-cli-commands.md
adds the `info [-v]` command to print to the user goose's version, file location/dirs, and optionally full configuration (no secrets from keyring)
ex:
```bash
root@97b2604d5258:/ goose info -v
Goose Version:
Version:          1.0.6
Goose Locations:
Config file:      /root/.config/goose/config.yaml
Sessions dir:     /root/.local/share/goose/sessions
Logs dir:         /root/.local/share/goose/logs
Goose Configuration:
extensions:
developer:
enabled: true
name: developer
type: builtin
GOOSE_PROVIDER: openai
GOOSE_MODEL: gpt-4o
```
and an example showing if users have `XDG_` envvars set:
```bash
export XDG_CONFIG_HOME=/test
export XDG_DATA_HOME=/data
root@97b2604d5258:/ goose info
Goose Version:
Version:          1.0.6
Goose Locations:
Config file:      /test/goose/config.yaml
Sessions dir: …
```
> feat: add goose info command to display directories in use + config

- documentation/docs/tutorials/tavily-mcp.md
This pull request adds a tutorial for integrating the Tavily MCP Server as a Goose extension to enable AI-powered web search functionality. The tutorial includes step-by-step instructions for configuring the extension via both the Goose CLI and Goose Desktop, as well as an example usage scenario.
* [`documentation/docs/tutorials/tavily-mcp.md`](diffhunk://#diff-bcdbb8edbfa85bf5c6edf87babc675ad37cff424381631b4842244ccde29bef0R1-R196): Added a new tutorial document with detailed steps for adding and configuring the Tavily MCP Server extension, including command examples and environment variable setup.
---
- https://app.asana.com/0/0/1209431188448117
> docs: Add Tavily MCP tutorial

- crates/goose-server/src/routes/providers_and_keys.json
- crates/goose/src/providers/openai.rs
- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
- ui/desktop/src/components/settings/providers/BaseProviderGrid.tsx
fix #1198 
Requires users to input the openai host, for existing users, it will still use the default value
Test:
CLI
```┌   goose-configure 
│
│  Configure Providers 
│
│  OpenAI 
│
●  OPENAI_API_KEY is already configured
│  
│  Yes 
│
◇  Enter new value for OPENAI_API_KEY
│  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪
│
◇  Provider OpenAI requires OPENAI_HOST, please enter a value
│  https://api.openai.com
│
◆  Enter a model from that provider:
│  gpt-4o (default)
└  
```
UI
> feat: allow users to configure openai host

- .husky/pre-commit
Only run husky pre-commit hook for auto-formatting app code if app code has been changed
> fix: Only run husky precommit hooks when relevant

- crates/goose/src/providers/databricks.rs
* Attempt to propagate `external_model_message.message` when we get a `400 Bad Request` from databricks provider
ex:
```
( O)> hi
◓  Evolving ethereal entities...                                                                                                                                          
2025-02-19T18:48:21.799301Z ERROR goose::agents::truncate: Error: Request failed: Request failed with status: 400 Bad Request. Message: Unknown error
at crates/goose/src/agents/truncate.rs:279
```
becomes:
```
2025-02-19T18:53:32.354126Z ERROR goose::agents::truncate: Error: Request failed: Request failed with status: 400 Bad Request. Message: Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/tools/4/name: string [6kr06od8__add nums] does not match …
```
> feat: propagate external_model_message upwards on errors

- crates/goose/build.rs
Sometimes the download failed without any detail: https://github.com/block/goose/actions/runs/13395267770/job/37412606892
```
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=../../tokenizer_files
Downloading tokenizer for Xenova/gpt-4o...
Downloaded Xenova/gpt-4o to ../../tokenizer_files/Xenova--gpt-4o/tokenizer.json
Downloading tokenizer for Xenova/claude-tokenizer...
--- stderr
Error: "Failed to download tokenizer for Xenova/claude-tokenizer"
```
> log tokenizer download status

- documentation/docs/tutorials/knowledge-graph-mcp.md
This PR introduces a new tutorial that explains how to integrate the **Knowledge Graph Memory MCP Server** as a Goose extension. The tutorial provides step-by-step instructions on configuring the extension using both the Goose CLI and the desktop interface. 
- **New Documentation**: Adds `knowledge-graph-mcp.md` under `documentation/docs/tutorials/`.
- **Command Setup**: Provides the necessary commands to install and configure the Knowledge Graph Memory extension.
- **Configuration Guide**: Details CLI and UI-based configuration steps.
- **Example Use Cases**: Demonstrates how Goose can leverage the knowledge graph for:
- **Security vulnerability detection** using connected knowledge patterns.
- **Code review automation** to detect and mitigate risks like SQL injection and authentication …
> docs: Add Knowledge Graph Memory Extension

- crates/goose-cli/src/commands/info.rs
* fix the usage of the state_dir for logs
> fix: use in_state_dir to match logs directory

- crates/mcp-client/src/transport/sse.rs
For `crates/mcp-client`, remove direct calls to stdio so that when the crate is used as a dependency, they do not disturb the related logs/tracing.
> For client, move println! and eprintln! to tracing

- crates/goose/src/providers/formats/openai.rs
- crates/mcp-server/src/router.rs
see https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or 
the CI process started using rust 1.85.0 which introduced these warnings on `cargo clippy -- -D warnings`
> style: use is_none_or instead of map_or per clippy warnings rust >= 1.85.0

- ui/desktop/openapi.json
- ui/desktop/src/components/settings/ProviderSetupModal.tsx
UI styling of modals was broken by changing the width to 800px from 500px [here](https://github.com/block/goose/pull/1201/files#diff-978d31b4e329a4fbc88baaffe0bb2d19e3529ac38bc9285822036b347e6e8f97R48)
In this change, it is fixed
Before
After
> fix: fixing UI styling of modals

- crates/goose-cli/src/commands/configure.rs
- crates/goose/src/config/experiments.rs
- crates/goose/src/config/mod.rs
Add experiment manager to control whether a feature enabled. Right now for dev, we can manually update our config.yaml to set the experiment. 
It is not enabled by default
Before:
```
│
│  Goose Settings 
│
◆  What setting would you like to configure?
│  ● Goose Mode (Configure Goose mode)
│  ○ Tool Output 
└  
```
After:
```
│
│  Goose Settings 
│
◆  What setting would you like to configure?
│  ● Goose Mode (Configure Goose mode)
│  ○ Tool Output 
│  ○ Toggle Experiment 
└ 
```
> feat: add experiment manager to control whether we enable a feature

- .github/workflows/bundle-desktop.yml
The script was moved in https://github.com/block/goose/pull/1319
> fix: ./add-macos-cert.sh: No such file or directory

- ui/desktop/src/App.tsx
- ui/desktop/src/components/settings/SettingsView.tsx
- ui/desktop/src/extensions.ts
- ui/desktop/src/main.ts
- ui/desktop/src/preload.ts
Deep link installs of extensions were completely broken. This fixes the feature by:
* Resetting much of the code related to handling the `goose://` protocol in `main.ts`
* Adding a new concept of `View` and `ViewOptions` which can be used to populate options when routing to a certain view (used to navigate to settings and open the env var entry modal dialog if env vars are needed to configure and enable an extension)
> fix: deep link installs of extensions

- ui/desktop/src/components/SplashPills.tsx
Can tweak the implementation of this longer term to perhaps send the longForm version as a hidden message.
> feat: remove longform of 'what can you do?' prompt

- ui/desktop/openapi.json
- ui/desktop/src/components/settings/api_keys/utils.tsx
Since adding the OPENAI_HOST, OLLAMA_HOST, and other environment variables to the `default_key_value` object in `ui/desktop/src/components/settings/api_keys/utils.tsx`, the `getActiveProviders` function was not registering OpenAI as active if you had a key in `~/.zshrc`. This was because we considered it not configured if we hadn't set OPENAI_HOST.
We now correctly identify providers like openAI where there's 1* needed key, and 1* default key. 
If a provider has N needed keys (such as OpenAI needing OPENAI_API_KEY), and M default keys (such as OPENAI_HOST), the provider is considered active if all N needed keys are set, and the M default keys do not matter.
BUT if a provider has 0 needed keys (such as Ollama), and M default keys (such as OLLAMA_HOST), the provider is considered active if …
> bug: Fix env var for openAI

- crates/goose/src/providers/errors.rs
- crates/goose/src/providers/utils.rs
I wanted to try Goose out, so I built it from source and tried configuring it with my local Ollama, only to be met with "Request failed with status: 404 Not Found". While I, knowing Ollama, could guess that meant "that model is not found", not everyone might.
This PR:
* gently cleans up error handling from OpenAI compatible endpoints by introducing a real type for them
* makes that error-handling branch handle 404 as well as 400
with the end result that the "model "qwen2.5" not found, try pulling it first" error is now surfaced.
```
$ goose configure
Welcome to goose! Let's get you set up with a provider.
you can rerun this command later to update your configuration
┌   goose-configure
│
│  Ollama
│
◇  Provider Ollama requires OLLAMA_HOST, please …
```
> fix: handle OpenAI API errors better

- crates/goose-mcp/src/computercontroller/platform/linux.rs
this replaces checking if wl-clipboard is installed, since wl-clipboard is not an actually executable (as far as i know)
> Check that we have wl-copy and paste

- documentation/docs/getting-started/using-extensions.md
- documentation/docs/tutorials/jetbrains-mcp.md
- added link to tutorials to Using Extensions guide
- add link to PulseMCP server directory
- changed example to Knowledge Graph Memory extension
> docs: links for tutorials

- documentation/docusaurus.config.ts
* Reordered `Extensions` link in navigation bar from 4th to 2nd link
* Added `Tutorials` link to nav bar
* Moved `Discord` and `GitHub` links from the left to the right side of the navigation bar.
**Before**
**After**
> docs: rearrange menu

- documentation/docs/guides/adjust-tool-output.md
Added a new guide explaining how to adjust tool output verbosity using the Goose CLI, including instructions on selecting different output levels such as High Importance, Medium Importance, and All.
> docs: new guide on adjusting tool output in CLI

- documentation/docs/guides/goose-cli-commands.md
- rearranged commands based on usage likelihood
- added more info about `goose agents` command
- added missing `Usage` and `Options` labels on some commands
> docs: cleaning up CLI guide

- documentation/docs/getting-started/using-extensions.md
- documentation/docs/troubleshooting.md
- documentation/docs/tutorials/_template_.md
- documentation/docs/tutorials/fetch-mcp.md
- documentation/docs/tutorials/figma-mcp.md
- documentation/docs/tutorials/github-mcp.md
- documentation/docs/tutorials/google-drive-mcp.md
- documentation/docs/tutorials/google-maps-mcp.md
- documentation/docs/tutorials/knowledge-graph-mcp.md
- documentation/docs/tutorials/tavily-mcp.md
- new tutorial for google maps extension
- updated tutorial template with node on required dependency manager
- moved note about dependency manager to top of configuration section
> docs: google maps tutorial

- documentation/docs/getting-started/using-extensions.md
This update removes an outdated screenshot from the **Using Extensions** documentation to improve clarity.
- **Removed:** `manage-extensions-ui.png` screenshot.
- **Updated:** Adjusted wording for better readability.
---
- https://app.asana.com/0/0/1209476671933343
> Remove Screenshot from Using Extension Guide

- ui/desktop/src/bin/uvx
i don't think we need to set SSL_CERT_FILE in uvx shim and we can set  `UV_NATIVE_TLS=true` instead & point to internal pypi. i have tested this out locally with 2 MCPs that use uvx:
- works with https://github.com/modelcontextprotocol/servers/tree/main/src/time 
- works with fetch
> fix: don't set SSL_CERT_FILE in uvx shim

- ui/desktop/src/App.tsx
- ui/desktop/src/components/settings_v2/SettingsView.tsx
- ui/desktop/src/components/ui/BackButton.tsx
Scaffolding out the new Settings page. Accessible behind the `ALPHA=true` flag so we can continue building and hooking up different actions on the page.
> feat: settings v2 scaffolding

- crates/goose-server/src/routes/providers_and_keys.json
- crates/goose/src/providers/openai.rs
- ui/desktop/src/components/settings/api_keys/utils.tsx
- ui/desktop/src/components/settings/models/hardcoded_stuff.tsx
Test:
```
●  OPENAI_HOST is already configured
│  
│  No 
│
◇  Provider OpenAI requires OPENAI_BASE_PATH, please enter a value
│  v1/chat/completions
│
◇  Enter a model from that provider:
│  gpt-4o
│
◐  Checking your configuration...                                                                                                   └  Configuration saved successfully
```
> feat: allow setting openai base path

- crates/goose-cli/src/main.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose-cli/src/session/output.rs
This adds a flag -s/--interactive that drops into an interactive session after starting from a CLI/file message
> feat: interactive after run

- crates/goose/src/agents/truncate.rs
Right now, we have two `Goose would like to call the above tool. Allow? (y/n):` in the terminal screen.
Before:
```
( O)> write a test.txt to my dir
I'll help you write a test.txt file to the current directory. I'll use the text editor tool to create this file.
─── text_editor | developer ──────────────────────────
path: ~/Documents/block/goose/test.txt
command: write
file_text: This is a test file.
Goose would like to call the above tool. Allow? (y/n):
( O)> y
Goose would like to call the above tool. Allow? (y/n):
```
After
```
( O)> write a test.txt to my dir
I'll help you write a test.txt file in the current directory. I'll use the text editor tool to create this file.
─── text_editor | developer ──────────────────────────
path: ~/Documents/block/goose/test.txt
command: write …
```
> fix: update approve prompt

- crates/goose/src/agents/truncate.rs
Right now, we always do the read only detection, however, it is useful iff the goose mode is approve
> fix: detect read only tool when only mode is approve

- ui/desktop/src/components/settings/SettingsView.tsx
- ui/desktop/src/components/settings/extensions/ExtensionItem.tsx
- ui/desktop/src/components/settings/extensions/ManualExtensionModal.tsx
`Add` in the extension header may have been confusing as it kicked off a custom extension flow. Updated the label to `Add custom extension` and moved it under the installed extensions.
> feat: moved extension add button and updated label

- documentation/docs/guides/managing-goose-sessions.md
This PR updates the location of `sessions` according to #1153.
> fix(docs): update default session location

- ui/desktop/src/components/settings/providers/BaseProviderGrid.tsx
Added `Launch` text to configured providers to make the call-to-action more prominent. This addresses #1270
> style: added launch text and styling

- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/Input.tsx
This PR is to implement the feature mentioned in this [issue](https://github.com/block/goose/issues/1335).  
I remove the disable state from the chat input box, while the Goose is generating.   
The `Enter` shortcut to submit is still disabled when Goose is generating. 
https://github.com/user-attachments/assets/5cbc1efd-d429-446a-ad7d-53eb5c64e37a
> feat: remove the disable state from chat input box

- crates/goose-cli/src/main.rs
- crates/goose-cli/src/session/builder.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose-cli/src/session/storage.rs
This PR adds support for arbitrary session paths, allowing one to use sessions under not only the default location, but also any other locations. This feature is useful when the user wants to share or backup sessions.
> feat(cli): support arbitrary path for sessions

- documentation/docs/tutorials/computer-controller-mcp.md
This pull request includes a small change to the `documentation/docs/tutorials/computer-controller-mcp.md` file. The change adds a YouTube video embed to the tutorial documentation.
* [`documentation/docs/tutorials/computer-controller-mcp.md`](diffhunk://#diff-8e9ab4ed524c97ce51c637da42c05b9ba6c0b913ae49abfeb27430a2a41adba7R10-R11): Added a YouTube video embed with the URL `https://www.youtube.com/embed/EuMzToNOQtw`.
---
- https://app.asana.com/0/0/1209354827268319
> docs: Adding YT short for Computer Controller Tutorial

- documentation/docs/getting-started/installation.md
- documentation/docs/guides/goose-cli-commands.md
- documentation/docs/guides/updating-goose.md
This pull request adds a new section to the Goose CLI documentation, detailing the `update` command and its options.
* [`documentation/docs/guides/goose-cli-commands.md`](diffhunk://#diff-3dcfd1ace334a91a35076b1c7e66337d2466d0aa1a5a13ee7e20db186fe401e4R109-R132): Added a new section for the `update` command, including options for updating to the canary version and forcing reconfiguration during the update process.
> docs: adding update command to cli command guide

- crates/goose-cli/src/commands/configure.rs
- crates/goose/src/agents/truncate.rs
- crates/goose/src/config/experiments.rs
Users can use goose configure to enable/disable the smart approve, or directly edit the config.yaml.
ExperimentManager will lazily refresh the experiment list.
Test:
```
│
│  Goose Settings 
│
◇  What setting would you like to configure?
│  Toggle Experiment 
│
◇  enable experiments: (use "space" to toggle and "enter" to submit)
│  GOOSE_SMART_APPROVE 
│
└  Experiments settings updated successfully
```
```
─── text_editor | developer ──────────────────────────
path: ~/Documents/block/goose/test.txt
command: write
file_text: This is a test file.
◇  Goose would like to call the above tool, do you approve?
│  Yes 
│
This is a test file.
I've created a file named "test.txt" with some simple content. Let me verify that the file was …
```
> feat: allow user to turn off smart approve

- ui/desktop/src/main.ts
**Summary**
Use most recent directory if no directory is specified when creating a new chat window.
**Testing**
- Open window with ⌘+N 
- Confirm new window has the same directory path.
**Issue**
https://github.com/block/goose/issues/1150
> ui: create-chat-window opens most recent directory

- ui/desktop/src/main.ts
**Summary**
Updated mcp extension shortcut to only toggle on when Goose window has focus
**Testing**
- Opened goose window
- ran ⌘⇧Y shortcut 
- saw popup
- Navigated away from goose
- ran ⌘⇧Y shortcut
- no popup
- returned to goose window
- ran ⌘⇧Y shortcut
- saw popup
https://github.com/user-attachments/assets/8df732c3-e2f5-44e9-9f0f-249e7c0cb221
**Issue**
https://github.com/block/goose/issues/1347
> ui: disable mcp extension shortcut when unfocused

- documentation/blog/2025-02-21-gooseteam-mcp/index.md
Fixing a broken link to Cliff Hall's GooseTeam [repo](https://github.com/cliffhall/GooseTeam) after his refactor.
> chore: Fix Broken Repo Link in Blog

- crates/goose-mcp/src/computercontroller/mod.rs
the LLM can hallucinate different params even when you provide it a list of choices
> fix: return tool error for invalid param

- crates/goose/src/providers/formats/google.rs
fix #1359 
In our tool call, the response may be empty, like running command `touch xxx`, in such case, gemini will return the error about empty content part. Fix it by setting default content.
Also gemini requires the number of function response parts should be equal to number of function call parts of the function call turn, sometime the tool response can have multiple content part, we need to combine them into one content
Before:
```
( O)> create a test.txt file under the dir
─── shell | developer ──────────────────────────
command: touch test.txt
◇  Goose would like to call the above tool, do you approve?
│  Yes 
│
◐  Enchanting electrons...                                                                                                            2025-02-27T18:24:55.244805Z ERROR …
```
> fix: gemini empty content

- crates/goose/src/providers/azure.rs
This PR fixes an issue where the Azure provider would overwrite existing paths in endpoint URLs. The fix ensures that any existing path in the Azure endpoint URL is preserved when appending the required deployment path.
> Related Issue: https://github.com/block/goose/issues/1352#issuecomment-2690807448
Previous behavior: 
- Base URL paths were completely overwritten when setting the Azure deployment path
- Custom deployments with path prefixes would fail to connect properly
New behavior:
- Existing paths in base URLs are preserved and joined with Azure-specific paths
- Trailing slashes are properly handled to ensure clean path construction
```rust
// Before
base_url.set_path(&format!(
"openai/deployments/{}/chat/completions",
self.deployment_name
));
// After
let existing_path = …
```
> fix(provider): update url path handling for azure provider

- extensions-site/install-link-generator/index.html
- extensions-site/install-link-generator/script.js
- extensions-site/install-link-generator/styles.css
A simple static site nested under `extensions-site` to generate a goose install link for an extension, either by form or JSON entry.
Can be run with `npx serve`
https://github.com/user-attachments/assets/cf4e6a14-61ba-43f6-96da-53ffe4934288
> feat: extensions install link generator

- crates/goose-cli/src/session/completion.rs
- crates/goose-cli/src/session/input.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose-cli/src/session/output.rs
Per some discussion in https://github.com/block/goose/discussions/1401, some quality of life features for `prompt` commands in the cli
This does introduce a prompt cache that stores the information for the completion logic
* Add the ability to filter `prompts` by `--extension` to reduce the number of prompts
* Add Tab completion for `/<Tab>` all slash commands, and the ability to cycle through existing commands
* Add Tab completion for `prompt` names
* Add Tab completion for `prompt` arguments
Hard to see button presses, but `<Tab>` to cycle
https://github.com/user-attachments/assets/274ab952-2306-4816-a103-922df654d787
> feat(cli): add tab based slash command completion and prompt info completion

- crates/goose-cli/src/main.rs
Instead of showing help message:
- Run configure if Goose is not yet configured
- Start interactive session by default if already configured
This makes the CLI more user-friendly by reducing the number of commands needed for common operations.
> feat(cli): Improve default behavior when no command is provided

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose-server/src/routes/extension.rs
- crates/goose/examples/agent.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/extension.rs
- crates/goose/src/config/extensions.rs
- crates/goose/src/config/mod.rs
- ui/desktop/src/components/UserMessage.tsx
- ui/desktop/src/components/settings/extensions/ManualExtensionModal.tsx
- ui/desktop/src/extensions.ts
This PR closes #1422, adding support for setting extension timeout in both CLI and app.
> feat(goose): support customizing extension timeout

- crates/goose-cli/src/session/output.rs
This PR closes #1305. As the author of that issue said, the problem really matters when the user wants to yank text from output. If we wrap lines manually, there would be redundant line breaks (according to the size of the current terminal), making it difficult to use the output directly.
> fix(cli): disable line wrap

- ui/desktop/src/App.tsx
- ui/desktop/src/components/MoreMenu.tsx
- ui/desktop/src/main.ts
A very standard shortcut is Command + comma (or Ctrl + comma) to go to an App's settings or preferences (try it out on Slack, Notion, Discord, or your favorite app).
Also adding Settings to the app menu, after the About item, which is also where Chrome/Notion/Slack has it.
Also, adding the general ability to change views with the `'set-view'` message.
> feat(desktop-ui): Command/ctrl + comma goes to Settings view

- crates/goose-cli/src/session/input.rs
- crates/goose-cli/src/session/mod.rs
Store command history in ~/.config/goose/history.txt instead of per-session.
This allows command history to persist across different chat sessions.
> feat: implement global command history storage

- ui/desktop/src/bin/uvx
* we were already installing node in the npx shim
* force uv to use python 3.10
> feat: install python3.10 in uvx shim before uv

- crates/goose-server/src/routes/agent.rs
- crates/goose-server/src/routes/configs.rs
- crates/goose-server/src/routes/extension.rs
- crates/goose-server/src/routes/reply.rs
- crates/goose-server/src/state.rs
- crates/goose/src/agents/truncate.rs
- ui/desktop/package-lock.json
- ui/desktop/package.json
- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/ToolCallConfirmation.tsx
- ui/desktop/src/components/ToolCallWithResponse.tsx
- ui/desktop/src/components/settings/SettingsView.tsx
- ui/desktop/src/components/settings/basic/ModeSelection.tsx
- ui/desktop/src/hooks/useMessageStream.ts
- ui/desktop/src/types/message.ts
- ui/desktop/src/utils/toolConfirm.ts
Right now, the approval workflow is like in the agent reply, when we have some tool calls, we will hold here before execution and have a recv queue waiting for confirmation, in CLI, it doesn't have any issue. In UI, I had two options to implement the approval flow:
1. have a separate API for confirmation only
2. send a confirmation message via reply endpoint,
However, I found that we have the [lock](https://github.com/block/goose/blob/main/crates/goose-server/src/routes/reply.rs#L116) on reply API until the streaming is done, so both of options don't work in this case, because previous session is not done, waiting for confirmation to finish the stream, but the confirmation message is waiting for the existing stream to release the lock, then you see, deadlock....
The tweak I did is to use …
> feat: support goose mode in UI

- ui/desktop/src/components/settings/providers/BaseProviderGrid.tsx
The current Provider grid gets a little squished if the window is wide:
Making this a little more responsive for the home screen
This CSS can be used in other places, and/or for the new Provider grid design.
> More responsive provider grid

- documentation/docs/tutorials/fetch-mcp.md
- documentation/docs/tutorials/figma-mcp.md
- documentation/docs/tutorials/github-mcp.md
- documentation/docs/tutorials/google-drive-mcp.md
- documentation/docs/tutorials/google-maps-mcp.md
- documentation/docs/tutorials/knowledge-graph-mcp.md
- documentation/docs/tutorials/memory-mcp.md
- documentation/docs/tutorials/puppeteer-mcp.md
- documentation/docs/tutorials/tavily-mcp.md
This pull request includes updates to the installation instructions for extensions in goose desktop. The changes simplify the installation process by replacing multiple manual steps with a single installer link.
> docs: Use Installer Link

- crates/goose/src/agents/capabilities.rs
this prevents seeing
```
2025-03-03T17:29:05.776501Z ERROR goose::agents::capabilities: errors from listing prompts, errors: ["ExecutionError(\"Unable to list prompts for google_drive, RpcError { code: -32601, message: \\\"Server does not support 'prompts' capability\\\" }\")"]
at crates/goose/src/agents/capabilities.rs:622
```
for every extension that doesn't support prompts on startup
> chore: log errors to debug, not all extensions support prompts

- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/ToolCallConfirmation.tsx
- ui/desktop/src/components/settings/SettingsView.tsx
- ui/desktop/src/components/settings/basic/ModeSelection.tsx
Also applied default auto value to the goose mode
Test: 
https://github.com/user-attachments/assets/7b5ce870-baf3-46e3-a32b-f61b27feb9c5
> fix: apply dark mode to tool confirmation message

- Cargo.lock
- ui/desktop/src/components/settings/api_keys/utils.tsx
- ui/desktop/src/utils/providerUtils.ts
To check whether it is required key, we should check the required_keys map instead of default_keys as some keys are required and do have default value. Right now users cannot launch with ollama
Before:
After:
> fix: check all required keys

- .github/workflows/release.yml
follow up to https://github.com/block/goose/pull/1488, the `.bundle-intel` command worked in https://github.com/block/goose/actions/runs/13646127790/job/38145289300
> ci: have release depend on bundle-desktop-intel so zip is ready

- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/MarkdownContent.tsx
- ui/desktop/src/components/UserMessage.tsx
- ui/desktop/src/components/ui/CopyButton.tsx
* Adds a copy button to each `GooseMessage` and `UserMessage`, which copies the content verbatim (markdown etc)
* Unifies the logic with the other thing we already had that did this for markdown code examples
* Button is invisible unless hovered
@nahiyankhan Do you know if we have a design for this?
> feat: copy messages on hoverable icon

- documentation/docs/tutorials/puppeteer-mcp.md
This PR adds a YouTube Short video to the **Puppeteer MCP** tutorial, providing a visual walkthrough of how to integrate the **Puppeteer MCP Server** as a Goose extension.
- **Added** a YouTubeShortEmbed component with the video link:
```html
<YouTubeShortEmbed videoUrl="https://youtube.com/embed/rms0wVGnlXA" />
---
- https://app.asana.com/0/0/1209548116780809
> docs: Add Puppeteer MCP Tutorial Video To Guide

- documentation/docs/guides/goose-cli-commands.md
This PR updates the Goose CLI commands guide to improve clarity and include additional information about the `goose info` command and keyboard shortcuts.
- **Enhanced `goose info` section**:
- Expanded details to include version, configuration file location, session storage, and logs.
- Clarified the `-v, --verbose` option to show additional configuration settings, including environment variables and enabled extensions.
- **Added a new "Keyboard Shortcuts" section**:
- **Slash Commands**:
- `/exit` or `/quit` - Exit the session.
- `/t` - Toggle between Light/Dark modes.
- `/?` or `/help` - Display the help menu.
- **Keyboard Navigation**:
- `Ctrl+C` - Interrupt the current request.
- `Ctrl+J` - Add a newline.
- Up/Down arrows - Navigate through command history.
- **Modified:** …
> docs: Update CLI Commands Guide

- documentation/docs/getting-started/installation.md
- documentation/docs/guides/updating-goose.md
- documentation/src/components/DesktopInstallButtons.js
- documentation/src/components/SupportedEnvironments.js
Updated the supported environments information by removing the note about the macOS desktop app not supporting x86.
> docs: remove limitation about mac intel

- ui/desktop/openapi.json
- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/MessageCopyLink.tsx
- ui/desktop/src/components/UserMessage.tsx
* Bringing back https://github.com/block/goose/pull/1492 with more of the UX figured out
* Aligning with provided designs
* Copying text with formatting included (bolding, links, etc) instead of copying the raw text
Demo:
https://github.com/user-attachments/assets/6b8e2338-318c-4158-a17a-9c46de3631f1
> feat: copy message content

- Cargo.lock
- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/BottomMenuModeSelection.tsx
Use a dropdown list for goose mode selection under the chat window. So users don't need to go to setting page and lost their session.
https://github.com/user-attachments/assets/5c00fcbf-446f-4dba-882c-25cf103f1066
> feat: use dropdown for goose selection

- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/reference.rs
- crates/goose/src/agents/truncate.rs
- crates/goose/src/prompts/system.md
We may not need the tool call in the chat mode, goose will provide misleading message to users. Removing the tool call can reduce the cost as well.
Sample payload:
```
payload Object {"messages": Array [Object {"content": String("You are a general-purpose AI agent called Goose, created by Block, the parent company of Square, CashApp, and Tidal. Goose is being developed as an open-source software project.\n\nThe current date is 2025-03-05 18:14:21.\n\nGoose uses LLM providers with tool calling capability. You can be used with different language models (gpt-4o, claude-3.5-sonnet, o1, llama-3.2, deepseek-r1, etc).\nThese models have varying knowledge cut-off dates depending on when they were trained, but typically it's between 5-10 months prior to the current date.\n\n\n\n# Response …
```
> feat: remove tools from chat mode

- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/oauth.rs
* add the `offline_access` scope to get back a `refresh_token`
* update `TokenData` struct
* add logic to check for `refresh_token` in the cached tokens
* try to refresh_token if we can, otherwise fallback to normal auth flow
> feat: use refresh_tokens from databricks api

- documentation/docs/guides/logs.md
- documentation/docs/guides/managing-goose-sessions.md
Docs for
- viewing and resuming previous sessions in Desktop
- resuming sessions across interfaces (Desktop to CLI, CLI to Desktop)
> docs: resuming sessions

- documentation/docs/getting-started/providers.md
Updated Provider/Model config instructions based on UI changes
> docs: update to provider view

- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/truncate.rs
- crates/goose/src/prompts/system.md
Partially revert the https://github.com/block/goose/pull/1533 because it introduce the issue that when we switch from approve/auto mode to chat mode in one session, we will see `Requests which include tool_use or tool_result blocks must define tools.`. 
Test:
```
( O)> write a demo.txt under my current dir
I'll help you create a demo.txt file in your current directory using the text editor tool.
─── text_editor | developer ──────────────────────────
path: ~/Documents/block/goose/demo.txt
command: write
file_text: ...
◇  Goose would like to call the above tool, do you approve?
│  Yes 
│
This is a demo text file.
It was created using Goose's text editor tool.
Feel free to modify this file as needed!
I've created a demo.txt file with some sample content. Let's verify that the file was …
```
> fix: get tool def back to chat mode

- ui/desktop/src/components/ChatView.tsx
this fixes a bug where we we see an error about matching tool results
fixes #1541 
looks like during the conversion to use matching rust types in #1393 we missed this `onStop` implementation
this implementation attempts to match the logic in the CLI https://github.com/block/goose/blob/main/crates/goose-cli/src/session/mod.rs#L498-L536
> fix: respond to interrupted tool calls with a ToolResponseMessageContent

- Justfile
Follow up to #1487, we actually need to run a `cargo update --workspace` to ensure the `Cargo.lock` file is also updated:
https://doc.rust-lang.org/cargo/commands/cargo-update.html
> --workspace
> Attempt to update only packages defined in the workspace. Other packages are updated only if they don’t already exist in the lockfile. This option is useful for updating Cargo.lock after you’ve changed version numbers in Cargo.toml.
> ci: use cargo update --workspace to ensure Cargo.lock is updated

- documentation/docs/guides/using-gooseignore.md
This pull request adds a new documentation guide for using `.gooseignore` files to prevent Goose from accessing certain files and directories. The guide includes detailed instructions and examples on how to create and use `.gooseignore` files.
---
- https://app.asana.com/0/0/1209564071738937
> docs: using gooseignore

- crates/goose-mcp/src/developer/mod.rs
Adds an image processing tool to the developer MCP. If you give goose an image path, the tool will read it in and process it (similar to the screen capture tool). 
Some limits:
- 10mb is the limit on the file size (this was arbitrary)
- image gets resized similar to screen cap's to fit with provider limitations
- works best when there are no spaces in the file name (I found that models have trouble escaping correctly)
> feat: add image tool to developer mcp

- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/GooseMessage.tsx
- ui/desktop/src/components/ToolCallConfirmation.tsx
- ui/desktop/src/components/ToolCallWithResponse.tsx
- ui/desktop/src/components/sessions/SessionHistoryView.tsx
In the original implementaion, if users use approve mode and there is a pending confirmation and then users switch to a new session and try to resume the session, the confirmation will not be displayed corrected and cannot keep using due to mismatched tool request and response error.
In the PR, we tracked the resumed message length and use it for the base to check whether the confirmation is broken. And also append a tool response error message(mentioning the tool is cancelled) to fix the mismatch error.
Test:
https://github.com/user-attachments/assets/bb0f823b-8f64-4adc-ac18-da7a157de4e1
> fix: continue to use resumed session after confirmation is cancelled

- crates/goose/src/providers/openrouter.rs
The logo for Goose on the OpenRouter leaderboard for top public apps is the Github logo instead of the Goose logo. This is probably because the referer site we point to in our requests is the Goose Github repo which uses the Github logo as the favicon. This PR changes it to point to the [Goose Github pages site](https://block.github.io/goose/) which uses the Goose favicon.
> fix: update openrouter referer website to point to github page site

- documentation/docs/getting-started/using-extensions.md
- documentation/docs/quickstart.md
- documentation/docs/tutorials/_template_.md
- documentation/docs/tutorials/computer-controller-mcp.md
- documentation/docs/tutorials/fetch-mcp.md
- documentation/docs/tutorials/figma-mcp.md
- documentation/docs/tutorials/github-mcp.md
- documentation/docs/tutorials/google-drive-mcp.md
- documentation/docs/tutorials/google-maps-mcp.md
- documentation/docs/tutorials/jetbrains-mcp.md
- documentation/docs/tutorials/knowledge-graph-mcp.md
- documentation/docs/tutorials/memory-mcp.md
- documentation/docs/tutorials/puppeteer-mcp.md
- documentation/docs/tutorials/tavily-mcp.md
- documentation/docs/tutorials/tutorial-extension.md
- Added timeout flow to all tutorials and guides for both CLI and Desktop
- Updated label instructions for adding extensions in desktop to match UI changes
> docs: extension timeout

- documentation/docs/tutorials/cicd.md
- documentation/docs/tutorials/running-goose-cicd.md
- documentation/docusaurus.config.ts
This pull request includes substantial updates to the documentation, specifically adding a new tutorial for running Goose in CI/CD environments. It also includes a minor fix in the Docusaurus configuration file.
* [`documentation/docs/tutorials/running-goose-cicd.md`](diffhunk://#diff-38e454b918e8e816d3b351e9c705d027ce6a2ce494cd9fe89dd6c998240f242dR1-R378): Added a comprehensive tutorial on setting up Goose in CI/CD pipelines, including use cases, GitHub CLI usage, GitHub Actions integration, and security considerations.
---
- https://app.asana.com/0/0/1209345123617286
> docs: Add running Goose in CI tutorial

- Cargo.lock
- crates/goose-bench/Cargo.toml
- crates/goose-bench/src/bench_work_dir.rs
- crates/goose-cli/src/commands/bench.rs
this should obviate the need to -i the assets dir. not needing it in the run bench shell-script either.
> Feat: support auto-including dirs in binary/bench-work-dir

- crates/goose/src/agents/truncate.rs
We have parallel processing in auto mode - batch tool requests and process in parallel. 
This should not affect the user experience very much.
> feat: parallel processing in approve mode

- crates/goose/src/providers/anthropic.rs
efficient tool use header only depends on the model being claude 3.7 sonnet (thinking doesn't need to be enabled)
> fix: update anthropic provider headers

- ui/desktop/src/components/GoosehintsModal.tsx
Fixes: https://github.com/block/goose/issues/1525
The current Goosehints modal hides the bottom buttons when the modal is very small.
Fixing this by having a minimum height on the modal instead of a fixed one, and reducing the minimum size of the textbox.
Tested this by shrinking the window down to very small and increasing the font-size.
https://github.com/user-attachments/assets/18e4c047-def2-45f0-b6a8-861ba692824c
> Fix Goosehints modal UI

- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/utils/providerUtils.ts
We should only lookup the current model from the UI settings and not use environment variables. 
If environment variables are provided, sync them at startup with the React context provider (the object that provides to all components the model and provider information)  so we don't keep looking up the environment variables every time we need to display the model name, we just use the context provider -- this allows the state to dynamically change and we don't keep showing the same model/provider for the bottom menu
> remove env vars from bottom menu model setting

- documentation/docs/tutorials/tutorial-extension.md
This pull request includes changes to the `documentation/docs/tutorials/tutorial-extension.md` file to cover the desktop instructions for Tutorial extension.
> docs: Add steps for desktop tutorial

- ui/desktop/src/App.tsx
- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/hooks/useChat.ts
- ui/desktop/src/sessions.ts
Fixes: https://github.com/block/goose/issues/1532
Currently, chat messages are stored in the Chat View. So, if you navigate away from the Chat View (such as to Settings), the chat messages are lost.
This PR:
1. Moves chat message storage to the root level of the App. That way, navigating to any screen means that the chat is always retained,
2. Consolidates chat logic inside of a new hook `useChat()`. There was a few different files in which messages we being loaded/reloaded, and now it all happens here. This also allows for some refactoring and simplifying. `chat` is now where both the `messages` and `id` (aka session id) now live. It might be a good idea to combine this with the `useMessageStream()` hook, given that they share a bit of responsibility and are mildly stepping on each …
> Retain session through view changes

- ui/desktop/src/components/ConfigContext.tsx
- ui/desktop/src/components/settings_v2/providers/modal/ProviderConfiguationModal.tsx
- ui/desktop/src/components/settings_v2/providers/modal/subcomponents/forms/DefaultProviderSetupForm.tsx
- ui/desktop/src/components/settings_v2/providers/modal/subcomponents/handlers/DefaultSubmitHandler.tsx
Allows for writing to config.yaml and keychain for configuring providers
> ui: setting configuration

- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/azure.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/gcpvertexai.rs
- crates/goose/src/providers/google.rs
- crates/goose/src/providers/groq.rs
- crates/goose/src/providers/ollama.rs
- crates/goose/src/providers/openai.rs
- crates/goose/src/providers/openrouter.rs
- crates/goose/src/providers/utils.rs
Incorrect trace payload was being written to logs which included api keys on the provider.
> [fix] fix model config logging to remove api key

- documentation/docs/guides/logs.md
This PR updates the **Goose Logging System** documentation to include **persistent command history storage**. Instead of session-based history, Goose now retains command history across chat sessions in a dedicated history file.  
- **Added `Command History` section** to `logs.md`, detailing where command history is stored.  
- **Updated logging table** to include `~/.config/goose/history.txt` (Unix-like) and `%APPDATA%\Block\goose\data\history.txt` (Windows).  
- **Clarified session records** by noting that commands are now persistently stored in `history.txt`.  
| **Type**            | **Unix-like (macOS, Linux)**             | **Windows**                              |
|---------------------|----------------------------------------|---------------------------------------------|
| …
> docs: Persistent Command History

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/session/completion.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose/src/agents/truncate.rs
- documentation/docs/guides/goose-permissions.md
Add the write approve as discussed, UI update will come later.
> feat: add write approve mode

- documentation/docs/guides/goose-in-docker.md
Updated the instructions for building Goose in Docker, including rephrasing and restructuring the content for better readability.
> docs: edits to docker guide

- ui/desktop/src/App.tsx
- ui/desktop/src/main.ts
- ui/desktop/src/preload.ts
Fixes https://github.com/block/goose/issues/1534
When clicking a deep link, sometimes the window is closed. We open up a new window, and then wait until that window has loaded to send a message to the renderer to open an extension link.
The issue is that even though the window has loaded, React has not loaded, so it misses this message.
Instead, we need React to tell the main process that it is ready. So, create a `reactReady` call that does this. This might be useful later on for other needs as well (deep link or otherwise).
Then, when the main process gets a `react-ready` message, if there is a `pendingDeepLink`, it sends the message to the renderer to open the extension link.
> Fix deep link opening when window is closed

- Cargo.lock
- crates/goose-mcp/Cargo.toml
- crates/goose-mcp/src/google_drive/auth.rs
- crates/goose-mcp/src/google_drive/mod.rs
- crates/goose-mcp/src/google_drive/token_storage.rs
* default to using the keychain to store the credentials
* stores it in `mcp_google_drive` so it does require an additional password input for keychain, wanted to keep it separate from the goose specific keychain but does add an extra step
* add logic to compare existing oauth config with env, and ensure they match the env setup
* for headless environments they can set `GOOGLE_DRIVE_DISK_FALLBACK=true` to attempt to fallback to disk
> feat(google_drive): move credentials into keychain, add optional fallback

- ui/desktop/src/extensions.ts
When Goose fails to load an extension the error message now stays on the screen until you dismiss it.
> Extension error toast stays until dismissed, and error message cleanup

- crates/goose-cli/src/main.rs
for stdin use: 
```bash
echo 'hi' | goose run -i -
```
Error message update
```bash
❯ ./target/debug/goose run -i 'hi'
Instruction file not found — did you mean to use goose run --text?
No such file or directory (os error 2)
```
> feat(cli): add better error message, support stdin via -i - or just no args

- documentation/docs/guides/goose-cli-commands.md
- documentation/docs/guides/running-tasks.md
This pull request includes updates to the Goose CLI documentation to add new command options and provide detailed usage instructions.
* [`documentation/docs/guides/goose-cli-commands.md`](diffhunk://#diff-3dcfd1ace334a91a35076b1c7e66337d2466d0aa1a5a13ee7e20db186fe401e4L153-R158): Added new command options `--interactive`, `--path`, `--with-extension`, and `--with-builtin` to the Goose CLI command reference.
* [`documentation/docs/guides/running-tasks.md`](diffhunk://#diff-72df0b00101b152475100b818a23517fe703a7598aa6f2ddc8d2407bad7b5cc5R1-R135): Created a new guide for running tasks with Goose CLI, including examples of basic usage, interactive mode, session management, working with extensions, and common use cases.
> docs: Add running tasks guide

- documentation/docs/guides/goose-permissions.md
> docs: updating goose modes doc

- .github/workflows/ci.yml
- Cargo.lock
- crates/goose-mcp/Cargo.toml
- crates/goose-mcp/src/computercontroller/document_tool.rs
- crates/goose-mcp/src/computercontroller/mod.rs
- crates/goose-mcp/src/computercontroller/pdf_tool.rs
Using a new library https://crates.io/crates/extractous which seems to perform vastly better (still using low level obejcts to extract images when needed).
Enhancements: 
* can load large PDFs
* can load PDFs from URLs/websites
* can load many other doc formats (office docs, email, ebooks, presentations)
* can load web content (as text)
* ADVANCED: if tesseract is installed, it can OCR text out of image files, PDFs
Fixes: https://github.com/block/goose/issues/1664
> feat: handling larger more complex PDF docs (and fix)

- ui/desktop/src/extensions.tsx
This fixes: https://github.com/block/goose/issues/1507
Right now, error messages from loading extensions are displayed in a toast with full stack trace.
This stack trace can be very large, and quickly goes off-screen inside the toast and you can only read a small portion of it.
You also cannot copy the error message in the toast, as clicking on the toast dismisses the toast.
This PR removes the stack trace from the toast, and adds a button in the toast that allows people to copy the error message to the clipboard.
We can update the styling for this button or behavior in any way we'd like.
> feat: Copy error message button in toast

- ui/desktop/src/components/ChatView.tsx
goose can be interrupted during tool responses as well, previously it would fall into the first conditional and just remove the last user message and get the following:
```
Ran into this error: Request failed: Request failed with status: 400 Bad Request. Message: {"external_model_provider":"amazon-bedrock","external_model_error":{"message":"messages.140: Did not find 1 tool_result block(s) at the beginning of this message. Messages following tool_use blocks must begin with a matching number of tool_result blocks."}}.
```
at some point before the message apis changes we were checking that
https://github.com/block/goose/blob/81a0334aa109b4c636ce1448c7425225ba11b3b6/ui/desktop/src/components/ChatView.tsx#L101
there were no "toolInvocations" in the user message.
this PR adds that check back …
> fix: handle interruptions during tool responses

- ui/desktop/openapi.json
- ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
Extensions that are in config.yaml will render now and can toggle on/off
https://github.com/user-attachments/assets/e9f7a788-f533-4791-86ab-09172f8ffa3c
> chore: update extensions section to work with new endpoints

- crates/mcp-client/src/client.rs
I followed the same pattern as for the proxy/server code - just put the string directly into the response.
There's an argument for extracting the protocol version out of the schema when it generates all the code - but that's a much much bigger change - and not something a drive-by contributor can do!
> Issue 1667 - update the client protocol string to match the spec

- documentation/docs/tutorials/filesystem-mcp.md
This pull request adds a YouTube Short video embed to the **Filesystem MCP** tutorial documentation. The video provides a visual guide on integrating the Filesystem MCP server as a Goose extension.
- **Modified file:** `documentation/docs/tutorials/filesystem-mcp.md`
- **Added:** YouTube Short embed for a quick tutorial on Filesystem MCP.
---
- https://app.asana.com/0/0/1209692018518352
> docs: Add Filesystem Short Video to Tutorial

- documentation/docs/guides/goose-cli-commands.md
This pull request adds documentation for the `session list` command, detailing its usage and available options in the Goose CLI guide.
The `session list` command allows users to view all saved sessions.
- **`-v, --verbose`**: Includes session file paths in the output.
- **`-f, --format <format>`**: Specify output format (`text` or `json`). Default is `text`.
```bash
goose session list
goose session list --verbose
goose session list --format json
```
---
- https://app.asana.com/0/0/1209683515285499
> docs: Add Session List To CLI Commands Guide

- documentation/docusaurus.config.ts
This pull request includes a small change to the `documentation/docusaurus.config.ts` file. The change adds a new configuration option to display all blog posts in the sidebar.
Configuration update:
* [`documentation/docusaurus.config.ts`](diffhunk://#diff-18363c0e89010c49d5f105f49fdc20200f1de368a3ec607c830d47b4a6b7d06cR58): Added the `blogSidebarCount` option with the value `'ALL'` to show all blog posts in the sidebar.
---
- https://app.asana.com/0/0/1209681798597464
> docs: fix docusaurus sidebar limit

- crates/goose-mcp/src/google_drive/mod.rs
this fixes the fact that the readonly commands would re-initiate the oauth flow after a write call, and vice versa, since they only requested a single differing scope
> feat(google_drive): set read/write scope on all commands to use the same token

- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/BottomMenuModeSelection.tsx
- ui/desktop/src/components/settings/basic/ModeSelectionItem.tsx
- ui/desktop/src/components/settings/models/ModelRadioList.tsx
- ui/desktop/src/components/settings/models/RecentModels.tsx
- ui/desktop/src/components/ui/RadioInput.tsx
Standardizing some of the Radio Inputs and how we show radio button groups in dropdowns.
Creating the `RadioInput` UI component for reusability.
There might also be an opportunity to do a similar update on the Settings page
> Standardize Radio Button input

- crates/goose-mcp/src/google_drive/mod.rs
copied from @zakiali 's implementation in https://github.com/block/goose/pull/1515
> feat(google_drive): add image resizing logic from developer, and use Content::Image

- .github/workflows/pr-comment-build-cli.yml
`.build-cli`
`.bundle-cli` will trigger .bundle workflows
> feat: build cli workflow 

- ui/desktop/src/components/settings/basic/ConfigureApproveMode.tsx
- ui/desktop/src/components/settings/basic/ModeSelectionItem.tsx
While using the Goose UI I stumbled across these 2 typos that are inside Settings -> Mode Selection
Main change is changing `determime` to `determine`
> fix: Goose UI fix typos

- crates/goose/src/agents/truncate.rs
> feat: update the deny call response

- ui/desktop/src/App.tsx
Uses config for the alpha feature flag -- also moved other functions around, tagging which ones we can get rid of once we are ready to test settings v2 end to end and ones that need modifications 
I also put some old functions into a separate conditional hook 
structure of the file:
* new stuff for providers, view setting, and builtin extensions loading
* old stuff that can be modified related to extensions
* old stuff we can get rid of later
> ui: new configure provider flow

- .github/workflows/deploy-docs-and-extensions.yml
This pull request includes a small but important change to the deployment process in the `.github/workflows/deploy-docs-and-extensions.yml` file. The change ensures that the install link generator files are copied to the correct directory during the deployment process.
* [`.github/workflows/deploy-docs-and-extensions.yml`](diffhunk://#diff-f4f5e7e1f608be6cd836684bc3c5094e63edbedfb2baee8512005bf9fb7450d3R68): Added a step to copy the `install-link-generator` files to the `combined-build/v1/extensions/install-link-generator/` directory.
> docs: add deployment for install link generator

- .github/workflows/deploy-docs-and-extensions.yml
- documentation/docs/guides/goose-cli-commands.md
- documentation/docs/guides/running-tasks.md
This pull request includes updates to the Goose CLI documentation to clarify the usage of the `--instructions` option and provide examples of using standard input for instructions.
* [`documentation/docs/guides/goose-cli-commands.md`](diffhunk://#diff-3dcfd1ace334a91a35076b1c7e66337d2466d0aa1a5a13ee7e20db186fe401e4L174-R174): Updated the description of the `-i, --instructions <FILE>` option to indicate that it can also accept instructions from standard input using `-`.
* [`documentation/docs/guides/running-tasks.md`](diffhunk://#diff-72df0b00101b152475100b818a23517fe703a7598aa6f2ddc8d2407bad7b5cc5R51-R68): Added examples demonstrating how to pass instructions to Goose using standard input, including simple echo pipe and multi-line instructions.
> docs: add stdin

- ui/desktop/openapi.json
- ui/desktop/src/App.tsx
> ui: add logs to app

- crates/goose-cli/src/commands/configure.rs
- crates/goose-cli/src/session/mod.rs
- crates/goose-server/src/routes/extension.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/extension.rs
- crates/goose/src/config/extensions.rs
- crates/goose/src/config/mod.rs
- ui/desktop/openapi.json
- ui/desktop/src/api/types.gen.ts
- ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
- ui/desktop/src/components/settings_v2/extensions/LoadBuiltins.tsx
- ui/desktop/src/components/settings_v2/extensions/built-in-extensions.json
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionItem.tsx
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx
Adds an optional `display_name` field to builtin extensions 
this will allow for forwards compatibility with settings v2 and backwards compatibility with the old config style.
Going forward, the `name` field of built-in extensions should just be the display name and optional display_name field can remain empty.
> extensions: add a display name field

- crates/goose-cli/src/session/builder.rs
When running `goose run --resume --text 'hello goose'` I get this prompt:
```
WARNING: The working directory of this session was set to <path>. It does not match the current working directory. Would you like to change it?
```
When I run `pwd` I get the exact same path.
This is doubly an issue for my use case as I am trying to run goose in a non-interactive environment, in which case the error I get is:
```
thread 'main' panicked at /Users/runner/work/goose/goose/crates/goose-cli/src/session/builder.rs:82:29:
Failed to get user input: Kind(NotConnected)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
goose failed: exit status 101
```
I have added a check so that the user prompt only occurs if the current working directory does not match the path found in the …
> fix: check if working directory has changed before asking

- documentation/docs/tutorials/memory-mcp.md
This PR updates the **Memory MCP tutorial** by adding a **Trigger Words and When to Use Them** section. This addition helps users understand when Goose will suggest using memory tools based on specific keywords.  
- Added a **Trigger Words and When to Use Them** section  
- Listed keywords that trigger memory tools  
- Updated **Example Usage** for better clarity  
- Improved sentence flow for readability  
---
- https://app.asana.com/0/0/1209683515285507
> docs: Adding Trigger Words to Memory Tutorial

- documentation/docs/tutorials/filesystem-mcp.md
This PR removes the installer link for the **Filesystem MCP extension** because the installation process incorrectly treats directories as environment variables, which causes the extension to fail. The installation command needs to be **dynamic**, and this approach is not feasible with the installer link.  
- ✅ Removed the **installer link** from the documentation.  
- ✅ Updated instructions to guide users through manually adding the extension with the correct **dynamic command format**.  
- ✅ Ensured the documentation provides a clear and functional installation process.
> docs: Remove Installer Link From Filesystem Tutorial

- crates/goose/src/config/experiments.rs
- documentation/docs/guides/experimental-features.md
Update docs to remove experimental features for smart approve
> fix: update experimental features docs

- ui/desktop/src/components/settings_v2/extensions/modal/EnvVarsSection.tsx
- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionInfoFields.tsx
- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx
Fixes modal buttons and the fields in dark mode
Refactored a bit so we can add description field in next pr (omitted because backend didnt support but now it does)
> tweak darkmode for modal

- documentation/blog/2025-03-18-goose-langfuse/index.md
Added tutorial link to [Goosing Around Langfuse blog](https://github.com/block/goose/pull/1746)
> docs: add langfuse tutorial to blog

- documentation/blog/2025-03-20-asana-calendar-mcp/index.md
- documentation/docs/getting-started/using-extensions.md
- documentation/docs/guides/goose-cli-commands.md
- documentation/docs/tutorials/_template_.md
- documentation/docs/tutorials/asana-mcp.md
- new tutorial for Asana MCP
Betterment:
- Corrected a typo in the blog post 
- Removed Google Drive extension from the list of built-in extensions
- Added notes to clarify the behavior of extensions enabled for the current session
- Added examples and clarified the usage of environment variables for the `goose session --with-extension` command
> docs: Asana tutorial

- documentation/docs/tutorials/vscode-mcp.md
This pull request includes an update to the `documentation/docs/tutorials/vscode-mcp.md` file to enhance the tutorial with an embedded YouTube video.
Documentation update:
* [`documentation/docs/tutorials/vscode-mcp.md`](diffhunk://#diff-b9caa09ea51de4fb225fd9722d4135cd2a628756830fcf1866ed79f2cea6e86cR8-R11): Added an embedded YouTube video to the tutorial for better visual guidance on using the VS Code MCP Server as a Goose extension.
> docs: add youtube vscode short

- crates/goose-mcp/src/google_drive/mod.rs
This PR adds a number of new features and improves existing ones:
- Pagination for listing LOTS of comments as well as removing duplication between the oddly redundant LIST and GET comments endpoints.
- Limit file searches to a specific folder
- List shared drives
- Create replies
- Resolve comments
- Create folders
- Create shortcuts
- Move files
- Change file searching to allow you to query based on just mimetype, just name-contains, just parent folder, or any combination of the 3.
- Create comments (although the drive API only allows _unanchored comments_, and the show up saying "Original content deleted" in addition to the actual content.
> feat(google_drive): More comments, replies, folders, shortcuts, file moves

- crates/goose/src/agents/extension.rs
Goose currently allows arbitrary environment variables to be provided as part of adding an extension. This PR introduces additional validation to deny-list a few "dangerous" environment variables.
This allows us to better protect Goose customers from malicious extensions (or fake extensions) by making it more difficult for it to execute unexpected code/libraries from the command block for an extension.
> feat: Improve Security of Goose Extensions Via Environment Variable Denylist

- ui/desktop/src/components/UserMessage.tsx
- ui/desktop/src/components/ui/scroll-area.tsx
This solves https://github.com/block/goose/issues/1152
This is an open issue with RadixUI. [Here is the issue, and a proposed somewhat hacky fix that works](https://github.com/radix-ui/primitives/issues/2722#issuecomment-2404594842). This fixes the issue with the width growing very wide.
Also adding `"break-all"` to the UserMessage to allow for the text wrapping to work properly, regardless of chat width, for very long strings.
> Fix chat width issues

- crates/goose-bench/src/eval_suites/factory.rs
This is the fix to allow you to pass multiple selectors to goosebench - previously would only run the first selector
e.g. `-s core:developer,core:developer_search_replace`
> fix: fix allowing multiple selectors in goosebench

- extensions-site/public/servers.json
The latest PR had a trailing comma in servers.json, so then the extension site rendered this :
I only realized because I'm copying parts of the extensions site for the prompt library
> fix: extension site not rendering servers

- crates/goose-cli/src/commands/configure.rs
Small QoL change to improve visibility when toggling options in a `cliclack` multi-select.
This visibility problem only seems to exist for light themes, where there's no visible difference in text colour contrast between the cursor item and the result.
Apply the same change to the 'Remove extension' and 'Experiments' dialogs as well
Multi-select prompt interaction videos
- Existing (no idea which position the cursor is at) 
https://github.com/user-attachments/assets/c0ecd88d-a999-4403-b3f8-4e8f6070d2ad
- New
https://github.com/user-attachments/assets/1531d42b-c950-46b7-8030-2d7c599d31f0
> fix(cli): multiselect visibility for light themes

- ui/desktop/forge.config.ts
- ui/desktop/package.json
- ui/desktop/scripts/build-main.js
- ui/desktop/src/main.ts
- ui/desktop/src/utils/binaryPath.ts
- ui/desktop/vite.preload.config.ts
a bit of build time shenanigans to fix uvx for windows.
> fix windows native uvx

- ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
- ui/desktop/src/components/settings_v2/extensions/index.ts
- ui/desktop/src/main.ts
Unify the approach between installing an extension via deep link and adding one via the modal in settings
> feat: settings v2 extension add refactor

- ui/desktop/src/App.tsx
- ui/desktop/src/agent/UpdateAgent.tsx
- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/ProviderGrid.tsx
- ui/desktop/src/components/settings/SettingsView.tsx
- ui/desktop/src/components/settings/extensions/ConfigureBuiltInExtensionModal.tsx
- ui/desktop/src/components/settings/extensions/ConfigureExtensionModal.tsx
- ui/desktop/src/components/settings/extensions/ManualExtensionModal.tsx
- ui/desktop/src/components/settings/models/toasts.tsx
- ui/desktop/src/components/settings/models/utils.tsx
- ui/desktop/src/components/settings/providers/ConfigureProvidersGrid.tsx
- ui/desktop/src/components/settings_v2/models/AddModelModal.tsx
- ui/desktop/src/extensions.tsx
- ui/desktop/src/styles/main.css
- ui/desktop/tailwind.config.ts
Consolidated all current toasts with common components, and styled to match the new designs.
New loading spinner to come soon.
> New toasts

- ui/desktop/src/components/settings/basic/ModeSelectionItem.tsx
> fix: goose modes styling

- ui/desktop/src/components/ToolCallArguments.tsx
fixes https://github.com/block/goose/issues/1742
The styling for non-string args (before stringifying) did not apply the `text-textStandard` which flips the styling depending on light vs dark mode. The arguments were there, just not visible:
light mode doesn't change
> fix: add text-textStandard to non-string args for light/dark mode

- ui/desktop/src/components/ChatView.tsx
- ui/desktop/src/components/Input.tsx
fixes #1750 
before:
- when you hit the stop button, the original input text will disappear
after:
- when you hit the stop button, the original input text will remain
> fix: disappearing user text when stopped

- download_cli.sh
fixes https://github.com/block/goose/issues/1745
The following error happens when the user runs the download script and their working directory has a `goose` directory:
```bash
❯ goose update -c
Downloading canary release: goose-aarch64-apple-darwin.tar.bz2...
Extracting goose-aarch64-apple-darwin.tar.bz2...
goose: Can't replace existing directory with non-directory
tar: Error exit delayed from previous errors.
```
Use a temporary directory in `/tmp` to extract the binary, then move it to the final location
* use $RANDOM (https://tldp.org/LDP/abs/html/randomvar.html) to get a random number suffix
* `trap 'rm -rf "$TMP_DIR"' EXIT` to cleanup on script exit, even if an error occurs
> feat: use temp dir for extracting goose binary

- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionInfoFields.tsx
- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx
- ui/desktop/src/components/settings_v2/extensions/utils.ts
Last week I added `description` to `ExtensionConfig` in the rust side, so now we can use it in the UI.
> ui: add description field  to modal

- ui/desktop/src/extensions.tsx
* use a regex extraction to pull the contents of the msg field, and if the length is < 100 characters we display the error, otherwise we leave "Error adding extension"
* looks likes there was a change to `ToastError`, it expects `traceback` instead of `errorMessage` now, the copy button was not showing up until this was changed
https://github.com/block/goose/blob/main/ui/desktop/src/components/settings/models/toasts.tsx#L24-L30
> feat: extract `StdioProcessError(msg)` to try to display

- crates/goose/src/providers/openai.rs
This update introduces a configurable timeout for the OpenAI client in `crates/goose/src/providers/openai.rs`.
1.  **Added `OPENAI_TIMEOUT` Config Key:**
*   A new `ConfigKey` named `OPENAI_TIMEOUT` was added to the `metadata()` function of the `OpenAiProvider`.
*   This key allows users to specify the timeout value in seconds via configuration.
*   It is set as not secret (`false`), not required (`false`), and defaults to 600 seconds (`Some("600")`).
2.  **Read Timeout from Config:**
*   In the `from_env()` function, the `OPENAI_TIMEOUT` value is read from the global configuration using `config.get_param("OPENAI_TIMEOUT")`.
*   If the value is not found in the config, it defaults to 600 seconds.
*   The retrieved value is parsed as a `u64` and used to set the timeout when building the …
> feat: Allow setting OpenAI timeout from config

- documentation/static/install-link-generator/index.html
This pull request includes changes to the `documentation/static/install-link-generator/index.html` file to update the paths for the CSS and JavaScript files.
* Updated the stylesheet link to point to `./styles.css` instead of `./install-link-generator/styles.css`.
* Updated the script link to point to `./script.js` instead of `./install-link-generator/script.js`.
> quickfix: Update install-link-generator path

- crates/goose/src/providers/anthropic.rs
- crates/goose/src/providers/databricks.rs
- crates/goose/src/providers/formats/anthropic.rs
- crates/goose/src/providers/formats/databricks.rs
- crates/goose/src/providers/formats/mod.rs
Changes:
- copy openai format to a new databricks format which databricks provider uses now (eventhough databricks uses OpenAI compatible endpoints, there are extras to deal with claude 3.7 sonnet thinking which is not in openai API)
- update create_request and response_to_message in `formats/databricks.rs`
testing:
```
cargo build
CLAUDE_THINKING_ENABLED=true GOOSE_MODEL=claude-3-7-sonnet ./target/debug/goose session
```
error:  
i asked `read README.md & summarize in 2 sentences` and goose does 2 things:
uses a tool to read file 'README.md' -> works
responds to user with summary -> fails
> feat: add databricks format that can use claude 3.7 with thinking

- .github/workflows/build-cli.yml
- .github/workflows/bundle-desktop-intel.yml
- .github/workflows/bundle-desktop-windows.yml
- .github/workflows/bundle-desktop.yml
- .github/workflows/canary.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-docs-and-extensions.yml
- .github/workflows/pr-comment-bundle-intel.yml
- .github/workflows/pr-comment-bundle-windows.yml
- .github/workflows/pr-comment-bundle.yml
- .github/workflows/pr-website-preview.yml
- .github/workflows/quarantine.yml
- .github/workflows/release.yml
We do not want a compromised github action (or maintainer thereof) to take over the repo's secrets or integrity. This PR pins every action to a full length commit SHA.
This is the way recommended by github [0]. The following tool was used in this PR: https://github.com/mheap/pin-github-action
Example vulnerability that exploits this vector: https://github.com/advisories/GHSA-mrrh-fwg8-r2c3 (CVE-2025-30066).
[0] https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> ci: pin github action to specific hash

- documentation/docs/guides/goose-cli-commands.md
This PR adds the `/plan` command to the list of available CLI commands in the Goose documentation. The `/plan` command allows users to create structured plans based on a given message. This update helps to improve the usability of the CLI for organizing tasks and workflows.
- Added `/plan <message>` command description under the Prompt Completion section of `goose-cli-commands.md`.
- Provided usage examples for the `/plan` command, including creating a plan for triaging test failures.
```bash
/plan let's create a plan for triaging test failures
```
> docs: Add `/plan` Command to CLI Documentation

- crates/goose/src/session/storage.rs
fixes #1524. generate_description wasn't being used. The (mostly duplicated) logic didn't filter for user messages. Sending the whole conversation for summary probably misses the point and burns tokens.
> fix: message summary incorrectly generated

- ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionItem.tsx
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx
Fixes confusing UX for succeeding to toggle on an extension
1. click toggle
2. see extension load toast but toggle still off... several seconds pass
3. server succeeds to spin up -> user sees toggle move to on position and gets success toast
Success flow now:
1. click toggle
2. see extension load toast and toggle switches to on
3. server succeeds to spin up -> user gets success toast
Failure flow:
1. click toggle
2. see extension load toast and toggle switches to on
3. server fails to spin up -> user gets error toast -> toggle switches off
> ui: toggle back off after failure

- crates/goose/src/providers/formats/bedrock.rs
This pr resolves this issue https://github.com/block/goose/issues/1500 and removes tool result user annotations from the context (which may have been bloating the context)
> fix: bedrock provider to only include non user annotations and convert non supported docs to text

- ui/desktop/src/components/settings_v2/extensions/ExtensionsSection.tsx
- ui/desktop/src/components/settings_v2/extensions/agent-api.ts
- ui/desktop/src/components/settings_v2/extensions/extension-manager.ts
- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionConfigFields.tsx
- ui/desktop/src/components/settings_v2/extensions/subcomponents/ExtensionList.tsx
- ui/desktop/src/components/settings_v2/extensions/utils.ts
- ui/desktop/src/toasts.tsx
1. Toasts for toggle errors don’t have a copy error button anymore – error takes up full toast / is cut off
2. Don’t show loading toast for builtins 
3. When you open the extension settings (gear button) – don’t show the shim part of the command if present (same with on the card – too long)
> ui: clean up extensions

- ui/desktop/src/components/BottomMenu.tsx
- ui/desktop/src/components/settings_v2/models/bottom_bar/ModelsBottomBar.tsx
- ui/desktop/src/components/settings_v2/models/index.ts
- ui/desktop/src/components/settings_v2/models/modelInterface.ts
- ui/desktop/src/components/settings_v2/models/model_list/BaseModelsList.tsx
- ui/desktop/src/components/settings_v2/models/model_list/recentModels.ts
Reuses some code from settings v1 to create a list of models. Re-introduces the idea of a "Model" interface with some metadata attached such as alias (a nickname for the model) and subtext (an alternative to the provider name). Also re-uses some code for getting and storing recent models in localStorage but this is not used yet. 
As a follow up, will start constructing the current model into a `Model` and use that for display. 
Purpose of this is for two reasons:
1. Some releases of Goose may want to used a pre-defined set of models, this allows them to do that
2. A future PR will replace the current Model settings (which just shows the current model) and show a list of recently used models, this is just setting up some components and interfaces that allow for that -- the BaseModelsList …
> ui: set up model list component

- ui/desktop/src/components/ConfigContext.tsx
- ui/desktop/src/components/settings_v2/extensions/modal/ExtensionModal.tsx
makes sure we don't submit the shim to the config
> ui: no shim in config

- ui/desktop/src/components/more_menu/MoreMenu.tsx
Because reset providers currently resets local storage but settings v2 uses config.yaml, this update adds a feature-flag gated reset providers flow that removes GOOSE_PROVIDER and GOOSE_MODEL from config to trigger the onboarding page
If we want to add more 'reset' functionality to this flow, we should do so, but for now it's just provider and model
> ui: alpha reset providers

- documentation/blog/2025-03-31-goose-benchmark/index.md
- documentation/docs/tutorials/tavily-mcp.md
- documentation/src/pages/prompt-library/index.tsx
- documentation/yarn.lock
- Updating Tavily MCP tutorial to use official company MCP server and not community built server
- Updating goose bench blog description as it was showing the old one
- Updated yarn lock because we were missing a dependency upon install
- Updating prompt library to say "search for prompts by keyword"
> docs: updating small typos I found

- ARCHITECTURE.md
Just a small typo fix in `ARCHITECTURE.md` I noticed while reading. Hope this is helpful!
> Fixed small typo in ARCHITECTURE.md

- documentation/blog/authors.yml
This pull request includes a small change to the `documentation/blog/authors.yml` file. The change corrects the LinkedIn username for the author "alice" from `alicehau` to `alice-hau`.
> Updating Alice's Author Linkedin

- documentation/docs/tutorials/youtube-transcript.md
This pull request adds a new tutorial to the documentation for integrating the YouTube Transcript MCP Server as a Goose extension. The tutorial provides detailed steps for configuring and using the extension through both the Goose CLI and Goose Desktop interfaces.
* [`documentation/docs/tutorials/youtube-transcript.md`](diffhunk://#diff-b00d715dcdd37842ddd1c954d37fbd3b34c2eff4df218c3a9e759d3580236f61R1-R169): Added a comprehensive tutorial on how to add and configure the YouTube Transcript MCP Server as a Goose extension. This includes step-by-step instructions, example usage, and configuration details for both CLI and desktop interfaces.
> docs: Add youtube extension tutorial

- ui/desktop/src/App.tsx
- ui/desktop/src/components/ConfigContext.tsx
- ui/desktop/src/components/settings_v2/models/index.ts
- ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx
- ui/desktop/src/components/settings_v2/providers/ProviderSettingsPage.tsx
- ui/desktop/src/utils/providerUtils.ts
Ensures extensions are carried over during model changes in V2 settings
> fix: V2 settings carry extensions over during model change

- ui/desktop/src/components/settings_v2/models/subcomponents/AddModelModal.tsx
Makes it so you can type the name of a model not matched by anything in the default list for a provider, and add it.
**Demo**
https://github.com/user-attachments/assets/b8b2ebe1-8af1-4096-aa3e-b3ded77a832f
> feat: additive entry in settings V2 model Select

- crates/goose-cli/src/commands/configure.rs
- crates/goose-mcp/src/computercontroller/mod.rs
- crates/goose-mcp/src/developer/mod.rs
- crates/goose-mcp/src/google_drive/mod.rs
- crates/goose-mcp/src/jetbrains/proxy.rs
- crates/goose-mcp/src/memory/mod.rs
- crates/goose-mcp/src/tutorial/mod.rs
- crates/goose/examples/image_tool.rs
- crates/goose/src/agents/capabilities.rs
- crates/goose/src/agents/permission_judge.rs
- crates/goose/src/agents/reference.rs
- crates/goose/src/agents/summarize.rs
- crates/goose/src/agents/truncate.rs
- crates/goose/src/providers/formats/anthropic.rs
- crates/goose/src/providers/formats/databricks.rs
- crates/goose/src/providers/formats/google.rs
- crates/goose/src/providers/formats/openai.rs
- crates/goose/src/token_counter.rs
- crates/goose/tests/providers.rs
- crates/mcp-client/src/client.rs
- crates/mcp-core/src/tool.rs
- crates/mcp-server/src/main.rs
- crates/mcp-server/src/router.rs
Add tool annotations for build-in tools following the new mcp schema: https://github.com/modelcontextprotocol/specification/blob/main/schema/2025-03-26/schema.ts#L730C18-L730C33
Our permission control will use such annotations to check whether we should ask for human approval. It will be done in following PRs
In this PR, we only add annotations for tools with clear intention, like pure read or write tools. Some tools like bash or google drive update, we DON'T add annotations because they require LLM-as-a-judge to check the permission
> feat: add tool annotations for build-in tools

- crates/goose-mcp/Cargo.toml
- crates/goose/Cargo.toml
Adding the "vendored" feature to the keyring crate lets you avoid having to install `libdbus-1-dev` and `pkg-config` ([src](https://github.com/open-source-cooperative/keyring-rs#:~:text=The%20default%20build%20of%20this%20crate%20expects%20that%20libdbus%20will%20be%20installed%20on%20users%27%20machines.%20If%20you%20have%20users%20whose%20machines%20might%20not%20have%20libdbus%20installed%2C%20you%20can%20specify%20the%20vendored%20feature%20when%20building%20this%20crate%20to%20statically%20link%20the%20dbus%20library%20with%20your%20app.))
> Vendor keyring crate to fix non-hermetic builds
